<a id="scrollTop" href>
  <div></div>
</a>
<aside>
  <nav>
    <ul>
    </ul>
  </nav>
</aside>
<main>
  <h1 class="eia-h1">Disabled</h1>
  <section>
    <div class="eia-container">
      <!-- h2 class="eia-h2"></h2 -->
      <!-- p class="eia-para"></p -->
      <h3 class="eia-h3">Example</h3>
      <div class="eia-card">
        <div class="l-margin-bottom eia-container-resizer">
	<div class="l-row l-two-col-left-wide">
		<div class="primary l-col form-area">

			<fieldset disabled="">
				<legend>Subscribe to the Newsletter</legend>
				<div>
					<div class="form-container">
						<input type="email" name="email" />
						<input type="email" name="email" placeholder="e.g. alex@smith.com" />
					</div>
					<div class="button-container">
						<button type="submit" id="submitFeedback" tabIndex="0" role="button" class="submit">
							ok
						</button>
					</div>
				</div>
			</fieldset>
		</div>
	</div>

	<div class="l-col"></div>
</div>
<!-- HTML -->
<code>disabled</code>
<p>Disables the input.</p>
<!-- Live Examples --
<h3 class="eia-h3">Live Examples</h3>
<dl class="">
	<dd><a [routerLink]="['/modules/']" [fragment]="'placeholder'">placeholder</a></dd>
</dl>
-->
<!-- Example -->
<h3 class="eia-h3">Example</h3>
<div class="eia-card">
	<div class="l-row l-two-col-left-wide">
		<div class="primary l-col form-area">

			<fieldset>
				<div class="form-container">
					<input disabled="" />
					<input type="email" name="email" placeholder="e.g. alex@smith.com" />
				</div>
			</fieldset>
		</div>
	</div>

	<div class="l-col"></div>
</div>
<!-- HTML -->
<h3 class="eia-h3">HTML</h3>
<pre><code class="language-html" id="Disabled"></code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element eia-button eia-button-primary" data-clipboard-action="copy" data-clipboard-target="#Disabled">
		<span></span>Copy to clipboard
	</button>
</p>
</div>
	</section>
</main>
<footer>
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
</footer>
<link href="https://www.eia.gov/global/styles/global.min.css" type="text/css" media="screen, projection" rel="stylesheet">