<a id="scrollTop" href>
  <div></div>
</a>
<aside>
  <nav>
    <ul>
    </ul>
  </nav>
</aside>
<main>
  <h1 class="eia-h1">Select Dropdown</h1>
  <section>
    <div class="eia-container">
      <!-- h2 class="eia-h2"></h2 -->
      <!-- p class="eia-para"></p -->
      <h3 class="eia-h3">Example</h3>
      <div class="eia-card">
        <div class="l-margin-bottom eia-container-resizer">
	<div class="l-row l-two-col-left-wide">
		<div class="primary l-col form-area">
			<fieldset>
				<legend>Select your Items:</legend>
				<select name="cars" id="cars">
					<option value="ItemOne">Item One</option>
					<option value="ItemOne">Item Two</option>
					<option value="ItemOne">Item Thr</option>
					<option value="ItemOne">Item Fou</option>
				</select>
			</fieldset>
		</div>
	</div>
	<div class="l-col"></div>
</div>
<!-- HTML -->
<h3 class="eia-h3">HTML</h3>
<pre><code class="language-html" id="Select"></code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element eia-button eia-button-primary" data-clipboard-action="copy" data-clipboard-target="#Select">
		<span></span>Copy to clipboard
	</button>
</p>
</div>
	</section>
</main>
<footer>
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
</footer>
<link href="https://www.eia.gov/global/styles/global.min.css" type="text/css" media="screen, projection" rel="stylesheet">