<a id="scrollTop" href>
  <div></div>
</a>
<aside>
  <nav>
    <ul>
    </ul>
  </nav>
</aside>
<main>
  <h1 class="eia-h1">Enctype</h1>
  <section>
    <div class="eia-container">
      <!-- h2 class="eia-h2"></h2 -->
      <!-- p class="eia-para"></p --><h4>enctype</h4>
<p>
	Defines the <a href="https://www.iana.org/assignments/media-types/media-types.xhtml">MIME type</a> of the information sent to the server. Only works if the method is <code>post</code>.
</p>
<code>"application/x-www-form-urlencoded"</code>
<strong class="value-is-default">Default.</strong>
<p>
	The <strong>default</strong> value.
</p>
      <h3 class="eia-h3">Example</h3>
      <div class="eia-card">
        <div class="l-margin-bottom eia-container-resizer">

<!-- Live Examples --
<h3 class="eia-h3">Live Examples</h3>
<dl class="">
	<dd><a [routerLink]="['/modules/']" [fragment]="'placeholder'">placeholder</a></dd>
</dl>
-->
<!-- Example -->

	<div class="l-row l-two-col-left-wide">
		<div class="primary l-col form-area">

			<fieldset>
				<div>
					<div class="form-container">
						<label>Email</label>
						<input type="email" name="email" placeholder="e.g. alex@smith.com" />
					</div>
					<div class="button-container">
						<button type="submit" id="submitFeedback" tabIndex="0" role="button" class="submit">
							ok
						</button>
					</div>
				</div>
			</fieldset>
		</div>
	</div>

	<div class="l-col"></div>
</div>

<code>"text/plain"</code>
<p>For HTML5 plain text.</p>
<!-- Live Examples --
<h3 class="eia-h3">Live Examples</h3>
<dl class="">
	<dd><a [routerLink]="['/modules/']" [fragment]="'placeholder'">placeholder</a></dd>
</dl>
-->
<!-- Example -->
<h3 class="eia-h3">Example</h3>
<div class="eia-card">
	<div class="l-row l-two-col-left-wide">
		<div class="primary l-col form-area">

			<fieldset>
				<div>
					<div class="form-container">
						<label>Email</label>
						<input type="email" name="email" placeholder="e.g. alex@smith.com" />
					</div>
					<div class="button-container">
						<button type="submit" id="submitFeedback" tabIndex="0" role="button" class="submit">
							ok
						</button>
					</div>
				</div>
			</fieldset>
		</div>
	</div>

	<div class="l-col"></div>
</div>
<code>"multipart/form-data"</code>
<p>
	Needed when using an <code>&lt;input type="file"&gt;</code> element.
</p>
<!-- Live Examples --
<h3 class="eia-h3">Live Examples</h3>
<dl class="">
	<dd><a [routerLink]="['/modules/']" [fragment]="'placeholder'">placeholder</a></dd>
</dl>
-->
<!-- Example -->
<h3 class="eia-h3">Example</h3>
<div class="eia-card">
	<div class="l-row l-two-col-left-wide">
		<div class="primary l-col form-area">

			<fieldset>
				<div class="form-container">
					<label>Upload</label>
					<input type="file" />
				</div>
			</fieldset>
		</div>
	</div>

	<div class="l-col"></div>
</div>
<!-- HTML -->
<h3 class="eia-h3">HTML</h3>

<pre><code class="language-html" id="Enctype"></code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element eia-button eia-button-primary" data-clipboard-action="copy" data-clipboard-target="#Enctype">
		<span></span>Copy to clipboard
	</button>
</p>
</div>
	</section>
</main>
<footer>
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
</footer>
<link href="https://www.eia.gov/global/styles/global.min.css" type="text/css" media="screen, projection" rel="stylesheet">