<a id="scrollTop" href>
  <div></div>
</a>
<aside>
  <nav>
    <ul>
    </ul>
  </nav>
</aside>
<main>
  <h1 class="eia-h1">Fieldset</h2>
<p>
	Defines a <strong>group of controls</strong> within a form.
</p>
<!-- Live Examples --
<h3 class="eia-h3">Live Examples</h3>
<dl class="">
	<dd><a [routerLink]="['/modules/']" [fragment]="'placeholder'">placeholder</a></dd>
</dl>
-->
<!-- Example -->
<h3 class="eia-h3">Example</h3>
<div class="eia-card">
	<fieldset>
		<br />
		<br />
	</fieldset>
</div>

<h3 id="" class="">Legend</h3>
<p>
	Defines a <strong>caption</strong> for the fieldset.
</p>
<!-- Example -->
<h3 class="eia-h3">Example</h3>
<div class="eia-card">
	<fieldset>
		<legend>Subscribe to the Newsletter</legend>
		<br />
		<br />
	</fieldset>
</div>
<!-- HTML -->
<h3 class="eia-h3">HTML</h3>
<pre><code class="language-html" id="Fieldset">&lt;fieldset&gt;
  &lt;legend&gt;Subscribe to the Newsletter&lt;/legend&gt;
  &lt;br /&gt;
  &lt;br /&gt;
&lt;/fieldset&gt;</code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element eia-button eia-button-primary" data-clipboard-action="copy" data-clipboard-target="#Fieldset">
		<span></span>Copy to clipboard
	</button>
</p>
</div>
	</section>
</main>
<footer>
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
</footer>
<link href="https://www.eia.gov/global/styles/global.min.css" type="text/css" media="screen, projection" rel="stylesheet">