<a id="scrollTop" href>
  <div></div>
</a>
<aside>
  <nav>
    <ul>
    </ul>
  </nav>
</aside>
<main>
  <h1 class="eia-h1">Label and Input</h2>
<div class="uk-section uk-section-muted ">
	<h3 id="" class=""><span class="uk-label uk-label-danger">ACCESSIBILITY REQUIREMENT</span></h3>
	<ul>
		<li>
			The <code> for="name"</code> associates the label with the form input
		</li>
		<li>
			the <code>id="name"</code> should reference the label <code> for="name"</code>
		</li>
		<li>
			The <code>&lt;fieldset&gt;...&lt;/fieldset&gt;</code> and <code>&lt;legend&gt;&lt;/legend&gt;</code> should be utilized
		</li>
	</ul>
</div>

<p class="_note p">The user can click on the label to set focus to the form control. This is useful on small screens and to some people with motor disabilities, particularly when targeting small checkboxes and radio buttons. Clicking on labels is also an easy way to check for proper form labeling. If clicking the label sets focus to or activates the form control, then that label is programmatically associated.</p>
<!-- HTML -->
<h3 class="eia-h3">HTML</h3>
<pre><code class="language-html" id="InputLabel"></code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element eia-button eia-button-primary" data-clipboard-action="copy" data-clipboard-target="#InputLabel">
		<span></span>Copy to clipboard
	</button>
</p>
</div>
	</section>
</main>
<footer>
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
</footer>
<link href="https://www.eia.gov/global/styles/global.min.css" type="text/css" media="screen, projection" rel="stylesheet">