<a id="scrollTop" href>
  <div></div>
</a>
<aside>
  <nav>
    <ul>
    </ul>
  </nav>
</aside>
<main>
  <h1 class="eia-h1">Placeholder</h1>
  <section>
    <div class="eia-container">
      <!-- h2 class="eia-h2"></h2 --><h4>placeholder</h4>
<p>Defines a non-selectable placeholder text that only appears when the input is empty.</p>
<code>"e.g. alex@smith.com"</code>
<p>You can hint at the format expected for the input.</p>

<p>As a best practice, it is recommended to have a label to describe the input, and use the placeholder to showcase an example:</p>
<p>Notice how the placeholder disappears on focus, hence the need to maintain a separate label.</p>
      <!-- p class="eia-para"></p -->
      <h3 class="eia-h3">Example</h3>
      <div class="eia-card">
        <div class="l-margin-bottom eia-container-resizer">


	<div class="l-row l-two-col-left-wide">
		<div class="primary l-col form-area">
			<fieldset>

				<div class="form-container">
					<label>Email</label>
					<input type="email" name="email" placeholder="e.g. alex@smith.com" />
				</div>
				<div class="button-container">
					<button type="submit" id="submitFeedback" tabIndex="0" role="button" class="submit">
						ok
					</button>
				</div>

			</fieldset>
		</div>
	</div>
	<div class="l-col"></div>
</div>
<!-- HTML -->
<h3 class="eia-h3">HTML</h3>
<pre><code class="language-html" id="FormPlaceholder"></code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element eia-button eia-button-primary" data-clipboard-action="copy" data-clipboard-target="#FormPlaceholder">
		<span></span>Copy to clipboard
	</button>
</p>
</div>
	</section>
</main>
<footer>
	<br />
	<br />
	<br />
	<br />
	<br />
	<br />
</footer>
<link href="https://www.eia.gov/global/styles/global.min.css" type="text/css" media="screen, projection" rel="stylesheet">