<h3>Iconic Table Cells</h3>
<div class="eia accordion-content">

	<h4><span>&lt;/&gt;</span> Source</h4>
	<div class="basic-table">
		<table class="basic-table full-width">
			<tbody>
				<tr>
					<td class="eia ico pdf">
						<a>Link to PDF Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce cursus augue at semper sagittis. Donec mauris odio, vulputate eu elit at, ornare pharetra orci. Fusce tristique enim lectus, ultricies facilisis lectus fermentum luctus. Praesent aliquam commodo sem quis facilisis. Donec pulvinar nunc quis orci iaculis posuere. Praesent fringilla imperdiet mattis. Curabitur ac sapien nisi. Praesent faucibus euismod purus, vitae dignissim diam aliquet non. Aliquam eget ipsum eros. Proin ullamcorper leo pretium efficitur vestibulum.</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico xls">
						<a>Link to XLS</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico csv">
						<a>Link to CSV</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico ppt">
						<a>Link to PPT</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico zip">
						<a>Link to zip</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico json">
						<a>Link to JSON</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico html">
						<a>Link to HTML</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico doc">
						<a>Link to DOC</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico image">
						<a>Link to image</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico interactive">
						<a>Link to interactive</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico efile">
						<a>Link to eFile</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico pedro">
						<a>Link to PEDRO</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico api">
						<a>Link to API</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico zip">
						<a>Link to ZIP</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
</div>