<h2>Nested Lists</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd></dd>
		<dd></dd>
	</dl>
	<!-- Example -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
	<div class="eia-card">
		<div class="l-row l-two-col-even">
			<div class="l-col">
				<h4>Correct list nesting:</h4>
				<ul>
					<li>Lorem ipsum dolor sit amet</li>
					<li>
						<ul>
							<li>Lorem ipsum dolor sit amet</li>
							<li>Lorem ipsum dolor sit amet</li>
							<li>Lorem ipsum dolor sit amet</li>
						</ul>
					</li>
					<li>Lorem ipsum dolor sit amet</li>
				</ul>
			</div>
			<div class="l-col">
				<h4>Incorrect list nesting:</h4>
				<ul>
					<li>Lorem ipsum dolor sit amet</li>
					<ul>
						<li>Lorem ipsum dolor sit amet</li>
						<li>Lorem ipsum dolor sit amet</li>
						<li>Lorem ipsum dolor sit amet</li>
					</ul>
					<li>Lorem ipsum dolor sit amet</li>
				</ul>
			</div>
		</div>
	</div>