<!--

<div class="primary">
<ul>
<li class="head">
      <h2>Lorem ipsum dolor sit amet consectetur</h2>
    </li>
<li><a href="https://www.eia.gov">1) Lorem ipsum dolor sit amet</a></li>
<li><a href="https://www.eia.gov">2) Lorem ipsum dolor sit amet</a></li>
<li><a href="https://www.eia.gov">3) Lorem ipsum dolor sit amet</a></li>
<li><a href="https://www.eia.gov">4) Lorem ipsum dolor sit amet</a></li>
<li><a href="https://www.eia.gov">5) Lorem ipsum dolor sit amet</a></li>
</ul>
</div>


-->


<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Primary</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd></dd>
		<dd></dd>
	</dl>
	<!-- Example -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
	<div class="eia-card">
		<div class="primary">
			<ul>
				<li class="head">
					<h2>Lorem ipsum dolor sit amet consectetur</h2>
				</li>
				<li>
					<a href="https://www.eia.gov">1) Lorem ipsum dolor sit amet</a>
				</li>
				<li>
					<a href="https://www.eia.gov">2) Lorem ipsum dolor sit amet</a>
				</li>
				<li>
					<a href="https://www.eia.gov">3) Lorem ipsum dolor sit amet</a>
				</li>
				<li>
					<a href="https://www.eia.gov">4) Lorem ipsum dolor sit amet</a>
				</li>
				<li>
					<a href="https://www.eia.gov">5) Lorem ipsum dolor sit amet</a>
				</li>
			</ul>
		</div>



		<h4>HTML Code </h4>
		<!-- Copy Button -->
		<p>

	</div>
	</div>
	</div>
	</div>