<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Upcoming Releases</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd></dd>
		<dd></dd>
	</dl>
	<!-- Example -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
	<div class="eia-card">
		<script>
			function upcomingReleasesArticle() {
				var upcomingReleases = document.getElementById("upcomingReleasesStyleSwitcher")
				upcomingReleases.setAttribute('class', 'article')
			}

			function upcomingReleasesPrimary() {
				var upcomingReleases = document.getElementById("upcomingReleasesStyleSwitcher")
				upcomingReleases.setAttribute('class', 'primary')
			}

			function upcomingReleasesPrimaryAlt() {
				var upcomingReleases = document.getElementById("upcomingReleasesStyleSwitcher")
				upcomingReleases.setAttribute('class', 'primary-alt')
			}

			function upcomingReleasesSecondary() {
				var upcomingReleases = document.getElementById("upcomingReleasesStyleSwitcher")
				upcomingReleases.setAttribute('class', 'secondary')
			}

			function upcomingReleasesSecondaryAlt() {
				var upcomingReleases = document.getElementById("upcomingReleasesStyleSwitcher")
				upcomingReleases.setAttribute('class', 'secondary-alt')
			}
		</script>
		<div class="style-switcher">
			<button onclick="upcomingReleasesArticle()">Article</button>
			<button onclick="upcomingReleasesPrimary()">Primary</button>
			<button onclick="upcomingReleasesPrimaryAlt()">Primary-alt</button>
			<button onclick="upcomingReleasesSecondary()">Secondary</button>
			<button onclick="upcomingReleasesSecondaryAlt()">Secondary-alt</button>
		</div>
		<div class="article" id="upcomingReleasesStyleSwitcher">
			<!-- includes/placeholders/upcoming-releases -->
		</div>
		<!-- HTML -->
		<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
		<div class="uk-margin-medium">


			<pre><code class="language-html" id="upcomingReleases">&lt;div class="primary hide-mt"&gt;
  &lt;ul class="upcoming-releases"&gt;
    &lt;li class="head"&gt;
      &lt;h2&gt;Upcoming Releases&lt;/h2&gt;
    &lt;/li&gt;
    &lt;li&gt;
      &lt;a title="Gasoline and Diesel Fuel Update" class="link-label"&gt;
Gasoline and Diesel Fuel Update&lt;em&gt;: 5:00 p.m. ET, Monday&lt;/em&gt;
      &lt;/a&gt;
    &lt;/li&gt;
    &lt;li&gt;
      &lt;a title="" class="link-label"&gt;
      &lt;em&gt;: &lt;/em&gt;
      &lt;/a&gt;
    &lt;/li&gt;
    &lt;li class="foot"&gt;&lt;a&gt;See all upcoming&lt;/a&gt;&lt;/li&gt;
  &lt;/ul&gt;
&lt;/div&gt;</code></pre>
		</div>
		<!-- Copy Button -->
		<p>
			<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#upcomingReleases">
				<span uk-icon="copy"></span>Copy to clipboard
			</button>
		</p>
		</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">