<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Updated Data Series</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd></dd>
		<dd></dd>
	</dl>
	<!-- Example -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
	<div class="eia-card">
		<script>
			function updatedDataSeriesArticle() {
				var updatedDataSeries = document.getElementById("updatedDataSeriesStyleSwitcher")
				updatedDataSeries.setAttribute('class', 'article')
			}

			function updatedDataSeriesPrimary() {
				var updatedDataSeries = document.getElementById("updatedDataSeriesStyleSwitcher")
				updatedDataSeries.setAttribute('class', 'primary')
			}

			function updatedDataSeriesPrimaryAlt() {
				var updatedDataSeries = document.getElementById("updatedDataSeriesStyleSwitcher")
				updatedDataSeries.setAttribute('class', 'primary-alt')
			}

			function updatedDataSeriesSecondary() {
				var updatedDataSeries = document.getElementById("updatedDataSeriesStyleSwitcher")
				updatedDataSeries.setAttribute('class', 'secondary')
			}

			function updatedDataSeriesSecondaryAlt() {
				var updatedDataSeries = document.getElementById("updatedDataSeriesStyleSwitcher")
				updatedDataSeries.setAttribute('class', 'secondary-alt')
			}
		</script>
		<div class="style-switcher">
			<button onclick="updatedDataSeriesArticle()">Article</button>
			<button onclick="updatedDataSeriesPrimary()">Primary</button>
			<button onclick="updatedDataSeriesPrimaryAlt()">Primary-alt</button>
			<button onclick="updatedDataSeriesSecondary()">Secondary</button>
			<button onclick="updatedDataSeriesSecondaryAlt()">Secondary-alt</button>
		</div>
		<div class="article" id="updatedDataSeriesStyleSwitcher">
			<!-- includes/placeholders/updated-data-series -->
		</div>

		<!-- HTML -->
		<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
		<div class="uk-margin-medium">


			<pre><code class="language-html" id="updatedDataSeries">&lt;div class="primary hide-mt"&gt;
  &lt;ul class="updated-data-series"&gt;
    &lt;li class="head"&gt;
      &lt;h2&gt;Updated Data Series&lt;/h2&gt;
    &lt;/li&gt;
    &lt;li&gt;
      &lt;span class="date"&gt;1/15/2020&lt;/span&gt;
      &lt;a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm" title="Weekly supply estimates"&gt;Weekly supply estimates&lt;/a&gt;
    &lt;/li&gt;
    &lt;li&gt;
      &lt;span class="date"&gt;&lt;/span&gt;
      &lt;a title=""&gt;&lt;/a&gt;
    &lt;/li&gt;
  &lt;/ul&gt;
&lt;/div&gt;</code></pre>
		</div>
		<!-- Copy Button -->
		<p>
			<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#updatedDataSeries">
				<span uk-icon="copy"></span>Copy to clipboard
			</button>
		</p>
		</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">