<div class="l-row header l-full-width-col">
	<div class="l-col title-banner default-pub-header">
		<h3>Energy &amp; Financial Markets</h3>
		<h1 style="padding-top:0px;">WHAT DRIVES CRUDE OIL PRICES?</h1>
		<p style="color: #7d7d7d;">An analysis of 7 factors that influence oil markets, with chart data updated monthly and quarterly</p>
	</div>
</div>

<style>
@media (min-width: 1px) {
	/*
	.title-banner {
		padding: 22px 12px 1px !important;
	}
		*/

	.title-banner h3 {
		margin: 0;
		padding: 0;
		font-size: 1.5em;
		line-height: 1;
		font-weight: normal;
		color: #333;
		font-family: Jost, sans-serif;
		font-weight: 700;
	}
}

@media (min-width: 1025px) {
	.title-banner h3 {
		padding: 32px 0 0 0;
	}
}
</style>
