<h1><?php echo "$pageYear"?> Previous CBECS Survey Data <span class="right"><b><a href="../1989/index.cfm" id="1989">1989</a> | <a href="../1986/" id="1986">1986</a> | <a href="../1983/" id="1983">1983</a> | <a href="../1979/" id="1979">1979</a> | <a href="../Newer/" id="Newer">Newer</a> | <a href="../archive.cfm" id="Archive">Archive</a></b></span></h1>
<script>
$(document).ready(function(){
	$('a#<?php echo "$pageYear"?>').replaceWith("<?php echo "$pageYear"?>");
	});
</script> 
