<div class="primary">
    <p>Find statistics on nuclear operable units, nuclear electricity net generation, nuclear share of electricity net generation, and capacity factor.</p>

    <span class="expand-collapse-container">
        <i class="ico expand"><span>Expand all</span></i>
        <i class="ico collapse"><span>Collapse all</span></i>
    </span>
    <div class="accordion">
        <h3><a name="nuclear"></a>Nuclear power plants</h3>
        <div class="accordion-content">
            <ul>
                <li class="head"> Daily nuclear status/outages (with annual capacity)</li>
                <li>Daily status of U.S. nuclear plants with summary and plant-specific data on percentage output, outage amount, and capacity</li>
                <li><span class="formats">Available formats:</span> <a href="/nuclear/outages/" title="Daily nuclear status/outages"> <span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li><a href="/nuclear/generation/index.html">Nuclear electricity generation and capacity</a></li>
                <li><span class="release-date">Release date:</span> <span class="date">May 27, 2021</span><span class="pipe">|</span><span class="source">Data from:</span> survey forms <a href="/electricity/data/eia923/">EIA-923</a> and <a href="/electricity/data/eia860/">EIA-860</a>.</li>
                <li>State and reactor-specific nuclear generation (monthly back to 2003)</li>
                <li class="list-spacer"></li>
                <li><strong>Nuclear generation, capacity summary data</strong> (monthly back to 1973, annual back to 1957)</li>
                <li><span class="release-date">Release date:</span> <span class="date">
                        <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
                    </span><span class="pipe">|</span><span class="source">Data from:</span> <a href="/totalenergy/data/monthly/">Monthly Energy Review</a> </li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec8_3.pdf" title="Nuclear generation, capacity summary data"> <span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/csv.php?tbl=T08.01" class="ico_csv" title="Nuclear generation, capacity summary data"> <span class="ico csv"><span>CSV</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T08.01&amp;freq=m" title="Nuclear generation, capacity summary data"> <span class="ico xls"><span>XLS</span></span></a><span class="pipe">|</span><a href="/beta/MER/index.php?tbl=T08.01#/?f=M&amp;start=200001" title="Nuclear generation, capacity summary data"> <span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li><a href="/nuclear/reactors/reactorcapacity.php">Reactor capacity and ownership</a></li>
                <li><span class="release-date">Release date:</span> <span class="date">July, 2025</span><span class="pipe">|</span><span class="source">Data from:</span> survey form <a href="/electricity/data/eia860/">EIA-860, Annual Electric Generator Report</a></li>
                <li class="list-spacer"></li>
                <li><a href="/totalenergy/data/annual/showtext.php?t=ptb0901">Nuclear generator licensing data</a></li>
                <li><span class="release-date">Release date:</span> <span class="date">September 27, 2012</span><span class="pipe">|</span><span class="source">Data from:</span> <a href="/totalenergy/data/annual/">Annual Energy Review, 1949 through 2011</a> <span class="alert">(no longer updated)</span> </li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/annual/pdf/sec9_3.pdf" title="Nuclear generator licensing data"> <span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/annual/xls/stb0901.xls" title="Nuclear generator licensing data"> <span class="ico xls"><span>XLS</span></span></a></li>
            </ul>
            <ul>
                <li class="head">International nuclear data</li>
                <li><span class="source">Data from:</span></li>
                <li>
                    <ul>
                        <li><a href="/international/data/world">International Energy Statistics</a></li>
                        <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=000000000000000000000000000004&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Nuclear generation</a></li>
                        <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=0000000000000000000002&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Nuclear capacity</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <h3><a name="uranium"></a>Uranium (nuclear fuel)</h3>
        <div class="accordion-content">
            <ul>
                <li class="head"><a href="/uranium/production/annual/ureserve.php">Uranium reserves estimates</a></li>
                <li><span class="release-date">Release date:</span> <span class="date">May 17, 2021</span><span class="pipe">|</span><span class="source">Data from:</span> <a href="/uranium/production/annual/">Domestic Uranium Production Report - Annual</a></li>
                <li>Estimates of uranium reserves as of end of year</li>
            </ul>
            <ul>
                <li class="head">Uranium production</li>
                <li class="list-spacer"></li>
                <li>Annual</li>
                <li><span class="release-date">Release date:</span> <span class="date">May 17, 2021</span><span class="pipe">|</span><span class="source">Data from:</span> <a href="/uranium/production/annual/">Domestic Uranium Production Report - Annual</a></li>
                <li class="list-spacer"></li>
                <li><a href="/uranium/production/annual/usummary.php">Summary uranium production data</a>, back to 1993</li>
                <li><span class="formats">Available formats:</span> <a href="/uranium/production/annual/pdf/usummarytbl9.pdf" title="Summary uranium production data, back to 1993"><span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/production/annual/xls/usummarytbl9.xls" title="Summary uranium production data, back to 1993"><span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li><a href="/uranium/production/annual/umills.php">U.S. uranium mills by owner, capacity, and operating status</a> </li>
                <li><span class="formats">Available formats:</span> <a href="/uranium/production/annual/pdf/umillstbl4.pdf" title="U.S. uranium mills by owner, capacity, and operating status"> <span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/production/annual/xls/umillstbl4.xls" title="U.S. uranium mills by owner, capacity, and operating status"> <span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li><a href="/uranium/production/annual/uisl.php">U.S. uranium in-situ-leach plants by owner, capacity, and operating status</a></li>
                <li><span class="formats">Available formats:</span> <a href="/uranium/production/annual/pdf/uisltbl5.pdf" title="U.S. uranium in-situ-leach plants by owner, capacity, and operating status"><span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/production/annual/xls/uisltbl5.xls" title="U.S. uranium in-situ-leach plants by owner, capacity, and operating status"><span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Quarterly</li>
                <li><span class="release-date">Release date:</span><span class="date">
                        <?php include('uranium/production/quarterly/includes/releasedate.inc') ?>
                    </span><span class="pipe">|</span><span class="source">Data from:</span><a href="/uranium/production/quarterly/">Domestic Uranium Production Report - Quarterly</a> </li>
                <li class="list-spacer"></li>
                <li><a href="/uranium/production/quarterly/qupdtable1.php">Total production of uranium concentrate</a> </li>
                <li><span class="formats">Available formats:</span> <a href="/uranium/production/quarterly/pdf/qupd_tbl1.pdf" title="Total production of uranium concentrate"><span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/production/quarterly/xls/qupd_tbl1.xls" title="Total production of uranium concentrate"> <span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li><a href="/uranium/production/quarterly/qupdtable2.php">Number of uranium mills and plants producing uranium concentrate in the United States</a> </li>
                <li><span class="formats">Available formats:</span> <a href="http://www.eia.gov/uranium/production/quarterly/pdf/qupd_tbl2.pdf" title="Number of uranium mills and plants producing uranium concentrate in the United States"> <span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/production/quarterly/xls/qupd_tbl2.xls" title="Number of uranium mills and plants producing uranium concentrate in the United States"> <span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li><a href="/uranium/production/quarterly/qupdtable3.php">U.S. uranium mills by owner, capacity, and operating status</a> </li>
                <li><span class="formats">Available formats:</span> <a href="/uranium/production/quarterly/pdf/qupd_tbl3.pdf" title="U.S. uranium mills by owner, capacity, and operating status"> <span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/production/quarterly/xls/qupd_tbl3.xls" title="U.S. uranium mills by owner, capacity, and operating status"> <span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li><a href="/uranium/production/quarterly/qupdtable4.php" class="no-border">U.S. uranium in-situ-leach plants by owner, capacity, and operating status</a> </li>
                <li><span class="formats">Available formats:</span> <a href="/uranium/production/quarterly/pdf/qupd_tbl4.pdf" title="U.S. uranium in-situ-leach plants by owner, capacity, and operating status"><span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/production/quarterly/xls/qupd_tbl4.xls" title="U.S. uranium in-situ-leach plants by owner, capacity, and operating status"><span class="ico xls"><span>XLS</span></span></a></li>
            </ul>
            <ul>
                <li class="head"><a href="/uranium/marketing/table1.php">Uranium purchases</a></li>
                <li><span class="release-date">Release date:</span>
                    <?php include('uranium/marketing/includes/uma-new-header.inc') ?></span><span class="pipe">|</span><span class="source">Data from:</span> <a href="/uranium/marketing/table1.php">Uranium Marketing Annual Report</a>
                </li>
                <li class="list-spacer"></li>
                <li>Quantity of uranium purchased by owners and operators of U.S. civilian nuclear power reactors</li>
                <li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartable1figures1n2.pdf"> <span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/marketing/xls/umartable1figures1n2.xls"> <span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li class="head"> <a href="/uranium/marketing/summarytable1b.php">Uranium price</a> </li>
                <li><span class="release-date">Release date:</span>
                    <?php include('uranium/marketing/includes/uma-new-header.inc') ?></span><span class="pipe">|</span><span class="source">Data from:</span> <a href="/uranium/marketing/table1.php">Uranium Marketing Annual Report</a>
                </li>
                <li>Weighted-average price of uranium purchased by owners and operators of U.S. civilian nuclear power reactors</li>
                <li><span class="formats">Available formats:</span> <a href="/uranium/marketing/pdf/umartableS1bfigureS2.pdf"> <span class="ico pdf"><span>PDF</span></span></a><a href="/uranium/marketing/xls/umartableS1bfigureS2.xls"> <span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li>...more uranium data from: <a href="/totalenergy/data/browser/index.php?tbl=T08.02#/?f=M&start=200001">Monthly Energy Review</a></li>
            </ul>
        </div>
        <h3><a name="spentfuel"></a>Spent nuclear fuel (radioactive waste)</h3>
        <div class="accordion-content">
            <ul>
                <li class="head"><a href="/nuclear/spent_fuel/">Spent nuclear fuel discharged and stored at commercial sites</a></li>
                <li><span class="release-date">Release date:</span> <span class="date">March, 2021</span><span class="pipe">|</span><span class="source">Data from:</span> form <a href="/survey/#gc-859">GC-859, Nuclear Fuel Data Survey</a></li>
                <li>Data cover all spent nuclear fuel discharged from and stored at commercial sites through December 31, 2017</li>
                <li class="list-spacer"></li>
                <li><a href="/nuclear/spent_fuel/ussnftab3.php">Annual commercial spent fuel discharges and burnup, 1968 - December 31, 2017 </a> </li>
                <li><span class="release-date">Release date:</span> <span class="date">March, 2021</span><span class="pipe">|</span><span class="source">Data from:</span> form <a href="/survey/#gc-859">GC-859, Nuclear Fuel Data Survey</a></li>
                <li>Number of assemblies, initial uranium content, and average burnup, 1968 - December 31, 2017</li>
                <li class="list-spacer"></li>
                <li><a href="/nuclear/spent_fuel/ussnftab2.php">Detailed spent nuclear fuel data</a></li>
                <li><span class="release-date">Release date:</span> <span class="date">March, 2021</span><span class="pipe">|</span><span class="source">Data from:</span> form <a href="/survey/#gc-859">GC-859, Nuclear Fuel Data Survey</a></li>
            </ul>
        </div>
    </div>
</div>