<h1>About the Commercial Buildings Energy Consumption Survey</h1>
<p>The Commercial Buildings Energy Consumption Survey (CBECS) is a national sample survey that collects information on the stock of U.S. commercial buildings, including their energy-related building characteristics and energy usage data (consumption and expenditures). Commercial buildings include all buildings in which at least half of the floorspace is used for a purpose that is not residential, industrial, or agricultural. By this definition, CBECS includes building types that might not traditionally be considered commercial, such as schools, hospitals, correctional institutions, and buildings used for religious worship, in addition to traditional commercial buildings such as stores, restaurants, warehouses, and office buildings.</p>

<p>CBECS is conducted in two phases:</p>
<p><strong>Phase 1 is the Buildings Survey</strong>, which collects building characteristics (such as building size and use, structural characteristics, energy sources and uses, and energy-using equipment) and energy usage data (annual consumption and costs) from a respondent at the building, either by an interviewer or using a web questionnaire.</p>
<p><strong>Phase 2 is the Energy Supplier Survey (ESS)</strong>, which is a follow-up survey of the energy providers for buildings that responded in Phase 1. Providers of electricity, natural gas, heating oil (which includes fuel oil, kerosene, and diesel), and district heat (steam or hot water) supply monthly energy usage data for each building. The energy data are collected using a secure website that offers several reporting options designed to minimize reporting burden.</p>
<p>The first CBECS was conducted in 1979; all CBECS data are available on this website. <?php /*CBECS is currently conducted on a quadrennial  basis.*/ ?></p>
<p>Users of the CBECS data are  diverse.  Among many others, they  include:</p>


  <ul>
    <li>Building owners and  managers (for benchmarking)</li>
    <li>Energy  modelers (for forecasting)</li>
    <li>Product developers (to  gauge market potential)</li>
    <li>Government leaders (to  formulate policy)</li>
    <li>Energy Star (as the  foundation for their rating system targets)</li>
  </ul>
