<!--data for Residential - RECS -->
<?php /* 
<h2>Consumption &amp; Expenditures (C&amp;E) Tables</h2>

<p>
<ul>
<li>Data will be released in early 2023</li>
</p>
*/ ?>




<h2>Consumption &amp; Expenditures (C&amp;E) Tables</h2>

<p>The six groups represent increasing level of detail:</p>

<ul>
  <li><strong>Summary statistics:</strong> National and regional totals and intensities across all fuels and end uses
  </li>
  <li><strong>by Fuel:</strong> Totals and averages for each major fuel: electricity, natural gas, LPG/propane, fuel
    oil, and kerosene</li>
  <li><strong>by End uses:</strong> Totals and averages for each major end use: space heating, water heating,
    air-conditioning, refrigerators, and other (other appliances, electronics, and lighting)</li>
  <li><strong>by End uses by fuel:</strong> Totals and averages for each fuel by end use. For example: natural gas space
    heating</li>
  <li><strong>Detailed end-use consumption and expenditure estimates:</strong> totals and averages for an expanded list
    of end uses</li>
  <li><strong>Wood:</strong> types of wood used, and household consumption totals and averages</li>
  <li><strong>Monthly consumption and expenditure estimates:</strong> totals and averages for electricity and natural gas, selected end uses</li>
</ul>

<!--<p style="background-color:#CCEAF7; height: 40px; padding:7px;">
All tables were updated in March 2024 to correct the payment method for energy bills rows. Estimates for the second and third rows within that category were inadvertently switched.</p>-->

<span class="condaterange"><a class="no-border expandall">+ EXPAND ALL</a></span>
<table width="100%" class="contable">

  <thead id="summary">
    <tr>
      <th colspan="2"><a name="summary"></a>Summary statistics</th>
      <?php /*<th width="20%"><span class="right"><a href="c&e/ce1.zip" class="ico_zip"><span
              hidden="Summary statistics"></span>
            ZIP (all tables)</a></span></th> */ ?>
    </tr>
  </thead>

  <tr class="summary">
    <!--<td>Release date: March 2023<br>
      Final Release Date: March 2024</td>
    <td>&nbsp;</td>-->

  <tr class="white_first">
    <td style="color: #adadad">CE1.1 Summary consumption and expenditures in the U.S.<br> - totals and intensities</strong></td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce1.1.pdf" class="ico_pdf"
          title="Download CE1.1 consumption and expenditures in the U.S.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce1.1.xlsx" class="ico_xls"
          title="Download CE1.1 consumption and expenditures in the U.S.xlsx">&nbsp;<span
            hidden="Summary consumption and expenditures in the U.S. - totals and intensities"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE1.2 Summary consumption and expenditures in the Northeast<br> - totals and intensities</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce1.2.pdf" class="ico_pdf"
          title="Download CE1.2  consumption and expenditures in the Northeast.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce1.2.xlsx" class="ico_xls"
          title="Download CE1.2 consumption and expenditures in the Northeast.xlsx">&nbsp;<span hidden="Summary consumption and expenditures in the Northeast - totals and intensities
"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE1.3 Summary consumption and expenditures in the Midwest<br> - totals and intensities</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce1.3.pdf" class="ico_pdf"
          title="Download CE1.3 consumption and expenditures in the Midwest">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce1.3.xlsx" class="ico_xls" title="Download CE1.3 Midwest Summary Site">&nbsp;<span
            hidden="Summary consumption and expenditures in the Midwest - totals and intensities"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE1.4 Summary consumption and expenditures in the South<br> - totals and intensities</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce1.4.pdf" class="ico_pdf"
          title="Download CE1.4 South Summary Site">PDF</a>&nbsp;&nbsp;<a href="c&e/xls/ce1.4.xlsx" class="ico_xls"
          title="Download CE1.4 consumption and expenditures in the South">&nbsp;<span
            hidden="Summary consumption and expenditures in the South - totals and intensities"></span>XLSX</a></span>
    </td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE1.5 Summary consumption and expenditures in the West<br> - totals and intensities</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce1.5.pdf" class="ico_pdf"
          title="Download CE1.5 Summary consumption and expenditures in the West">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce1.5.xlsx" class="ico_xls"
          title="Download CE1.5 Summary consumption and expenditures in the West - totals and intensities">&nbsp;<span
            hidden="Summary consumption and expenditures in the West - totals and intensities"></span>XLSX</a></span>
    </td>-->
  </tr>

  <thead id="by fuel">

    <tr>
      <th colspan="2"><a name="by fuel"></a>by Fuel (includes Btu and physical unit tabs)</th>
      <?php /* <th><span class="right"><a href="c&e/ce2.ZIP" class="ico_zip">ZIP (all tables)</a></span></th><?php /*
    </tr>*/ ?>
  </thead>

  <tr class="by fuel">
    <!--<td>Release date: March 2023<br>
      Final Release Date: March 2024</td>
    <td>&nbsp;</td>-->
  </tr>
  <tr class="white_first">
    <td style="color: #adadad">CE2.1 Fuel consumption in the U.S. - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.1.pdf" class="ico_pdf"
          title="Download CE2.1 Fuel consumption in the U.S. - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.1.xlsx" class="ico_xls"
          title="Download CE2.1 Fuel consumption in the U.S. - totals and averages.xlsx">&nbsp;<span
            hidden="Fuel consumption in the U.S. - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.2 Fuel consumption in the Northeast - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.2.pdf" class="ico_pdf"
          title="Download CE2.2 Fuel consumption in the Northeast - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.2.xlsx" class="ico_xls"
          title="Download CE2.2 Fuel consumption in the Northeast - totals and averages">&nbsp;<span
            hidden="Fuel consumption in the Northeast - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.3 Fuel consumption in the Midwest - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.3.pdf" class="ico_pdf"
          title="Download CE2.3 Fuel consumption in the Midwest - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.3.xlsx" class="ico_xls"
          title="Download CE2.3 Fuel consumption in the Midwest - totals and averages">&nbsp;<span
            hidden="Fuel consumption in the Midwest - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.4 Fuel consumption in the South - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.4.pdf" class="ico_pdf"
          title="Download CE2.4 Fuel consumption in the South - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.4.xlsx" class="ico_xls"
          title="Download CE2.4 Fuel consumption in the South - totals and averages">&nbsp;<span
            hidden="Fuel consumption in the South - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.5 Fuel consumption in the West - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.5.pdf" class="ico_pdf"
          title="Download CE2.5 Fuel consumption in the West - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.5.xlsx" class="ico_xls"
          title="Download CE2.5 Fuel consumption in the West - totals and averages">&nbsp;<span
            hidden="Fuel consumption in the West - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.6 Fuel expenditures in the U.S. - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.6.pdf" class="ico_pdf"
          title="Download CE2.6 Fuel expenditures in the U.S. - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.6.xlsx" class="ico_xls"
          title="Download CE2.6 Fuel expenditures in the U.S. - totals and averages">&nbsp;<span
            hidden="Fuel expenditures in the U.S. - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.7 Fuel expenditures in the Northeast - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.7.pdf" class="ico_pdf"
          title="Download CE2.7 Fuel expenditures in the Northeast - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.7.xlsx" class="ico_xls" title="Download CE2.7 End-Use Expenditures_Northeast">&nbsp;<span
            hidden="Fuel expenditures in the Northeast - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.8 Fuel expenditures in the Midwest - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.8.pdf" class="ico_pdf"
          title="Download CE2.8 Fuel expenditures in the Midwest - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.8.xlsx" class="ico_xls"
          title="Download CE2.8 Fuel expenditures in the Midwest - totals and averages.xlsx">&nbsp;<span
            hidden="Fuel expenditures in the Midwest - totals and averages"></span>XLSX</a></span></td>-->

  <tr>
    <td style="color: #adadad">CE2.9 Fuel expenditures in the South - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.9.pdf" class="ico_pdf"
          title="Download CE2.9 Fuel expenditures in the South - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.9.xlsx" class="ico_xls"
          title="Download CE2.9 Fuel expenditures in the South - totals and averages">&nbsp;<span
            hidden="Fuel expenditures in the South - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.10 Fuel expenditures in the West - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce2.10.pdf" class="ico_pdf"
          title="Download CE2.10 Fuel expenditures in the West - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce2.10.xlsx" class="ico_xls"
          title="Download CE2.10 Fuel expenditures in the West - totals and averages">&nbsp;<span
            hidden="Fuel expenditures in the West - totals and averages"></span>XLSX</a></span></td>-->
  </tr>


  <thead id="by end uses">
    <th colspan="2"><a name="by end uses"></a>by End uses</th>
    <?php /* <th><span class="right"><a href="c&e/ce3.zip" class="ico_zip">ZIP (all tables)</a></span></th>*/ ?>
  </thead>
  <tr class="by end uses">
     <!--<td>Release date: June 2023<br>
      Final Release Date: March 2024</td>
    <td>&nbsp;</td>-->
  </tr>
 <tr class="white_first">
    <td style="color: #adadad">CE3.1 Annual household site end-use consumption in the U.S. - totals and averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.1.pdf" class="ico_pdf"
          title="Download CE3.1 Annual household site end-use consumption in the U.S. - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.1.xlsx" class="ico_xls"
          title="Download CE3.1 Annual household site end-use consumption in the U.S. - totals and averages.xlsx">&nbsp;<span
            hidden="Annual household site end-use consumption in the U.S. - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.2 Annual household site end-use consumption in the Northeast - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.2.pdf" class="ico_pdf"
          title="Download CE3.2 Annual household site end-use consumption in the Northeast - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.2.xlsx" class="ico_xls"
          title="Download CE3.2 Annual household site end-use consumption in the Northeast - totals and averages.xlsx">&nbsp;<span
            hidden="Annual household site end-use consumption in the Northeast - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.3 Annual household site end-use consumption in the Midwest - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.3.pdf" class="ico_pdf"
          title="Download CE3.3 Annual household site end-use consumption in the Midwest - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.3.xlsx" class="ico_xls"
          title="Download CE3.3 Annual household site end-use consumption in the Midwest - totals and averages.xlsx">&nbsp;<span
            hidden="Annual household site end-use consumption in the Midwest - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.4 Annual household site end-use consumption in the South - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.4.pdf" class="ico_pdf"
          title="Download CE3.4 Annual household site end-use consumption in the South - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.4.xlsx" class="ico_xls"
          title="Download CE3.4 Annual household site end-use consumption in the South - totals and averages.xlsx">&nbsp;<span
            hidden="Annual household site end-use consumption in the South - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.5 Annual household site end-use consumption in the West - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.5.pdf" class="ico_pdf"
          title="Download CE3.5 Annual household site end-use consumption in the West - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.5.xlsx" class="ico_xls"
          title="Download CE3.5 Annual household site end-use consumption in the West - totals and averages.xlsx">&nbsp;<span
            hidden="Annual household site end-use consumption in the West - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.6 Annual household end-use expenditures in the U.S. - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.6.pdf" class="ico_pdf"
          title="Download CE3.6 Annual household end-use expenditures in the U.S. - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.6.xlsx" class="ico_xls"
          title="Annual household end-use expenditures in the U.S. - totals and averages.xlsx">&nbsp;XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.7 Annual household end-use expenditures in the Northeast - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.7.pdf" class="ico_pdf"
          title="Download CE3.7 Annual household end-use expenditures in the Northeast - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.7.xlsx" class="ico_xls"
          title="Download CE3.7 Annual household end-use expenditures in the Northeast - totals and averages.xlsx">&nbsp;XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.8 Annual household end-use expenditures in the Midwest - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.8.pdf" class="ico_pdf"
          title="Download CE3.8 Annual household end-use expenditures in the Midwest - totals and averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.8.xlsx" class="ico_xls"
          title="Download CE3.8 Annual household end-use expenditures in the Midwest - totals and averages.xlsx">&nbsp;<span
            hidden="Annual household end-use expenditures in the Midwest - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.9 Annual household end-use expenditures in the South - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.9.pdf" class="ico_pdf"
          title="Download CE3.9 Annual household end-use expenditures in the South - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.9.xlsx" class="ico_xls"
          title="Download CE3.9 Annual household end-use expenditures in the South - totals and averages">&nbsp;<span
            hidden="Annual household end-use expenditures in the South - totals and averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.10 Annual household end-use expenditures in the West - totals and averages</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce3.10.pdf" class="ico_pdf"
          title="Annual household end-use expenditures in the West - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce3.10.xlsx" class="ico_xls"
          title="Annual household end-use expenditures in the West - totals and averages">&nbsp;<span
            hidden="Annual household end-use expenditures in the West - totals and averages"></span>XLSX</a></span></td>-->
  </tr>

  <thead id="by End uses by fuel (includes Btu and physical unit tabs)">
    <tr>
      <th colspan="2"><a name="by End uses by fuel"></a>by End uses by fuel (includes Btu and physical unit tabs)</th>
      <?php /*<th><span class="right"><a href="c&e/ce4.zip" class="ico_zip">ZIP (all tables)</a></span></th>*/ ?>
  </thead>
  </tr>
  <tr class="by End uses by fuel">
    <!--<td>Release date: June 2023<br>
      Final Release Date: March 2024</td>
    <td>&nbsp;</td>-->
  </tr>
  <tr class="white_first">
    <td style="color: #adadad">CE4.1 Annual household site end-use consumption by fuel in the U.S. - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.1.pdf" class="ico_pdf"
          title="Download CE4.1 Annual household site end-use consumption by fuel in the U.S. - totals.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.1.xlsx" class="ico_xls"
          title="Download CE4.1 Annual household site end-use consumption by fuel in the U.S. - totals.xlsx">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the U.S. - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.2 Annual household site end-use consumption by fuel in the Northeast - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.2.pdf" class="ico_pdf"
          title="Download CE4.2 Annual household site end-use consumption by fuel in the Northeast - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.2.xlsx" class="ico_xls"
          title="Download CE4.2 Annual household site end-use consumption by fuel in the Northeast - totals">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the Northeast - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.3 Annual household site end-use consumption by fuel in the Midwest - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.3.pdf" class="ico_pdf"
          title="Download CE4.3 Annual household site end-use consumption by fuel in the Midwest - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.3.xlsx" class="ico_xls"
          title="Download CE4.3 Annual household site end-use consumption by fuel in the Midwest - totals">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the Midwest - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.4 Annual household site end-use consumption by fuel in the South - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.4.pdf" class="ico_pdf"
          title="Download CE4.4 Annual household site end-use consumption by fuel in the South - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.4.xlsx" class="ico_xls"
          title="Download CE4.4 Annual household site end-use consumption by fuel in the South - totals">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the South - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.5 Annual household site end-use consumption by fuel in the West - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.5.pdf" class="ico_pdf"
          title="Download CE4.5 Annual household site end-use consumption by fuel in the West - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.5.xlsx" class="ico_xls"
          title="Download CE4.5 Annual household site end-use consumption by fuel in the West - totals">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the West - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.6 Annual household site end-use consumption by fuel in the U.S. - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.6.pdf" class="ico_pdf"
          title="Download CE4.6 Annual household site end-use consumption by fuel in the U.S. - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.6.xlsx" class="ico_xls"
          title="Download CE4.6 EAnnual household site end-use consumption by fuel in the U.S. - averages">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the U.S. - averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.7 Annual household site end-use consumption by fuel in the Northeast - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.7.pdf" class="ico_pdf"
          title="Download CE4.7 Annual household site end-use consumption by fuel in the Northeast - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.7.xlsx" class="ico_xls"
          title="Download CE4.7 Annual household site end-use consumption by fuel in the Northeast - averages">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the Northeast - averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.8 Annual household site end-use consumption by fuel in the Midwest - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.8.pdf" class="ico_pdf"
          title="Annual household site end-use consumption by fuel in the Midwest - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.8.xlsx" class="ico_xls"
          title="Annual household site end-use consumption by fuel in the Midwest - averages">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the Midwest - averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.9 Annual household site end-use consumption by fuel in the South - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.9.pdf" class="ico_pdf"
          title="Download CE4.9 EAnnual household site end-use consumption by fuel in the South - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.9.xlsx" class="ico_xls"
          title="Annual household site end-use consumption by fuel in the South - averages">&nbsp;<span
            hidden="Annual household site end-use consumption by fuel in the South - averages"></span>XLSX</a></span></td>-->
  </tr>

  <td style="color: #adadad">CE4.10 Annual household site end-use consumption by fuel in the West - averages</td>
<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><span class="right"><a href="c&e/pdf/ce4.10.pdf" class="ico_pdf"
        title="Annual household site end-use consumption by fuel in the West - averages">PDF</a>&nbsp;&nbsp;<a
        href="c&e/xls/ce4.10.xlsx" class="ico_xls"
        title="Annual household site end-use consumption by fuel in the West - averages">&nbsp;<span
          hidden="Annual household site end-use consumption by fuel in the West - averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.11 Annual household end-use expenditures by fuel in the U.S. - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.11.pdf" class="ico_pdf"
          title="Annual household end-use expenditures by fuel in the U.S. - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.11.xlsx" class="ico_xls"
          title="Annual household end-use expenditures by fuel in the U.S. - totals">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the U.S. - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.12 Annual household end-use expenditures by fuel in the Northeast - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.12.pdf" class="ico_pdf"
          title="Annual household end-use expenditures by fuel in the Northeast - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.12.xlsx" class="ico_xls"
          title="Annual household end-use expenditures by fuel in the Northeast - totals">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the Northeast - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.13 Annual household end-use expenditures by fuel in the Midwest - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.13.pdf" class="ico_pdf"
          title="Annual household end-use expenditures by fuel in the Midwest - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.13.xlsx" class="ico_xls"
          title="Download CE4.13 Annual household end-use expenditures by fuel in the Midwest - totals">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the Midwest - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.14 Annual household end-use expenditures by fuel in the South - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.14.pdf" class="ico_pdf"
          title="Annual household end-use expenditures by fuel in the South - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.14.xlsx" class="ico_xls"
          title="Annual household end-use expenditures by fuel in the South - totals">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the South - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.15 Annual household end-use expenditures by fuel in the West - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.15.pdf" class="ico_pdf"
          title="Annual household end-use expenditures by fuel in the West - totals.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.15.xlsx" class="ico_xls"
          title="Annual household end-use expenditures by fuel in the West - totals.xlsx">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the West - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.16 Annual household end-use expenditures by fuel in the U.S. - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.16.pdf" class="ico_pdf"
          title="Annual household end-use expenditures by fuel in the U.S. - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.16.xlsx" class="ico_xls"
          title="Annual household end-use expenditures by fuel in the U.S. - averages">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the U.S. - averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.17 Annual household end-use expenditures by fuel in the Northeast - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.17.pdf" class="ico_pdf"
          title="Download CE4.17 EAnnual household end-use expenditures by fuel in the Northeast - averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.17.xlsx" class="ico_xls"
          title="Download CE4.17 EAnnual household end-use expenditures by fuel in the Northeast - averages.xlsx">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the Northeast - averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.18 Annual household end-use expenditures by fuel in the Midwest - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.18.pdf" class="ico_pdf"
          title="Download CE4.18 Annual household end-use expenditures by fuel in the Midwest - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.18.xlsx" class="ico_xls"
          title="Download CE4.18 Annual household end-use expenditures by fuel in the Midwest - averages">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the Midwest - averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.19 Annual household end-use expenditures by fuel in the South - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.19.pdf" class="ico_pdf"
          title="Download CE4.19 Annual household end-use expenditures by fuel in the South - averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.19.xlsx" class="ico_xls"
          title="Download CE4.19 Annual household end-use expenditures by fuel in the South - averages.xlsx">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the South - averages"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.20 Annual household end-use expenditures by fuel in the West - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce4.20.pdf" class="ico_pdf"
          title="Annual household end-use expenditures by fuel in the West - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce4.20.xlsx" class="ico_xls"
          title="Annual household end-use expenditures by fuel in the West - averages">&nbsp;<span
            hidden="Annual household end-use expenditures by fuel in the West - averages"></span>XLSX</a></span></td>-->
  </tr> 


  <thead id="Detailed end-use consumption and expenditure estimates">

    <tr>
      <th colspan="2">Detailed end-use consumption and expenditure estimates</th>
      <?php /*<th><span class="right"><a href="c&e/ce5.zip" class="ico_zip">ZIP (all tables)</a></span></th>*/ ?>
  </thead>

  </tr>
  </thead>
  <tr>
 <!--<td>Release date: June 2023<br>
      Final Release Date: March 2024</td>
    <td>&nbsp;</td>-->
  </tr>

  <tr class="white_first">
    <td style="color: #adadad">CE5.1a Detailed household site electricity end-use consumption, part 1 - totals</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.1a.pdf" class="ico_pdf"
          title="Download CE5.1a Detailed household site electricity end-use consumption, part 1 - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.1a.xlsx" class="ico_xls"
          title="Download CE5.1a DDetailed household site electricity end-use consumption, part 1 - totals">&nbsp;<span
            hidden="Detailed household site electricity end-use consumption, part 1 - totals"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.1b Detailed household site electricity end-use consumption, part 2 - totals</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.1b.pdf" class="ico_pdf"
          title="Download CE5.1b Detailed household site electricity end-use consumption, part 2 - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.1b.xlsx" class="ico_xls"
          title="Download CE5.1b Detailed household site electricity end-use consumption, part 2 - totals">&nbsp;<span
            hidden="Detailed household site electricity end-use consumption, part 2 - totals"></span>XLSX</a></td>-->
  </tr>

  <tr>
    <td style="color: #adadad">CE5.2 Detailed household natural gas and propane end-use consumption - totals</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.2.pdf" class="ico_pdf"
          title="Download CE5.2 Detailed household natural gas and propane end-use consumption - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.2.xlsx" class="ico_xls"
          title="Download CE5.2 Detailed household natural gas and propane end-use consumption - totals.xlsx">&nbsp;<span
            hidden="Detailed household natural gas and propane end-use consumption - totals"></span>XLSX</a></td>-->
  </tr>

  <tr>
    <td style="color: #adadad">CE5.3a Detailed household site electricity end-use consumption, part 1 - averages</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.3a.pdf" class="ico_pdf"
          title="Detailed household site electricity end-use consumption, part 1 - averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.3a.xlsx" class="ico_xls"
          title="Download CE5.3a DDetailed household site electricity end-use consumption, part 1 - averages.xlsx">&nbsp;<span
            hidden="Detailed household site electricity end-use consumption, part 1 - averages"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.3b Detailed household site electricity end-use consumption, part 2 - averages</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.3b.pdf" class="ico_pdf"
          title="Download CE5.3b Detailed household site electricity end-use consumption, part 2 - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.3b.xlsx" class="ico_xls"
          title="Download CE5.3b Detailed household site electricity end-use consumption, part 2 - averages">&nbsp;<span
            hidden="Detailed household site electricity end-use consumption, part 2 - averages"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.4 Detailed household natural gas and propane end-use consumption - averages</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.4.pdf" class="ico_pdf"
          title="Download CE5.4 DDetailed household natural gas and propane end-use consumption - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.4.xlsx" class="ico_xls"
          title="Download CE5.4 Detailed household natural gas and propane end-use consumption - averages">&nbsp;<span
            hidden="Detailed household natural gas and propane end-use consumption - averages"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.5a Detailed household electricity end-use expenditures, part 1 - totals</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.5a.pdf" class="ico_pdf"
          title="Download CE5.5a Detailed household electricity end-use expenditures, part 1 - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.5a.xlsx" class="ico_xls"
          title="Download CE5.5a Detailed household electricity end-use expenditures, part 1 - totals">&nbsp;<span
            hidden="Detailed household electricity end-use expenditures, part 1 - totals"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.5b Detailed household electricity end-use expenditures, part 2 - totals</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.5b.pdf" class="ico_pdf"
          title="Download CE5.5b Detailed household electricity end-use expenditures, part 2 - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.5b.xlsx" class="ico_xls"
          title="Download CE5.5b Detailed household electricity end-use expenditures, part 2 - totals">&nbsp;<span
            hidden="Detailed household electricity end-use expenditures, part 2 - totals"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.6 Detailed household natural gas and propane end-use expenditures - totals</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.6.pdf" class="ico_pdf"
          title="Download CE5.6 Detailed household natural gas and propane end-use expenditures - totals">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.6.xlsx" class="ico_xls"
          title="Download CE5.6 Detailed household natural gas and propane end-use expenditures - totals">&nbsp;<span
            hidden="Detailed household natural gas and propane end-use expenditures - totals"></span>XLSX</a></span></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.7a Detailed household electricity end-use expenditures, part 1 - averages</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.7a.pdf" class="ico_pdf"
          title="Download CE5.7a Detailed household electricity end-use expenditures, part 1 - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.7a.xlsx" class="ico_xls"
          title="Download CE5.7a Detailed household electricity end-use expenditures, part 1 - averages">&nbsp;<span
            hidden="Detailed household electricity end-use expenditures, part 1 - averages"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.7b Detailed household electricity end-use expenditures, part 2 - averages</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.7b.pdf" class="ico_pdf"
          title="Download CE5.7b Detailed household electricity end-use expenditures, part 2 - averages.pdf">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.7b.xlsx" class="ico_xls"
          title="Download CE5.7b Detailed household electricity end-use expenditures, part 2 - averages">&nbsp;<span
            hidden="Detailed household electricity end-use expenditures, part 2 - averages"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.8 Detailed household natural gas and propane end-use expenditures - averages</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/ce5.8.pdf" class="ico_pdf"
          title="Download CE5.8 Detailed household natural gas and propane end-use expenditures - averages">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce5.8.xlsx" class="ico_xls"
          title="Download CE5.8 Detailed household natural gas and propane end-use expenditures - averages">&nbsp;<span
            hidden="Detailed household natural gas and propane end-use expenditures - averages"></span>XLSX</a></td>-->
  </tr> 

<?php /*
  <thead id="Space heating consumption by main heating fuel">

    <tr>
      <th>Wood</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tr>
    <td>Data will be released by June 2023</td>
    <td>&nbsp;</td>
  </tr>

  
  <tr>
    <td>Release date: May 2018</td>
    <td>&nbsp;</td>
  </tr>
  <tr class="white_first">
    <td> CE6.1 <strong>Average space heating consumption</strong> by main heating fuel </td>
    <td><span class="right"><a href="../2020/c&e/pdf/ce6.1.pdf" class="ico_pdf"
          title="Download CE6.1 Average space heating consumption by main heating fuel">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce6.1.xlsx" class="ico_xls"
          title="Download CE6.1 Average space heating consumption by main heating fuel">&nbsp;<span
            hidden="Average space heating consumption by main heating fuel"></span>XLSX</a></span></td>
  </tr>*/ ?>

  <thead id="wood">

    <tr>
      <th>Wood</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tr>
    <!--<td>Release date: June 2023<br>
      Final Release Date: March 2024</td>
    <td>&nbsp;</td>-->
  </tr>

  <tr class="white_first">
     <tr>
    <td style="color: #adadad">CE7.1 Wood types used</td>
		   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
   <!--<td><span class="right"><a href="../2020/c&e/pdf/ce7.1.pdf" class="ico_pdf"
          title=Download CE7.1 Wood types used">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce7.1.xlsx" class="ico_xls"
          title="Download Download CE7.1 Wood types used">&nbsp;<span
            hidden="Download CE7.1 Wood types used"></span>XLSX</a></td>-->
  </tr> 
  <tr>
    <td style="color: #adadad">CE7.2 Household wood consumption</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="../2020/c&e/pdf/ce7.2.pdf" class="ico_pdf"
          title="Download CE7.2 Household wood consumption">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/ce7.2.xlsx" class="ico_xls"
          title="Download CE7.2  Household wood consumption">&nbsp;<span
            hidden="CE7.2  Household wood consumption"></span>XLSX</a></td>-->
  </tr> 

 <thead id="estimates">

    <tr>
      <th>Monthly consumption and expenditure estimates</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tr>
    <!--<td>Release date: May 2025</td>
    <td>&nbsp;</td>0-->
  </tr>

  <tr class="white_first">
    <td style="color: #adadad">CE8.1.M.2020 Monthly household site electricity consumption in the United States&mdash;totals, 2020</strong></td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.1.M.2020.TotalSiteElectricityConsumption.pdf" class="ico_pdf"
          title="Download CE8.1.M.2020 Monthly household site electricity consumption in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.1.M.2020.TotalSiteElectricityConsumption.xlsx" class="ico_xls"
          title="Download CE8.1.M.2020 Monthly household site electricity consumption in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.1.M.2020 Monthly household site electricity consumption in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.2.M.2020 Monthly household site electricity space heating consumption in the United States&mdash;totals, 2020</strong></td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.2.M.2020.TotalSpaceHeatingElectricityConsumption.pdf" class="ico_pdf"
          title="Download CE8.2.M.2020 Monthly household site electricity space heating consumption in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.2.M.2020.TotalSpaceHeatingElectricityConsumption.xlsx" class="ico_xls"
          title="Download CE8.2.M.2020 Monthly household site electricity space heating consumption in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.2.M.2020 Monthly household site electricity space heating consumption in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.3.M.2020 Monthly household site electricity cooling consumption in the United States&mdash;totals, 2020</strong></td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.3.M.2020.TotalSpaceCoolingElectricityConsumption.pdf" class="ico_pdf"
          title="Download CE8.3.M.2020 Monthly household site electricity cooling consumption in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.3.M.2020.TotalSpaceCoolingElectricityConsumption.xlsx" class="ico_xls"
          title="Download CE8.3.M.2020 Monthly household site electricity cooling consumption in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.3.M.2020 Monthly household site electricity cooling consumption in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.4.M.2020 Monthly household site electricity water heating consumption in the United States&mdash;totals, 2020</strong></td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.4.M.2020.TotalWaterHeatingElectricityConsumption.pdf" class="ico_pdf"
          title="Download CE8.4.M.2020 Monthly household site electricity water heating consumption in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.4.M.2020.TotalWaterHeatingElectricityConsumption.xlsx" class="ico_xls"
          title="Download CE8.4.M.2020 Monthly household site electricity water heating consumption in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.4.M.2020 Monthly household site electricity water heating consumption in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.5.M.2020 Monthly household site electricity consumption in the United States&mdash;averages, 2020</strong></td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.5.M.2020.AverageSiteElectricityConsumption.pdf" class="ico_pdf"
          title="Download CE8.5.M.2020 Monthly household site electricity consumption in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.5.M.2020.AverageSiteElectricityConsumption.xlsx" class="ico_xls"
          title="Download CE8.5.M.2020 Monthly household site electricity consumption in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.5.M.2020 Monthly household site electricity consumption in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>
 <tr>
    <td style="color: #adadad">CE8.6.M.2020 Monthly household site electricity space heating consumption in the United States&mdash;averages, 2020</strong></td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.6.M.2020.AverageSpaceHeatingElectricityConsumption.pdf" class="ico_pdf"
          title="Download CE8.6.M.2020 Monthly household site electricity space heating consumption in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.6.M.2020.AverageSpaceHeatingElectricityConsumption.xlsx" class="ico_xls"
          title="Download CE8.6.M.2020 Monthly household site electricity space heating consumption in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.6.M.2020 Monthly household site electricity space heating consumption in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>
   <tr>
    <td style="color: #adadad">CE8.7.M.2020 Monthly household site electricity cooling consumption in the United States&mdash;averages, 2020</td>
	   <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.7.M.2020.AverageSpaceCoolingElectricityConsumption.pdf" class="ico_pdf"
          title="Download CE8.7.M.2020 Monthly household site electricity cooling consumption in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.7.M.2020.AverageSpaceCoolingElectricityConsumption.xlsx" class="ico_xls"
          title="Download CE8.7.M.2020 Monthly household site electricity cooling consumption in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.7.M.2020 Monthly household site electricity cooling consumption in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.8.M.2020 Monthly household site electricity water heating consumption in the United States&mdash;averages, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.8.M.2020.AverageWaterHeatingElectricityConsumption.pdf" class="ico_pdf"
          title="Download CE8.8.M.2020 Monthly household site electricity water heating consumption in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.8.M.2020.AverageWaterHeatingElectricityConsumption.xlsx" class="ico_xls"
          title="Download CE8.8.M.2020 Monthly household site electricity water heating consumption in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.8.M.2020 Monthly household site electricity water heating consumption in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
     <td style="color: #adadad">CE8.9.M.2020 Monthly household site electricity expenditure in the United States&mdash;totals, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.9.M.2020.TotalSiteElectricityExpenditures.pdf" class="ico_pdf"
          title="Download CE8.9.M.2020 Monthly household site electricity expenditure in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.9.M.2020.TotalSiteElectricityExpenditures.xlsx" class="ico_xls"
          title="Download CE8.9.M.2020 Monthly household site electricity expenditure in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.9.M.2020 Monthly household site electricity expenditure in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.10.M.2020 Monthly household site electricity expenditures in the United States&mdash;averages, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.10.M.2020.AverageSiteElectricityExpenditures.pdf" class="ico_pdf"
          title="Download CE8.10.M.2020 Monthly household site electricity expenditures in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.10.M.2020.AverageSiteElectricityExpenditures.xlsx" class="ico_xls"
          title="Download CE8.10.M.2020 Monthly household site electricity expenditures in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.10.M.2020 Monthly household site electricity expenditures in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.11.M.2020 Monthly household site natural gas consumption in the United States&mdash;totals, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.11.M.2020.TotalSiteNaturalGasConsumption.pdf" class="ico_pdf"
          title="Download CE8.11.M.2020 Monthly household site natural gas consumption in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.11.M.2020.TotalSiteNaturalGasConsumption.xlsx" class="ico_xls"
          title="Download CE8.11.M.2020 Monthly household site natural gas consumption in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.11.M.2020 Monthly household site natural gas consumption in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.12.M.2020 Monthly household site natural gas space heating consumption in the United States&mdash;totals, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.12.M.2020.TotalSpaceHeatingNaturalGasConsumption.pdf" class="ico_pdf"
          title="Download CE8.12.M.2020 Monthly household site natural gas space heating consumption in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.12.M.2020.TotalSpaceHeatingNaturalGasConsumption.xlsx" class="ico_xls"
          title="Download CE8.12.M.2020 Monthly household site natural gas space heating consumption in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.12.M.2020 Monthly household site natural gas space heating consumption in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.13.M.2020 Monthly household site natural gas water heating consumption in the United States&mdash;totals, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.13.M.2020.TotalWaterHeatingNaturalGasConsumption.pdf" class="ico_pdf"
          title="Download CE8.13.M.2020 Monthly household site natural gas water heating consumption in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.13.M.2020.TotalWaterHeatingNaturalGasConsumption.xlsx" class="ico_xls"
          title="Download CE8.13.M.2020 Monthly household site natural gas water heating consumption in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.13.M.2020 Monthly household site natural gas water heating consumption in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
     <td style="color: #adadad">CE8.14.M.2020 Monthly household site natural gas consumption in the United States&mdash;averages, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.14.M.2020.AverageSiteNaturalGasConsumption.pdf" class="ico_pdf"
          title="Download CE8.14.M.2020 Monthly household site natural gas consumption in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.14.M.2020.AverageSiteNaturalGasConsumption.xlsx" class="ico_xls"
          title="Download CE8.14.M.2020 Monthly household site natural gas consumption in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.14.M.2020 Monthly household site natural gas consumption in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.15.M.2020 Monthly household site natural gas space heating consumption in the United States&mdash;averages, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.15.M.2020.AverageSpaceHeatingNaturalGasConsumption.pdf" class="ico_pdf"
          title="Download CE8.15.M.2020 Monthly household site natural gas space heating consumption in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.15.M.2020.AverageSpaceHeatingNaturalGasConsumption.xlsx" class="ico_xls"
          title="Download CE8.15.M.2020 Monthly household site natural gas space heating consumption in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.15.M.2020 Monthly household site natural gas space heating consumption in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.16.M.2020 Monthly household site natural gas water heating consumption in the United States&mdash;averages, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.16.M.2020.AverageWaterHeatingNaturalGasConsumption.pdf" class="ico_pdf"
          title="Download CE8.16.M.2020 Monthly household site natural gas water heating consumption in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.16.M.2020.AverageWaterHeatingNaturalGasConsumption.xlsx" class="ico_xls"
          title="Download CE8.16.M.2020 Monthly household site natural gas water heating consumption in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.16.M.2020 Monthly household site natural gas water heating consumption in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE8.17.M.2020 Monthly household site natural gas expenditures in the United States&mdash;totals, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.17.M.2020.TotalSiteNaturalGasExpenditures.pdf" class="ico_pdf"
          title="Download CE8.17.M.2020 Monthly household site natural gas expenditures in the United States—totals, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.17.M.2020.TotalSiteNaturalGasExpenditures.xlsx" class="ico_xls"
          title="Download CE8.17.M.2020 Monthly household site natural gas expenditures in the United States—totals, 2020">&nbsp;<span
            hidden="CE8.17.M.2020 Monthly household site natural gas expenditures in the United States—totals, 2020"></span>XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad" style="color: #adadad">CE8.18.M.2020 Monthly household site natural gas expenditures in the United States&mdash;averages, 2020</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="c&e/pdf/CE8.18.M.2020.AverageSiteNaturalGasExpenditures.pdf" class="ico_pdf"
          title="Download CE8.18.M.2020 Monthly household site natural gas expenditures in the United States—averages, 2020">PDF</a>&nbsp;&nbsp;<a
          href="c&e/xls/CE8.18.M.2020.AverageSiteNaturalGasExpenditures.xlsx" class="ico_xls"
          title="Download CE8.18.M.2020 Monthly household site natural gas expenditures in the United States—averages, 2020">&nbsp;<span
            hidden="CE8.18.M.2020 Monthly household site natural gas expenditures in the United States—averages, 2020"></span>XLSX</a></td>-->
  </tr>

</table>


&nbsp;
<div class="clear"></div>
<?php /* 
<div class="weeklies"> <span>
    The public-use microdata file, which contains detailed characteristics, consumption, and expenditures data for each
    2020 RECS case, is available in the microdata tab, for users who would like to produce custom tabulations or perform
    detailed analysis.
  </span> </div>*/ ?>