<?php $locale = 'data'; ?>
<?php $page['year'] = '2024'; ?>
<h2>Housing characteristics tables</h2>

<p>Housing characteristics data were collected in late 2024 and early 2025.</p>
<tr class="summary">
  <span class="condaterange"><a class="no-border expandall">+ EXPAND ALL</a></span>
  <table class="contable" width="100%">
    <thead>
      <tr>
        <th><a name="fueluses" id="fueluses"></a>Fuels used &amp; end uses </th>
        <th width="25%">&nbsp;</th>
      </tr>
    </thead>
    <tr class="summary">
		<td colspan="2">Data will be released in early 2027</td>
      <!--<td colspan="2">Preliminary release date: May 2022</br>
        Final release date: March 2023</td>-->
    </tr>

    <tr class="white_first">
      <td style="color: #adadad">by Housing unit type (HC1.1)</td>
      <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
      <!--<td><a href="hc/pdf/HC1.1<?php /* Fuels Used and End Uses by Housing Unit Type*/ ?>.pdf" class="ico_pdf">PDF</a>
        <a href="hc/xls/HC1.1.xlsx" class="ico_xls right" title="Fuels used & end uses by Housing unit type">
          XLSX</a>
      </td>-->
    </tr>
    <tr>
      <td style="color: #adadad">by Owner/renter status (HC1.2)</td>
      <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
      <!--<td><a href="hc/pdf/HC1.2<?php /*  Fuels Used and End Uses by OwnerRenter*/ ?>.pdf" class="ico_pdf">PDF</a>
        <a href="hc/xls/HC1.2.xlsx" class="ico_xls right" title="Fuels used & end uses by Owner/renter status">XLSX</a>
      </td>-->
    </tr>
    <tr>
      <td style="color: #adadad">by Year of construction (HC1.3)</td>
      <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
      <!--<td><a href="hc/pdf/HC1.3<?php /*  Fuels Used and End Uses by Number of Household Members.*/ ?>.pdf"
          class="ico_pdf">PDF</a>
        <a href="hc/xls/HC1.3.xlsx" class="ico_xls right" title="Fuels used & end uses by Year of construction">XLSX</a>
      </td>-->
    </tr>
    <tr>
      <td style="color: #adadad">by Number of household members (HC1.4)</td>
      <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
      <!--<td><a href="hc/pdf/HC1.4<?php /*  Fuels Used and End Uses by Number of Household Members*/ ?>.pdf"
          class="ico_pdf">PDF</a> <a href="hc/xls/HC1.4.xlsx" class="ico_xls right" title="Fuels used & end uses by Number of household members">
          XLSX</a>
      </td>-->
    </tr>
    <tr>
      <td style="color: #adadad">by Household income (HC1.5)</td>
      <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
      <!--<td> <a href="hc/pdf/HC1.5<?php /*  Fuels Used and End Uses by Household Income*/ ?>.pdf" class="ico_pdf">PDF</a>
        <a href="hc/xls/HC1.5.xlsx" class="ico_xls right" title="Fuels used & end uses by Household income">XLSX</a>
      </td>-->
    </tr>
    <tr>
      <td style="color: #adadad">>by Climate region (HC1.6)</td>
     <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
      <!--<td><a href="hc/pdf/HC1.6<?php /*  Fuels Used and End Uses by Climate Region*/ ?>.pdf" class="ico_pdf">PDF</a>
        <a href="hc/xls/HC1.6.xlsx" class="ico_xls right" title="Fuels used & end uses by Climate region">XLSX</a>
      </td>-->
    </tr>
    <td style="color: #adadad">in the Northeast and Midwest regions (HC1.7)</td>
    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><a href="hc/pdf/HC1.7<?php /*  Fuels Used and End Uses by Climate Region*/ ?>.pdf" class="ico_pdf">PDF</a>
      <a href="hc/xls/HC1.7.xlsx" class="ico_xls right"
        title="Fuels used & end uses in the Northeast and Midwest regions">XLSX</a>
    </td>-->
</tr>
<td style="color: #adadad">in the South and West regions (HC1.8)</td>
<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
<!--<td><a href="hc/pdf/HC1.8<?php /*  Fuels Used and End Uses by Climate Region*/ ?>.pdf" class="ico_pdf">PDF</a>
  <a href="hc/xls/HC1.8.xlsx" class="ico_xls right" title="Fuels used & end uses in the South and West regions">
    XLSX</a>
</td>-->
</tr>
<td style="color: #adadad">in U.S. homes by home size (HC1.9)</a></td>
<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
<!--<td><a href="hc/pdf/HC1.9.pdf" class="ico_pdf">PDF</a>
  <a href="hc/xls/HC1.9.xlsx" class="ico_xls right" title="Fuels used & end uses in U.S. homes by home size">XLSX</a>
</td>-->
</tr>


<thead>
  <tr>
    <th><a name="structural" id="structural"></a>Structural and geographic characteristics</th>
    <th>&nbsp;</th>
  </tr>
</thead>
<tr class="summary">
  <td colspan="2">Preliminary release date: March 2026<!--</br>
    Final release date: March 2023--></td>
</tr>
<tr class="white_first">
  <td>by Housing unit type (HC2.1)</td>
  <td><a href="hc/pdf/HC2.1_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC2.1_2024.xlsx" class="ico_xls right"
      title="Structural and geographic characteristics by Housing unit type">
      XLSX</a>
  </td>
</tr>
<tr>
  <td>by Owner/renter status (HC2.2)</td>
  <td><a href="hc/pdf/HC2.2_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC2.2_2024.xlsx" class="ico_xls right"
      title="Structural and geographic characteristics by Owner/renter status">
      XLSX</a></td>
</tr>
<tr>
  <td>by Year of construction (HC2.3)</td>
  <td><a href="hc/pdf/HC2.3_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC2.3_2024.xlsx" class="ico_xls right"
      title="Structural and geographic characteristics by Year of construction">
      XLSX</a></td>
</tr>
<tr>
  <td>by Number of household members (HC2.4)</td>
  <td><a href="hc/pdf/HC2.4_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC2.4_2024.xlsx" class="ico_xls right"
      title="Structural and geographic characteristics by Number of household members  ">
      XLSX</a></td>
</tr>
<tr>
  <td>by Household income (HC2.5)</a>
  </td>
  <td><a href="hc/pdf/HC2.5_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC2.5_2024.xlsx" class="ico_xls right" title="Structural and geographic characteristics by Household income">XLSX</a></td>
</tr>
<tr>
  <td>by Climate region (HC2.6)</td>
  <td><a href="hc/pdf/HC2.6_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC2.6_2024.xlsx" class="ico_xls right">&nbsp;XLSX</a></td>
</tr>
<tr>
  <td>in the Northeast and Midwest regions (HC2.7)</td>
  <td><a href="hc/pdf/HC2.7_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC2.7_2024.xlsx" class="ico_xls right"
      title="Structural and geographic characteristics in the Northeast and Midwest regions  ">
      XLSX</a></td>
</tr>
<tr>
  <td>in the South and West regions (HC2.8)</td>
  <td><a href="hc/pdf/HC2.8_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC2.8_2024.xlsx" class="ico_xls right"
      title="Structural and geographic characteristics in the South and West regions">XLSX</a></td>
</tr>
<tr>
  <td>of U.S. homes by home size (HC2.9)</a></td>
  <td><a href="hc/pdf/HC2.9_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC2.9_2024.xlsx" class="ico_xls right"
      title="Structural and geographic characteristics in U.S. homes by home size">XLSX</a></td>
</tr>

<thead>
  <tr>
    <th><a name="appliances" id="appliances"></a>Appliances</th>
    <th>&nbsp;</th>
  </tr>
</thead>
<tr class="summary">
  <td colspan="2">Preliminary release date: March 2026<!--</br>
    Final release date: March 2023--></td>
</tr>
<tr class="white_first">
  <td>by Housing unit type (HC3.1)</td>
  <td><a href="hc/pdf/HC3.1_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.1_2024.xlsx" class="ico_xls right" title="Appliances by Housing unit type of">XLSX</a></td>
</tr>
<tr>
  <td>by Owner/renter status (HC3.2)</td>
  <td><a href="hc/pdf/HC3.2_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.2_2024.xlsx" class="ico_xls right" title="Appliances by Owner/renter status">XLSX</a></td>
</tr>
<tr>
  <td>by Year of construction (HC3.3)</td>
  <td><a href="hc/pdf/HC3.3_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.3_2024.xlsx" class="ico_xls right" title="Appliances by Year of construction">
      XLSX</a></td>
</tr>
<tr>
  <td>by Number of household members (HC3.4)</td>
  <td><a href="hc/pdf/HC3.4_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.4_2024.xlsx" class="ico_xls right" title="Appliances by Number of household members">
      XLSX</a></td>
</tr>
<tr>
  <td>by Household income (HC3.5)</td>
  <td><a href="hc/pdf/HC3.5_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.5_2024.xlsx" class="ico_xls right" title="Appliances by Household income">
      XLSX</a></td>
</tr>
<tr>
  <td>by Climate region (HC3.6)</td>
  <td><a href="hc/pdf/HC3.6_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.6_2024.xlsx" class="ico_xls right" title="Appliances by Climate region">
      XLSX</a></td>
</tr>
<tr>
  <td>in the Northeast and Midwest regions (HC3.7)</td>
  <td><a href="hc/pdf/HC3.7_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.7_2024.xlsx" class="ico_xls right" title="Appliances in the Northeast and Midwest regions">XLSX</a></td>
</tr>
<tr>
  <td>in the South and West regions (HC3.8)</td>
  <td><a href="hc/pdf/HC3.8_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.8_2024.xlsx" class="ico_xls right" title="Appliances in the South and West regions">
      XLSX</a></td>
</tr>
<tr>
  <td>in U.S. homes by home size (HC3.9)</a></td>
  <td><a href="hc/pdf/HC3.9_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC3.9_2024.xlsx" class="ico_xls right"
      title="Appliances in U.S. homes by home size">XLSX</a></td>

</tr>
<thead>
  <tr>
    <th><a name="electronics" id="electronics"></a>Electronics</th>
    <th>&nbsp;</th>
  </tr>
</thead>
<tr class="summary">
  <td colspan="2">Preliminary release date: March 2026<!--</br>
    Final release date: March 2023--></td>
</tr>
<tr class="white_first">
  <td>by Housing unit type (HC4.1)</td>
  <td><a href="hc/pdf/HC4.1_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.1_2024.xlsx" class="ico_xls right" title="Electronics by Housing unit type of">
      XLSX</a></td>
</tr>
<tr>
  <td>by Owner/renter status (HC4.2)</td>
  <td><a href="hc/pdf/HC4.2_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.2_2024.xlsx" class="ico_xls right" title="Electronics by Owner/renter status">
      XLSX</a></td>
</tr>
<tr>
  <td>by Year of construction (HC4.3)</td>
  <td><a href="hc/pdf/HC4.3_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.3_2024.xlsx" class="ico_xls right" title="Electronics by Year of construction">
      XLSX</a></td>
</tr>
<tr>
  <td>by Number of household members (HC4.4)</td>
  <td><a href="hc/pdf/HC4.4_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.4_2024.xlsx" class="ico_xls right" title="Electronics by Number of household members">
      XLSX</a></td>
</tr>
<tr>
  <td>by Household income (HC4.5)</td>
  <td><a href="hc/pdf/HC4.5_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.5_2024.xlsx" class="ico_xls right" title="Electronics by Household income">
      XLSX</a></td>
</tr>
<tr>
  <td>by Climate region (HC4.6)</td>
  <td><a href="hc/pdf/HC4.6_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.6_2024.xlsx" class="ico_xls right" title="Electronics by Climate region">
      XLSX</a></td>
</tr>
<tr>
  <td>in the Northeast and Midwest regions (HC4.7)</td>
  <td><a href="hc/pdf/HC4.7_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.7_2024.xlsx" class="ico_xls right" title="Electronics in the Northeast and Midwest regions">XLSX</a></td>
</tr>
<tr>
  <td>in the South and West regions (HC4.8)</td>
  <td><a href="hc/pdf/HC4.8_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.8_2024.xlsx" class="ico_xls right" title="Electronics in the South and West regions">
      XLSX</a></td>
</tr>
<tr>
  <td>in U.S. homes by home size (HC4.9)</a></td>
  <td><a href="hc/pdf/HC4.9_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC4.9_2024.xlsx" class="ico_xls right" title="Electronics in U.S. homes by home size">
      XLSX</a></td>
</tr>

<thead>
  <tr>
    <th><a name="lighting" id="lighting"></a>Lighting</th>
    <th>&nbsp;</th>
  </tr>
</thead>
<tr class="summary">
  <td colspan="2">Preliminary release date: March 2026<!--</br>
    Final release date: March 2023--></td>
</tr>
<tr class="white_first">
  <td>by Housing unit type (HC5.1)</td>
  <td><a href="hc/pdf/HC5.1_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC5.1_2024.xlsx" class="ico_xls right" title="Lighting by Housing unit type of">
      XLSX</a></td>
</tr>
<tr>
  <td>by Owner/renter status (HC5.2)</td>
  <td><a href="hc/pdf/HC5.2_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC5.2_2024.xlsx" class="ico_xls right" title="Lighting by Owner/renter status">
      XLSX</a></td>
</tr>
<tr>
  <td>by Year of construction (HC5.3)</td>
  <td><a href="hc/pdf/HC5.3_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC5.3_2024.xlsx" class="ico_xls right" title="Lighting by Year of construction">
      XLSX</a></td>
</tr>
<tr>
  <td>by Number of household members (HC5.4)</td>
  <td><a href="hc/pdf/HC5.4_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC5.4_2024.xlsx" class="ico_xls right" title="Lighting by Number of household members">
      XLSX</a></td>
</tr>
<tr>
  <td>by Household income (HC5.5)</td>
  <td><a href="hc/pdf/HC5.5_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC5.5_2024.xlsx" class="ico_xls right" title="Lighting by Household income">
      XLSX</a></td>
</tr>
<tr>
  <td>by Climate region (HC5.6)</td>
  <td><a href="hc/pdf/HC5.6_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC5.6_2024.xlsx" class="ico_xls right" title="Lighting by Climate region">
      XLSX</a></td>
</tr>
<tr>
  <td>in the Northeast and Midwest regions (HC5.7)</td>
  <td><a href="hc/pdf/HC5.7_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC5.7_2024.xlsx" class="ico_xls right" title="Lighting in the Northeast and Midwest regions">XLSX</a></td>
</tr>
<td>in the South and West regions (HC5.8)</td>
<td><a href="hc/pdf/HC5.8_2024.pdf" class="ico_pdf">PDF</a>
	<a href="hc/xls/HC5.8_2024.xlsx" class="ico_xls right" title="Lighting in the South and West regions">
    XLSX</a></td>
</tr>
<td>in U.S. homes by home size (HC5.9)</a></td>
<td><a href="hc/pdf/HC5.9_2024.pdf" class="ico_pdf">PDF</a>
	<a href="hc/xls/HC5.9_2024.xlsx" class="ico_xls right" title="Lighting in U.S. homes by home size">
    XLSX</a></td>
</tr>

<thead>
  <tr>
    <th><a name="sh" id="sh"></a>Space heating</th>
    <th>&nbsp;</th>
  </tr>
</thead>
<tr class="summary">
	<td colspan="2">Data will be released in early 2027</td>
  <!--<td colspan="2">Preliminary release date: May 2022</br>
    Final release date: March 2023</td>-->
</tr>
<tr class="white_first">
  <td style="color: #adadad">by Housing unit type (HC6.1)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.1.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.1.xlsx" class="ico_xls right" title="Space heating by Housing unit type of  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Owner/renter status (HC6.2)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.2.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.2.xlsx" class="ico_xls right" title="Space heating by Owner/renter status  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Year of construction (HC6.3)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.3.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.3.xlsx" class="ico_xls right" title="Space heating by Year of construction">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Number of household members (HC6.4)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.4.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.4.xlsx" class="ico_xls right" title="Space heating by Number of household members">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Household income (HC6.5)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.5.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.5.xlsx" class="ico_xls right" title="Space heating by Household income  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Climate region (HC6.6)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.6.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.6.xlsx" class="ico_xls right" title="Space heating by Climate region">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">in the Northeast and Midwest regions (HC6.7)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.7.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.7.xlsx" class="ico_xls right" title="Space heating in the Northeast and Midwest regions">XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">in the South and West regions (HC6.8)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.8.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.8.xlsx" class="ico_xls right" title="Space heating in the South and West regions">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">in U.S. homes by home size (HC6.9)</a></td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC6.9.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC6.9.xlsx" class="ico_xls right" title="Space heating in U.S. homes by home size  ">
      XLSX</a>
  </td>-->
</tr>


<thead>
  <tr>
    <th><a name="ac" id="ac"></a>Air conditioning</th>
    <th>&nbsp;</th>
  </tr>
</thead>
<tr class="summary">
	<td colspan="2">Data will be released in early 2027</td>
  <!--<td colspan="2">Preliminary release date: May 2022</br>
    Final release date: March 2023</td>-->
</tr>
<tr class="white_first">
  <td style="color: #adadad">by Housing unit type (HC7.1)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC7.1.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.1.xlsx" class="ico_xls right" title="Air conditioning by Housing unit type of">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Owner/renter status (HC7.2)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC7.2.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.2.xlsx" class="ico_xls right" title="Air conditioning by Owner/renter status">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Year of construction (HC7.3)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC7.3.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.3.xlsx" class="ico_xls right" title="Air conditioning by Year of construction  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Number of household members (HC7.4)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td> <a href="hc/pdf/HC7.4.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.4.xlsx" class="ico_xls right" title="Air conditioning by Number of household members  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Household income (HC7.5)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC7.5.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.5.xlsx" class="ico_xls right" title="Air conditioning by Household income">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Climate region (HC7.6)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC7.6.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.6.xlsx" class="ico_xls right" title="Air conditioning by Climate region">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">in the Northeast and Midwest regions (HC7.7)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC7.7.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.7.xlsx" class="ico_xls right" title="Air conditioning in the Northeast and Midwest regions  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">in the South and West regions (HC7.8)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC7.8.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.8.xlsx" class="ico_xls right" title="Air conditioning in the South and West regions">XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">in U.S. homes by home size (HC7.9)</a></td>
<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC7.9.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC7.9.xlsx" class="ico_xls right" title="Air conditioning in U.S. homes by home size">
      XLSX</a>
  </td>-->
</tr>


<thead>
  <tr>
    <th><a name="waterheating" id="waterheating"></a>Water heating</th>
    <th></th>
  </tr>
</thead>
<tr class="summary">
	<td colspan="2">Data will be released in early 2027</td>
  <!--<td colspan="2">Preliminary release date: May 2022</br>
    Final release date: March 2023</td>-->
</tr>
<tr class="white_first">
  <td style="color: #adadad">by Housing unit type (HC8.1)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC8.1.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.1.xlsx" class="ico_xls right" title="Water heating by Housing unit type of  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Owner/renter status (HC8.2)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC8.2.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.2.xlsx" class="ico_xls right" title="Water heating by Owner/renter status">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Year of construction (HC8.3)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC8.3.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.3.xlsx" class="ico_xls right" title="Water heating by Year of construction  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Number of household members (HC8.4)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC8.4.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.4.xlsx" class="ico_xls right" title="Water heating by Number of household members">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Household income (HC8.5)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td> <a href="hc/pdf/HC8.5.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.5.xlsx" class="ico_xls right" title="Water heating by Household income  ">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">by Climate region (HC8.6)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC8.6.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.6.xlsx" class="ico_xls right" title="Water heating by Climate region">
      XLSX</a>
  </td> -->
</tr>
<tr>
  <td style="color: #adadad">in the Northeast and Midwest regions (HC8.7)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC8.7.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.7.xlsx" class="ico_xls right" title="Water heating in the Northeast and Midwest regions">XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">in the South and West regions (HC8.8)</td>
	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC8.8.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.8.xlsx" class="ico_xls right" title="Water heating in the South and West regions">
      XLSX</a>
  </td>-->
</tr>
<tr>
  <td style="color: #adadad">in U.S. homes by home size (HC8.9)</a></td>
<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
  <!--<td><a href="hc/pdf/HC8.9.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC8.9.xlsx" class="ico_xls right" title="Water heating in U.S. homes by home size">
      XLSX</a>
  </td>-->

</tr>


<thead>
  <tr>
    <th><a name="house" id="house"></a>Household demographics</th>
    <th></th>
  </tr>
</thead>
<tr class="summary">
  <td colspan="2">Preliminary release date: March 2026<!--</br>
    Final release date: March 2024<br><br>
    Updated tables were posted for Household Demographics in March 2024 to correct the payment method for energy bills rows.-->
    </td>
</tr>
<tr class="white_first">
  <td>by Housing unit type (HC9.1)</a>
  </td>
  <td><a href="hc/pdf/HC9.1_2024.pdf" class="ico_pdf">PDF</a><a
      href="hc/xls/HC9.1_2024.xlsx" class="ico_xls right" title="Household demographics by Housing unit type of">XLSX</a></td>
</tr>
<tr>
  <td>by Owner/renter status (HC9.2)</td>
  <td><a href="hc/pdf/HC9.2_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC9.2_2024.xlsx" class="ico_xls right" title="Household demographics by Owner/renter status  ">
      XLSX</a></td>
</tr>
<tr>
  <td>by Year of construction (HC9.3)</td>
  <td><a href="hc/pdf/HC9.3_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC9.3_2024.xlsx" class="ico_xls right" title="Household demographics by Year of construction">XLSX</a></td>
</tr>
<tr>
  <td>by Number of household members (HC9.4)</td>
  <td><a href="hc/pdf/HC9.4_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC9.4_2024.xlsx" class="ico_xls right" title="Household demographics by Number of household members">XLSX</a></td>
</tr>
<tr>
  <td>by Household income (HC9.5)</td>
  <td><a href="hc/pdf/HC9.5_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC9.5_2024.xlsx" class="ico_xls right" title="Household demographics by Household income">
      XLSX</a></td>
</tr>
<tr>
  <td>by Climate region (HC9.6)</td>
  <td><a href="hc/pdf/HC9.6_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC9.6_2024.xlsx" class="ico_xls right" title="Household demographics by Climate region  ">
      XLSX</a></td>
</tr>
<tr>
  <td>in the Northeast and Midwest regions (HC9.7)</td>
  <td><a href="hc/pdf/HC9.7_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC9.7_2024.xlsx" class="ico_xls right"
      title="Household demographics in the Northeast and Midwest regions  ">
      XLSX</a></td>
</tr>
<tr>
  <td>in the South and West regions (HC9.8)</td>
  <td><a href="hc/pdf/HC9.8_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC9.8_2024.xlsx" class="ico_xls right" title="Household demographics in the South and West regions">XLSX</a></td>
</tr>
<tr>
  <td>of U.S. homes by home size (HC9.9)</a></td>
  <td><a href="hc/pdf/HC9.9_2024.pdf" class="ico_pdf">PDF</a>
	  <a href="hc/xls/HC9.9_2024.xlsx" class="ico_xls right" title="Household demographics in U.S. homes by home size">XLSX</a></td>
</tr>

<thead>
  <tr>
    <th><a name="squarefootage" id="squarefootage"></a>Square footage (housing unit size)</th>
    <th></th>
  </tr>
</thead>
<tr class="summary">
  <td colspan="2">Preliminary release date: March 2026</td>
</tr>
<tr class="white_first">
  <td>Total square footage of U.S. homes (HC10.1)</td>
  <td><a href="hc/pdf/HC10.1_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.1_2024.xlsx" class="ico_xls right" title="Total square footage of U.S. homes">
      XLSX</a>
  </td>
</tr>
<tr>
  <td>Total square footage of Northeast homes (HC10.2)</td>
  <td><a href="hc/pdf/HC10.2_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.2_2024.xlsx" class="ico_xls right" title="Total square footage of Northeast homes">XLSX</a>
  </td>
</tr>
<tr>
  <td>Total square footage of Midwest homes (HC10.3)</td>
  <td><a href="hc/pdf/HC10.3_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.3_2024.xlsx" class="ico_xls right" title="Total square footage of Midwest homes">
      XLSX</a>
  </td>
</tr>
<tr>
  <td>Total square footage of South homes (HC10.4)</td>
  <td><a href="hc/pdf/HC10.4_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.4_2024.xlsx" class="ico_xls right" title="Total square footage of South homes">
      XLSX</a>
  </td>
</tr>
<tr>
  <td>Total square footage of West homes (HC10.5)</td>
  <td> <a href="hc/pdf/HC10.5_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.5_2024.xlsx" class="ico_xls right" title="Total square footage of West homes">
      XLSX</a>
  </td>
</tr>
<tr>
  <td>Total square footage of single-family homes (HC10.6)</td>
  <td><a href="hc/pdf/HC10.6_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.6_2024.xlsx" class="ico_xls right" title="Total square footage of single-family homes">XLSX</a>
  </td>
</tr>
<tr>
  <td>Total square footage of apartment units (HC10.7)</td>
  <td><a href="hc/pdf/HC10.7_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.7_2024.xlsx" class="ico_xls right" title="Total square footage of apartment units">XLSX</a>
  </td>
</tr>
<tr>
  <td>Total square footage of mobile homes (HC10.8)</td>
  <td><a href="hc/pdf/HC10.8_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.8_2024.xlsx" class="ico_xls right" title="Total square footage of mobile homes">
      XLSX</a>
  </td>
</tr>

<tr>
  <td>Average square footage of U.S. homes (HC10.9)</td>
  <td><a href="hc/pdf/HC10.9_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.9_2024.xlsx" class="ico_xls right" title="Average square footage of U.S. homes">
      XLSX</a>
  </td>
</tr>
<tr>
  <td>Average square footage of Northeast homes (HC10.10)</td>
  <td><a href="hc/pdf/HC10.10_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.10_2024.xlsx" class="ico_xls right" title="Average square footage of Northeast homes">XLSX</a>
  </td>
</tr>
<tr>
  <td>Average square footage of Midwest homes (HC10.11)</td>
  <td><a href="hc/pdf/HC10.11_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.11_2024.xlsx" class="ico_xls right" title="Average square footage of Midwest homes">XLSX</a>
  </td>
</tr>
<tr>
  <td>Average square footage of South homes (HC10.12)</td>
  <td><a href="hc/pdf/HC10.12_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.12_2024.xlsx" class="ico_xls right" title="Average square footage of South homes">
      XLSX</a>
  </td>
</tr>
<tr>
  <td>Average square footage of West homes (HC10.13)</td>
  <td><a href="hc/pdf/HC10.13_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.13_2024.xlsx" class="ico_xls right" title="Average square footage of West homes">
      XLSX</a>
  </td>
</tr>
<tr>
  <td>Average square footage of single-family homes (HC10.14)</td>
  <td><a href="hc/pdf/HC10.14_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.14_2024.xlsx" class="ico_xls right" title="Average square footage of single-family homes">XLSX</a>
  </td>
</tr>
<tr>
  <td>Average square footage of apartment units (HC10.15)</td>
  <td> <a href="hc/pdf/HC10.15_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.15_2024.xlsx" class="ico_xls right" title="Average square footage of apartment units">XLSX</a>
  </td>
</tr>
<tr>
  <td>Average square footage of mobile homes (HC10.16)</td>
  <td><a href="hc/pdf/HC10.16_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC10.16_2024.xlsx" class="ico_xls right" title="Average square footage of mobile homes">XLSX</a>
  </td>
</tr>


<thead>
  <tr>
    <th><a name="household" id="household"></a>Household energy insecurity </th>
    <th></th>
  </tr>
</thead>
<tr class="summary">
  <td colspan="2">Preliminary release date: March 2026<!--</br>
    Final release date: August 2025<br><br>
    Updated tables were posted for Household energy insecurity in August 2025 to correct the payment method for energy bills rows.</td>-->
</tr>
<tr class="white_first">
  <td>Household energy insecurity (HC11.1)</a>
  </td>
  <td><a href="hc/pdf/HC11.1_2024.pdf" class="ico_pdf">PDF</a>
    <a href="hc/xls/HC11.1_2024.xlsx" class="ico_xls right" title="Household energy insecurity">
      XLSX</a>
  </td>
</tr>
<!--&nbsp;
      <thead id="wood">
      <tr>
        <th><a name="wood"></a>Special tabulations: wood characteristics and consumption</th>
        <th></th>
      </tr>
    </thead>
    <tr>
      <td><em>Release date: December  XX, 2018</em></td>
      <td><span class="right"></td>
    </tr>
    <tr class="white_first">
      <td> CE7.1 Wood types used </td>
      <td><span class="right"><a href="hc/xls/ce7.1.xlsx" class="ico_xls" title="CE7.1 Wood End-Use Consumption by Fuel_US" title="Wood types used ">
XLSX</a></span></td>
    </tr>
    <tr>
      <td>CE7.2 
        Household wood consumption</td>
      <td><span class="right"><a href="hc/xls/ce7.2.xlsx" class="ico_xls" title="CE7.2 Wood types used in U.S. homes, 2020" title="Household wood consumption ">
XLSX</a></span></td>
    </tr>-->
</table>