<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Visualizations</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd></dd>
	</dl>
	<!-- Example -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
	<div class="eia-card">
		<div uk-alert>
			<a class="uk-alert-close" uk-close></a>
			<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Notice</h2>
			<p>This is not a working demo.</p>
		</div>
		<div class="primary">
			<div class="l-row l-six-col-even visualizations">
				<h1>Interactive Visualizations, Data, &amp; Multimedia</h1>
				<p class="uk-text-lead"></p>

				<div class="l-col">
					<ul>
						<li>
							<a href="https://www.eia.gov">
								<div class="circle">
									<img src="https://www.eia.gov/global/images/interactive/petroleum-map.png" alt="U.S. Petroleum Infrastructure Map" />
								</div>
								<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">U.S. Petroleum Infrastructure Map </h2>
							</a>
						</li>
					</ul>
				</div>
				<div class="l-col">
					<ul>
						<li>
							<a href="https://www.eia.gov">
								<div class="circle">
									<img src="https://www.eia.gov/global/images/interactive/fossil-fuel-map.png" alt="U.S. Fossil Fuel Resource Map" />
								</div>
								<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">U.S. Fossil Fuel Resource Map </h2>
							</a>
						</li>
					</ul>
				</div>
				<div class="l-col">
					<ul>
						<li>
							<a href="https://www.eia.gov">
								<div class="circle">
									<img src="https://www.eia.gov/global/images/interactive/crude-oil-import-data.png" alt="U.S. Crude Import Tracking Tool" />
								</div>
								<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">U.S. Crude Import Tracking Tool </h2>
							</a>
						</li>
					</ul>
				</div>
				<div class="l-col">
					<ul>
						<li>
							<a href="https://www.eia.gov">
								<div class="circle">
									<img src="https://www.eia.gov/global/images/interactive/steo-data-browser.png" alt="STEO Data Browser" />
								</div>
								<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">STEO Data Browser </h2>
							</a>
						</li>
					</ul>
				</div>
				<div class="l-col">
					<ul>
						<li>
							<a href="https://www.eia.gov">
								<div class="circle">
									<img src="https://www.eia.gov/global/images/interactive/radio.png" alt="Radio Spot" />
								</div>
								<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Radio Spot </h2>
							</a>
						</li>
					</ul>
				</div>
				<div class="l-col">
					<ul>
						<li>
							<a href="https://www.eia.gov">
								<div class="circle">
									<img src="https://www.eia.gov/global/images/interactive/video.png" alt="Trends in Energy Video" />
								</div>
								<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Trends in Energy Video </h2>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<br />
		<!-- HTML -->
		<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
		<div class="uk-margin-medium">

			<pre><code class="language-html" id="ModalEnlargeContent">&lt;div class="l-row l-six-col-even visualizations"&gt;
  &lt;h1&gt;Interactive Visualizations, Data, &amp;amp; Multimedia&lt;/h1&gt;
  &lt;div class="l-col"&gt;
    &lt;ul&gt;
      &lt;li&gt;
        &lt;a href="https://www.eia.gov"&gt;
  &lt;div class="circle"&gt;
            &lt;img src="https://www.eia.gov/global/images/interactive/petroleum-map.png" alt="U.S. Petroleum Infrastructure Map".inc') ?&gt;
  &lt;/div&gt;
          &lt;h3&gt;U.S. Petroleum Infrastructure Map&lt;/h3&gt;
        &lt;/a&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
  &lt;div class="l-col"&gt;
    &lt;ul&gt;
      &lt;li&gt;
        &lt;a href="https://www.eia.gov"&gt;
          &lt;div class="circle"&gt;
            &lt;img src="https://www.eia.gov/global/images/interactive/fossil-fuel-map.png" alt="U.S. Fossil Fuel Resource Map".inc') ?&gt;
          &lt;/div&gt;
          &lt;h3&gt;U.S. Fossil Fuel Resource Map&lt;/h3&gt;
        &lt;/a&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
  &lt;div class="l-col"&gt;
    &lt;ul&gt;
      &lt;li&gt;
        &lt;a href="https://www.eia.gov"&gt;
          &lt;div class="circle"&gt;
            &lt;img src="https://www.eia.gov/global/images/interactive/crude-oil-import-data.png" alt="U.S. Crude Import Tracking Tool".inc') ?&gt;
          &lt;/div&gt;
          &lt;h3&gt;U.S. Crude Import Tracking Tool&lt;/h3&gt;
        &lt;/a&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
  &lt;div class="l-col"&gt;
    &lt;ul&gt;
      &lt;li&gt;
        &lt;a href="https://www.eia.gov"&gt;
          &lt;div class="circle&gt;
            &lt;img src=" https://www.eia.gov/global/images/interactive/steo-data-browser.png" alt="STEO Data Browser".inc') ?&gt;
          &lt;/div&gt;
          &lt;h3&gt;STEO Data Browser&lt;/h3&gt;
        &lt;/a&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
  &lt;div class="l-col"&gt;
    &lt;ul&gt;
      &lt;li&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
  &lt;div class="l-col"&gt;
    &lt;ul&gt;
      &lt;li&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
&lt;/div&gt;</code></pre>
		</div>
		<!-- Copy Button -->
		<p>
			<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#ModalEnlargeContent">
				<span uk-icon="copy"></span>Copy to clipboard
			</button>
		</p>
	</div>