<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Full-width Modal</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd></dd>
	</dl>
	<!-- Example -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
	<div class="eia-card">
		<div uk-alert>
			<a class="uk-alert-close" uk-close></a>
			<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Notice</h2>
			<p>This is not a working demo.</p>
		</div>


		<strong><a href="#enlargeContentID" class="full-screen">Open</a></strong> full-width responsive modal.

		<div id="enlargeContentID" class="l-col l-two-col-even" style="display: none">
			<div class="l-col article">
				<!-- includes/placeholders/h1 -->
				<h2>H2 Lorem Ipsum Dolor</h2>
				<!-- includes/placeholders/lorem-ipsum-p -->
				<!-- includes/placeholders/h4 -->
				<!-- modules/lists/unordered -->
				<!-- includes/placeholders/lorem-ipsum-p -->
				<!-- includes/placeholders/h4 -->
				<!-- modules/lists/unordered -->
				<!-- includes/placeholders/lorem-ipsum-p -->
			</div>
			<div class="l-col article">
				<!-- includes/placeholders/h1 -->
				<h2>H2 Lorem Ipsum Dolor</h2>
				<!-- includes/placeholders/lorem-ipsum-p -->
				<!-- includes/placeholders/h4 -->
				<!-- modules/lists/unordered -->
				<!-- includes/placeholders/lorem-ipsum-p -->
				<!-- includes/placeholders/h4 -->
				<!-- modules/lists/unordered -->
				<!-- includes/placeholders/lorem-ipsum-p -->
			</div>
		</div>
	</div>
	<!-- HTML -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
	<pre><code class="language-html" id="ModalFullWidth">&lt;a href="#enlargeContentID" class="full-screen"&gt;Open&lt;/a&gt;
  &lt;div id="enlargeContentID" style="display: none;"&gt;
  &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem massa, semper nec eros a, lacinia porttitor nunc. Phasellus ex dolor.&lt;/p&gt;
&lt;/div&gt;</code></pre>
	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#ModalFullWidth">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
	</p>
	</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">