<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Inline Content</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd></dd>
	</dl>
	<!-- Example -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
	<div class="eia-card">
		<div uk-alert>
			<a class="uk-alert-close" uk-close></a>
			<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Notice</h2>
			<p>This is not a working demo.</p>
		</div>
		<a href="#enlargeContentID2" class="enlarge-content">
			<img src="https://www.eia.gov/homepage/images/energy-kids/kids-tablet-halloween.png" style="width: 200px" alt="" />
		</a>


		<div id="enlargeContentID2" style="display: none">
			<img src="https://www.eia.gov/homepage/images/energy-kids/kids-tablet-halloween.png" alt="" />
		</div>

	</div>

	<br />
	<!-- HTML -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
	<div class="uk-margin-medium">

		<pre><code class="language-html" id="AccordionAllClosed">&lt;p&gt;
  &lt;a href="#enlargeContentID2" class="enlarge-content"&gt;
    &lt;img src="https://www.eia.gov/homepage/images/energy-kids/kids-tablet-halloween.png" style="width: 200px" alt="" /&gt;
  &lt;/a&gt;
&lt;/p&gt;

&lt;div id="enlargeContentID2" style="display: none"&gt;
  &lt;img src="https://www.eia.gov/homepage/images/energy-kids/kids-tablet-halloween.png" alt="" /&gt;
&lt;/div&gt;</code></pre>
		<!-- Copy Button -->
		<p>
			<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#AccordionAllClosed">
				<span uk-icon="copy"></span>Copy to clipboard
			</button>
		</p>
		</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">