<?php $locale = 'data'; ?>
<?php $page['year'] = '2022'; ?>

<!--<p align="right"><a href="pdf/alltables2010.pdf" class="ico pdf" alt="all 2010 tables in pdf">all tables</a>-->
<div class="basic-table">
	<table class="basic-table full-width">
		<caption>2022 MECS Release Schedule</caption>
		<thead>
			<th>Task name</th>
			<th>Release date</th>
		</thead>
		<tbody>
			<tr>
				<td>Consumption, end use, and fuel-switching tables</li>
				<td>August 2025</li>
			</tr>
			<tr>
				<td>Economic and expenditure tables</li>
				<td>September 2025</li>
			</tr>
			<tr>
				<td>Energy-management and count tables</li>
				<td>December 2025</li>
			</tr>
			<tr>
				<td>Hand-suppressed tables</li>
				<td>March 2026</li>
			</tr>
		</tbody>
	</table>
</div>

<div class="primary">
	<span class="expand-collapse-container">
		<span class="ico expand"><span>Expand all</span></span>
		<span class="ico collapse"><span>Collapse all</span></span>
	</span>
	<div class="accordion">
		<!-- start new panel -->
		<h3 id="r1">Consumption of Energy for All Purposes (First Use)</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 1.1 By Manufacturing Industry and Region (physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table1_1.xlsx" class="ico xls" title="Table 1.1 By By Manufacturing Industry and Region (physical units)"><span>XLS</span></a> <a href="pdf/Table1_1.pdf" class="ico pdf" title="Table 1.1 By Manufacturing Industry and Region (physical units)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 1.2 By Manufacturing Industry and Region (trillion Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table1_2.xlsx" class="ico xls" title="Table 1.2 By Manufacturing Industry and Region (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table1_2.pdf" class="ico pdf" title="Table 1.2 By Manufacturing Industry and Region (trillion Btu)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 1.3 By Value of Shipments & Employment Size Category & Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table1_3.xlsx" class="ico xls" title="Table 1.3 By Value of Shipments & Employment Size Category & Region"><span>XLS</span></a> <a href="pdf/Table1_3.pdf" class="ico pdf" title=" By Value of Shipments & Employment Size Category & Region"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 1.4 Number of Establishments Using Energy Consumed for All Purpose</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table1_4.xlsx" class="ico xls" title="Table 1.4 Number of Establishments Using Energy Consumed for All Purpose"><span>XLS</span></a> <a href="pdf/Table1_4.pdf" class="ico pdf" title="Table 1.4 Number of Establishments Using Energy Consumed for All Purpose"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 1.5 By Further Classification of 'Other' Energy Sources</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table1_5.xlsx" class="ico xls" title="Table 1.5 By Further Classification of " Other" Energy Sources"><span>XLS</span></a> <a href="pdf/Table1_5.pdf" class="ico pdf" title="Table 1.5 By Further Classification of " Other" Energy Sources"><span>PDF</span></a>
			</ul>
		</div>
		<!-- start new panel -->
		<h3 id="r2">Energy Used as a Nonfuel (Feedstock)</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 2.1 By Manufacturing Industry and Region (physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table2_1.xlsx" class="ico xls" title="Table 2.1 By Manufacturing Industry and Region (physical units)"><span>XLS</span></a> <a href="pdf/Table2_1.pdf" class="ico pdf" title="Table 2.1 By Manufacturing Industry and Region (physical units)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 2.2 By Manufacturing Industry and Region (trillion Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table2_2.xlsx" class="ico xls" title="Table 2.2 By Manufacturing Industry and Region (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table2_2.pdf" class="ico pdf" title="Table 2.2 By Manufacturing Industry and Region (trillion Btu)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 2.3 By Value of Shipments & Employment Size Category & Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table2_3.xlsx" class="ico xls" title="Table 2.3 By Value of Shipments & Employment Size Category & Region"><span>XLS</span></a> <a href="pdf/Table2_3.pdf" class="ico pdf" title="Table 2.3 Nonfuel (Feedstock) Use of Combustible Energy"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 2.4 Number of Establishment Using Energy Consumed as a Nonfuel</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table2_4.xlsx" class="ico xls" title="Table 2.4 Number of Establishment Using Energy Consumed as a Nonfuel"><span>XLS</span></a> <a href="pdf/Table2_4.pdf" class="ico pdf" title="Table 2.4 Number of Establishment Using Energy Consumed as a Nonfuel"><span>PDF</span></a>
			</ul>
		</div>
		<!-- start new panel -->
		<h3 id="r3">Energy Consumption as a Fuel</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 3.1 By Manufacturing Industry and Region (physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table3_1.xlsx" class="ico xls" title="Table 3.1 By Manufacturing Industry and Region (physical units)"><span>XLS</span></a> <a href="pdf/Table3_1.pdf" class="ico pdf" title="Table 3.1 By Manufacturing Industry and Region (physical units)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 3.2 By Manufacturing Industry and Region (trillion Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table3_2.xlsx" class="ico xls" title="Table 3.2 By Manufacturing Industry and Region (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table3_2.pdf" class="ico pdf" title="Table 3.2 By Manufacturing Industry and Region (trillion Btu)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 3.3 By Value of Shipments & Employment Size Category & Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table3_3.xlsx" class="ico xls" title="Table 3.3 By Value of Shipments & Employment Size Category & Region"><span>XLS</span></a> <a href="pdf/Table3_3.pdf" class="ico pdf" title="Table 3.3 By Value of Shipments & Employment Size Category & Region"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 3.4 Number of Establishments Using Energy Consumed as a Fuel</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table3_4.xlsx" class="ico xls" title="Table 3.4 Number of Establishments Using Energy Consumed as a Fuel"><span>XLS</span></a> <a href="pdf/Table3_4.pdf" class="ico pdf" title="Table 3.4 Number of Establishments Using Energy Consumed as a Fuel"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 3.5 Byproducts in Fuel Consumption By Manufacturing Industry and Region (trillion Btu) </li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table3_5.xlsx" class="ico xls" title="Table 3.5 Byproducts in Fuel Consumption By Manufacturing Industry and Region (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table3_5.pdf" class="ico pdf" title="Table 3.5 Byproducts in Fuel Consumption By Manufacturing Industry and Region (trillion Btu)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 3.6 Selected Wood and Wood-Related Products in Fuel Consumption (trillion Btu) </li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table3_6.xlsx" class="ico xls" title="Table 3.6 Selected Wood and Wood-Related Products in Fuel Consumption (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table3_6.pdf" class="ico pdf" title="Table 3.6 Selected Wood and Wood-Related Products in Fuel Consumption (trillion Btu)"><span>PDF</span></a>
			</ul>
		</div>
		<h3 id="r4">Offsite-Produced Fuel Consumption</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 4.1 By Manufacturing Industry (physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table4_1.xlsx" class="ico xls" title="Table 4.1 By Manufacturing Industry (physical units)"><span>XLS</span></a> <a href="pdf/Table4_1.pdf" class="ico pdf" title="Table 4.1 By Manufacturing Industry (physical units)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 4.2 By Manufacturing Industry and Region (trillion Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table4_2.xlsx" class="ico xls" title="Table 4.2 By Manufacturing Industry and Region (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table4_2.pdf" class="ico pdf" title="Table 4.2 By Manufacturing Industry and Region (trillion Btu)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 4.3 By Value of Shipments & Employment Size Category & Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table4_3.xlsx" class="ico xls" title="Table 4.3 By Value of Shipments & Employment Size Category & Region"><span>XLS</span></a> <a href="pdf/Table4_3.pdf" class="ico pdf" title="Table 4.3 By Value of Shipments & Employment Size Category & Region"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 4.4 Number of Establishments Using Offsite-Produced Fuel for Consumption</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table4_4.xlsx" class="ico xls" title="Table 4.4 Number of Establishments Using Offsite-Produced Fuel for Consumption"><span>XLS</span></a> <a href="pdf/Table4_4.pdf" class="ico pdf" title="Table 4.4 Number of Establishments Using Offsite-Produced Fuel for Consumption"><span>PDF</span></a>
			</ul>
		</div>
		<h3 id="r5">Energy Consumed as a Fuel by End Use</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 5.1 By Manufacturing Industry with Net Electricity (physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table5_1.xlsx" class="ico xls" title="Table 5.1 By Manufacturing Industry with Net Electricity (physical units)"><span>XLS</span></a> <a href="pdf/Table5_1.pdf" class="ico pdf" title="Table 5.1 By Manufacturing Industry with Net Electricity (physical units)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 5.2 By Manufacturing Industry with Net Electricity (trillion Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table5_2.xlsx" class="ico xls" title="Table 5.2 By Manufacturing Industry with Net Electricity (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table5_2.pdf" class="ico pdf" title="Table 5.2 By Manufacturing Industry with Net Electricity (trillion Btu)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 5.3 By Manufacturing Industry with Total Consumption of Electricity (physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table5_3.xlsx" class="ico xls" title="Table 5.3 By Manufacturing Industry with Total Consumption of Electricity (physical units)"><span>XLS</span></a> <a href="pdf/Table5_3.pdf" class="ico pdf" title="Table 5.3 By Manufacturing Industry with Total Consumption of Electricity (physical units)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 5.4 By Manufacturing Industry with Total Consumption of Electricity (trillion Btu) </li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table5_4.xlsx" class="ico xls" title="Table 5.4 By Manufacturing Industry with Total Consumption of Electricity (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table5_4.pdf" class="ico pdf" title="Table 5.4 By Manufacturing Industry with Total Consumption of Electricity (trillion Btu)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 5.5 By Region with Net Electricity (physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table5_5.xlsx" class="ico xls" title="Table 5.5 By Region with Net Electricity (physical units)"><span>XLS</span></a> <a href="pdf/Table5_5.pdf" class="ico pdf" title="Table 5.5 By Region with Net Electricity (physical units)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 5.6 By Region with Net Electricity (trillion Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table5_6.xlsx" class="ico xls" title="Table 5.6 By Region with Net Electricity (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table5_6.pdf" class="ico pdf" title="Table 5.6 By Region with Net Electricity (trillion Btu)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 5.7 By Region with Total Consumption of Electricity (physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table5_7.xlsx" class="ico xls" title="Table 5.7 By Region with Total Consumption of Electricity (physical units)"><span>XLS</span></a> <a href="pdf/Table5_7.pdf" class="ico pdf" title="Table 5.7 By Region with Total Consumption of Electricity (physical units)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 5.8 By Region with Total Consumption of Electricity (trillion Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table5_8.xlsx" class="ico xls" title="Table 5.8 By Region with Total Consumption of Electricity (trillion Btu)"><span>XLS</span></a> <a href="pdf/Table5_8.pdf" class="ico pdf" title="Table 5.8 By Region with Total Consumption of Electricity (trillion Btu)"><span>PDF</span></a>
			</ul>
		</div>
		<h3 id="r6">Ratios of Manufacturing Fuel Consumption to Economic Characteristics</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 6.1 By Manufacturing Industry and Region</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
			<ul>
				<li>Table 6.2 By Value of Shipments or Employment Size Category and Region</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
			<ul>
				<li>Table 6.3 By Manufacturing Industry and Value of Shipments</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
			<ul>
				<li>Table 6.4 By Manufacturing Industry and Employment Size</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
		</div>
		<h3 id="r7">Average Prices of Purchased Energy Sources</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 7.1 All Collected Energy Sources By Manufacturing Industry and Region (dollars per physical units)</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
			<ul>
				<li>Table 7.2 All Collected Energy Sources By Manufacturing Industry and Region (dollars per million Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
			<ul>
				<li>Table 7.3 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing Industry, and Region (dollars per physical unit)</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
			<ul>
				<li>Table 7.4 Selected Energy Sources by Region and Employment or Value of Shipments Size Categories (dollars per physical unit)</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
			<ul>
				<li>Table 7.5 Selected Energy Sources by Region and Employment or Value of Shipments Size Categories (dollars per million Btu)</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
		</div>
		<h3 id="r8">Quantity of Purchased Energy</h3>
		<div class="accordion-content">
			<ul>
				<li><span class="formats">Available formats:</span> <a href="xls/Table7_6.xlsx" class="ico xls" title="Table 7.6 Selected Energy Sources By Manufacturing Industry and Region (physical units)"><span>XLS</span></a> <a href="pdf/Table7_6.pdf" class="ico pdf" title="Table 7.6 Selected Energy Sources By Manufacturing Industry and Region (physical units)"><span>PDF</span></a></li>-->
			</ul>
			<ul>
				<li>Table 7.7 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>

				<li>Table 7.8 Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, and Manufacturing Industry</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table7_8.xlsx" class="ico xls" title="Table 7.8 Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, and Manufacturing Industry"><span>XLS</span></a> <a href="pdf/Table7_8.pdf" class="ico pdf" title="Table 7.8 Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, and Manufacturing Industry"><span>PDF</span></a>
			</ul>
		</div>
		<h3 id="r9">Expenditures for Purchased Energy (Millions of Dollars)</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 7.9 Selected Energy Sources By Manufacturing Industry and Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table7_9.xlsx" class="ico xls" title="Table 7.9 Selected Energy Sources By Manufacturing Industry and Region"><span>XLS</span></a> <a href="pdf/Table7_9.pdf" class="ico pdf" title="Table 7.9 Selected Energy Sources By Manufacturing Industry and Region"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 7.10 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table7_10.xlsx" class="ico xls" title="Table 7.10 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region"><span>XLS</span></a> <a href="pdf/Table7_10.pdf" class="ico pdf" title="Table 7.10 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region"><span>PDF</span></a>
			</ul>
		</div>
		<!-- start new panel -->
		<h3 id="r10">Energy Management Activities and Energy-Savings Technologies</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 8.1 Number of Establishments Participating in Energy Management Activities</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_1.xlsx" class="ico xls" title="Table 8.1 Number of Establishments Participating in Energy Management Activities"><span>XLS</span></a> <a href="pdf/Table8_1.pdf" class="ico pdf" title="Table 8.1 Number of Establishments Participating in Energy Management Activities"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.2 Number of Establishments with General Technologies</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_2.xlsx" class="ico xls" title="Table 8.2 Number of Establishments with General Technologies"><span>XLS</span></a> <a href="pdf/Table8_2.pdf" class="ico pdf" title="Table 8.2 Number of Establishments with General Technologies"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.3 Number of Establishments with Cogeneration Technologies</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_3.xlsx" class="ico xls" title="Table 8.3 Number of Establishments with Cogeneration Technologies"><span>XLS</span></a> <a href="pdf/Table8_3.pdf" class="ico pdf" title="Table 8.3 Number of Establishments with Cogeneration Technologies"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.4 Number of Establishments Participating in Specific Energy-Management Activities</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_4.xlsx" class="ico xls" title="Table 8.4 Number of Establishments Participating in Specific Energy-Management Activities"><span>XLS</span></a> <a href="pdf/Table8_4.pdf" class="ico pdf" title="Table 8.4 Number of Establishments Participating in Specific Energy-Management Activities"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.5 Number of Establishments by Management Decision-Making Process</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_5.xlsx" class="ico xls" title="Table 8.5 Number of Establishments by Management Decision-Making Process"><span>XLS</span></a> <a href="pdf/Table8_5.pdf" class="ico pdf" title="Table 8.5 Number of Establishments by Management Decision-Making Process"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.6 Number of Establishments by Participation in Programs Dedicated to Improving Energy Consumption</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_6.xlsx" class="ico xls" title="Table 8.6 Number of Establishments by Participation in Programs Dedicated to Improving Energy Consumption"><span>XLS</span></a> <a href="pdf/Table8_6.pdf" class="ico pdf" title="Table 8.6 Number of Establishments by Participation in Programs Dedicated to Improving Energy Consumption"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.7 Number of Establishments by Simple Payback Period</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_7.xlsx" class="ico xls" title="Table 8.7 Number of Establishments by Simple Payback Period"><span>XLS</span></a> <a href="pdf/Table8_7.pdf" class="ico pdf" title="Table 8.7 Number of Establishments by Simple Payback Period"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.8 Number of Establishments by Participation in Setting Goals for Improving Energy Consumption</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_8.xlsx" class="ico xls" title="Table 8.8 Number of Establishments by Participation in Setting Goals for Improving Energy Consumption"><span>XLS</span></a> <a href="pdf/Table8_8.pdf" class="ico pdf" title="Table 8.8 Number of Establishments by Participation in Setting Goals for Improving Energy Consumption"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.9 Number of Establishments by Designation of Representative(s) Responsible for Energy Management</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_9.xlsx" class="ico xls" title="Table 8.9 Number of Establishments by Designation of Representative(s) Responsible for Energy Management"><span>XLS</span></a> <a href="pdf/Table8_9.pdf" class="ico pdf" title="Table 8.9 Number of Establishments by Designation of Representative(s) Responsible for Energy Management"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.10 Number of Establishments by Submetering Capability</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_10.xlsx" class="ico xls" title="Table 8.10 Number of Establishments by Submetering Capability"><span>XLS</span></a> <a href="pdf/Table8_10.pdf" class="ico pdf" title="Table 8.10 Number of Establishments by Submetering Capability"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.11 Number of Establishments by Participation of Audits to Identify Potential Energy Saving Opportunities</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_11.xlsx" class="ico xls" title="Table 8.11 Number of Establishments by Participation of Audits to Identify Potential Energy Saving Opportunities"><span>XLS</span></a> <a href="pdf/Table8_11.pdf" class="ico pdf" title="Table 8.11 Number of Establishments by Participation of Audits to Identify Potential Energy Saving Opportunities"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 8.12 Number of Establishments by Purchase of Electricity Produced from Renewable Sources</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table8_12.xlsx" class="ico xls" title="Table 8.12 Number of Establishments by Purchase of Electricity Produced from Renewable Sources"><span>XLS</span></a> <a href="pdf/Table8_12.pdf" class="ico pdf" title="Table 8.12 Number of Establishments by Purchase of Electricity Produced from Renewable Sources"><span>PDF</span></a>
			</ul>
		</div>
		<!-- start new panel -->
		<h3 id="r11">Floorspace and Building Counts</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 9.1 Enclosed Floorspace and Number of Establishment Buildings</li>
				<li><span class="formats">Available formats:</span> <a href="" class="ico xls" title=""><span>XLS</span></a> <a href="" class="ico pdf" title=""><span>PDF</span></a></li>
			</ul>
		</div>
		<!-- start new panel -->
		<h3 id="r12">Fuel Switching</a></h3>
		<div class="accordion-content">
			<ul>
				<li>Table 10.1 Nonswitchable Minimum Requirements &amp; Maximum Consumption Potential (establishment counts)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table10_1.xlsx" class="ico xls" title="Table 10.1 Nonswitchable Minimum Requirements & Maximum Consumption Potential (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_1.pdf" class="ico pdf" title="Table 10.1 Nonswitchable Minimum Requirements & Maximum Consumption Potential (establishment counts)"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 10.2 Capability to Switch from Natural Gas to Alternative Energy (quantities)</li>
				<li><span><a href="xls/Table10_2.xlsx" class="ico xls" title="Table 10.2 Capability to Switch from Natural Gas to Alternative Energy (quantities)"><span>XLS</span></a> <a href="pdf/Table10_2.pdf" class="ico pdf" title="Table 10.2 Capability to Switch from Natural Gas to Alternative Energy (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.3 Capability to Switch from Natural Gas to Alternative Energy Sources (establishment counts)</li>
				<li><span><a href="xls/Table10_3.xlsx" class="ico xls" title="Table 10.3 Capability to Switch from Natural Gas to Alternative Energy Sources (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_3.pdf" class="ico pdf" title="Table 10.3 Capability to Switch from Natural Gas to Alternative Energy Sources (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.4 Capability to Switch Residual Fuel Oil to Alternative Energy Sources (quantities)</li>
				<li><span><a href="xls/Table10_4.xlsx" class="ico xls" title="Table 10.4 Capability to Switch Residual Fuel Oil to Alternative Energy Sources (quantities)"><span>XLS</span></a> <a href="pdf/Table10_4.pdf" class="ico pdf" title="Table 10.4 Capability to Switch Residual Fuel Oil to Alternative Energy Sources (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.5 Capability to Switch from Residual Fuel Oil to Alternative Energy Sources (establishment counts)</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table10_5.xlsx" class="ico xls" title="Table 10.5 Capability to Switch from Residual Fuel Oil to Alternative Energy Sources (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_5.pdf" class="ico pdf" title="Table 10.5 Capability to Switch from Residual Fuel Oil to Alternative Energy Sources (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.6 Capability to Switch from Electricity to Alternative Energy Sources (quantities)</li>
				<li><span><a href="xls/Table10_6.xlsx" class="ico xls" title="Table 10.6 Capability to Switch from Electricity to Alternative Energy Sources (quantities)"><span>XLS</span></a> <a href="pdf/Table10_6.pdf" class="ico pdf" title="Table 10.6 Capability to Switch from Electricity to Alternative Energy Sources (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.7 Capability to Switch from Electricity to Alternative Energy Sources (establishment counts)</li>
				<li><span><a href="xls/Table10_7.xlsx" class="ico xls" title="Table 10.7 Capability to Switch from Electricity to Alternative Energy Sources (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_7.pdf" class="ico pdf" title="Table 10.7 Capability to Switch from Electricity to Alternative Energy Sources (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.8 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (quantities)</li>
				<li><span><a href="xls/Table10_8.xlsx" class="ico xls" title="Table 10.8 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (quantities)"><span>XLS</span></a> <a href="pdf/Table10_8.pdf" class="ico pdf" title="Table 10.8 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.9 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (establishment counts)</li>
				<li><span><a href="xls/Table10_9.xlsx" class="ico xls" title="Table 10.9 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_9.pdf" class="ico pdf" title="Table 10.9 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.10 Capability to Switch from Coal to Alternative Energy Sources (quantities)</li>
				<li><span><a href="xls/Table10_10.xlsx" class="ico xls" title="Table 10.10 Capability to Switch from Coal to Alternative Energy Sources (quantities)"><span>XLS</span></a> <a href="pdf/Table10_10.pdf" class="ico pdf" title="Table 10.10 Capability to Switch from Coal to Alternative Energy Sources (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.11 Capability to Switch from Coal to Alternative Energy Sources (establishment counts)</li>
				<li><span><a href="xls/Table10_11.xlsx" class="ico xls" title="Table 10.11 Capability to Switch from Coal to Alternative Energy Sources (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_11.pdf" class="ico pdf" title="Table 10.11 Capability to Switch from Coal to Alternative Energy Sources (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.12 Capability to Switch from HGL to Alternative Energy Sources (quantities)</li>
				<li><span><a href="xls/Table10_12.xlsx" class="ico xls" title="Table 10.12 Capability to Switch from HGL to Alternative Energy Sources (quantities)"><span>XLS</span></a> <a href="pdf/Table10_12.pdf" class="ico pdf" title="Table 10.12 Capability to Switch from HGL to Alternative Energy Sources (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.13 Capability to Switch from HGL to Alternative Energy Sources (establishment counts)</li>
				<li><span><a href="xls/Table10_13.xlsx" class="ico xls" title="Table 10.13 Capability to Switch from HGL to Alternative Energy Sources (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_13.pdf" class="ico pdf" title="Table 10.13 Capability to Switch from HGL to Alternative Energy Sources (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.14 Levels of Price Difference that Would Cause Establishments to Switch from Electricity (establishment counts)</li>
				<li><span><a href="xls/Table10_14.xlsx" class="ico xls" title="Table 10.14 Levels of Price Difference that Would Cause Establishments to Switch from Electricity (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_14.pdf" class="ico pdf" title="Table 10.14 Levels of Price Difference that Would Cause Establishments to Switch from Electricity (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.15 Levels of Price Difference that Would Cause Establishments to Switch from Natural Gas (establishment counts)</li>
				<li><span><a href="xls/Table10_15.xlsx" class="ico xls" title="Table 10.15 Levels of Price Difference that Would Cause Establishments to Switch from Natural Gas (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_15.pdf" class="ico pdf" title="Table 10.15 Levels of Price Difference that Would Cause Establishments to Switch from Natural Gas (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.16 Levels of Price Difference that Would Cause Establishments to Switch from Coal (establishment counts)</li>
				<li><span><a href="xls/Table10_16.xlsx" class="ico xls" title="Table 10.16 Levels of Price Difference that Would Cause Establishments to Switch from Coal (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_16.pdf" class="ico pdf" title="Table 10.16 Levels of Price Difference that Would Cause Establishments to Switch from Coal (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.17 Levels of Price Difference that Would Cause Establishments to Switch from HGL (establishment counts)</li>
				<li><span><a href="xls/Table10_17.xlsx" class="ico xls" title="Table 10.17 Levels of Price Difference that Would Cause Establishments to Switch from HGL (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_17.pdf" class="ico pdf" title="Table 10.17 Levels of Price Difference that Would Cause Establishments to Switch from HGL (establishment ounts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.18 Levels of Price Difference that Would Cause Establishments to Switch from Distillate Fuel Oil (establishment counts)</li>
				<li><span><a href="xls/Table10_18.xlsx" class="ico xls" title="Table 10.18 Levels of Price Difference that Would Cause Establishments to Switch from Distillate Fuel Oil (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_18.pdf" class="ico pdf" title="Table 10.18 Levels of Price Difference that Would Cause Establishments to Switch from Distillate Fuel Oil (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.19 Levels of Price Difference that Would Cause Establishments to Switch from Residual Fuel Oil (establishment counts)</li>
				<li><span><a href="xls/Table10_19.xlsx" class="ico xls" title="Table 10.19 Levels of Price Difference that Would Cause Establishments to Switch from Residual Fuel Oil (establishment counts)"><span>XLS</span></a> <a href="pdf/Table10_19.pdf" class="ico pdf" title="Table 10.19 Levels of Price Difference that Would Cause Establishments to Switch from Residual Fuel Oil (establishment counts)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.20 Reasons that Made Electricity Unswitchable (quantities)</li>
				<li><span><a href="xls/Table10_20.xlsx" class="ico xls" title="Table 10.20 Reasons that Made Electricity Unswitchable (quantities)"><span>XLS</span></a> <a href="pdf/Table10_20.pdf" class="ico pdf" title="Table 10.20 Reasons that Made Electricity Unswitchable (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.21 Reasons That Made Natural Gas Unswitchable (quantities)</li>
				<li><span><a href="xls/Table10_21.xlsx" class="ico xls" title="Table 10.21 Reasons That Made Natural Gas Unswitchable (quantities)"><span>XLS</span></a> <a href="pdf/Table10_21.pdf" class="ico pdf" title="Table 10.21 Reasons That Made Natural Gas Unswitchable (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.22 Reasons That Made Coal Unswitchable (quantities)</li>
				<li><span><a href="xls/Table10_22.xlsx" class="ico xls" title="Table 10.22 Reasons That Made Coal Unswitchable (quantities)"><span>XLS</span></a> <a href="pdf/Table10_22.pdf" class="ico pdf" title="Table 10.22 Reasons That Made Coal Unswitchable (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.23 Reasons That Made HGL Unswitchable (quantities)</li>
				<li><span><a href="xls/Table10_23.xlsx" class="ico xls" title="Table 10.23 Reasons That Made HGL Unswitchable (quantities)"><span>XLS</span></a> <a href="pdf/Table10_23.pdf" class="ico pdf" title="Table 10.23 Reasons That Made HGL Unswitchable (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.24 Reasons That Made Distillate Fuel Oil Unswitchable (quantities)</li>
				<li><span><a href="xls/Table10_24.xlsx" class="ico xls" title="Table 10.24 Reasons That Made Distillate Fuel Oil Unswitchable (quantities)"><span>XLS</span></a> <a href="pdf/Table10_24.pdf" class="ico pdf" title="Table 10.24 Reasons That Made Distillate Fuel Oil Unswitchable (quantities)"><span>PDF</span></a></span></li>
			</ul>
			<ul>
				<li>Table 10.25 Reasons That Made Residual Fuel Oil Unswitchable (quantities)</li>
				<li><span><a href="xls/Table10_25.xlsx" class="ico xls" title="Table 10.25 Reasons That Made Residual Fuel Oil Unswitchable (quantities)"><span>XLS</span></a> <a href="pdf/Table10_25.pdf" class="ico pdf" title="Table 10.25 Reasons That Made Residual Fuel Oil Unswitchable (quantities)"><span>PDF</span></a></span></li>
			</ul>
		</div>
		<!-- start new panel -->
		<h3 id="r13">Electricity: Components of Net Demand</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 11.1 By Manufacturing Industry and Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table11_1.xlsx" class="ico xls" title="Table 11.1 By Manufacturing Industry and Region"><span>XLS</span></a> <a href="pdf/Table11_1.pdf" class="ico pdf" title="Table 11.1 By Manufacturing Industry and Region"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 11.2 By Value of Shipments & Employment Size Category & Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table11_2.xlsx" class="ico xls" title="Table 11.2 By Value of Shipments & Employment Size Category & Region"><span>XLS</span></a> <a href="pdf/Table11_2.pdf" class="ico pdf" title="Table 11.2 By Value of Shipments & Employment Size Category & Region"><span>PDF</span></a>
			</ul>
		</div>
		<!-- start new panel -->
		<h3 id="r14">Electricity: Components of Onsite Generation</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 11.3. By Manufacturing Industry and Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table11_3.xlsx" class="ico xls" title="Table 11.3. By Manufacturing Industry and Region"><span>XLS</span></a> <a href="pdf/Table11_3.pdf" class="ico pdf" title="Table 11.3. By Manufacturing Industry and Region"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 11.4 By Value of Shipments & Employment Size Category & Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table11_4.xlsx" class="ico xls" title="Table 11.4 By Value of Shipments & Employment Size Category & Region"><span>XLS</span></a> <a href="pdf/Table11_4.pdf" class="ico pdf" title="Table 11.4 By Value of Shipments & Employment Size Category & Region"><span>PDF</span></a>
			</ul>
		</div>
		<!-- start new panel -->
		<h3 id="r15">Electricity: Sales to Utility and Nonutility Purchasers</h3>
		<div class="accordion-content">
			<ul>
				<li>Table 11.5 By Manufacturing Industry and Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table11_5.xlsx" class="ico xls" title="Table 11.5  By Manufacturing Industry and Region"><span>XLS</span></a> <a href="pdf/Table11_5.pdf" class="ico pdf" title="Table 11.5 Electricity Sales to Utility and Nonutility Purchasers By Manufacturing Industry and Regiony"><span>PDF</span></a>
			</ul>
			<ul>
				<li>Table 11.6 By Value of Shipments & Employment Size Category & Region</li>
				<li><span class="formats">Available formats:</span> <a href="xls/Table11_6.xlsx" class="ico xls" title="Table 11.6 By Value of Shipments & Employment Size Category & Region"><span>XLS</span></a> <a href="pdf/Table11_6.pdf" class="ico pdf" title="Table 11.6 By Value of Shipments & Employment Size Category & Region"><span>PDF</span></a>
			</ul>
		</div>
	</div>
</div>