

<!-- BEGIN BANNER, & SEARCH -->
<h2>2006 Energy Consumption by Manufacturers--Data Table</h2>
<p><span class="update">Released June 2009</span></p>
<p><span class="SubSection">Printer-friendly versions:</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="SubSection"><a href="pdf/alltables2006.pdf" target="_blank">2006 Tables</a>| <a href="pdf/alltables2002.pdf">2002 Tables </a></span></p>
<p>Below are data tables from the 2006 Manufacturing Energy Consumption Survey (MECS) that cover energy consumption by energy source type, industry type, and Census Region. The tables provide estimates for energy consumed as a fuel, energy consumed as a nonfuel, energy consumed for all purposes, offsite-produced fuel consumption, energy consumed as a fuel by end use, ratios of fuel consumption, and consumption and generatiq2on of electricity. Tables of average prices of purchased energy sources, energy-management activities, enclosed floor space, and fuel switching capability will be added soon. Definitions of those and other terms necessary to understanding the tables are found by clicking on the section titles. For each of the industry by region tables, there is both a physical unit version and a British Thermal Unit (BTU) version. </p>
<p>MECS 2006 Tables 1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 3.5, 4.1 and 4.2 have been slightly revised as of November, 2009 due to further editing. The revisions in EXCEL are indicated with a value of "R" in an adjacent column. In the PDF versions, the revised values are superscripted with an "R". No further revisions are anticipated for these tables. </p>
<table width="100%" border="0">
  <tr class="TblHeadGrey">
    <th colspan="2" rowspan="2" valign="middle" bordercolor="#000000" class="TblHeadGrey"><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/census.html">Census Region definitions</a></div></th>
    <td colspan="3" bordercolor="#000000"><div align="center">2006</div></td>
    <td colspan="3" bordercolor="#000000"><div align="center"> 2002 </div></td>
    <td colspan="4" bordercolor="#000000"><div align="center">Previous</div></td>
  </tr>
  <tr>
    <td colspan="2" bordercolor="#000000" class="TblHeadGrey"><div align="center">2006 Values</div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">2006 RSE</div></td>
    <td colspan="2" bordercolor="#000000" class="TblHeadGrey"><div align="center">Values</div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center"><a 
            href="data02/rseexcel/rsedef.html">RSE</a></div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">1998 </div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">1998<br />
      (SIC) </div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">1994 </div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">1991</div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><a name=allpurposes>Consumption of Energy for All Purposes</a> <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/firstusedef.html"><strong> (First Use)</strong></a></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 1.1</strong></td>
    <td width="50%">By Mfg. Industry &amp; Region (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table1_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table1_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable1_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table1.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable1.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n1_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s1_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_01a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs01a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 1.2</strong></td>
    <td>By Mfg. Industry &amp; Region (trillion Btu) </td>
    <td><div align="center"><a 
            href="excel/Table1_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table1_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable1_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table1.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 1.2:By Manufacturing Industry and Region (trillion Btu) " border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.2-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable1.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n1_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s1_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_01b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs01b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 1.3</strong></td>
    <td>By Value of Shipments & Employment Size Category & Region</td>
    <td><div align="center">
      <div align="center"><a 
            href="excel/Table1_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category & Region" border=0 align="top" /></a></div>
    </div></td>
    <td><div align="center"><a href="pdf/Table1_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Value of Shipments & Employment Size Category & Region" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable1_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category & Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table1.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 1.3:By Value of Shipments and Employment Size Category and Region" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.3-By Value of Shipments and Employment Size Category and Region" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e1_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s1_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_01c.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs09.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 1.4</strong></td>
    <td>Number of Establishments Using Energy Consumed for All Purpose</td>
    <td><div align="center"><a 
            href="excel/Table1_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Number of Establishments Using Energy Consumed for All Purpose" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table1_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Value of Shipments & Employment Size Category & Region" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable1_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category & Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table1.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 1.4 - By Further Classification of "other" energy sources" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.4_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:Table 1.4 - By Further Classification of "other" energy sources" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98c1_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s1_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_01c.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 1.5</strong></td>
    <td>By Further Classification of "Other" Energy Sources</td>
    <td><div align="center">
      <div align="center"><a 
            href="excel/Table1_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div>
    </div></td>
    <td><div align="center">
      <div align="center"><a href="pdf/Table1_5.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div>
    </div></td>
    <td><div align="center"><a 
            href="excel/RSETable1_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table1.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 1.5 - By Further Classification of "" border=0 align="top"other" energy sources /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.5_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:Table 1.4 - By Further Classification of "other" energy sources" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n1_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s1_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_74.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr>
    <td colspan="12" class="SectionHead"><a name=nonfuel class="style1"></a>Energy Used as a <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/nonfueldef.html"><strong>Nonfuel </strong></a><span class="style4">(Feedstock)</span></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 2.1</strong></td>
    <td nowrap>By Mfg. Industry &amp; Region (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table2_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table2_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable2_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table2.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 2.1 -&nbsp;By Manufacturing Industry and Region (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table2.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 2.1:By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable2.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n2_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s2_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_03a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs03a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 2.2</span></td>
    <td><span class="SubSection">By Mfg. Industry &amp; Region (trillion Btu)</span></td>
    <td><div align="center"><a 
            href="excel/Table2_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table2_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable2_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table2.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 2.2 - By Manufacturing Industry and Region (trillion Btu) " border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table2.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 2.2:By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable2.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n2_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s2_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_03b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs03b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 2.3</span></td>
    <td>By Value of Shipments &amp; Employment Size Category</td>
    <td><div align="center"><a 
            href="excel/Table2_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table2_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Value of Shipments & Employment Size Category" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable2_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:BBy Value of Shipments & Employment Size Category" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table2.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 2.3 - By Value of Shipments and Employment Size Category" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table2.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 2.3 - By Value of Shipments and Employment Size Category" width="16" height="16" border="0" align="top" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e2_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_22.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs11.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 2.4</span></td>
    <td><span class="SubSection">Number of Establishment Using Energy Consumed as a Nonfuel</span></td>
    <td><div align="center"><a 
            href="excel/Table2_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Number of Establishment Using Energy Consumed as a Nonfuel" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table2_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:Number of Establishment Using Energy Consumed as a Nonfuel" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable2_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Number of Establishment Using Energy Consumed as a Nonfuel" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table2.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 2.4 - Number of Establishment Using Energy Consumed as a Nonfuel" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table2.4_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 2.4 - Number of Establishment Using Energy Consumed as a Nonfuel" width="16" height="16" border="0" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98c2_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_03c.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><div align="left"><a name=fuel id="fuel"></a>Energy Consumption as a <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/fueldef.html"><strong>Fuel</strong></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 3.1</span></td>
    <td nowrap>By Mfg. Industry &amp; Region (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table3_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table3_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 3.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable3_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table3.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 3.1 - By Manufacturing Industry and Region (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table3.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 3.1:By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable3.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n3_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s3_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_04a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs04a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 3.2</span></td>
    <td><span class="SubSection">By Mfg. Industry &amp; Region (trillion Btu)</span></td>
    <td><div align="center"><a 
            href="excel/Table3_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table3_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 3.2-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable3_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table3.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 3.2 - By Manufacturing Industry and Region (trillion Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table3.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 3.2 - By Manufacturing Industry and Region (trillion Btu)" width="16" height="16" border="0" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable3.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n3_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s3_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_04b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs04b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 3.3</span></td>
    <td>By Value of Shipments &amp; Employment Size Category &amp; Region</td>
    <td><div align="center"><a 
            href="excel/Table3_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category & Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table3_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 3.2-By Value of Shipments & Employment Size Category & Region" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable3_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category & Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table3.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 3.3 - By Value of Shipments and Employment Size Category and Region" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table3.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 3.3 - By Value of Shipments and Employment Size Category and Region" width="16" height="16" border="0" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_23.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs12.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 3.4</span></td>
    <td><span class="SubSection">Number of Establishments Using Energy Consumed as a Fuel</span></td>
    <td><div align="center"><a 
            href="excel/Table3_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category & Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table3_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 3.2-By Value of Shipments & Employment Size Category & Region" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable3_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category & Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table3.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 3.4 - Number of Establishments Using Energy Consumed as a Fuel" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table3.4_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 3.4:Number of Establishments Using Energy Consumed as a Fuel" width="16" height="16" border="0" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_04c.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 3.5</span></td>
    <td>Byproducts in Fuel Consumption by Mfg. Industry &amp; Region (trillion&nbsp;Btu)</td>
    <td><div align="center"><a 
            href="excel/Table3_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table3_5.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable3_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table3.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 3.5 - Byproducts in Fuel Consumption by Manufacturing Industry and Region (trillion&nbsp;Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table3.5_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 3.5:Byproducts in Fuel Consumption by  Manufacturing Industry and Region(trillion Btu)" width="16" height="16" border="0" longdesc="pdf/table3.5_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable3.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n5_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s5_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs06.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 3.6</span></td>
    <td nowrap><span class="SubSection">Selected Wood &amp; Wood-Related Products in Fuel Consumption</span></td>
    <td><div align="center"><a 
            href="excel/Table3_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table3_6.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable3_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table3.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 3.6 - Selected Wood and Wood-Related Products in Fuel Consumption" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table3.6_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 3.6:Selected Wood and Wood-Related Products in Fuel Consumption" width="16" height="16" border="0" longdesc="pdf/table3.6_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_73.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><div align="left"><a name=offsite 3></a><a href="http://www.eia.gov/emeu/mecs/mecs98/datatables/offsitedef.html">Offsite-Produced Fuel</a> Consumption </div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 4.1</span></td>
    <td>By Mfg. Industry (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table4_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table4_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable4_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table4.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 4.1 - By Manufacturing Industry (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table4.1_02.pdf" class="SubSectionSHD"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 4.1:By Manufacturing Industry (Physical units)" width="16" height="16" border="0" longdesc="pdf/table4.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable4.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n4_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s4_1.xls" class="SubSectionSHD"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_05a.wk"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs05a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 4.2</span></td>
    <td><span class="SubSection">By Mfg. Industry &amp; Region (trillion Btu)</span></td>
    <td><div align="center"><a 
            href="excel/Table4_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table4_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Manufacturing Industry and Region(Physical units)" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable4_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Manufacturing Industry and Region (physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table4.2_02.xls"><img 

            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 4.2 - By Manufacturing Industry and Region (trillion Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table4.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 4.2:By Manufacturing Industry and Region(trillion Btu)" width="16" height="16" border="0" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable4.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n4_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98s4_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_05b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs05b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 4.3</span></td>
    <td>By Value of Shipments &amp; Employment Size Category&nbsp;</td>
    <td><div align="center"><a 
            href="excel/Table4_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category " border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table4_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:table 1.1-By Value of Shipments & Employment Size Category " width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable4_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:By Value of Shipments & Employment Size Category " border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table4.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 4.3 - By Value of Shipments and Employment Size Category" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table4.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 4.3 - By Value of Shipments and Employment Size Category" width="16" height="16" border="0" class="SubSectionSHD" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e4_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_24.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 

            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs13.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 4.4</span></td>
    <td><span class="SubSection">Number of Establishments Using Offsite-Produced Fuel for Consumption</span></td>
    <td><div align="center"><a 
            href="excel/Table4_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Number of Establishments Using Offsite-Produced Fuel for Consumption" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table4_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf logo:Number of Establishments Using Offsite-Produced Fuel for Consumption" width="16" height="16" border="0" longdesc="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table1.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable4_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Number of Establishments Using Offsite-Produced Fuel for Consumption" width="15" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table4.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 4.4 - Number of Establishments Using Offsite-Produced Fuel for Consumption" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table4.4_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 4.4:Number of Establishments Using Offsite-Produced Fuel for Consumption" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98c4_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_05c.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><a name="energy"></a><a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/endusedef.html" 
            name="enduse">Energy Consumed as a Fuel by End Use</a></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 5.1</span></td>
    <td>By Mfg. Industry with Net Electricity (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table5_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table5_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable5_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table5.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table5.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable5.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n6_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n6_1.xls"></a>&nbsp;</div></td>
    <td><div align="center"><a 

            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_10a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs36a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 5.2</span></td>
    <td><span class="SubSection">By Mfg. Industry with Net Electricity (trillion Btu)</span></td>
    <td><div align="center"><a 
            href="excel/Table5_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table5_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable5_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table5.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.2 - By Manufacturing Industry with Net Electricity (trillion Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/ata02/pdf/table5.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.2:By Manufacturing Industry with Net Electricity (trillion Btu)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable5.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n6_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_10b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs36b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 5.3</span></td>
    <td>By Mfg. Industry with Total Consumption of Electricity (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table5_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table5_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable5_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table5.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.3 - By Manufacturing Industry with Total Consumption of Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table5.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.3:By Manufacturing Industry with Total Consumption of Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable5.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n6_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_11a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs37a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 5.4</span></td>
    <td>By Mfg. Industry with Total Consumption of Electricity (trillion Btu)</td>
    <td><div align="center"><a 
            href="excel/Table5_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table5_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable5_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table5.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.4 - By Manufacturing Industry with Total Consumption of Electricity (trillion Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="dhttp://www.eia.gov/emeu/mecs/mecs2002/ata02/pdf/table5.4_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.3:By Manufacturing Industry with Total Consumption of Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable5.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e6_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_12b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs37b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 5.5</span></td>
    <td>By Region with Net Electricity (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table5_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table5_5.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable5_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table5.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.5 - By Region with Net Electricity (physical units" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table5.5_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.5:By Region with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable5.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e6_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_13a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs39a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 5.6</span></td>
    <td><span class="SubSection">By Region with Net Electricity (trillion Btu)</span></td>
    <td><div align="center"><a 
            href="excel/Table5_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table5_6.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable5_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table5.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.6 -&nbsp;By Region with Net Electricity (trillion Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table5.6_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.6:By Region with Net Electricity (trillion Btu)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable5.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e6_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_13b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs39b.wk1"><img 

            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 5.7</span></td>
    <td nowrap>By Region with Total Consumption of Electricity (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table5_7.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table5_7.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable5_7.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table5.7_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.7 - By Region with Total Consumption of Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table5.7_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.7:By Region with Total Consumption of Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="/mecs2002/data02/rseexcel/rsetable5.7_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e6_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_13a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs39a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 5.8</span></td>
    <td nowrap><span class="SubSection">By Region with Total Consumption of Electricity (trillion Btu)</span></td>
    <td><div align="center"><a 
            href="excel/Table5_8.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table5_8.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.1:By Manufacturing Industry with Net Electricity (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable5_8.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.1 - By Manufacturing Industry with Net Electricity (physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table5.8_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 5.8 - By Region with Total Consumption of Electricity (trillion Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table5.8_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 5.8:By Region with Total Consumption of Electricity (trillion Btu)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable5.8_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e6_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_13b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs39b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><a
            name="ratios"></a><a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/ratiodef.html">Ratios of Mfg. Fuel Consumption to Economic Characteristics</a></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 6.1</span></td>
    <td>By Mfg. Industry &amp; Region</td>
    <td><div align="center"><a 
            href="excel/Table6_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.1 - By Mfg. Industry & Region" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table6_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 6.1 - By Manufacturing Industry and Region</span>" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable6_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.1 - By Manufacturing Industry and Region" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table6.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.1 - By Manufacturing Industry and Region" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table6.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 6.1 - By Manufacturing Industry and Region</span>" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable6.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n7_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_47.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs08.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 6.2</span></td>
    <td><span class="SubSection">By Value of Shipments or Employment Size Category &amp; Region</span>&nbsp;</td>
    <td><div align="center"><a 
            href="excel/Table6_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.1 - By Value of Shipments or Employment Size Category & Region " border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table6_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 6.1 - By Value of Shipments or Employment Size Category & Region </span>" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable6_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.2 - By Value of Shipments or Employment Size Category & Region " border=0 /></a></div></td>
    <td><div align="center"><a 
            href="data02/excel/table6.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.2 - By Value of Shipments or Employment Size Category and Region&nbsp;" border=0 /></a></div></td>
    <td><div align="center"><a href="data02/pdf/table6.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 6.2 - By Value of Shipments or Employment Size Category and Region&nbsp;" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable6.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e7_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_48.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs08.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 6.3</span></td>
    <td>By Mfg. Industry &amp; Value of Shipments</td>
    <td><div align="center"><a 
            href="excel/Table6_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.1 - By Mfg. Industry & Value of Shipments;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table6_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="By Mfg. Industry & Value of Shipments</span>" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable6_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.3 - By Mfg. Industry & Value of Shipments;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table6.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.3 - By Manufacturing Industry and Value of Shipments" border=0 /></a></div></td>
    <td><div align="center"><a href="data02/pdf/table6.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 6.3 - By Manufacturing Industry and Value of Shipments" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable6.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e7_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs94_45.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs50.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 6.4</span></td>
    <td><strong class="SubSection">By Mfg. Industry &amp; Employment Size</strong></td>
    <td><div align="center"><a 
            href="excel/Table6_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="file:///X|/EMEU/mecs/mecs2006/pdf/Table6_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 6.4 - By Mfg. Industry & Employment Size;</span>" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable6_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="data02/excel/table6.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Manufacturing Industry and Employment Size" border=0 /></a></div></td>
    <td><div align="center"><a href="data02/pdf/table6.4_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 6.4 - By Manufacturing Industry and Employment Size" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable6.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e7_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_46.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs51.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><div align="left"> <a name=average></a>Average Prices of <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/purchasedenergydef.html">Purchased Energy </a>Sources</div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 7.1</span></td>
    <td nowrap>All Collected Energy Sources by Mfg. Industry &amp; Region (dollars per physical units)</td>
    <td><div align="center"><a 
            href="excel/Table7_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/excel/table7.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n8_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="bottom" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_42a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 7.2</span></td>
    <td nowrap><span class="SubSection">All Collected Energy Sources by Mfg. Industry &amp; Region (dollars per million Btu)</span></td>
    <td><div align="center"><a 
            href="excel/Table7_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table7.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.2 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per million Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.2 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per million Btu)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n8_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_42b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td nowrap><span class="report_bold">Table 7.3</span></td>
    <td>Purchased Electricity, Natural Gas, Steam by type of Supplier, Mfg. Industry, &amp; Region (dollars per physical unit)</td>
    <td><div align="center"><a 
            href="excel/Table7_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table7.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.2 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per million Btu)" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="pdf width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:" border=0 /></a><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n8_3.xls"></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n8_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_43.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs47.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 7.4</span></td>
    <td><span class="SubSection">Selected Energy Sources by Region &amp; Employment or Value of Shipments Size Categories (dollars per physical unit)</span></td>
    <td><div align="center"><a 
            href="excel/Table7_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table7.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.4 - Selected Energy Sources by Region and Employment or Value of Shipments Size Categories&nbsp;(dollars per physical unit)" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.4_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.4 - Selected Energy Sources by Region and Employment or Value of Shipments Size Categories&nbsp;(dollars per physical unit)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e8_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_41a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs29a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 7.5</span></td>
    <td>Selected Energy Sources by Region &amp; Employment or Value of Shipments Size Categories (dollars per million Btu)</td>
    <td><div align="center"><a 
            href="excel/Table7_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_5.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table7.5_02.xls"><img 

            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.5 - Selected Energy Sources by Region and Employment or Value of Shipments Size Categories dollars per million Btu)" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.5_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.5 - Selected Energy Sources by Region and Employment or Value of Shipments Size Categories dollars per million Btu)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e8_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_41b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs29b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><a name=quantity></a>Quantity of <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/purchasedenergydef.html">Purchased Energy</a></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 7.6</span></td>
    <td nowrap>Selected Energy Sources by Mfg. Industry &amp; Region (physical units)</td>
    <td><div align="center"><a 
            href="excel/Table7_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_6.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table7.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table7.6_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.6 - Selected Energy Sources by Manufacturing Industry and Region (physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt=" " border=0 /></a><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n11_1.xls"></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n11_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_32.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs22.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 7.7</span></td>
    <td nowrap><span class="SubSection">Purchased Electricity, Natural Gas, Steam by type of Supplier, Mfg., Industry, &amp; Region</span></td>
    <td><div align="center"><a 
            href="excel/Table7_7.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.7" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_7.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.7" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_7.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.7;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table7.7_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.7 - Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.7_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.7 - Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region" width="16" height="16" border="0" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.7_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n11_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_34.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs23.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 7.8</span></td>
    <td>Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, &amp; Mfg. Industry</td>
    <td><div align="center"><a 
            href="excel/Table7_8.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_8.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_8.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table7.8_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.8 - Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, and Manufacturing Industry" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.8_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.8:Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, and Manufacturing Industry" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98c11_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><div align="left"> <a 
            name=expenditures></a>Expenditures for <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/purchasedenergydef.html">Purchased Energy</a> (Millions of Dollars)</div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 7.9</span></td>
    <td>Selected Energy Sources by Mfg. Industry &amp; Region</td>
    <td><div align="center"><a 
            href="excel/Table7_9.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_9.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_9.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/excel/table7.9_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.9 - Selected Energy Sources by Manufacturing Industry and Region" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.9_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.9 - Selected Energy Sources by Manufacturing Industry and Region" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.9_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n11_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_36.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs24.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 7.10</span></td>
    <td><span class="SubSection">Purchased Electricity, Natural Gas, Steam by type of Supplier, Mfg., Industry, &amp; Region</span></td>
    <td><div align="center"><a 
            href="excel/Table7_10.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table7_10.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable7_10.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 6.4 - By Mfg. Industry & Employment Size;" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="file:///X|/EMEU/mecs/mecs2002/data02/excel/table7.10_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.9 - Selected Energy Sources by Manufacturing Industry and Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table7.10_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.9 - Selected Energy Sources by Manufacturing Industry and Region" width="16" height="16" border="0" align="bottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable7.10_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 align="top" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n11_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs46.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="TblHeadGrey">
    <td colspan="2" rowspan="2" bordercolor="#000000"><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/census.html">Census Region definitions</a></div></td>
    <td colspan="3" bordercolor="#000000"><div align="center">2006</div></td>
    <td colspan="3" bordercolor="#000000"><div align="center">2002 </div></td>
    <td colspan="4" bordercolor="#000000">Previous</td>
  </tr>
  <tr class="SubSectionSHD">
    <td colspan="2" bordercolor="#000000" class="TblHeadGrey"><div align="center">Values</div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">RSE</div></td>
    <td colspan="2" bordercolor="#000000" class="TblHeadGrey"><div align="center">Values</div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center"><a 
            href="data02/rseexcel/rsedef.html">RSE</a></div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">1998</div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">1998<br />
      (SIC)</div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">1994 </div></td>
    <td bordercolor="#000000" class="TblHeadGrey"><div align="center">1991</div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><div align="left"><a name=management></a>Energy Management Activities &amp; Energy-Savings Technologies</div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 8.1</span></td>
    <td>Number of Establishments Participating in <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/emadef.html" class="SubSection"><strong>Energy Management Activities </strong></a></td>
    <td><div align="center"><a 
            href="excel/Table8_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table8_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="excel" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable8_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table8.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table8.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.9 - Selected Energy Sources by Manufacturing Industry and Region" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable8.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98c9_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_49b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 8.2</span></td>
    <td><span class="SubSection">Number of Establishments with <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/gentechdef.html"><strong>General Technologies</strong></a></span></td>
    <td><div align="center"><a 
            href="excel/Table8_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table8_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="excel" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable8_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table8.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table8.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="excel" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable8.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 7.1 - All Collected Energy Sources by Manufacturing Industry and Region (dollars per physical units)" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98c10_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_54b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 8.3</span></td>
    <td>Number of Establishments with <a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/cogentechdef.html"><strong>Cogeneration Technologies</strong></a></td>
    <td><div align="center"><a 
            href="excel/Table8_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table8_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="excel" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable8_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="http://www.eia.gov/emeu/mecs/mecs2002/data02/excel/table8.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table8.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.9 - Selected Energy Sources by Manufacturing Industry and Region" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable8.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98c10_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_55b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 8.4</strong></td>
    <td>Number of Establishments Participating in Specific Energy-Management Activities</td>
    <td><div align="center"><a 
            href="excel/Table8_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table8_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="excel" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable8_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><a 
            name=floorspace></a>Floorspace &amp; Building Counts</td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 9.1</span></td>
    <td>Enclosed Floorspace &amp; Number of Establishment Buildings&nbsp;</td>
    <td><div align="center"><a href="excel/Table9_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><a href="pdf/Table9_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="excel" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></td>
    <td><div align="center"><a href="excel/RSETable9_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/excel/table9.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="" border=0 /></a></div></td>
    <td><div align="center"><a href="http://www.eia.gov/emeu/mecs/mecs2002/data02/pdf/table9.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 7.9 - Selected Energy Sources by Manufacturing Industry and Region" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98c12_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_07.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SectionHead">
    <td colspan="12"><a name="switch"></a>Fuel Switching </td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.1</strong></td>
    <td>Nonswitchable Minimum Requirements &amp; Maximum Consumption Potential</td>
    <td><div align="center"><a href="excel/Table10_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="excel" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.2 - Nonswitchable Minimum Requirements and Maximum Consumption Potential" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable10.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.1 - Nonswitchable Minimum Requirements and Maximum Consumption Potential</span>" border=0 align="top" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_57.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs52.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 10.2</span></td>
    <td><span class="SubSection">Capability to Switch from Natural Gas to Alternative Energy (quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="excel" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.2 - Capability to Switch from Natural Gas to Alternative Energy" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.2 - Capability to Switch from Natural Gas to Alternative Energy" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a href="data02/rseexcel/rsetable10.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.2 - Capability to Switch from Natural Gas to Alternative Energy" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_59a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs54.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.3</strong></td>
    <td>Capability to Switch from Natural Gas to Alternative Energy Sources (establishment counts)</td>
    <td><div align="center" class="style5">
      <div align="center"><a href="excel/Table10_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div>
    </div></td>
    <td><div align="center"><a href="pdf/Table10_3.pdf" class="style6"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.3" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center" class="style6">
      <div align="center"><a href="excel/RSETable10_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div>
    </div></td>
    <td><div align="center" class="style6"><a href="../mecs2002/data02/excel/table10.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3 - Number of Establishments by Capability to Switch from Natural Gas to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center" class="style6"><a href="../mecs2002/data02/pdf/table10.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.3 -Number of Establishments by Capability to Switch from Natural Gas to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><span class="style6"></span></div></td>
    <td><div align="center" class="style6"><a href="data02/rseexcel/rsetable10.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3 - Number of Establishments by Capability to Switch from Natural Gas to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><span class="style6"></span></div></td>
    <td><div align="center" class="style6"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_59b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><span class="style6"></span></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 10.4</span></td>
    <td><span class="SubSection">Capability to Switch from Residual Fuel Oil to Alternative Energy Sources(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_4.pdf" class="style6"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.3" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.4 - Capability to Switch from Residual Fuel Oil to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.4_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.4 - Capability to Switch from Residual Fuel Oil to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a href="data02/rseexcel/rsetable10.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.4 -Capability to Switch from Residual Fuel Oil to Alternative Energy Sources " border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_63a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs56.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.5</strong></td>
    <td>Capability to Switch from Residual Fuel Oil to Alternative Energy Sources(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.5" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_5.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.5" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.5" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.5 - Number of Establishments by Capability to Switch from Residual Fuel Oil to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.5_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.5 - Number of Establishments by Capability to Switch from Residual Fuel Oil to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a href="data02/rseexcel/rsetable10.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3 -Number of Establishments by Capability to Switch from Residual Fuel Oil to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_63b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 10.6</span></td>
    <td><span class="SubSection">Capability to Switch from Electricity to Alternative Energy Sources(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_5.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.5" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.6 -Capability to Switch from Electricity to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.6_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.6 - Capability to Switch from Electricity to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a href="data02/rseexcel/rsetable10.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.6 - Capability to Switch from Electricity to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_67a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs53.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 10.7</span></td>
    <td>Capability to Switch from Electricity to Alternative Energy Sources(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_7.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.7" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_7.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.7" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_7.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.7" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.7_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.7 - Number of Establishments by Capability to Switch from Electricity to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.7_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.7 - Number of Establishments by Capability to Switch from Electricity to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a href="data02/rseexcel/rsetable10.7_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.7 - Number of Establishments by Capability to Switch from Electricity to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_67b.wk1"><img 

            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 10.8</span></td>
    <td>Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources<span class="SubSection">(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_8.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_8.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.7" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_8.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.8_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.8 - Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources" border=0 /></a><a href="data02/excel/table10.7_02.xls"></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.8_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.8 - Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a><a href="data02/pdf/table10.7_02.pdf"></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/rseexcel/rsetable10.8_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.8 - Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="data02/rseexcel/rsetable10.7_02.xls"></a>&nbsp;</div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_68a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_67b.wk1"></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs55.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 10.9</span></td>
    <td>Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_9.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.9" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_9.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.9" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_9.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.9-" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.9_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.9 - Number of Establishments by Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.9_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.9 - Number of Establishments by Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/rseexcel/rsetable10.9_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.9 - Number of Establishments by Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_68b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 10.10</span></td>
    <td>Capability to Switch from Coal to Alternative Energy Sources<span class="SubSection">(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_10.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_10.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.9" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_10.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.10_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.10 - Capability to Switch from Coal to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.10_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.10 -Capability to Switch from Coal to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/rseexcel/rsetable10.10_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.10 - Capability to Switch from Coal to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_69a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs57.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 10.11</span></td>
    <td>Capability to Switch from Coal to Alternative Energy Sources(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_11.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.11 - " border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_11.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.11 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_11.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.11" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.11_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.11 - Number of Establishments by Capability to Switch from Coal to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.11_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.11 - Number of Establishments by Capability to Switch from Coal to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/rseexcel/rsetable10.10_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.11 - Number of Establishments by Capability to Switch from Coal to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_69b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 10.12</span></td>
    <td><span class="SubSection">Capability to Switch from LPG to Alternative Energy Sources(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_12.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_12.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.12 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_12.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.12_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.12 - Capability to Switch from LPG to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.12_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.12 - Capability to Switch from LPG to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/rseexcel/rsetable10.12_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.12 - Capability to Switch from LPG to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_70a.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs58.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 10.13</span></td>
    <td>Capability to Switch from LPG to Alternative Energy Sources(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_13.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.13-" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_13.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.13 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_13.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.13- " border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/excel/table10.13_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.13 - Number of Establishments by Capability to Switch from LPG to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table10.13_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.13 - Number of Establishments by Capability to Switch from LPG to Alternative Energy Sources" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/rseexcel/rsetable10.13_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.13 - Number of Establishments by Capability to Switch from LPG to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_70b.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 10.14</strong></td>
    <td>Levels of Price Difference that  Would Cause Establishments to Switch from Electricity<span class="SubSection">(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_14.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_14.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.13 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_14.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.15</strong></td>
    <td>Levels of Price Difference that  Would Cause Establishments to Switch from Natural Gas(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_15.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_15.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.13 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_15.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 10.16</strong></td>
    <td>Levels of Price Difference that Would Cause Establishments to Switch from Coal<span class="SubSection">(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_16.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_16.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.13 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_16.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.17</strong></td>
    <td>Levels of Price Difference that Would Cause Establishments to Switch from LPG(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_17.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_17.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.13 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_17.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 10.18</strong></td>
    <td>Levels of Price Difference that Would Cause Establishments to Switch from Distillate Fuel Oil<span class="SubSection">(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_18.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_18.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.13 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_18.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.19</strong></td>
    <td>Levels of Price Difference that Would Cause Establishments to Switch from Residual Fuel Oil(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_19.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_19.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.13 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_19.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 10.20</strong></td>
    <td> Reasons that Made Electricity Unswitchable<span class="SubSection">(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_20.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3 - Number of Establishments by Capability to Switch from Natural Gas to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_20.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.20 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_20.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.20 - " border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.21</strong></td>
    <td>Reasons That Made Natural Gas Unswitchable(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_21.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.21- " border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_21.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.21 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_21.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.21-" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 10.22</strong></td>
    <td>Reasons That Made Coal Unswitchable<span class="SubSection">(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_22.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.22-" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_22.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.22 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_22.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.3 - Number of Establishments by Capability to Switch from Natural Gas to Alternative Energy Sources" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.23</strong></td>
    <td>Reasons That Made LPG Unswitchable(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_23.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.23-" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_23.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.23 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_23.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.22-" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><strong>Table 10.24</strong></td>
    <td>Reasons That Made Distillate Fuel Oil Unswitchable<span class="SubSection">(quantities)</span></td>
    <td><div align="center"><a href="excel/Table10_24.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.24 - " border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_24.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.24 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_24.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.24 -" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr class="SubSection">
    <td><strong>Table 10.25</strong></td>
    <td>Reasons That Made Residual Fuel  Oil Unswitchable(establishment counts)</td>
    <td><div align="center"><a href="excel/Table10_25.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.25" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table10_25.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.25 -" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table4.2_02.pdf" /></a></div></td>
    <td><div align="center"><a href="excel/RSETable10_25.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.25-" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
  </tr>
  <tr>
    <td colspan="12" valign="bottom" class="SectionHead" ><a 
            href="http://www.eia.gov/emeu/mecs/mecs98/datatables/netdemand.html" 
            name="totalelectricity"></a>Total Consumption of Electricity</td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 11.1</span></td>
    <td>By Mfg. Industry &amp; Region</td>
    <td><div align="center"><a 
            href="excel/Table11_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.1 - By Manufacturing Industry and Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="data02/excel/table11.1_02.xls"></a><a href="pdf/Table11_1.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 11.1:By Manufacturing Industry and Region" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable11_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.1 - By Manufacturing Industry and Region" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="data02/excel/table11.1_02.xls"></a><a 
            href="../mecs2002/data02/excel/table11.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.1 - By Manufacturing Industry and Region" border=0 align="top" /></a><a href="data02/pdf/table11.1_02.pdf"></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/pdf/table11.1_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.1:By Manufacturing Industry and Region" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table2.1_02.pdf" /></a><a 
            href="data02/rseexcel/rsetable11.1_02.xls"></a></div></td>
    <td><div align="center"><a 
            href="data02/rseexcel/rsetable11.1_02.xls"></a><a 
            href="../mecs2002/data02/rseexcel/rsetable11.1_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98n13_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_25.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs16.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 11.2</span></td>
    <td><span class="SubSection">By Value of Shipments &amp; Employment Size Category</span></td>
    <td><div align="center"><a 
            href="excel/Table11_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="By Value of Shipments & Employment Size Category" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table11_2.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="By Value of Shipments & Employment Size Category" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="file:///Z|/cons/mecs/data_tables/mecs2006/RSETable11_2.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="By Value of Shipments & Employment Size Category" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/excel/table11.2_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.2 - By Value of Shipments and Employment Size Category" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table11.2_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 11.2 - By Value of Shipments and Employment Size Category " width="16" height="16" border="0" align="absbottom" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e13_1.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98e13_1.xls"></a>&nbsp;</div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_26.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs19.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="top" /></a></div></td>
  </tr>
  <tr>
    <td colspan="12" class="SectionHead">Components of Onsite Generation of Electricity</td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 11.3</span></td>
    <td>By Mfg. Industry</td>
    <td><div align="center"><a 
            href="excel/Table11_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="By Mfg. Industry" border=0 align="top" /></a></div></td>
    <td><div align="center"><a href="pdf/Table11_3.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="By Mfg. Industry" width="16" height="16" border="0" /></a></div></td>
    <td><div align="center"><a 
            href="excel/RSETable11_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="By Mfg. Industry" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/excel/table11.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 11.3 - By Manufacturing Industry" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table11.3_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 10.3:By Manufacturing Industry and Region" width="16" height="16" border="0" align="top" longdesc="pdf/table10.3_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable11.3_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98nl1_3.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_27.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs17.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 11.4</span></td>
    <td><span class="SubSection">By Value of Shipments &amp; Employment Size Category</span></td>
    <td><div align="center"><a 
            href="excel/Table11_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.4 - By Value of Shipments and Employment Size Category" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table11_4.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="By Value of Shipments & Employment Size Category" width="16" height="16" border="0" align="absbottom" longdesc="pdf/table2.1_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/Table11_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.4 - By Value of Shipments and Employment Size Category" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/excel/table11.4_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo:Table 10.4 - By Value of Shipments and Employment Size Category" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98el1_4.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98el3_2.xls"></a>&nbsp;</div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_28.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs20.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr>
    <td colspan="12" class="SectionHead"><div align="left"> <a 
            name=electricitysales></a>Electricity Sales to Utility &amp; Nonutility Purchasers</div></td>
  </tr>
  <tr class="SubSection">
    <td><span class="report_bold">Table 11.5</span></td>
    <td>By Mfg. Industry</td>
    <td><div align="center">
      <div align="center"><a 
            href="excel/Table11_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.5 - By Mfg. Industry" border=0 /></a></div>
    </div></td>
    <td><div align="center"><a href="pdf/Table11_5.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 11.5 - By Mfg. Industry" width="16" height="16" border="0" align="top" longdesc="pdf/table10.5_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="excel/Table11_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.5 - By Mfg. Industry" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/excel/table11.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.5 - By Manufacturing Industry" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table11.5_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 11.5 - By Manufacturing Industry" width="16" height="16" border="0" align="top" longdesc="pdf/table10.5_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/rseexcel/rsetable11.5_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.5 - By Manufacturing Industry" border=0 /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98nl1_5.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_30.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs18.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
  <tr class="SubSectionSHD">
    <td><span class="report_bold">Table 11.6</span></td>
    <td><span class="SubSection">By Value of Shipments &amp; Employment Size Category</span></td>
    <td><div align="center"><a 
            href="excel/Table11_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.6 - By Value of Shipments and Employment Size Category" border=0 /></a></div></td>
    <td><div align="center"><a href="pdf/Table11_6.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 11.6 - By Value of Shipments & Employment Size Category" width="16" height="16" border="0" align="top" longdesc="pdf/table10.5_02.pdf" /></a></div></td>
    <td><div align="center"><a 
            href="data02/excel/table11.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.6 - By Value of Shipments & Employment Size Category" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="../mecs2002/data02/excel/table11.6_02.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="Table 11.6 - By Value of Shipments and Employment Size Category" border=0 /></a></div></td>
    <td><div align="center"><a href="../mecs2002/data02/pdf/table11.6_02.pdf"><img src="http://www.eia.gov/emeu/mecs/mecs2002/images/pdf.gif" alt="Table 11.6 - By Value of Shipments and Employment Size Category" width="16" height="16" border="0" align="top" longdesc="pdf/table10.5_02.pdf" /></a></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/d98el1_6.xls"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 align="top" /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/m94_31.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
    <td><div align="center"><a 
            href="ftp://ftp.eia.doe.gov/pub/consumption/industry/mecs21.wk1"><img 
            src="http://www.eia.gov/emeu/mecs/mecs2002/images/xls.gif" alt="excel logo" border=0 /></a></div></td>
  </tr>
</table>
