<div class="secondary">
	<ul>
		<li><a href="../../about.php">About the MECS</a></li>
		<li><a href="/survey/#eia-846">Survey forms</a></li>
		<li><a href="/consumption/manufacturing/maps.php">Maps</a></li>
		<li><a href="../../terms.php">MECS Terminology</a></li>
		<li><a href="../archive/">Archives</a></li>
		<li class="head">Other End Use Survey Data</li>
		<li><a href="/consumption/commercial/">Commercial Buildings - CBECS</a></li>
		<li><a href="/consumption/residential/">Residential - RECS</a></li>
	</ul>
</div>