<h1 class="l-border-bottom l-border-thin">
    <?=$pageTitle?>
</h1>
<p>Understanding what moves crude oil prices is vital for informed decision-making across government, industry, and the public. Crude oil prices are shaped by a dynamic interplay of global forces, and have impacts on energy security, the economy, and consumers.</p>
<p>Here, we present an <strong>analysis of the seven key factors that influence crude oil markets</strong>, including both physical market dynamics and influences from trading and finance, and examine their connection to crude oil prices.</p>
<p>This resource serves as a guide for those seeking a deeper understanding of crude markets and the major drivers of crude prices.</p>
<h3>Key factors influencing crude oil prices:</h3>
<ul>
    <li>Spot prices </li>
    <li>Supply from non-OPEC countries </li>
    <li>Supply from OPEC countries</li>
    <li>The supply demand balance: inventories</li>
    <li>Financial markets</li>
    <li>Demand in non-OECD countries</li>
    <li>Demand in OECD countries</li>
</ul>