<div id="sticker" class="social-fixed positionable">
<div class="addthis_toolbox addthis_default_style ">
		<ul class="social">
			<li>
			<a href="http://x.com/eiagov/" target="_blank"><span class="ico-sticker twitter"></span></a>
				<div class="link-social">
					<div class="link-twitter"><a class="addthis_button_tweet"></a></div>
				</div>
			</li>
			<li>
				<a href="https://www.facebook.com/eiagov" target="_blank"><span class="ico-sticker facebook"></span></a>
				<div class="link-social">
					<div class="link-facebook"><a class="addthis_button_facebook_like at300b" fb:like:layout="button_count"></a></div>
				</div>
			</li>
		</ul>
	</div>
</div>