<?php $locale = 'data'; ?>
<?php $page['year'] = '2022'; ?>

<!--<p align="right"><a href="pdf/alltables2010.pdf" class="ico_pdf" alt="all 2010 tables in pdf">all tables</a>-->
<table  width="100%" class="contable">

<h2>2022 MECS Release Schedule</h2>
<table class="basic_table">
<thead>
	<th>Task name</th>
	<th>Release date</th>
	</thead>
	<tbody>
  <!-- <tr>
    <td>Flash Estimate (Table 1.5)</td>
    <td>September 2020</td>
  </tr>-->
  <tr>
    <td>Consumption, end use, and fuel-switching tables</td>
    <td>August 2025</td>
  </tr>
		 <tr>
    <td>Economic and expenditure tables</td>
    <td>September 2025</td>
  </tr>
		 <tr>
    <td>Energy-management and count tables</td>
    <td>December 2025</td>
  </tr>
  <tr>
    <td>Hand-suppressed tables</td>
    <td>March 2026</td>
  </tr>
</tbody>
</table>
<span class="condaterange"><a class="no-border expandall">+ EXPAND ALL</a></span>
<table width="100%" class="contable">
	<!--<thead id="r1">
		<tr>
			<th><a name="r1"></a>Preliminary Estimates</th>
			<th>&nbsp;</th>
    	</tr> 
	</thead>
	<tr class="white_first">
		<td>Table 1.5 By Further Classification of 'Other' Energy Sources</td>
		<td><p class="right" style="line-height:0px;"><a href="xls/Table 1_5 Preliminary_2022.xlsx" class="ico_xls" title="Table 1.5 (Preliminary) First use of energy for all purposes (fuel and nonfuel), 2022"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table 1_5 Preliminary_2022.pdf" class="ico_pdf" title=" Table 1.5 By Further Classification of "Other" Energy Sources"
>PDF</a></td>
		</tr>-->
	<thead id="r1">
		<tr>
			<th><a name="r1"></a>Consumption of Energy for All Purposes (First Use)</th>
			<th>&nbsp;</th>
    	</tr> 
	</thead>
	<tr class="white_first">
		<td>Table 1.1 By Manufacturing Industry and Region (physical units)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table1_1.xlsx" class="ico_xls" title=" Table 1.1 By By Manufacturing Industry and Region (physical units)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table1_1.pdf" class="ico_pdf" title=" Table 1.1 By Manufacturing Industry and Region (physical units)">PDF</a></td>
	</tr>
	<tr>
		<td>Table 1.2 By Manufacturing Industry and Region (trillion Btu)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table1_2.xlsx" class="ico_xls" title=" Table 1.2 By Manufacturing Industry and Region (trillion Btu)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table1_2.pdf" class="ico_pdf" title=" Table 1.2 By Manufacturing Industry and Region (trillion Btu)">PDF</a></td>
	</tr>
	<tr>
		<td>Table 1.3 By Value of Shipments & Employment Size Category & Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table1_3.xlsx" class="ico_xls" title=" Table 1.3 By Value of Shipments & Employment Size Category & Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table1_3.pdf" class="ico_pdf" title=" By Value of Shipments & Employment Size Category & Region">PDF</a></td>
		</tr>
	<tr>
		<td>Table 1.4 Number of Establishments Using Energy Consumed for All Purpose</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table1_4.xlsx" class="ico_xls" title=" Table 1.4 Number of Establishments Using Energy Consumed for All Purpose">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table1_4.pdf" class="ico_pdf" title=" Table 1.4 Number of Establishments Using Energy Consumed for All Purpose">PDF</a></td>
	</tr>
	<tr>
		<td>Table 1.5 By Further Classification of 'Other' Energy Sources</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table1_5.xlsx" class="ico_xls" title=" Table 1.5 By Further Classification of "Other" Energy Sources"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table1_5.pdf" class="ico_pdf" title=" Table 1.5 By Further Classification of "Other" Energy Sources"
>PDF</a></td>
		</tr>
	<thead id="r2">
		<tr>
			<th><a name="r2"></a>Energy Used as a Nonfuel (Feedstock)</th>
			<th>&nbsp;</th>
	</thead>
	<tr class="white_first">
		<td>Table 2.1 By Manufacturing Industry and Region (physical units)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table2_1.xlsx" class="ico_xls" title=" Table 2.1 By Manufacturing Industry and Region (physical units)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table2_1.pdf" class="ico_pdf" title=" Table 2.1 By Manufacturing Industry and Region (physical units)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 2.2 By Manufacturing Industry and Region (trillion Btu)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table2_2.xlsx" class="ico_xls" title=" Table 2.2 By Manufacturing Industry and Region (trillion Btu)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table2_2.pdf" class="ico_pdf" title=" Table 2.2 By Manufacturing Industry and Region (trillion Btu)"
>PDF</a></td>
			</tr>
	<tr>
		<td>Table 2.3 By Value of Shipments & Employment Size Category & Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table2_3.xlsx" class="ico_xls" title=" Table 2.3 By Value of Shipments & Employment Size Category & Region"
		>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table2_3.pdf" class="ico_pdf" title=" Table 2.3 Nonfuel (Feedstock) Use of Combustible Energy">PDF</a></td>
	</tr>
	<tr>
		<td>Table 2.4 Number of Establishment Using Energy Consumed as a Nonfuel</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table2_4.xlsx" class="ico_xls" title=" Table 2.4 Number of Establishment Using Energy Consumed as a Nonfuel"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table2_4.pdf" class="ico_pdf" title=" Table 2.4 Number of Establishment Using Energy Consumed as a Nonfuel">PDF</a></td>
	</tr>
	</tr>
	<thead id="r3">
		<tr>
			<th><a name="r3"></a>Energy Consumption as a Fuel</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tr class="white_first">
		<td>Table 3.1 By Manufacturing Industry and Region (physical units)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table3_1.xlsx" class="ico_xls" title=" Table 3.1 By Manufacturing Industry and Region (physical units)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table3_1.pdf" class="ico_pdf" title=" Table 3.1 By Manufacturing Industry and Region (physical units)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 3.2 By Manufacturing Industry and Region (trillion Btu)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table3_2.xlsx" class="ico_xls" title=" Table 3.2 By Manufacturing Industry and Region (trillion Btu)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table3_2.pdf" class="ico_pdf" title=" Table 3.2 By Manufacturing Industry and Region (trillion Btu)"
>PDF</a></td>
		</tr>
	<tr class="white_first">
		<td>Table 3.3 By Value of Shipments & Employment Size Category & Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table3_3.xlsx" class="ico_xls" title=" Table 3.3 By Value of Shipments & Employment Size Category & Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table3_3.pdf" class="ico_pdf" title=" Table 3.3 By Value of Shipments & Employment Size Category & Region">PDF</a></td>
	</tr>
	<tr>
		<td>Table 3.4 Number of Establishments Using Energy Consumed as a Fuel</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table3_4.xlsx" class="ico_xls" title=" Table 3.4 Number of Establishments Using Energy Consumed as a Fuel"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table3_4.pdf" class="ico_pdf" title=" Table 3.4 Number of Establishments Using Energy Consumed as a Fuel"
>PDF</a></td>
	</tr>
	</tr>
	<tr>
		<td>Table 3.5 Byproducts in Fuel Consumption By Manufacturing Industry and Region (trillion Btu) </td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table3_5.xlsx" class="ico_xls" title=" Table 3.5 Byproducts in Fuel Consumption By Manufacturing Industry and Region (trillion Btu)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table3_5.pdf" class="ico_pdf" title=" Table 3.5 Byproducts in Fuel Consumption By Manufacturing Industry and Region (trillion Btu)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 3.6 Selected Wood and Wood-Related Products in Fuel Consumption (trillion Btu) </td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table3_6.xlsx" class="ico_xls" title=" Table 3.6 Selected Wood and Wood-Related Products in Fuel Consumption (trillion Btu)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table3_6.pdf" class="ico_pdf" title=" Table 3.6 Selected Wood and Wood-Related Products in Fuel Consumption (trillion Btu)"
>PDF</a></td>
	</tr>
	<thead id="r4">
		<tr>
			<th><a name="r4"></a>Offsite-Produced Fuel Consumption </th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tr class="white_first">
		<td>Table 4.1 By Manufacturing Industry (physical units)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table4_1.xlsx" class="ico_xls" title=" Table 4.1 By Manufacturing Industry (physical units)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table4_1.pdf" class="ico_pdf" title=" Table 4.1 By Manufacturing Industry (physical units)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 4.2 By Manufacturing Industry and Region (trillion Btu)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table4_2.xlsx" class="ico_xls" title=" Table 4.2 By Manufacturing Industry and Region (trillion Btu)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table4_2.pdf" class="ico_pdf" title=" Table 4.2 By Manufacturing Industry and Region (trillion Btu)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 4.3 By Value of Shipments & Employment Size Category & Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table4_3.xlsx" class="ico_xls" title=" Table 4.3 By Value of Shipments & Employment Size Category & Region"
		>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table4_3.pdf" class="ico_pdf" title=" Table 4.3 By Value of Shipments & Employment Size Category & Region">PDF</a></td>
	</tr>
	<tr>
		<td>Table 4.4 Number of Establishments Using Offsite-Produced Fuel for Consumption</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"> <a href="xls/Table4_4.xlsx" class="ico_xls" title=" Table 4.4 Number of Establishments Using Offsite-Produced Fuel for Consumption"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table4_4.pdf" class="ico_pdf" title=" Table 4.4 Number of Establishments Using Offsite-Produced Fuel for Consumption"
>PDF</a></td>
</tr>
		<thead id="r5">
			<tr>
				<th><a name="r5"></a>Energy Consumed as a Fuel by End Use</a></th>
				<th>&nbsp;</th>
			</tr>
		</thead>
	<tr class="white_first">
		<td>Table 5.1 By Manufacturing Industry with Net Electricity (physical units)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table5_1.xlsx" class="ico_xls" title=" Table 5.1 By Manufacturing Industry with Net Electricity (physical units)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table5_1.pdf" class="ico_pdf" title=" Table 5.1 By Manufacturing Industry with Net Electricity (physical units)"
>PDF</a></td>
		</tr>

	<tr>
		<td>Table 5.2 By Manufacturing Industry with Net Electricity (trillion Btu)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table5_2.xlsx" class="ico_xls" title=" Table 5.2 By Manufacturing Industry with Net Electricity (trillion Btu)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table5_2.pdf" class="ico_pdf" title=" Table 5.2 By Manufacturing Industry with Net Electricity (trillion Btu)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 5.3 By Manufacturing Industry with Total Consumption of Electricity (physical units)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table5_3.xlsx" class="ico_xls" title=" Table 5.3 By Manufacturing Industry with Total Consumption of Electricity (physical units)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table5_3.pdf" class="ico_pdf" title=" Table 5.3 By Manufacturing Industry with Total Consumption of Electricity (physical units)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 5.4 By Manufacturing Industry with Total Consumption of Electricity (trillion Btu) </td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table5_4.xlsx" class="ico_xls" title=" Table 5.4 By Manufacturing Industry with Total Consumption of Electricity (trillion Btu)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table5_4.pdf" class="ico_pdf" title=" Table 5.4 By Manufacturing Industry with Total Consumption of Electricity (trillion Btu)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 5.5 By Region with Net Electricity (physical units)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table5_5.xlsx" class="ico_xls" title=" Table 5.5 By Region with Net Electricity (physical units)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table5_5.pdf" class="ico_pdf" title=" Table 5.5 By Region with Net Electricity (physical units)"
>PDF</a></td>
		</tr>
	<tr>
		<td>Table 5.6 By Region with Net Electricity (trillion Btu)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table5_6.xlsx" class="ico_xls" title=" Table 5.6 By Region with Net Electricity (trillion Btu)" >&nbsp;XLSX</a>&nbsp;<a href="pdf/Table5_6.pdf" class="ico_pdf" title=" Table 5.6 By Region with Net Electricity (trillion Btu)">PDF</a></td>
		</tr>
	<tr>
		<td>Table 5.7 By Region with Total Consumption of Electricity (physical units)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table5_7.xlsx" class="ico_xls" title=" Table 5.7 By Region with Total Consumption of Electricity (physical units)"
>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table5_7.pdf" class="ico_pdf" title=" Table 5.7 By Region with Total Consumption of Electricity (physical units)"
>PDF</a></td>
</tr>
		<tr>
		<td>Table 5.8 By Region with Total Consumption of Electricity (trillion Btu)</td>
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table5_8.xlsx" class="ico_xls" title=" Table 5.8 By Region with Total Consumption of Electricity (trillion Btu)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table5_8.pdf" class="ico_pdf" title=" Table 5.8 By Region with Total Consumption of Electricity (trillion Btu)">PDF</a></td>
	 </tr>
		 <thead id="r6">
			<tr>
				<th><a name="r6"></a> Ratios of Manufacturing Fuel Consumption to Economic Characteristics</th>
				<th>&nbsp;</th>
				</tr>
		</thead>
	<tr class="white_first">
		<td>Table 6.1 By Manufacturing Industry and Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table6_1.xlsx" class="ico_xls" title=" Table 6.1 By Manufacturing Industry and Region" >&nbsp;XLSX</a>&nbsp;<a href="pdf/Table6_1.pdf" class="ico_pdf" title=" Table 6.1 By Manufacturing Industry and Region">PDF</a></td>
		</tr>
	<tr>
		<td>Table 6.2 By Value of Shipments or Employment Size Category and Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table6_2.xlsx" class="ico_xls" title=" Table 6.2 By Value of Shipments or Employment Size Category and Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table6_2.pdf" class="ico_pdf" title=" Table 6.2 By Value of Shipments or Employment Size Category and Region">PDF</a></td>
		 </tr> 
	<tr>
		<td>Table 6.3 By Manufacturing Industry and Value of Shipments</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table6_3.xlsx" class="ico_xls" title=" Table 6.3 By Manufacturing Industry and Value of Shipments">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table6_3.pdf" class="ico_pdf" title=" Table 6.3 By Manufacturing Industry and Value of Shipments">PDF</a></td>
		</tr>
	<tr>
		<td>Table 6.4 By Manufacturing Industry and Employment Size</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table6_4.xlsx" class="ico_xls" title=" Table 6.4 By Manufacturing Industry and Employment Size">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table6_4.pdf" class="ico_pdf" title=" Table 6.4 By Manufacturing Industry and Employment Size">PDF</a></td>
		</tr>
		<thead id="r7">
			<tr>
				<th><a name="r7"></a>Average Prices of Purchased Energy Sources</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
	<tr class="white_first">
		<td>Table 7.1 All Collected Energy Sources By Manufacturing Industry and Region (dollars per physical units)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_1.xlsx" class="ico_xls" title=" Table 7.1 All Collected Energy Sources By Manufacturing Industry and Region (dollars per physical units)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_1.pdf" class="ico_pdf" title=" Table 7.1 All Collected Energy Sources By Manufacturing Industry and Region (dollars per physical units)">PDF</a></td>
		</tr>
   <tr>
		<td>Table 7.2 All Collected Energy Sources By Manufacturing Industry and Region (dollars per million Btu)</td>
	    <!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_2.xlsx" class="ico_xls" title=" Table 7.2 All Collected Energy Sources By Manufacturing Industry and Region (dollars per million Btu)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_2.pdf" class="ico_pdf" title=" Table 7.2 All Collected Energy Sources By Manufacturing Industry and Region (dollars per million Btu)">PDF</a></td>
		</tr> 
	<tr>
		<td>Table 7.3 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing Industry, and Region (dollars per physical unit)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_3.xlsx" class="ico_xls" title=" Table 7.3 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing Industry, and Region (dollars per physical unit)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_3.pdf" class="ico_pdf" title=" Table 7.3 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing Industry, and Region (dollars per physical unit)">PDF</a></td>
		</tr>
	<tr>
		<td>Table 7.4 Selected Energy Sources by Region and Employment or Value of Shipments Size Categories (dollars per physical unit)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_4.xlsx" class="ico_xls" title=" Table 7.4 Selected Energy Sources by Region and Employment or Value of Shipments Size Categories (dollars per physical unit)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_4.pdf" class="ico_pdf" title=" Table 7.4 Selected Energy Sources by Region and Employment or Value of Shipments Size Categories (dollars per physical unit)">PDF</a></td>
		</tr>
	<tr>
		<td>Table 7.5 Selected Energy Sources by Region and Employment or Value of Shipments Size Categories (dollars per million Btu)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_5.xlsx" class="ico_xls" title=" Table 7.5 Selected Energy Sources by Region and Employment or Value of Shipments Size Categories (dollars per million Btu)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_5.pdf" class="ico_pdf" title=" Table 7.5 Selected Energy Sources by Region and Employment or Value of Shipments Size Categories (dollars per million Btu)">PDF</a></td>
 </tr>
		<thead id="r8">
			<tr>
				<th><a name="r8"></a>Quantity of Purchased Energy</th>
				<th>&nbsp;</th>
		</thead>
	<tr class="white_first">
	
		<td>Table 7.6 Selected Energy Sources By Manufacturing Industry and Region (physical units) </td>
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_6.xlsx" class="ico_xls" title=" Table 7.6 Selected Energy Sources By Manufacturing Industry and Region (physical units)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_6.pdf" class="ico_pdf" title=" Table 7.6 Selected Energy Sources By Manufacturing Industry and Region (physical units)">PDF</a></td>
 </tr>
	<tr>
		<td>Table 7.7 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_7.xlsx" class="ico_xls" title=" Table 7.7 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_7.pdf" class="ico_pdf" title=" Table 7.7 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region">PDF</a></td>
		 </tr>

<tr>
	<td>Table 7.8 Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, and Manufacturing Industry</td>
	<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
	 <td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_8.xlsx" class="ico_xls" title=" Table 7.8 Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, and Manufacturing Industry">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_8.pdf" class="ico_pdf" title=" Table 7.8 Number of Establishments by Purchased Electricity, Natural Gas, Steam by type of Supplier, and Manufacturing Industry">PDF</a></td>
 </tr>
		<thead id="r9">
			<tr>
				<th><a name="r9"></a>Expenditures for Purchased Energy (Millions of Dollars)</th>
				<th>&nbsp;</span</th>
			</tr> 
		</thead>
	<tr class="white_first">
		<td>Table 7.9 Selected Energy Sources By Manufacturing Industry and Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_9.xlsx" class="ico_xls" title=" Table 7.9 Selected Energy Sources By Manufacturing Industry and Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_9.pdf" class="ico_pdf" title=" Table 7.9 Selected Energy Sources By Manufacturing Industry and Region">PDF</a></td>
 </tr>
	<tr>
		<td>Table 7.10 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table7_10.xlsx" class="ico_xls" title=" Table 7.10 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table7_10.pdf" class="ico_pdf" title=" Table 7.10 Purchased Electricity, Natural Gas, Steam by type of Supplier, Manufacturing, Industry, and Region">PDF</a></td>
		</tr>
		<thead id="r10">
			<tr>
				<th><a name="r10"></a>Energy Management Activities and Energy-Savings Technologies</th> 
				<th>&nbsp;</th>
			</tr>
			</thead>
	<tr class="white_first">
		<td>Table 8.1 Number of Establishments Participating in Energy Management Activities</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" s style="line-height:0px; font-size: 12px"><a href="xls/Table8_1.xlsx" class="ico_xls" title=" Table 8.1 Number of Establishments Participating in Energy Management Activities">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_1.pdf" class="ico_pdf" title=" Table 8.1 Number of Establishments Participating in Energy Management Activities">PDF</a></td>
		</tr> 
	<tr>
		<td>Table 8.2 Number of Establishments with General Technologies</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_2.xlsx" class="ico_xls" title=" Table 8.2 Number of Establishments with General Technologies">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_2.pdf" class="ico_pdf" title=" Table 8.2 Number of Establishments with General Technologies">PDF</a></td>
		</tr> 
	<tr>
		<td>Table 8.3 Number of Establishments with Cogeneration Technologies</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_3.xlsx" class="ico_xls" title=" Table 8.3 Number of Establishments with Cogeneration Technologies">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_3.pdf" class="ico_pdf" title=" Table 8.3 Number of Establishments with Cogeneration Technologies">PDF</a></td>
		</tr>
	<tr>
		<td>Table 8.4 Number of Establishments Participating in Specific Energy-Management Activities</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_4.xlsx" class="ico_xls" title=" Table 8.4 Number of Establishments Participating in Specific Energy-Management Activities">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_4.pdf" class="ico_pdf" title=" Table 8.4 Number of Establishments Participating in Specific Energy-Management Activities">PDF</a></td>
		 </tr>
    <tr>
		<td>Table 8.5 Number of Establishments by Management Decision-Making Process</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_5.xlsx" class="ico_xls" title=" Table 8.5 Number of Establishments by Management Decision-Making Process">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_5.pdf" class="ico_pdf" title=" Table 8.5 Number of Establishments by Management Decision-Making Process">PDF</a></td>
		</tr>
    <tr>
		<td>Table 8.6 Number of Establishments by Participation in Programs Dedicated to Improving Energy Consumption</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_6.xlsx" class="ico_xls" title=" Table 8.6 Number of Establishments by Participation in Programs Dedicated to Improving Energy Consumption">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_6.pdf" class="ico_pdf" title=" Table 8.6 Number of Establishments by Participation in Programs Dedicated to Improving Energy Consumption">PDF</a></td>
		</tr>
    <tr>
		<td>Table 8.7 Number of Establishments by Simple Payback Period</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_7.xlsx" class="ico_xls" title=" Table 8.7 Number of Establishments by Simple Payback Period">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_7.pdf" class="ico_pdf" title=" Table 8.7 Number of Establishments by Simple Payback Period">PDF</a></td>
		</tr>
      <tr>
		<td>Table 8.8 Number of Establishments by Participation in Setting Goals for Improving Energy Consumption</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_8.xlsx" class="ico_xls" title=" Table 8.8 Number of Establishments by Participation in Setting Goals for Improving Energy Consumption">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_8.pdf" class="ico_pdf" title=" Table 8.8 Number of Establishments by Participation in Setting Goals for Improving Energy Consumption">PDF</a></td>
		</tr>
    <tr>
		<td>Table 8.9 Number of Establishments by Designation of Representative(s) Responsible for Energy Management</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_9.xlsx" class="ico_xls" title=" Table 8.9 Number of Establishments by Designation of Representative(s) Responsible for Energy Management">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_9.pdf" class="ico_pdf" title=" Table 8.9 Number of Establishments by Designation of Representative(s) Responsible for Energy Management">PDF</a></td>
	</tr>
    <tr>
		<td>Table 8.10 Number of Establishments by Submetering Capability</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_10.xlsx" class="ico_xls" title=" Table 8.10 Number of Establishments by Submetering Capability">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_10.pdf" class="ico_pdf" title=" Table 8.10 Number of Establishments by Submetering Capability">PDF</a></td>
		</tr>
    <tr>
		<td>Table 8.11 Number of Establishments by Participation of Audits to Identify Potential Energy Saving Opportunities</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_11.xlsx" class="ico_xls" title="Table 8.11 Number of Establishments by Participation of Audits to Identify Potential Energy Saving Opportunities">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_11.pdf" class="ico_pdf" title="Table 8.11 Number of Establishments by Participation of Audits to Identify Potential Energy Saving Opportunities">PDF</a></td>
		</tr>
	<tr>
		<td>Table 8.12 Number of Establishments by Purchase of Electricity Produced from Renewable Sources</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table8_12.xlsx" class="ico_xls" title="Table 8.12 Number of Establishments by Purchase of Electricity Produced from Renewable Sources">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table8_12.pdf" class="ico_pdf" title="Table 8.12 Number of Establishments by Purchase of Electricity Produced from Renewable Sources">PDF</a></td>
		</tr>
		 <thead id="r11">
			<tr>
				<th> <a name="r11"></a>Floorspace and Building Counts</th>
				<th>&nbsp;</th>
		 </tr> 
		</thead>
	<tr class="white_first">
		<td>Table 9.1 Enclosed Floorspace and Number of Establishment Buildings</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table9_1.xlsx" class="ico_xls" title=" Table 9.1 Enclosed Floorspace and Number of Establishment Buildings">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table9_1.pdf" class="ico_pdf" title=" Table 9.1 Enclosed Floorspace and Number of Establishment Buildings">PDF</a></td>
		</tr> 
		<thead id="r12">
			<tr>
				<th><a name="r12"></a>Fuel Switching</a></th>
				<th>&nbsp;</th>
			</tr>
		</thead>
	<tr class="white_first">
		<td>Table 10.1 Nonswitchable Minimum Requirements &amp; Maximum Consumption Potential (establishment counts)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_1.xlsx" class="ico_xls" title="Table 10.1 Nonswitchable Minimum Requirements & Maximum Consumption Potential (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_1.pdf" class="ico_pdf" title=" Table 10.1 Nonswitchable Minimum Requirements & Maximum Consumption Potential (establishment counts)">PDF</a></td>
	</tr>
	<tr>
		<td>Table 10.2 Capability to Switch from Natural Gas to Alternative Energy (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_2.xlsx" class="ico_xls" title="Table 10.2 Capability to Switch from Natural Gas to Alternative Energy (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_2.pdf" class="ico_pdf" title=" Table 10.2 Capability to Switch from Natural Gas to Alternative Energy (quantities)">PDF</a></span></td>
		</tr>
	<tr>
		<td>Table 10.3 Capability to Switch from Natural Gas to Alternative Energy Sources (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_3.xlsx" class="ico_xls" title=" Table 10.3 Capability to Switch from Natural Gas to Alternative Energy Sources (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_3.pdf" class="ico_pdf" title=" Table 10.3 Capability to Switch from Natural Gas to Alternative Energy Sources (establishment counts)">PDF</a></span></td>
	</tr>
	<tr>
		<td>Table 10.4 Capability to Switch Residual Fuel Oil to Alternative Energy Sources (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_4.xlsx" class="ico_xls" title="Table 10.4 Capability to Switch Residual Fuel Oil to Alternative Energy Sources (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_4.pdf" class="ico_pdf" title=" Table 10.4 Capability to Switch Residual Fuel Oil to Alternative Energy Sources (quantities)">PDF</a></span></td>
		</tr>
	<tr>
		<td>Table 10.5 Capability to Switch from Residual Fuel Oil to Alternative Energy Sources (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px;" ><a href="xls/Table10_5.xlsx" class="ico_xls" title=" Table 10.5 Capability to Switch from Residual Fuel Oil to Alternative Energy Sources (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_5.pdf" class="ico_pdf" title=" Table 10.5 Capability to Switch from Residual Fuel Oil to Alternative Energy Sources (establishment counts)">PDF</a></span></td>
	</tr> 
	<tr>
		<td>Table 10.6 Capability to Switch from Electricity to Alternative Energy Sources (quantities)</td>
		<!--<td><span class="right" style="line-height:0px; font-size: 12px">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_6.xlsx" class="ico_xls" title="Table 10.6 Capability to Switch from Electricity to Alternative Energy Sources (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_6.pdf" class="ico_pdf" title=" Table 10.6 Capability to Switch from Electricity to Alternative Energy Sources (quantities)">PDF</a></span></td>
		</tr>
	<tr>
		<td>Table 10.7 Capability to Switch from Electricity to Alternative Energy Sources (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_7.xlsx" class="ico_xls" title=" Table 10.7 Capability to Switch from Electricity to Alternative Energy Sources (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_7.pdf" class="ico_pdf" title=" Table 10.7 Capability to Switch from Electricity to Alternative Energy Sources (establishment counts)">PDF</a></span></td>
	</tr>
	<tr>
		<td>Table 10.8 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_8.xlsx" class="ico_xls" title="Table 10.8 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_8.pdf" class="ico_pdf" title=" Table 10.8 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (quantities)">PDF</a></span></td>
	</tr>
	<tr>
	<td>Table 10.9 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_9.xlsx" class="ico_xls" title=" Table 10.9 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_9.pdf" class="ico_pdf" title=" Table 10.9 Capability to Switch from Distillate Fuel Oil to Alternative Energy Sources (establishment counts)">PDF</a></span></td>
	</tr>
	<tr>
		<td>Table 10.10 Capability to Switch from Coal to Alternative Energy Sources (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_10.xlsx" class="ico_xls" title="Table 10.10 Capability to Switch from Coal to Alternative Energy Sources (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_10.pdf" class="ico_pdf" title=" Table 10.10 Capability to Switch from Coal to Alternative Energy Sources (quantities)">PDF</a></span></td>
		</tr>
    <tr>
		<td>Table 10.11 Capability to Switch from Coal to Alternative Energy Sources (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_11.xlsx" class="ico_xls" title=" Table 10.11 Capability to Switch from Coal to Alternative Energy Sources (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_11.pdf" class="ico_pdf" title=" Table 10.11 Capability to Switch from Coal to Alternative Energy Sources (establishment counts)">PDF</a></span></td>
	</tr>
	<tr>
		<td>Table 10.12 Capability to Switch from HGL to Alternative Energy Sources (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_12.xlsx" class="ico_xls" title=" Table 10.12 Capability to Switch from HGL to Alternative Energy Sources (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_12.pdf" class="ico_pdf" title=" Table 10.12 Capability to Switch from HGL to Alternative Energy Sources (quantities)">PDF</a></span></td>
	</tr>
	<tr>
		<td>Table 10.13 Capability to Switch from HGL to Alternative Energy Sources (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_13.xlsx" class="ico_xls" title=" Table 10.13 Capability to Switch from HGL to Alternative Energy Sources (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_13.pdf" class="ico_pdf" title=" Table 10.13 Capability to Switch from HGL to Alternative Energy Sources (establishment counts)">PDF</a></span></td>
	</tr> 
	<tr>
		<td>Table 10.14 Levels of Price Difference that Would Cause Establishments to Switch from Electricity (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_14.xlsx" class="ico_xls" title=" Table 10.14 Levels of Price Difference that Would Cause Establishments to Switch from Electricity (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_14.pdf" class="ico_pdf" title=" Table 10.14 Levels of Price Difference that Would Cause Establishments to Switch from Electricity (establishment counts)">PDF</a></span></td>
	</tr>
	<tr>
		<td>Table 10.15 Levels of Price Difference that Would Cause Establishments to Switch from Natural Gas (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_15.xlsx" class="ico_xls" title=" Table 10.15 Levels of Price Difference that Would Cause Establishments to Switch from Natural Gas (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_15.pdf" class="ico_pdf" title=" Table 10.15 Levels of Price Difference that Would Cause Establishments to Switch from Natural Gas (establishment counts)">PDF</a></span></td>
		</tr>
	<tr>
		<td>Table 10.16 Levels of Price Difference that Would Cause Establishments to Switch from Coal (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_16.xlsx" class="ico_xls" title=" Table 10.16 Levels of Price Difference that Would Cause Establishments to Switch from Coal (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_16.pdf" class="ico_pdf" title=" Table 10.16 Levels of Price Difference that Would Cause Establishments to Switch from Coal (establishment counts)">PDF</a></span></td>
		</tr>
	<tr>
		<td>Table 10.17 Levels of Price Difference that Would Cause Establishments to Switch from HGL (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_17.xlsx" class="ico_xls" title=" Table 10.17 Levels of Price Difference that Would Cause Establishments to Switch from HGL (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_17.pdf" class="ico_pdf" title=" Table 10.17 Levels of Price Difference that Would Cause Establishments to Switch from HGL (establishment ounts)">PDF</a></span></td>
		</tr>
	<tr>
		<td>Table 10.18 Levels of Price Difference that Would Cause Establishments to Switch from Distillate Fuel Oil (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_18.xlsx" class="ico_xls" title=" Table 10.18 Levels of Price Difference that Would Cause Establishments to Switch from Distillate Fuel Oil (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_18.pdf" class="ico_pdf" title=" Table 10.18 Levels of Price Difference that Would Cause Establishments to Switch from Distillate Fuel Oil (establishment counts)">PDF</a></span></td>
        </tr>
	<tr>
		<td>Table 10.19 Levels of Price Difference that Would Cause Establishments to Switch from Residual Fuel Oil (establishment counts)</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table10_19.xlsx" class="ico_xls" title=" Table 10.19 Levels of Price Difference that Would Cause Establishments to Switch from Residual Fuel Oil (establishment counts)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_19.pdf" class="ico_pdf" title="Table 10.19 Levels of Price Difference that Would Cause Establishments to Switch from Residual Fuel Oil (establishment counts)">PDF</a></span></td>
	</tr>
		<tr>
		<td>Table 10.20 Reasons that Made Electricity Unswitchable (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right"><a href="xls/Table10_20.xlsx" class="ico_xls" title=" Table 10.20 Reasons that Made Electricity Unswitchable (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_20.pdf" class="ico_pdf" title=" Table 10.20 Reasons that Made Electricity Unswitchable (quantities)">PDF</a></span></td>
			</tr>
	<tr>
		<td>Table 10.21 Reasons That Made Natural Gas Unswitchable (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right"><a href="xls/Table10_21.xlsx" class="ico_xls" title=" Table 10.21 Reasons That Made Natural Gas Unswitchable (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_21.pdf" class="ico_pdf" title=" Table 10.21 Reasons That Made Natural Gas Unswitchable (quantities)">PDF</a></span></td>
		</tr>
	<tr>
		<td>Table 10.22 Reasons That Made Coal Unswitchable (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right"><a href="xls/Table10_22.xlsx" class="ico_xls" title=" Table 10.22 Reasons That Made Coal Unswitchable (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_22.pdf" class="ico_pdf" title=" Table 10.22 Reasons That Made Coal Unswitchable (quantities)">PDF</a></span></td>
			</tr> 
	<tr>
		<td>Table 10.23 Reasons That Made HGL Unswitchable (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right"><a href="xls/Table10_23.xlsx" class="ico_xls" title=" Table 10.23 Reasons That Made HGL Unswitchable (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_23.pdf" class="ico_pdf" title=" Table 10.23 Reasons That Made HGL Unswitchable (quantities)">PDF</a></span></td>
		</tr> 
	<tr> 
		<td>Table 10.24 Reasons That Made Distillate Fuel Oil Unswitchable (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right"><a href="xls/Table10_24.xlsx" class="ico_xls" title=" Table 10.24 Reasons That Made Distillate Fuel Oil Unswitchable (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_24.pdf" class="ico_pdf" title=" Table 10.24 Reasons That Made Distillate Fuel Oil Unswitchable (quantities)">PDF</a></span></td>
	</tr>
	<tr>
		<td>Table 10.25 Reasons That Made Residual Fuel Oil Unswitchable (quantities)</td>
		<!--<td><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><span class="right"><a href="xls/Table10_25.xlsx" class="ico_xls" title=" Table 10.25 Reasons That Made Residual Fuel Oil Unswitchable (quantities)">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table10_25.pdf" class="ico_pdf" title=" Table 10.25 Reasons That Made Residual Fuel Oil Unswitchable (quantities)">PDF</a></span></td>
			</tr>
	<thead id="r13">
		<tr>
			<th><a name="r13"></a>Electricity: Components of Net Demand</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tr class="white_first">
		<td>Table 11.1 By Manufacturing Industry and Region</td>
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table11_1.xlsx" class="ico_xls" title=" Table 11.1 By Manufacturing Industry and Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table11_1.pdf" class="ico_pdf" title=" Table 11.1 By Manufacturing Industry and Region">PDF</a></td>
	</tr>
	<tr>
		<td>Table 11.2 By Value of Shipments & Employment Size Category & Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table11_2.xlsx" class="ico_xls" title=" Table 11.2 By Value of Shipments & Employment Size Category & Region"
		>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table11_2.pdf" class="ico_pdf" title=" Table 11.2 By Value of Shipments & Employment Size Category & Region">PDF</a></td>
	</tr>
	<thead id="r14">
		<tr>
			<th><a name="r14"></a>Electricity: Components of Onsite Generation</th>
			<th>&nbsp;</th>
			</tr>
	</thead>
	<tr class="white_first">
		<td>Table 11.3. By Manufacturing Industry and Region</td>
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table11_3.xlsx" class="ico_xls" title="Table 11.3. By Manufacturing Industry and Region"
		>&nbsp;XLSX</a>&nbsp;<a href="pdf/Table11_3.pdf" class="ico_pdf" title="Table 11.3. By Manufacturing Industry and Region">PDF</a></td>
	</tr>
	<tr>
		<td>Table 11.4 By Value of Shipments & Employment Size Category & Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table11_4.xlsx" class="ico_xls" title=" Table 11.4 By Value of Shipments & Employment Size Category & Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table11_4.pdf" class="ico_pdf" title=" Table 11.4 By Value of Shipments & Employment Size Category & Region">PDF</a></td>
	</tr>
	 <thead id="r15">
		<tr>
			<th><a name="r15"></a>Electricity: Sales to Utility and Nonutility Purchasers</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
<tr class="white_first">
	<td>Table 11.5  By Manufacturing Industry and Region</td>
	<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
	<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table11_5.xlsx" class="ico_xls" title="Table 11.5  By Manufacturing Industry and Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table11_5.pdf" class="ico_pdf" title=" Table 11.5 Electricity Sales to Utility and Nonutility Purchasers By Manufacturing Industry and Regiony">PDF</a></td>
	</tr>
	<tr>
		<td>Table 11.6 By Value of Shipments & Employment Size Category & Region</td>
		<!--<td style="color: #adadad"><span class="right" style="line-height:0px;">&nbsp;XLS&nbsp;PDF</span></td>-->
		<td><p class="right" style="line-height:0px; font-size: 12px"><a href="xls/Table11_6.xlsx" class="ico_xls" title=" Table 11.6 By Value of Shipments & Employment Size Category & Region">&nbsp;XLSX</a>&nbsp;<a href="pdf/Table11_6.pdf" class="ico_pdf" title=" Table 11.6 By Value of Shipments & Employment Size Category & Region">PDF</a></td>
	</tr>
</table>
