<?php $locale = 'data'; ?>
<?php $page['year'] = '2022'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Methodology &amp; Forms</title>
<?php  if(!isset($no_titling)) include "global/includes/titling.inc"; ?></head>

<body>
<h4>&nbsp;</h4>
  <p><strong>2022 MECS Methodology</strong></p>
 <table class="basic_table">
  <tr>
   <td height="87%" valign="top" style="border-bottom-color:#FFF">
    <p>The 2022 MECS is EIA's eleventh survey of the manufacturing sector and covers the 50 States and the District of Columbia. Previous surveys were conducted every three years starting in 1985, and every four years since 1994. Subsequent MECS are planned for every three to four years. For more details on how the scope of the MECS survey has changed over time, see <a href="/consumption/manufacturing/xls/MECS%20Attributes.xlsx" class="ico_xls">MECS attributes</a>. The data collection for the 2026 MECS starts in 2027.</p>
    <p>The basic unit of data collection for MECS is the manufacturing establishment. The 2022 MECS sample size of about 15,000 establishments was drawn from a nationally representative sample frame representing 97-98% of the manufacturing payroll. This sample allows EIA to report separate estimates of energy use for 21 three-digit industry subsectors, and 58 industry groups and industries according to the North American Industry Classification System (NAICS).</p>
    <p>The 2022 MECS methodology was identical to the methodology used for the 2018 MECS. Until we can update the 2022 MECS methodology webpage, please use the  <a href="/consumption/manufacturing/data/2018/index.php?view=methodology">2018 MECS methodology</a> as a reference.</p>
    </td>
  </tr>
  <tr>
  <td><br /><br />
  <strong>2018 MECS Survey Forms</strong>
  <table width="100%" align=center cellpadding="2">
          <TR>
          <TD vAlign=top width="78"><A class="ico_pdf" href="/survey/form/eia_846/form_a.pdf">EIA-846A</A> 
                  <SPAN class="dat">(3mb)</SPAN>
                  </TD>
                <TD style="text-align:left">This form encompasses all of the establishments in the Manufacturing Energy   Consumption Survey (MECS) with the exception of the Petroleum Refining Industry   (NAICS 324110).&nbsp; The U.S. Energy Information Administration (EIA)&nbsp;does not want   to duplicate data it has already collected for this industry.&nbsp; Form EIA-846A   collects information on fuel and nonfuel (except NAICS 324110) energy   consumption, energy expenditures, storage capacity (if applicable), on-site   generation, energy end uses, fuel switching capabilities, general energy-saving   technologies, energy management activities, square footage, and number of   buildings in the establishment.</p>
                  </TD>
              <TR >
                <TD vAlign=top width="78"><A class="ico_pdf" href="/survey/form/eia_846/form_b.pdf">EIA-846B</A> 
                  <SPAN class="dat">(2mb)</SPAN></TD>
                <TD style="text-align:left">This is the shortest of the two MECS forms because the U.S. Energy Information   Administration (EIA) does not want to duplicate data that it has already   collected.&nbsp; Only those establishments in the Petroleum Refining Industry   (324110) complete the EIA-846B.</TD></TR>
</table>
</td></tr>
</table> 

</body>
</html>