<form class="eia-select">
	<div class="fieldset">Previous Years</div>
	<div>
		<ul class="select">
			<li>
				<input class="select__close" type="radio" name="archive" id="archive--close" value="" />
				<span class="select__label select__label--placeholder">Select Year</span>
			</li>
			<li class="select__items">
				<input class="select__expand" type="radio" name="archive" id="archive--opener" />
				<label class="select__close--label" for="archive--close"></label>
				<ul class="select__options">
					<li class="select__option">
						<label class="select__label"><a href="../2014/" id="2014">2014</a></label>
					</li>
					<li class="select__option">
						<label class="select__label"><a href="../2010/" id="2010">2010</a></label>
					</li>
					<li class="select__option">
						<label class="select__label"><a href="../2006/" id="2006">2006</a></label>
					</li>
					<li class="select__option">
						<label class="select__label"><a href="../2002/" id="2002">2002</a></label>
					</li>
					<li class="select__option">
						<label class="select__label"><a href="../1998/" id="1998">1998</a></label>
					</li>
					<li class="select__option">
						<label class="select__label"><a href="../1994/" id="1994">1994</a></label>
					</li>
					<li class="select__option">
						<label class="select__label"><a href="../1991/" id="1991">1991</a></label>
					</li>
					<li class="select__option">
						<label class="select__label"><a href="../archive/" id="Archive">Archive</a></label>
					</li>
				</ul>
				<label class="select__expand--label" for="archive--opener"></label>
			</li>
		</ul>
	</div>
</form>