<div class="primary">
    <p>Find statistics on coal production, consumption, exports, imports, stocks, mining, and prices.</p> <span class="expand-collapse-container"> <span class="ico expand"><span>Expand all</span></span> <span class="ico collapse"><span>Collapse all</span></span> </span>
    <div class="accordion">
        <h3 id="summary">Summary </h3>
        <div class="accordion-content">
            <ul>
                <li class="head">Coal overview</li>
                <li>Monthly</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from: </span> <a href="/totalenergy/data/monthly/">Monthly Energy Review</a> <span class="pipe">|</span> <span class="source">Interactive data from:</span> <a href="/totalenergy/data/browser/" title="Interactive data from">Total Energy Browser</a></li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec6_3.pdf" title="Coal overview monthly"><span class="ico pdf"><span>PDF</span></span></a> <a href="/totalenergy/data/browser/csv.php?tbl=T06.01" title="Coal overview monthly"><span class="ico csv"><span>CSV</span></span></a> <a href="/totalenergy/data/browser/xls.php?tbl=T06.01&amp;freq=m" title="Coal overview monthly"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a title="View Coal overview monthly in Total Energy Browser" href="/totalenergy/data/browser/index.php?tbl=T06.01#/?f=M&start=200001"><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li><a href="/totalenergy/data/annual/showtext.pdf?t=ptb0701">Annual</a></li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('totalenergy/data/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/totalenergy/data/annual/">Annual Energy Review, 1949 through 2011</a> <span class="alert">(no longer updated)</span></li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/annual/pdf/sec7_5.pdf" title="Coal overview annual"><span class="ico pdf"><span>PDF</span></span></a> <a href="/totalenergy/data/annual/xls/stb0701.xls" title="Coal overview annual"><span class="ico xls"><span>XLS</span></span></a></li>
            </ul>
        </div>
        <h3 id="prices">Prices </h3>
        <div class="accordion-content">
            <ul>
                <li><a href="/coal/markets/">Spot prices</a> (regional)</li>
                <li><span class="release-date">Released:</span> <span class="date">Weekly (on Mondays)</span> <span class="source">from</span> <a href="/coal/markets/">Coal Market Report</a></li>
            </ul>
            <ul>
                <li class="head">Average sales price</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/annual/">Annual Coal Report</a> <span class="pipe">|</span> <span class="source">Interactive data from:</span> <a href="/beta/coal/data/browser/" title="Average sales price Interactive data from">Coal Data Browser</a></li>
                <li class="list-spacer"></li>
                <li>By state and mine type</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table28.pdf" title="Average sales price By state and mine type"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table28.xlsx" title="Average sales price By state and mine type"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Open market and captive sales price by state</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table33.pdf" title="Average sales price Open market and captive sales price by state"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table33.xlsx" title="Average sales price Open market and captive sales price by state"><span class="ico xls"><span>XLSX</span></span></a><span class="pipe-alt">|</span><a href="/beta/coal/data/browser/#/topic/28?agg=0,2,1&amp;geo=vvvvvvvvvvvvo&amp;freq=A&amp;start=2001&amp;ctype=map&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Average sales price Open market and captive sales price by state"><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By state and underground mining method</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table29.pdf" title="Average sales price By state and underground mining method"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table29.xlsx" title="Average sales price By state and underground mining method"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By state and county, with number of mines</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table30.pdf" title="Average sales price By state and county, with number of mines"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table30.xlsx" title="Average sales price By state and county, with number of mines"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By state and coal rank</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table31.pdf" title="Average sales price By state and coal rank"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table31.xlsx" title="Average sales price By state and coal rank"><span class="ico xls"><span>XLSX</span></span></a><span class="pipe-alt">|</span><a href="/beta/coal/data/browser/#/topic/29?agg=1,0&amp;geo=vvvvvvvvvvvvo&amp;freq=A&amp;start=2001&amp;ctype=map&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Average sales price By state and coal rank"><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By mine production range and mine type</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table32.pdf" title="Average sales price By mine production range and mine type"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table32.xlsx" title="Average sales price By mine production range and mine type"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By coal rank</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('totalenergy/data/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/totalenergy/data/annual/">Annual Energy Review, 1949 through 2011</a> <span class="alert">(no longer updated)</span> </li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/annual/pdf/sec7_21.pdf" title="Average sales price By coal rank"><span class="ico pdf"><span>PDF</span></span></a> <a href="/totalenergy/data/annual/xls/stb0709.xls" title="Average sales price By coal rank"><span class="ico xls"><span>XLS</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Average delivered prices to end use sector by Census division and state</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/annual/">Annual Coal Report</a> <span class="pipe">|</span> <span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table34.pdf"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table34.xlsx"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Price of coal shipments to the electric power sector, by Census division, and state</li>
                <li><span class="formats">Available formats:</span> <a href="/beta/coal/data/browser/#/topic/45?agg=1,0&amp;geo=vvvvvvvvvvvvo&amp;freq=A&amp;start=2008&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Price of coal shipments to the electric power sector, by Census division, and state"><span class="ico interactive"><span>Interactive</span></span></a></li>
            </ul>
        </div>
        <h3 id="reserves">Reserves </h3>
        <div class="accordion-content">
            <ul>
                <li><a href="/coal/reserves/">Demonstrated Reserve Base</a></li>
                <li><span class="release-date">Release Date:</span> <span class="date">October 4, 2021 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/reserves/">U.S. Coal Reserves</a></li>
            </ul>
            <ul>
                <li class="head">Recoverable reserves</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/annual/">Annual Coal Report</a> <span class="pipe">|</span> <span class="source">Interactive data from:</span> <a href="/coal/data/browser/" title="Recoverable reserves Interactive data from">Coal Data Browser</a></li>
                <li class="list-spacer"></li>
                <li>At producing mines, estimated recoverable, and Demonstrated Reserve Base; by mine type</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table15.pdf" title="Recoverable reserves At producing mines, estimated recoverable, and Demonstrated Reserve Base; by mine type"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table15.xlsx" title="Recoverable reserves At producing mines, estimated recoverable, and Demonstrated Reserve Base; by mine type"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>At producing underground coal mines by state and mining method</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table16.pdf" title="Recoverable reserves At producing underground coal mines by state and mining method"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table14.xlsx" title="Recoverable reserves At producing underground coal mines by state and mining method"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>At producing mines by mine production range and mine type</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table17.pdf" title="Recoverable reserves At producing mines by mine production range and mine type"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table17.xlsx" title="Recoverable reserves At producing mines by mine production range and mine type"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>At producing mines by state</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table14.pdf" title="Recoverable reserves At producing mines by state"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table14.xlsx" title="Recoverable reserves At producing mines by state"><span class="ico xls"><span>XLSX</span></span></a><span class="pipe-alt">|</span> <a title="View Recoverable reserves At producing mines by state in Total Energy Browser" href="/beta/coal/data/browser/#/topic/31?agg=1,0&amp;geo=vvvvvvvvvvvvo&amp;freq=A&amp;start=2008&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin="><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
                <li>
                    <ul>
                        <li><a href="/international/data/world/coal-and-coke/coal-reserves">International coal reserves</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <h3 id="consumption">Consumption </h3>
        <div class="accordion-content">
            <ul>
                <li class="head">Monthly</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/totalenergy/data/monthly/">Monthly Energy Review</a></li>
                <li><span class="source">Interactive data from:</span> <a href="/coal/data/browser/" title="Consumption Monthly Interactive data from">Coal Data Browser</a></li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec6_4.pdf" title="Consumption Monthly"><span class="ico pdf"><span>PDF</span></span></a> <a href="/totalenergy/data/browser/csv.php?tbl=T06.02" title="Consumption Monthly"><span class="ico csv"><span>CSV</span></span></a> <a href="/totalenergy/data/browser/xls.php?tbl=T06.02&amp;freq=m" title="Consumption Monthly"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span> <a href="/totalenergy/data/browser/index.php?tbl=T06.02#/?f=M&start=200001" title="Consumption Monthly"><span class="ico interactive"><span>Interactive</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Quarterly</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/production/quarterly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/production/quarterly/">Quarterly Coal Report</a></li>
                <li class="list-spacer"></li>
                <li>By sector</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t32p01p1.pdf" title="Consumption Quarterly By sector"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t32p01p1.xlsx" title="Consumption Quarterly By sector"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>At manufacturing plants by North American Industry Classification System (NAICS) code</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t35p01p1.pdf" title="Consumption Quarterly At manufacturing plants by North American Industry Classification System (NAICS) code"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t35p01p1.xlsx" title="Consumption Quarterly At manufacturing plants by North American Industry Classification System (NAICS) code"><span class="ico xls"><span>XLSX</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Annual</li>
                <li><span class="source">Interactive data from:</span> <a href="/coal/data/browser/" title="Consumption Annual Interactive data from">Coal Data Browser</a></li>
                <li class="list-spacer"></li>
                <li>By sector (latest year), Census division and state</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/annual/">Annual Coal Report</a> <span class="pipe">|</span> <span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table26.pdf" title="Consumption Annual By sector (latest year), Census division and state"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table26.xlsx" title="Consumption Annual By sector (latest year), Census division and state"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By sector (1949-2011)</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('totalenergy/data/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/totalenergy/data/annual/">Annual Energy Review, 1949 through 2011</a> <span class="alert">(no longer updated)</span></li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/annual/pdf/sec7_9.pdf" title="Consumption Annual By sector (1949-2011)"><span class="ico pdf"><span>PDF</span></span></a> <a href="/totalenergy/data/annual/xls/stb0703.xls" title="Consumption Annual By sector (1949-2011)"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span> <a href="/beta/MER/index.pdf?tbl=T06.02#/?f=A&amp;start=1949&amp;end=2014&amp;charted=1-5-12-13-14" title="Consumption Annual By sector (1949-2011)"><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By electric power sector, Census division, and state</li>
                <li><span class="formats">Available formats:</span> <a href="/beta/coal/data/browser/#/topic/20?agg=1,0&amp;geo=vvvvvvvvvvvvo&amp;sec=g&amp;freq=A&amp;start=2008&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Consumption Annual By electric power sector, Census division, and state"><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By commercial, coke plants, and other industrial, Census division, and state</li>
                <li><span class="formats">Available formats:</span> <a href="/beta/coal/data/browser/#/topic/20?agg=1,0&amp;geo=vvvvvvvvvvvvo&amp;sec=0s&amp;freq=A&amp;start=2008&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Consumption Annual By commercial, coke plants, and other industrial, Census division, and state"><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
                <li>
                    <ul>
                        <li><a href="/international/data/world/coal-and-coke/coal-and-coke-consumption">Coal and coke consumption</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <h3 id="production">Production </h3>
        <div class="accordion-content">
            <ul class="highlight">
                <li><strong>Detailed data from the <a href="/survey/form/eia_7a/form.pdf">EIA-7A<span class="ico pdf"><span>PDF</span></span></a> and the U.S. Mine Safety and Health Administration</strong> (back to 1983)</li>
                <li>Production, company and mine information, operation type, union status, labor hours, and number of employees</li>
                <li>
                    <div class="form-container do-not-print">
                        <fieldset>
                            <legend>Previous date</legend>
                            <div class="dropdown-container no-js">
                                <div class="dropdown-button"> <span class="text">Select Year</span> <span class="ico d-arrow"><span>dropdown arrow</span></span> </div>
                                <div class="dropdown-menu">
                                    <ul>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2024.xlsx">2024</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2023.xlsx">2023</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2022.xls">2022</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2021.xls">2021</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2020.xls">2020</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2019.xls">2019</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2018.xls">2018</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2017.xls">2017</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2016.xls">2016</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2015.xls">2015</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2014.xls">2014</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2013.xls">2013</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2012.xls">2012</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2011.xls">2011</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2010.xls">2010</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2009.xls">2009</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2008.xls">2008</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2007.xls">2007</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2006.xls">2006</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2005.xls">2005</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2004.xls">2004</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2003.xls">2003</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2002.xls">2002</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2001.xls">2001</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic2000.xls">2000</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1999.xls">1999</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1998.xls">1998</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1997.xls">1997</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1996.xls">1996</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1995.xls">1995</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1994.xls">1994</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1993.xls">1993</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1992.xls">1992</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1991.xls">1991</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1990.xls">1990</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1989.xls">1989</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1988.xls">1988</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1987.xls">1987</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1986.xls">1986</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1985.xls">1985</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1984.xls">1984</a></li>
                                        <li class="ico xls"><a href="/coal/data/public/xls/coalpublic1983.xls">1983</a></li>
                                    </ul>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </li>
            </ul>
            <ul>
                <li class="head"><a href="/coal/production/weekly/">Weekly estimates</a></li>
                <li><span class="release-date">Released:</span> <span class="date">Weekly (on Thursday)</span> <span class="pipe">|</span> <span class="source">from:</span> <a href="/coal/production/weekly/">Weekly Coal Production Report</a></li>
            </ul>
            <ul>
                <li class="head">Quarterly</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/production/quarterly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/production/quarterly/">Quarterly Coal Report</a></li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t1p01p1.pdf" title="Consumption quarterly"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t1p01p1.xlsx" title="Consumption quarterly"><span class="ico xls"><span>XLSX</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Annual</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/annual/">Annual Coal Report</a> <span class="pipe">|</span> <span class="source">Interactive data from:</span> <a href="/coal/data/browser/">Coal Data Browser</a></li>
                <li class="list-spacer"></li>
                <li>By state and mine type</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table1.pdf" title="production Annual By state and mine type"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table1.xlsx" title="production Annual By state and mine type"><span class="ico xls"><span>XLSX</span></span></a><span class="pipe-alt">|</span><a href="/beta/coal/data/browser/#/topic/33?agg=1,0&amp;geo=vvvvvvvvvvvvo&amp;freq=A&amp;start=2008&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="production Annual By state and mine type"><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By state, county, and mine type</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table2.pdf" title="production Annual By state, county, and mine type"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table2.xlsx" title="production Annual By state, county, and mine type"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By state and coal rank</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table6.pdf" title="production Annual By state and coal rank"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table6.xlsx" title="production Annual By state and coal rank"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Coal mining productivity &amp; employees by state and mine type</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table21.pdf" title="Annual Coal mining productivity & employees by state and mine type"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table21.xlsx" title="Annual Coal mining productivity & employees by state and mine type"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Detailed mine level production data</li>
                <li><span class="formats">Available formats:</span> <a href="/beta/coal/data/browser/#/topic/38?agg=0,2,1&amp;rank=g&amp;geo=vvvvvvvvvvvvo&amp;mntp=g&amp;freq=A&amp;start=2001&amp;ctype=map&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="production Annual, Detailed mine level production data"><span class="ico interactive"><span>Interactive</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By coal rank and mining method, 1949&ndash;2021</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/tableES1.pdf" title="production Annual By coal rank and mining method, 1949-2017"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/tableES1.xlsx" title="production Annual By coal rank and mining method, 1949-2017"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
                <li>
                    <ul>
                        <li><a href="/international/data/world/coal-and-coke/coal-and-coke-production">Coal and coke production</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <h3 id="stocks">Stocks </h3>
        <div class="accordion-content">
            <ul>
                <li class="head">Quarterly</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/production/quarterly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/production/quarterly/">Quarterly Coal Report</a></li>
                <li class="list-spacer"></li>
                <li>By consuming sector and by producers</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t37p01p1.pdf" title="Quarterly stocks By consuming sector and by producers"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t37p01p1.xlsx" title="Quarterly stocks By consuming sector and by producers"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>At coke plants by Census division</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t38p01p1.pdf" title="Quarterly stocks At coke plants by Census division"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t38p01p1.xlsx" title="Quarterly stocks At coke plants by Census division"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>At other industrial plants by Census division and state</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t39p01p1.pdf" title="Quarterly stocks At industrial plants by Census division and state"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t39p01p1.xlsx" title="Quarterly stocks At industrial plants by Census division and state"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>At manufacturing plants by North American Industry Classification System (NAICS) code</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t40p01p1.pdf" title="Quarterly stocks At manufacturing plants by North American Industry Classification System (NAICS) code"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t40p01p1.xlsx" title="Quarterly stocks At manufacturing plants by North American Industry Classification System (NAICS) code"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>At commercial and institutional users by Census division and state</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t42p01p1.pdf" title="Quarterly stocks At commercial and institutional users by Census division and state"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t42p01p1.xlsx" title="Quarterly stocks At commercial and institutional users by Census division and state"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Coke and breeze stocks at coke plants by Census division</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t41p01p1.pdf" title="Quarterly stocks At coke and breeze stocks at coke plants by Census division"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t41p01p1.xlsx" title="Quarterly stocks At coke and breeze stocks at coke plants by Census division"><span class="ico xls"><span>XLSX</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Monthly by sector</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/totalenergy/data/monthly/">Monthly Energy Review</a> <span class="pipe">|</span> <span class="source">Interactive data from</span> <a href="/totalenergy/data/browser/" title="Interactive data from">Total Energy Browser</a></li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec6_5.pdf" title="Monthly by sector"><span class="ico pdf"><span>PDF</span></span></a> <a href="/totalenergy/data/browser/csv.php?tbl=T06.03" title="Monthly by sector"><span class="ico csv"><span>CSV</span></span></a> <a href="/totalenergy/data/browser/xls.php?tbl=T06.03&amp;freq=m" title="Monthly by sector"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/index.php?tbl=T06.03#/?f=M&start=200001" title="Monthly by sector"><span class="ico interactive"><span>Interactive</span></span></a></li>
            </ul>
            <ul>
                <li class="head"><a href="/totalenergy/data/annual/showtext.cfm?t=ptb0706" title="Annual by sector">Annual by sector</a></li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('totalenergy/data/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/totalenergy/data/annual/">Annual Energy Review, 1949 through 2011</a> <span class="alert">(no longer updated)</span></li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/annual/pdf/sec7_15.pdf" title="Annual by sector"><span class="ico pdf"><span>PDF</span></span></a> <a href="/totalenergy/data/annual/xls/stb0706.xls" title="Annual by sector"><span class="ico xls"><span>XLS</span></span></a></li>
            </ul>
        </div>
        <h3 id="imports">Imports, exports &amp; distribution </h3>
        <div class="accordion-content">
            <ul>
                <li class="head">Imports by country of origin</li>
                <li><span class="source">Interactive data from:</span> <a href="/coal/data/browser/" title="Imports by country of origin Interactive data from">Coal Data Browser</a></li>
            </ul>
            <ul>
                <li class="head">Quarterly</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/production/quarterly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/production/quarterly/">Quarterly Coal Report</a></li>
                <li class="list-spacer"></li>
                <li>Latest two quarters</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t18p01p1.pdf" title="Imports by country of origin Latest two quarters"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t18p01p1.xlsx" title="Imports by country of origin Latest two quarters"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Quarterly</li>
                <li><span class="formats">Available formats:</span> <a href="/beta/coal/data/browser/#/topic/39?agg=2,1,0&amp;rank=ok&amp;linechart=COAL.IMPORT_QTY.TOT-TOT-TOT.Q&amp;columnchart=COAL.IMPORT_QTY.TOT-TOT-TOT.Q&amp;map=COAL.EXPORT_QTY.TOT-TOT-TOT.Q&amp;freq=Q&amp;ctype=map&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Imports by country of origin Quarterly"><span class="ico interactive"><span>Interactive</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Quarterly</li>
                <li><span class="source">Data from:</span> Bureau of the Census, 'Monthly Report IM 145.'</span></li>
                <li class="list-spacer"></li>
                <li>Back to 2002</li>
                <li><span class="formats">Available formats:</span> <a href="archive/coal_historical_imports.xlsx" title="Imports by country of origin Quarterly Back to 2002"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span> <a href="/beta/coal/data/browser/#/topic/39?agg=2,1,0&amp;rank=ok&amp;linechart=COAL.IMPORT_QTY.TOT-TOT-TOT.A&amp;columnchart=COAL.IMPORT_QTY.TOT-TOT-TOT.A&amp;map=COAL.EXPORT_QTY.TOT-TOT-TOT.A&amp;freq=A&amp;ctype=map&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Imports by country of origin Quarterly Back to 2002"><span class="ico interactive"><span>Interactive</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Exports by country of destination</li>
                <li><span class="source">Interactive data from:</span> <a href="/coal/data/browser/" title="Exports by country of destination Interactive data from">Coal Data Browser</a></li>
            </ul>
            <ul>
                <li class="head">Quarterly</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/production/quarterly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/production/quarterly/">Quarterly Coal Report</a></li>
                <li class="list-spacer"></li>
                <li>Latest two quarters</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t7p01p1.pdf" title="Exports by country of destination Latest two quarters"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t7p01p1.xlsx" title="Exports by country of destination Latest two quarters"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Quarterly</li>
                <li><span class="formats">Available formats:</span> <a href="/beta/coal/data/browser/#/topic/41?agg=2,1,0&rank=ok&map=COAL.EXPORT_QTY.TOT-TOT-TOT.Q&freq=Q&start=200001&end=201403&ctype=map&ltype=pin&rtype=s&pin=&rse=0&maptype=0" title="Exports by country of destination Quarterly"><span class="ico interactive"><span>Interactive</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Quarterly</li>
                <li><span class="source">Data from:</span> Bureau of the Census, 'Monthly Report EM 545.</li>
                <li class="list-spacer"></li>
                <li>Back to 2002</li>
                <li><span class="formats">Available formats:</span> <a href="archive/coal_historical_exports.xlsx" title="Exports by country of destination Quarterly Back to 2002"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span> <a href="/beta/coal/data/browser/#/topic/41?agg=2,1,0&amp;rank=ok&amp;linechart=COAL.EXPORT_QTY.TOT-TOT-TOT.A&amp;columnchart=COAL.EXPORT_QTY.TOT-TOT-TOT.A&amp;map=COAL.EXPORT_QTY.TOT-TOT-TOT.A&amp;freq=A&amp;ctype=map&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Exports by country of destination Quarterly Back to 2002"><span class="ico interactive"><span>Interactive</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Distribution</li>
                <li class="description">By origin/destination state, consuming sector, and method of transportatio</li>
                <li class="list-spacer"></li>
                <li><a href="/coal/distribution/quarterly/" title="Distribution Quarterly">Quarterly</a></li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/distribution/quarterly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="release-date">Re-release Date:</span> <span class="date"> February 6, 2025 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/distribution/quarterly/">Quarterly Coal Distribution Report</a></li>
                <li class="list-spacer"></li>
                <li><a href="/coal/distribution/annual/" title="Distribution Annual">Annual</a></li>
                <li><span class="release-date">Release Date: </span> <span class="date">
                        <?php include('coal/distribution/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/distribution/annual/">Annual Coal Distribution Report</a></li>
                <li class="list-spacer"></li>
                <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
                <li>
                    <ul>
                        <li><a href="/international/data/world/coal-and-coke/coal-and-coke-imports">Coal and coke imports</a></li>
                        <li><a href="/international/data/world/coal-and-coke/coal-and-coke-exports">Coal and coke exports</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <h3 id="metallurgical">Metallurgical coal </h3>
        <div class="accordion-content">
            <ul>
                <li class="head">Monthly coal consumed by coke plants</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/totalenergy/data/monthly/">Monthly Energy Review</a> <span class="pipe">|</span> <span class="source">Interactive data from</span> <a href="/coal/data/browser/" title="Interactive data from">Coal Data Browser</a></li>
                <li><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec6_4.pdf" title="Coal consumption by sector"><span class="ico pdf"><span>PDF</span></span></a> <a href="/totalenergy/data/browser/csv.php?tbl=T06.02" title="Coal consumption by sector"><span class="ico csv"><span>CSV</span></span></a> <a href="/totalenergy/data/browser/xls.php?tbl=T06.02&amp;freq=m" title="Coal consumption by sector"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/index.php?tbl=T06.02#/?f=M&start=200001" title="Coal consumption by sector"><span class="ico interactive"><span>Interactive</span></span></a></li>
            </ul>
            <ul>
                <li class="head">Quarterly</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/production/quarterly/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/production/quarterly/">Quarterly Coal Report</a></li>
            </ul>
            <ul>
                <li>Coke Summary statistics</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/tes2p01p1.pdf" title="U.S. coke summary statistics"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/tes2p01p1.xlsx" title="U.S. coke summary statistics"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Coke and breeze production at coke plants</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t3p01p1.pdf" title="Coke and breeze production at coke plants"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t3p01p1.xlsx" title="Coke and breeze production at coke plants"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>U.S. metallurgical coal exports</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t11p01p1.pdf" title="U.S. metallurgical coal exports"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t11p01p1.xlsx" title="U.S. metallurgical coal exports"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Average price of U.S. metallurgical coal exports</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t12p01p1.pdf" title="Average price of U.S. metallurgical coal exports"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t12p01p1.xlsx" title="Average price of U.S. metallurgical coal exports"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Metallurgical coal exports by customs district</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t15p01p1.pdf" title="Metallurgical coal exports by customs district"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t15p01p1.xlsx" title="Metallurgical coal exports by customs district"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>U.S. coke exports</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t16p01p1.pdf" title="U.S. coke exports"><span clas="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t16p01p1.xlsx" title="U.S. coke exports "><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Average price of U.S. coke exports</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t17p01p1.pdf" title="Average price of U.S. coke exports"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t17p01p1.xlsx" title="Average price of U.S. coke exports"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>U.S. coke imports</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t18p01p1.pdf" title="U.S. coke imports"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t18p01p1.xlsx" title="U.S. coke imports"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Average price of U.S. coke imports</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t19p01p1.pdf" title="Average price of U.S. coke imports"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t19p01p1.xlsx" title="Average price of U.S. coke imports"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Coal receipts at coke plants by census division</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t23p01p1.pdf" title="Coal receipts at coke plants by census division"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t23p01p1.xlsx" title="Coal receipts at coke plants by census division"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Average price of coal receipts at coke plants by census division</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t24p01p1.pdf" title="Average price of coal receipts at coke plants by census division"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t24p01p1.xlsx" title="Average price of coal receipts at coke plants by census division"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Open market sales and average price of coke and breeze</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t25p01p1.pdf" title="Open market sales and average price of coke and breeze"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t25p01p1.xlsx" title="Open market sales and average price of coke and breeze"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>U.S. coal consumption by end-use sector</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t32p01p1.pdf" title="U.S. coal consumption by end-use sector"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t32p01p1.xlsx" title="U.S. coal consumption by end-use sector"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Coal carbonized at coke plants by census division</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t33p01p1.pdf" title="Coal carbonized at coke plants by census division"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t33p01p1.xlsx" title="Coal carbonized at coke plants by census division"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>U.S. coal stocks</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t37p01p1.pdf" title="U.S. coal stocks"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t37p01p1.xlsx" title="U.S. coal stocks"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Coal stocks at coke plants by census division</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/production/quarterly/pdf/t38p01p1.pdf" title="Coal stocks at coke plants by census division"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/production/quarterly/xls/t38p01p1.xlsx" title="Coal stocks at coke plants by census division"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Annual</li>
                <li><span class="release-date">Release Date:</span> <span class="date">
                        <?php include('coal/annual/includes/releasedate.inc') ?>
                    </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/coal/annual/">Annual Coal Report</a></li>
                <li class="list-spacer"></li>
                <li>Coal disposition by state</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table8.pdf" title="Coal disposition by state"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table8.xlsx" title="Coal disposition by state"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Average number of employees and number of mines by state and coal type</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table18_1.pdf" title="Average number of employees and number of mines by state and coal type"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table18_1.xlsx" title="Average number of employees and number of mines by state and coal type"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li>Average sales price of U.S. coal by use and disposition</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/annual/pdf/table33_1.pdf" title="Average sales price of U.S. coal by use and disposition"><span class="ico pdf"><span>PDF</span></span></a> <a href="/coal/annual/xls/table33_1.xlsx" title="Average sales price of U.S. coal by use and disposition"><span class="ico xls"><span>XLSX</span></span></a></li>
                <li class="list-spacer"></li>
                <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
                <li>
                    <ul>
                        <li><a href="/international/data/world/coal-and-coke/coal-and-coke-consumption">Coal and coke consumption</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <h3 id="plants">Coal-fired electric power plants </h3>
        <div class="accordion-content">
            <ul class="highlight">
                <li class="head">
                <li><span class="release-date">Release Date:</span> <span class="date">September 9, 2025</span> <span class="pipe">|</span> <span class="source">Detailed data from the <a href="/survey/form/eia_860/instructions.pdf">EIA-860</a> (back to 2003)</span></li>
                <li>Capacity, energy source, date of first operation, and planned retirement date for coal-fired generating units</li>
                <li>
                    <div class="form-container do-not-print">
                        <fieldset>
                            <legend>Releases</legend>
                            <div class="dropdown-container no-js">
                                <div class="dropdown-button"> <span class="text">Select Year</span> <span class="ico d-arrow"><span>dropdown arrow</span></span> </div>
                                <div class="dropdown-menu">
                                    <ul>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/Coal Generators 2024.xlsx">2024</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/Coal Generators 2023.xlsx">2023</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/Coal Generators 2022.xlsx">2022</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/Coal Generators 2021.xlsx">2021</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2020.xlsx">2020</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2019.xlsx">2019</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2018.xlsx">2018</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2017.xlsx">2017</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2016.xlsx">2016</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2015.xlsx">2015</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2014.xls">2014</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2013.xls">2013</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2012.xls">2012</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2011.xls">2011</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2010.xls">2010</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2009.xls">2009</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2008.xls">2008</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2007.xls">2007</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2006.xls">2006</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2005.xls">2005</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2004.xls">2004</a></li>
                                        <li class="ico xls"><a href="/electricity/archive/capacity/xls/existing_gen_units_2003.xls">2003</a></li>
                                    </ul>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </li>
            </ul>
        </div>
        <h3 id="transrate">Transportation costs to electric power sector </h3>
        <div class="accordion-content">
            <ul>
                <li class="head"><strong>Real and nominal average transportation costs (back to 2008)</strong> - <a href="/coal/transportationrates/">methodology</a></li>
                <li><span class="release-date">Release Date:</span> <span class="date">May 2, 2022</span> <span class="pipe">|</span> <span class="source">Data from:</span> <a href="/electricity/data/eia923/">Form EIA-923, &quot;Power Plant Operations Report&quot;</a></li>
            </ul>
            <ul>
                <li class="head">Delivered costs</li>
                <li>By year and primary transport mode</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/transportationrates/excel/Table 1_Real.xlsx" title="Real Transportation costs to electric power sector Delivered costs By year and primary transport mode"><span class="ico xls"><span>Real (XLS)</span></span></a> <span class="space"></span><a href="/coal/transportationrates/excel/Table 1_Nominal.xlsx" title="Nominal Transportation costs to electric power sector Delivered costs By year and primary transport mode"><span class="ico xls"><span>Nominal (XLS)</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By primary transport mode and supply region</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/transportationrates/excel/Table 2_Real.xlsx" title="Real Transportation costs to electric power sector Delivered costs By primary transport mode and supply region"><span class="ico xls"><span>Real (XLS)</span></span></a> <span class="space"></span> <a href="/coal/transportationrates/excel/Table 2_Nominal.xlsx" title="Nominal Transportation costs to electric power sector Delivered costs By primary transport mode and supply region"><span class="ico xls"><span>Nominal (XLS)</span></span></a></li>
            </ul>
            <ul>
                <li class="head">From coal basin to state</li>
                <li>By truck</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/transportationrates/excel/Table 3a_Real.xlsx" title="Real Transportation costs to electric power sector From coal basin to state By truck"><span class="ico xls"><span>Real (XLS)</span></span></a> <span class="space"></span><a href="/coal/transportationrates/excel/Table 3a_Nominal.xlsx" title="Nominal Transportation costs to electric power sector From coal basin to state By truck"><span class="ico xls"><span>Nominal (XLS)</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By waterway</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/transportationrates/excel/Table 3b_Real.xlsx" title="Real Transportation costs to electric power sector From coal basin to state By waterway"><span class="ico xls"><span>Real (XLS)</span></span></a> <span class="space"></span><a href="/coal/transportationrates/excel/Table 3b_Nominal.xlsx" title="Nominal Transportation costs to electric power sector From coal basin to state By waterway"><span class="ico xls"><span>Nominal (XLS)</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By railroad</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/transportationrates/excel/Table 3c_Real.xlsx" title="Real Transportation costs to electric power sector From coal basin to state By railroad"><span class="ico xls"><span>Real (XLS)</span></span></a> <span class="space"></span><a href="/coal/transportationrates/excel/Table 3c_Nominal.xlsx" title="Nominal Transportation costs to electric power sector From coal basin to state By railroad"><span class="ico xls"><span>Nominal (XLS)</span></span></a></li>
            </ul>
            <ul>
                <li class="head">From state to state</li>
                <li>By truck</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/transportationrates/excel/Table 4a_Real.xlsx" title="Real Transportation costs to electric power sector From state to state By truck"><span class="ico xls"><span>Real (XLS)</span></span></a> <span class="space"></span><a href="/coal/transportationrates/excel/Table 4a_Nominal.xlsx" title="Nominal Transportation costs to electric power sector From state to state By truck"><span class="ico xls"><span>Nominal (XLS)</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By waterway</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/transportationrates/excel/Table 4b_Real.xlsx" title="Real Transportation costs to electric power sector From state to state By waterway"><span class="ico xls"><span>Real (XLS)</span></span></a> <span class="space"></span><a href="/coal/transportationrates/excel/Table 4b_Nominal.xlsx" title="Nominal Transportation costs to electric power sector From state to state By waterway"><span class="ico xls"><span>Nominal (XLS)</span></span></a></li>
                <li class="list-spacer"></li>
                <li>By railroad</li>
                <li><span class="formats">Available formats:</span> <a href="/coal/transportationrates/excel/Table 4c_Real.xlsx" title="Real Transportation costs to electric power sector From state to state By railroad"><span class="ico xls"><span>Real (XLS)</span></span></a> <span class="space"></span><a href="/coal/transportationrates/excel/Table 4c_Nominal.xlsx" title="Nominal Transportation costs to electric power sector From state to state By railroad"><span class="ico xls"><span>Nominal (XLS)</span></span></a></li>
            </ul>
        </div>
    </div>
</div>