<h2 id="" class="eia-h2 eia-margin-xlarge-top">Branded Checkbox</h2>
<h5>Checkboxes</h5>
<p>A toggle checkbox that can only be one of two states: checked or unchecked. The value is only submitted by the form if the checkbox is checked.</p>
<!-- Live Examples -->
<h3 class="eia-h3">Live Examples</h3>
<dl class="">
	<dd><a>placeholder</a></dd>
</dl>
<!-- Example -->
<h3 class="eia-h3">Example</h3>
<div class="eia-card">
	<div class="l-row l-two-col-left-wide">
		<div class="primary l-col form-area">
			<ul class="checkbox-container">
				<li class="custom-checkbox">
					<input type="checkbox" name="elements" class="custom-checkbox-input" value="Item One" id="elementOne" />
					<label for="elementOne" class="custom-checkbox-label">
						<span class="custom-checkbox-label-inside"> Item One</span>
					</label>
				</li>
				<li class="custom-checkbox">
					<input type="checkbox" name="elements" class="custom-checkbox-input" value="Item Two" id="elementTwo" />
					<label for="elementTwo" class="custom-checkbox-label">
						<span class="custom-checkbox-label-inside"> Item Two</span>
					</label>
				</li>
			</ul>
		</div>
	</div>
	<div class="l-col"></div>
</div>
<!-- HTML -->
<h3 class="eia-h3">HTML</h3>
<pre><code class="language-html" id="BrandedCheckbox"></code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element eia-button eia-button-primary" data-clipboard-action="copy" data-clipboard-target="#BrandedCheckbox">
		<span></span>Copy to clipboard
	</button>
</p>