<h2 class="uk-h3 tm-heading-fragment" id="Fieldset">Fieldset</h2>
<p>
	Defines a <strong>group of controls</strong> within a form.
</p>
<!-- Live Examples --
<div class="uk-text-default uk-text-normal uk-text-uppercase">Live Examples</div>
<dl class="uk-description-list uk-description-list-divider">
	<dd><a [routerLink]="['/modules/']" [fragment]="'placeholder'">placeholder</a></dd>
</dl>
-->
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="uk-card uk-card-default uk-padding">
	<fieldset>
		<br />
		<br />
	</fieldset>
</div>

<h3 id="" class="uk-h3 tm-heading-fragment">Legend</h3>
<p>
	Defines a <strong>caption</strong> for the fieldset.
</p>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="uk-card uk-card-default uk-padding">
	<fieldset>
		<legend>Subscribe to the Newsletter</legend>
		<br />
		<br />
	</fieldset>
</div>
<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="Fieldset">&lt;fieldset&gt;
  &lt;legend&gt;Subscribe to the Newsletter&lt;/legend&gt;
  &lt;br /&gt;
  &lt;br /&gt;
&lt;/fieldset&gt;</code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Fieldset">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
<hr class="uk-margin-large" />