<div class="form-wrapper">
    <form accept-charset="UTF-8" action="//search.usa.gov/search" id="search_form" method="get" _lpchecked="1">
        <input name="utf8" type="hidden" value="✓">
        <input id="affiliate" name="affiliate" type="hidden" value="eia.doe.gov">
        <input autocomplete="off" class="usagov-search-autocomplete ui-autocomplete-input" id="search-input" name="query" type="text" maxlength="256" placeholder="Search survey forms by name or #" onfocus="this.placeholder=''" onblur="this.placeholder='Search survey forms by name or #'">
        <button type="submit" class="search-submit"  name="search" alt="enter terms to search" border="0" title="Click to search EIA"></button>
    </form>
</div>






