<!--
import FormLayout from "../Containers/FormLayout"

class AccessibilityCheckbox -->
<!-- code

<fieldset>
<label>Select your elements:</label>
<ul class="checkbox-container">
<li class="custom-checkbox">
<input type="checkbox" name="elements" class="custom-checkbox-input" value="Item One" id="elementOne" />
<label  for="elementOne" class="custom-checkbox-label">
<span class="custom-checkbox-label-inside">
Item One/span>
</label>
</li>
<li class="custom-checkbox">
<input type="checkbox" name="elements" class="custom-checkbox-input" value="Item Two" id="elementTwo" />
<label  for="elementTwo" class="custom-checkbox-label">
<span class="custom-checkbox-label-inside">
Item Two/span>
</label>
</li>
</ul>
</fieldset>


-->



</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">