<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Date Picker</h2>
<p>Not approved!</p>
<!-- Live Examples --
<div class="uk-text-default uk-text-normal uk-text-uppercase">Live Examples</div>
<dl class="uk-description-list uk-description-list-divider">
	<dd><a [routerLink]="['/modules/']" [fragment]="'placeholder'">placeholder</a></dd>
</dl>
-->
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <div class="primary form-area">
    <div class="l-row l-two-col-left">
      <div class="l-col">
        <p>Date Picker.</p>
      </div>
      <div class="l-col">
        <div class="form-container do-not-print">
          <label>Select Date</label>
          <input id="date" type="date" class="date-picker" value="Datepicker" />
        </div>
      </div>
    </div>
  </div>

  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <pre><code class="language-html" id="DatePicker"></code></pre>
  <!-- Copy Button -->
  <p>
    <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#DatePicker"><span uk-icon="copy"></span>Copy to clipboard</button>
  </p>
  -->
</div>
