<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Secondary Column</h2>
<h4>Live examples:</h4>
<div class="primary">
  <ul>
    <li><a href="https://wwwdev.eia.gov/outlooks/ieo/section_issue_aiso.php">https://wwwdev.eia.gov/outlooks/ieo/section_issue_aiso.php</a></li>
  </ul>
</div>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <ul class="contact">
    <li class="head">
      <h4>About the author</h4>
    </li>
    <li class="author">Elizabeth Sendich</li>
    <li class="title">Lead Industry Economist/ Economist</li>
    <li class="list-spacer"></li>
    <li class="contact">
      <a href="mailto:Elizabeth.Sendich@eia.gov">Elizabeth.Sendich@eia.gov</a>
    </li>
    <li class="contact">
      <a href="tel:+1202586-4412">(202) 586-4412</a>
    </li>
  </ul>
  <p>Elizabeth Sendich, PhD, is Lead Industry Economist on the Macroeconomic Analysis Team. She helps maintain EIA&apos;s long-term production forecasts and enhances public understanding of important issues related to the industrial sector, including manufacturing, construction, mining, and agriculture. She is responsible for the integrated modeling of a diverse set of industries across the world and for analysis of topics important to the sector, such as trade, supply chains, and technology.</p>

  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="LinksLinkLabelAria"></code></pre>
    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#LinksLinkLabelAria"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
