<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Block Quote</h2>
<h4>Live examples:</h4>
<div class="primary">
  <ul>
    <li><a href="https://www.eia.gov/outlooks/ieo/section_issue_aiso.php">https://www.eia.gov/outlooks/ieo/section_issue_aiso.php</a></li>
  </ul>
</div>

<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <div class="article">
    <p>Elizabeth Sendich, PhD, is Lead Industry Economist on the Macroeconomic Analysis Team. She helps maintain EIA&apos;s long-term production forecasts and enhances public understanding of important issues related to the industrial sector, including manufacturing, construction, mining, and agriculture. She is responsible for the integrated modeling of a diverse set of industries across the world and for analysis of topics important to the sector, such as trade, supply chains, and technology.</p>
    <blockquote>long-term energy consumption projections are uncertain because of the rapid rate of change that is magnified by the size of the economy.</blockquote>
    <p>Elizabeth Sendich, PhD, is Lead Industry Economist on the Macroeconomic Analysis Team. She helps maintain EIA&apos;s long-term production forecasts and enhances public understanding of important issues related to the industrial sector, including manufacturing, construction, mining, and agriculture. She is responsible for the integrated modeling of a diverse set of industries across the world and for analysis of topics important to the sector, such as trade, supply chains, and technology.</p>
  </div>
  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="LinksLinkLabelAria"></code></pre>
    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#LinksLinkLabelAria"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
