<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Primary Column Example Three</h2>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
	<ul class="contact">
		<li class="foot">
			<a href="/about/contact/coal.php">Coal Data Contacts</a>
		</li>
	</ul>


	<!-- HTML -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
	<div class="uk-margin-medium">


		<pre><code class="language-html" id="Dilly">Code sample not ready yet.</code></pre>
		<!-- Copy Button -->
		<p>
			<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly">
				<span uk-icon="copy"></span>Copy to clipboard
			</button>
		</p>
	</div>
	<!-- HTML -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>

	<pre><code class="language-html" id="LinksLinkLabelAria"></code></pre>
	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#LinksLinkLabelAria">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
	</p>
	</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">