<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Primary Column Example Two</h2>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <div class="article">
    <ul class="contact">
      <li class="head">
        <h4>Contacts</h4>
      </li>
      <li class="contact">Robert Merriam</li>
      <li class="contact"><span class="label">Email:</span> <a href="mailto:Robert.Merriam@eia.gov">Robert.Merriam@eia.gov</a></li>
      <li class="contact"><span class="label">Phone:</span> <a href="tel:+12025864615">(202) 586-4615</a></li>
      <li class="title"><span class="label">Title:</span> Director, Office of Petroleum and Biofuels Statistics, Office of Energy Statistics.</li>
      <li class="address">
        <span class="label">Address:</span> U.S. Energy Information Administration
        <br />
        1000 Independence Ave., SW
        <br />
        Washington, DC 20585
      </li>
    </ul>
  </div>
  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="LinksLinkLabelAria"></code></pre>
    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#LinksLinkLabelAria"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
