<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Primary Column Report Contact Example One</h2>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <p>Please comment by September 25, 2014.</p>
  <ul class="contact">
    <li class="head">
      <h4>Contact Survey Manager</h4>
    </li>
    <li class="contact">Marcela Rourk</li>
    <li class="contact"><span class="label">Email:</span> <a href="mailto:neal.davis@eia.gov">neal.davis@eia.gov</a></li>
    <li class="contact"><span class="label">Phone:</span> <a href="tel:+12025866581">(202) 586-6581</a></li>
    <li class="list-spacer"></li>
    <li class="head">
      <h4>More Natural Gas Notices</h4>
    </li>
    <li class="foot">
      <a href="/survey/notice/ngdownstreamforms2015.php">Changes to Downstream Natural Gas Survey forms for 2015</a>
    </li>
  </ul>

  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="LinksLinkLabelAria"></code></pre>
    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#LinksLinkLabelAria"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
