<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Primary Column Report Contact Example Two</h2>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <div class="article">
    <p>Please send comments on the proposed information collection and WPSR methodology changes to:</p>
    <ul class="contact">
      <li class="head">
        <h4>Contact Survey Manager</h4>
      </li>
      <li class="contact">Sasha Abdalla</li>
      <li class="contact"><span class="label">Email:</span> <a href="mailto:Sasha.Abdalla@eia.gov">Sasha.Abdalla@eia.gov</a></li>
      <li class="contact"><span class="label">Phone:</span> <a href="tel:+12022876323">(202) 287-6323</a></li>
    </ul>
  </div>
  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="LinksLinkLabelAria"></code></pre>
    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#LinksLinkLabelAria"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
