<!--


import Page from "../Page"
//import Top from "./Placeholders/Top.js"
import Listpdf.inc'); from "./Listpdf.inc');"
import Listxls.inc'); from "./Listxls.inc');"
import Listcsv.inc'); from "./Listcsv.inc');"
import Listdoc.inc'); from "./Listdoc.inc');"
import Listppt.inc'); from "./Listppt.inc');"
import Listint.inc');eractive from "./Listint.inc');eractive"
import Listhtml.inc'); from "./Listhtml.inc');"
import txt.inc');from "./Listtxt.inc');"
import ListIcoImage from "./ListIcoImage"
import Listjson.inc'); from "./Listjson.inc');"
import ListIcoPedro from "./ListIcoPedro"
import Listefile.inc'); from "./Listefile.inc');"

class IconicListItems

-->

<h3>Iconic List Items</h3>
<div class="icon-container">
	<ul>
		<li class="eia ico pdf">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico pdf">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/pdf.inc');.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico xls">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico xls">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/xls.inc');.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico csv">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico csv">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/csv.inc');.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico interactive">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico interactive">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/int.inc');eractive.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico ppt">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico ppt">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/ppt.inc');.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico html">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico html">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/html.inc');.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico doc">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico doc">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/doc.inc');.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico image">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico image">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/IcoImage.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico pedro">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico pedro">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/IcoPedro.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico json">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico json">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/json.inc');.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico efile">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico efile">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<?php include('./includes/icons/lists/efile.inc');.inc') ?>
</div>
<div class="icon-container">
	<ul>
		<li class="eia ico txt">
			<a>Lorem ipsum dolor sit amet</a>
		</li>
		<li class="eia ico txt">
			<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra luctus lorem vitae pharetra. Morbi blandit, turpis sagittis semper volutpat, erat massa gravida dui, ut dignissim ligula nibh eu mi.</a>
		</li>
	</ul>
	<txt.inc');.inc') ?>
</div>