<ul>
	<li class="eia ico pdf">
		<a>Lorem ipsum dolor sit amet PDF</a>
	</li>
	<li class="eia ico xls">
		<a>Lorem ipsum dolor sit amet XLS</a>
	</li>
	<li class="eia ico csv">
		<a>Lorem ipsum dolor sit amet CSV</a>
	</li>
	<li class="eia ico interactive">
		<a>Lorem ipsum dolor sit amet Interactive</a>
	</li>
	<li class="eia ico ppt">
		<a>Lorem ipsum dolor sit amet PPT</a>
	</li>
	<li class="eia ico html">
		<a>Lorem ipsum dolor sit amet HTML</a>
	</li>
	<li class="eia ico doc">
		<a>Lorem ipsum dolor sit amet DOC</a>
	</li>
	<li class="eia ico image">
		<a>Lorem ipsum dolor sit amet Image</a>
	</li>
	<li class="eia ico json">
		<a>Lorem ipsum dolor sit amet JSON</a>
	</li>
	<li class="eia ico efile">
		<a>Lorem ipsum dolor sit amet eFile</a>
	</li>
	<li class="eia ico txt">
		<a>Lorem ipsum dolor sit amet TXT</a>
	</li>
	<li class="eia ico pedro">
		<a>Lorem ipsum dolor sit amet PEDRO</a>
	</li>
</ul>