<h3>List Items</h3>

<div class="accordion-content horizontal-icon-container list-item">


	<?php include('./includes/icons/list-items/example -->


	<div class="icon-container">
		<a class="eia ico pdf">
			<span>PDF</span>
		</a>
		<?php include('./includes/icons/list-items/pdf -->
	</div>
	<div class="icon-container">
		<a class="eia ico xls">
			<span>XLS</span>
		</a>
		<?php include('./includes/icons/list-items/xls -->
	</div>
	<div class="icon-container">
		<a class="eia ico csv">
			<span>CSV</span>
		</a>
		<?php include('./includes/icons/list-items/csv -->
	</div>
	<div class="icon-container">
		<a class="eia ico interactive">
			<span>Interactive</span>
		</a>
		<?php include('./includes/icons/list-items/interactive -->
	</div>
	<div class="icon-container">
		<a class="eia ico ppt">
			<span>PPT</span>
		</a>
		<?php include('./includes/icons/list-items/ppt -->
	</div>
	<div class="icon-container">
		<a class="eia ico html">
			<span>HTML</span>
		</a>
		<?php include('./includes/icons/list-items/html -->
	</div>
	<div class="icon-container">
		<a class="eia ico doc">
			<span>DOC</span>
		</a>
		<?php include('./includes/icons/list-items/doc -->
	</div>
	<div class="icon-container">
		<a class="eia ico jspn">
			<span>JSON</span>
		</a>
		<?php include('./includes/icons/list-items/json -->
	</div>
	<div class="icon-container">
		<a class="eia ico image">
			<span>IMAGE</span>
		</a>
		<?php include('./includes/icons/list-items/image -->
	</div>

	<div class="icon-container">
		<a class="eia ico efile">
			<span>eFile</span>
		</a>
		<?php include('./includes/icons/list-items/efile -->
	</div>
	<div class="icon-container">
		<a class="eia ico txt">
			<span>TXT</span>
		</a>
		<?php include('./includes/icons/list-items/txt -->
	</div>
	<div class="icon-container">
		<a class="eia ico pedro">
			<span>PEDRO</span>
		</a>
		<?php include('./includes/icons/list-items/pedro -->
	</div>
	<div class="icon-container">
		<a class="eia ico api">
			<span>API</span>
		</a>
		<?php include('./includes/icons/list-items/api -->
	</div>
	<div class="icon-container">
		<a class="eia ico zip">
			<span>ZIP</span>
		</a>
		<?php include('./includes/icons/list-items/zip -->
	</div>
</div>
</div>