<h2 id="xoxoxo" class="uk-h3 tm-heading-fragment">xoxoxo</h2>
<!-- Live Examples --
<div class="uk-text-default uk-text-normal uk-text-uppercase">Live Examples</div>
<dl class="uk-description-list uk-description-list-divider">
	<dd><a [routerLink]="['/themes/']" [fragment]="'placeholder'">placeholder</a></dd>
</dl>
-->
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card"></div>
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="xoxoxo"></code></pre>
<!-- Copy Button -->
<p>
  <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#xoxoxo"><span uk-icon="copy"></span>Copy to clipboard</button>
</p>
