<div class="fake-tabs">
	<ul>
		<li class="tab-nav-active">
			<a>Consumption</a>
		</li>
		<li class="tab-nav">
			<a>Electricity</a>
		</li>
		<li class="tab-nav">
			<a>Production</a>
		</li>
	</ul>
</div>


<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="fakeTabs">&lt;div class="fake-tabs"&gt;
	&lt;ul&gt;
		&lt;li class="tab-nav-active"&gt;
			&lt;a&gt;Consumption&lt;/a&gt;
		&lt;/li&gt;
		&lt;li class="tab-nav"&gt;
			&lt;a&gt;Electricity&lt;/a&gt;
		&lt;/li&gt;
		&lt;li class="tab-nav"&gt;
			&lt;a&gt;Production&lt;/a&gt;
		&lt;/li&gt;
	&lt;/ul&gt;
&lt;/div&gt;</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#fakeTabs">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>