<?php
include(path() . '/includes/lists/unordered.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/basic.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/head.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/foot.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/spacer.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/seperator.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/bulleted.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/correct-nesting.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/nested-sub.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/nested-list-item.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/top.inc');
?>
<h3>Nested Bulleted List with Spacer</h3>
<?php
include(path() . '/includes/lists/list-correct-nesting.inc');
include(path() . '/includes/top.inc');
?>
<p class="eia">Lists Features</p>
<?php
include(path() . '/includes/lists/highlight.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/oOrdered.inc');
include(path() . '/includes/top.inc');
?>
<h3>Calculated Numbered List Items</h3>
<p class="eia">
	(See
	<a href="/states/calculated-numbered-lists">Calculated Numbered Lists</a> for more information)
</p>
<?php
include(path() . '/includes/lists/calculatedNumberedLists.inc');
include(path() . '/includes/lists/unordered.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/release-schedule.inc');
include(path() . '/includes/top.inc');
include(path() . '/includes/lists/iconic-list-items.inc');
?>
<h3>Link-Lists with Trailing Link-label</h3>
<p class="eia">
	(See <a href="/style-guide/states/empty-list-items">Empty List-items</a> for more information)
</p>
<?php
include(path() . '/includes/lists/updated-data-series.inc');
include(path() . '/includes/top.inc');
?>
<h3>Link-Lists with Link-label (Month)</h3>
<?php
include(path() . '/includes/lists/upcoming-releases.inc');
include(path() . '/includes/top.inc');
?>