<!--




import H1Example from "../Placeholders/H1Example"

class SubTabsExample -->
<!-- code

<div class="tabs">
<ul>
<li><a href="#tabOne">Tab One</a></li>
<li><a href="#tabTwo">Tab Two</a></li>
</ul>
<div id="tabOne">
<div class="tab-content">\n
			<!-- tab one content here -->\n
</div>
</div>
<div id="tabTwo">
	<div class="tab-content">\n
		<!-- tab one content here -->\n
	</div>
</div>
</div>


-->

<h3>Sub-Tabs</h3>

<div>
	<div class="sub-tabs">
		<ul>
			<li class="sub-tab-nav-active">
				<a href="/outlooks/aeo/2021/consumption/sub-topic-01.php">Sub-topic 01</a>
			</li>
			<li class="sub-tab-nav">
				<a href="/outlooks/aeo/2021/consumption/sub-topic-02.php">Sub-topic 02</a>
			</li>
			<li class="sub-tab-nav">
				<a href="/outlooks/aeo/2021/consumption/sub-topic-03.php">Sub-topic 03</a>
			</li>
			<li class="sub-tab-nav">
				<a href="/outlooks/aeo/2021/consumption/sub-topic-04.php">Sub-topic 04</a>
			</li>
		</ul>
	</div>
	<!-- includes/placeholders/h1 -->
</div>

<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="Dilly">Code sample not ready yet.</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>