<div class="tabs">
	<ul>
		<li><a href="#tabOne">Tab One</a></li>
		<li><a href="#tabTwo">Tab Two</a></li>
	</ul>
	<div id="tabOne">
		<div class="tab-content">
			<!-- tab one content here -->
		</div>
	</div>
	<div id="tabTwo">
		<div class="tab-content">
			<!-- tab one content here -->
		</div>
	</div>
</div>




<h3>Nested Tabs</h3>

<div>
	<div class="fake-tabs">
		<ul>
			<li class="tab-nav-active">
				<a>Consumption</a>
			</li>
			<li class="tab-nav">
				<a>Electricity</a>
			</li>
			<li class="tab-nav">
				<a>Production</a>
			</li>
		</ul>
	</div>
</div>

<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="Dilly">Code sample not ready yet.</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>