<nav class="uk-navbar-container">
	<div class="uk-container">
		<div uk-navbar>

			<div class="uk-navbar-left">

				<ul class="uk-navbar-nav">
					<li><a href="/index.html">Home</a></li>
					<li>
						<a href="/base/home.html">Base</a>
						<div class="uk-navbar-dropdown">
							<ul class="uk-nav uk-navbar-dropdown-nav">
								<li><a href="/base/home.html">base</a></li>
								<li><a href="/base/color-palette.html">color-palette</a></li>
								<li><a href="/base/logos.html">logos</a></li>
								<li><a href="/base/margin.html">margin</a></li>
								<li><a href="/base/padding.html">padding</a></li>
								<li><a href="/base/typography.html">typography</a></li>
							</ul>
						</div>
					</li>
					<li><a href="/layouts/page-layouts.html">Layouts</a>
						<div class="uk-navbar-dropdown">
							<ul class="uk-nav uk-navbar-dropdown-nav">
							</ul>
						</div>
					</li>

					<li><a href="/layouts/">Modules</a>
						<div class="uk-navbar-dropdown">
							<ul class="uk-nav uk-navbar-dropdown-nav">

							</ul>
						</div>
					</li>

					<li><a href="/layouts/">Themes</a>
						<div class="uk-navbar-dropdown">
							<ul class="uk-nav uk-navbar-dropdown-nav">

							</ul>
						</div>
					</li>

					<li><a href="/states/">States</a>
						<div class="uk-navbar-dropdown">
							<ul class="uk-nav uk-navbar-dropdown-nav">
								<li><a href="/states/build-anchor.html">build-anchor</a>
								<li><a href="/states/calculated-numbered-lists.html">calculated-numbered-lists</a>
								<li><a href="/states/empty-list-items.html">empty-list-items</a>
								<li><a href="/states/header-shrink-expand.html">header-shrink-expand</a>
								<li><a href="/states/includes/build-anchor-description.inc">build-anchor-description.inc</a>
								<li><a href="/states/includes/build-anchor-example.inc">build-anchor-example.inc</a>
								<li><a href="/states/includes/primary-alt-example.inc">primary-alt-example.inc</a>
								<li><a href="/states/includes/primary-example.inc">primary-example.inc</a>
								<li><a href="/states/includes/secondary-alt-example.inc">secondary-alt-example.inc</a>
								<li><a href="/states/includes/secondary-example.inc">secondary-example.inc</a>
								<li><a href="/states/includes/sub-nav.inc">sub-nav.inc</a>
								<li><a href="/states/index.html">index</a>
								<li><a href="/states/link-lists.html">link-lists</a>
								<li><a href="/states/sticky-table-headers.html">sticky-table-headers</a>
								<li><a href="/states/toggle.html">toggle</a>
								<li><a href="/states/videos.html">videos</a>
							</ul>
						</div>
					</li>

				</ul>
			</div>

			<div class="uk-navbar-right">
				<ul class="uk-navbar-nav">
					<li>
						<a href="#">Templates</a>
						<div class="uk-navbar-dropdown">
							<ul class="uk-nav uk-navbar-dropdown-nav">
								<li><a href="/templates/index.html">Home</a></li>
								<li><a href="/templates/faqs.html">FAQs</a></li>
								<li><a href="/templates/report-header.html">Report Header</a></li>
								<li><a href="/templates/outlooks.html">Outlooks</a></li>
							</ul>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</nav>