<div class="primary">
	<p>Find statistics on prices, exploration &amp; reserves, production, imports, exports, storage and consumption.</p>
	<span class="expand-collapse-container">
		<span class="ico expand"><span>Expand all</span></span>
		<span class="ico collapse"><span>Collapse all</span></span>
	</span>
	<div class="accordion">
		<h3><a name="summary"></a>Summary</h3>
		<div class="accordion-content">
			<ul>
				<li class="head"><a href="/dnav/ng/ng_sum_lsum_dcu_nus_m.htm">Summary &mdash; price, supply,
						disposition</a></li>
				<li class="hide-bullet"><span class="release-date">Monthly release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/annual/includes/releasedate.inc') ?>
					</span></li>
				<li>Key natural gas data for prices, exploration &amp; reserves, production, imports, exports, storage
					and consumption by U.S. and state.</li>
			</ul>
			<ul>
				<li><a href="/dnav/ng/ng_sum_sndm_s1_m.htm">U.S. monthly supply and disposition</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Includes production, imports, withdrawals and consumption</li>
				<li class="release-schedule">Monthly</li>
			</ul>
			<ul>
				<li><a href="/dnav/ng/ng_sum_snd_a_EPG0_FPD_Mmcf_a.htm">Annual supply &amp; disposition by state</a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and state level statistics for production, deliveries and receipts, storage injections and
					withdrawals</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li><a href="/oil_gas/natural_gas/applications/eia176query.html">Annual company level data from Form
						EIA-176</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">October 2020</span></li>
				<li>Company level statistics for supply, disposition, and delivery volumes; end-use prices; and number
					of customers.</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head">Natural gas overview</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
					</span><span class="pipe">|</span><span class="source">Data from:</span> <a
						href="/totalenergy/data/monthly/">Monthly Energy Review</a></li>
				<li class="hide-bullet"><span class="release-date">Annual release date:</span> <span class="date">September 27, 2012</span>
				</li>
				<li>Statistics on gross withdrawals, marketed production, dry gas production, supplemental gases,
					imports, exports, consumption, and storage withdrawals.</li>
				<li class="list-item">
					<ul>
						<li>Monthly (<a href="/totalenergy/data/monthly/#naturalgas" title="monthly data">more on
								natural gas</a>)</li>
						<li class="hide-bullet"><span class="formats">Available formats:</span> <a
								href="/totalenergy/data/monthly/pdf/sec4_3.pdf"><span class="ico pdf"
									title="Natural gas overview monthly"><span>PDF</span></span></a><a
								href="/totalenergy/data/browser/csv.php?tbl=T04.01"><span
									class="ico csv"><span>CSV</span></span></a><a
								href="/totalenergy/data/browser/xls.php?tbl=T04.01&amp;freq=m"><span class="ico xls"
									title="Natural gas overview monthly"><span>XLS</span></span></a></li>
					</ul>
					<ul>
						<li>Annual (<a href="/totalenergy/data/annual/showtext.php?t=ptb0601" title="annual data">more
								on natural gas</a>)</li>
						<li class="hide-bullet"><span class="formats">Available formats:</span> <a
								href="/totalenergy/data/annual/pdf/sec6_5.pdf"><span class="ico pdf"
									title="Natural gas overview annual"><span>PDF</span></span></a><a
								href="/totalenergy/data/annual/xls/stb0601.xls"><span class="ico xls"
									title="Natural gas overview annual"><span>XLS</span></span></a></li>
					</ul>
				</li>
			</ul>
			<ul>
				<li><a href="/cfapps/ipdbproject/IEDIndex3.php">Natural gas statistics by country</a></li>
				<li>Query detailed country and regional energy data supply, disposition</li>
				<li class="release-schedule">Annual</li>
			</ul>
		</div>
		<h3><a name="prices"></a>Prices</h3>
		<div class="accordion-content">
			<ul>
				<li class="head"><a href="/dnav/ng/ng_pri_sum_dcu_nus_m.htm">Prices</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and state prices for imports, exports, citygate, and end-use sectors, and wellhead (through
					2012). Percentages of total volume delivered by sector.</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_pri_sum_a_EPG0_PRS_DMcf_m.htm">Residential</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Average price of natural gas delivered to residential consumers by state</li>
				<li class="release-schedule">Monthly</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_pri_sum_a_EPG0_PCS_DMcf_m.htm">Commercial</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Average price of natural gas delivered to commercial consumers by state</li>
				<li class="release-schedule">Monthly</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_pri_fut_s1_d.htm">Natural gas spot and futures prices </a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('petroleum/supply/weekly/includes/releasedate_wpsr.inc') ?>
					</span></li>
				<li>New York Mercantile Exchange futures contracts for natural gas based on delivery at the Henry Hub in
					Louisiana</li>
				<li class="release-schedule">Daily, weekly, monthly, annual</li>
				<li class="list-item">
					<ul>
						<li> <a href="/dnav/ng/ng_pri_fut_s1_m.htm">Natural gas liquid composite</a></li>
						<li class="release-schedule">Monthly, annual</li>
					</ul>
				</li>
			</ul>
		</div>
		<h3><a name="exploration"></a>Exploration &amp; reserves</h3>
		<div class="accordion-content">
			
			<ul>
				<li class="head"><a href="/naturalgas/crudeoilreserves/">U.S. Crude Oil and Natural Gas Proved Reserves</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">April 29, 2024</span></li>
				<li class="release-schedule">Annual</li>
			</ul>
			
			
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_sum_a_EPG0_r21_BCF_a.htm">Reserves summary</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>Proved reserves for natural gas and natural gas liquids by U.S., region, and state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head">Proved reserves, reserves changes, and production</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>by U.S., region, and state</li>
				<li class="release-schedule">Annual</li>
				<li>
					<ul>
						<li><a href="/dnav/ng/ng_enr_wals_a_EPG0_R21_Bcf_a.htm">Natural gas, wet after lease
								separation</a></li>
						<li><a href="/dnav/ng/ng_enr_dry_a_EPG0_r11_bcf_a.htm">Natural gas, dry</a></li>
						<li><a href="/dnav/ng/ng_enr_nang_a_EPG0_R31_Bcf_a.htm">Natural gas, nonassociated wet</a></li>
						<li><a href="/dnav/ng/ng_enr_adng_a_EPG0_r41_Bcf_a.htm">Natural gas, associated-dissolved
								wet</a></li>
						<li><a href="/dnav/ng/ng_enr_shalegas_a_EPG0_R5301_Bcf_a.htm">Shale gas</a></li>
						<li><a href="/dnav/ng/ng_enr_coalbed_a_EPG0_R51_Bcf_a.htm" title="reserves of">Coalbed
								methane</a></li>
						<li><a href="/dnav/ng/ng_enr_cplc_a_EPCCOND_R01_MMbbl_a.htm">Crude oil plus lease condensate</a>
						</li>
						<li><a href="/dnav/ng/ng_enr_lc_a_EPL0_r56_MMbbl_a.htm">Lease condensate</a></li>
					</ul>
				</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_ngl_dcu_NUS_a.htm">Natural gas liquids proved reserves</a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>Proved reserves, reserves changes, and estimated production by U.S., region, and state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_ngpl_s1_a.htm">Estimated Natural Gas Plant Liquids contained
						in Total Natural Gas Proved Reserves</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>Proved reserves, reserves changes, and estimated production by U.S., region, and state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_nprod_a_epc0_r9907_mmbbl_a.htm">Proved nonproducing
						reserves</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>Reported proved reserves of crude oil, lease condensate, and wet natural gas, after lease separation
					by U.S., region, and state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_deep_s1_a.htm">Federal Offshore Gulf of America Deepwater
						reserves</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>Proved reserves of crude oil, natural gas wet after lease separation, natural gas liquids, dry
					natural gas, and lease condensate</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_drill_s1_m.htm">Crude oil and natural gas drilling
						activity</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/includes/releasedate_ngmer_rigs.inc') ?>
					</span></li>
				<li>Rotary rigs in operation, footage drilled, and active well service rig counts</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_wellend_s1_m.htm">Crude oil and natural gas exploratory and
						development wells</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/includes/releasedate_ngmer.inc') ?>
					</span></li>
				<li>Exploratory and development wells drilled for crude oil, natural gas and dry holes; total footage
					drilled</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_wellfoot_s1_a.htm">Footage drilled for crude oil and natural
						gas wells</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/includes/releasedate_ngmer.inc') ?>
					</span></li>
				<li>Footage drilled by exploratory and development wells and by crude oil, natural gas, and dry holes
				</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_welldep_s1_a.htm">Average depth of crude oil and natural gas
						wells</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/includes/releasedate_ngmer.inc') ?>
					</span></li>
				<li>Average depth of wells drilled by exploratory and development wells and by crude oil, natural gas,
					and dry holes</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_wellcost_s1_a.htm">Costs of crude oil and natural gas wells
						drilled</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/includes/releasedate_ngmer.inc') ?>
					</span></li>
				<li>Per well and per foot costs of crude oil, natural gas, and dry hole wells</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_enr_seis_s1_m.htm">Maximum U.S. active seismic crew counts</a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/includes/releasedate_ngmer.inc') ?>
					</span></li>
				<li>By onshore/offshore/Alaska and dimension (monthly)</li>
			</ul>
			<ul>
				<li class="head"><a href="/naturalgas/crudeoilreserves/top100/">Top 100 U.S. Oil and Gas Fields</a></li>
				<li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">April 2, 2015</span></li>
				<li>Ranks the 100 largest U.S. oil and gas fields by their estimated 2013 proved reserves.</li>
			</ul>
		</div>
		<h3><a name="production"></a>Production</h3>
		<div class="accordion-content">
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_sum_a_EPG0_FGW_mmcf_m.htm">Gross withdrawals and
						production</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Components of natural gas production for the U.S., states and the Gulf of America</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/outlooks/steo/images/Fig43.png" alt="monthly dry shale"
						class="enlarge-image">Dry shale gas production estimates by play</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">June 11, 2024</span></li>
				<li>Estimated monthly production derived from state administrative data</li>
				<li class="release-schedule">Monthly</span></li>
				<li class="hide-bullet"><span class="formats">Available formats:</span> <a
						href="/outlooks/steo/xls/Fig43.xlsx"><span class="ico xls"
							title="Dry shale gas production estimates by play"> <span>XLS</span></span></a></li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_wells_s1_a.htm">Number of producing gas wells</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and state level data</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_oilwells_s1_a.htm">Number of gas producing oil wells</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and state level data</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_whv_dcu_nus_a.htm">Wellhead value &amp; marketed
						production</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and state level natural gas wellhead values and prices of marketed production</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_off_s1_a.htm">Offshore gross withdrawals</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S., state, and Gulf of America gross withdrawals from oil and gas wells</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_ss_a_EPG0_ovi_mmcf_a.htm">Supplemental supplies</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and State supplies of synthetic natural gas, biomass, refinery gas, propane-air, etc.</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_pp_a_EPG0_ygp_mmcf_a.htm">Natural gas plant processing</a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and state level statistics for natural gas processed, total liquids extracted, extraction loss.
				</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a
						href="/cfapps/ngqs/ngqs.php?f_report=RP9&amp;f_sortby=&amp;f_items=&amp;f_year_start=&amp;f_year_end=&amp;f_show_compid=&amp;f_fullscreen">Plant-level
						location and capacity</a></li>
				<li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">January 31, 2019 </span></li>
				<li>Plant-level location and capacity information for all natural gas processing plants in the United
					States.</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_deep_s1_a.htm">Gulf of America Federal Offshore production</a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>Production of crude oil, natural gas wet after lease separation, natural gas liquids, dry natural
					gas, and lease condensate</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_ngpl_s1_a.htm">Natural gas plant liquids production</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>Production by U.S., region, and state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_prod_lc_s1_a.htm">Lease condensate production</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>Production by U.S., region, and state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head">Unconventional dry natural gas production</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 30, 2022</span></li>
				<li>
					<ul>
						<li> <a href="/dnav/ng/ng_prod_coalbed_s1_a.htm" title="Unconventional">Coalbed methane</a></li>
						<li> <a href="/dnav/ng/ng_prod_shalegas_s1_a.htm" class="no-border" title="Unconventional">Shale
								gas</a></li>
					</ul>
				</li>
			</ul>
			<ul>
				<li class="head"><a href="/naturalgas/fieldcode/">Oil and gas field code master list</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/fieldcode/includes/releasedate.inc') ?>
					</span></li>
				<li>Comprehensive listing of U.S. oil and gas field names.</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/petroleum/wells/">Distribution and production of oil &amp; gas wells</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">December 20, 2019</span></li>
				<li> Yearly estimates of the number of U.S. producing oil and natural gas wells, which are grouped into
					26 production volume brackets ranging from less than 1 BOE/day to more than 12,800 BOE/day.</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a
						href="/cfapps/ngqs/ngqs.php?f_report=RP2&amp;f_sortby=ICA&amp;f_items=0110VL,0120VL,0210VL,0220VL,0230VL,0300VL,0400VL,0500VL,0600VL,0700VL,0800VL,&amp;f_year_start=2009&amp;f_year_end=2012&amp;f_show_compid=Name&amp;f_fullscreen=">Production
						by company</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Annual production volumes from data collected on Form EIA-176 (Annual Report of Natural and
					Supplemental Gas Supply and Disposition)</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/petroleum/production/">Monthly Crude Oil and Natural Gas Production</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('petroleum/production/includes/releasedate.inc') ?>
					</span></li>
				<li>Monthly crude oil and natural gas production data collected on Form EIA-914 (Monthly Crude Oil,
					Lease Condensate, and Natural Gas Production Report)</li>
				<li class="release-schedule">Monthly</li>
			</ul>
		</div>
		<h3><a name="imports"></a>Imports/exports</h3>
		<div class="accordion-content">
			<ul>
				<li class="head"><a href="/dnav/ng/ng_move_impc_s1_m.htm">U.S. imports by country</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Prices and volumes</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_move_expc_s1_m.htm">U.S. exports by country</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Prices and volumes</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_move_state_a_EPG0_IM0_Mmcf_a.htm">U.S. imports &amp; exports by
						state</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Prices and volumes</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_move_poe1_a_EPG0_IRP_Mmcf_a.htm">U.S. imports by point of
						entry</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Prices and volumes</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_move_poe2_a_EPG0_ENP_Mmcf_a.htm">U.S. exports by point of exit</a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Prices and volumes</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_move_ist_a2dcu_nus_a.htm">U.S. international &amp; interstate
						movements of natural gas by state</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Includes International and Interstate receipts, deliveries and net receipts by state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a
						href="/beta/international/data/browser/#/?pa=0000000000001&c=ruvvvvvfvtvnvv1urvvvvfvvvvvvfvvvou20evvvvvvvvvnvvuvo&ct=0&tl_id=3002-A&vs=INTL.26-3-AFG-BCF.A&vo=0&v=H&start=1980&end=2017">International
						imports data</a></li>
				<li>Imports by country, region and country groups</li>
			</ul>
			<ul>
				<li class="head"><a
						href="/beta/international/data/browser/#/?pa=000000000000000001&c=ruvvvvvfvtvnvv1urvvvvfvvvvvvfvvvou20evvvvvvvvvnvvuvo&ct=0&tl_id=3002-A&vs=INTL.26-4-AFG-BCF.A&vo=0&v=H&start=1980&end=2017">International
						exports data</a></li>
				<li>Exports by country, region and country groups</li>
			</ul>


			<ul>
				<li class="head"><a name="liquefaction_capy">U.S. liquefaction capacity</a></li>
				<li>Detailed information on the size and location of U.S. LNG export projects (existing, under
					construction, and approved)</li>


				<li>
					<br>
					<div class="form-container do-not-print" style="width: 50%">
						<fieldset>
							<legend>Releases</legend>
							<div class="dropdown-container no-js">
								<div class="dropdown-button">
									<span class="text">Select one</span>
									<span class="ico d-arrow"><span>dropdown arrow</span></span>
								</div>
								<div class="dropdown-menu">
									<ul>
									<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2026_Q1.xlsx">1Q
												2026 (release date 4/1/2026)</a></li>
									<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2025_Q4.xlsx">4Q
												2025 (release date 12/30/2025)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2025_Q3.xlsx">3Q
												2025 (release date 10/1/2025)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2025_Q2.xlsx">2Q
												2025 (release date 6/30/2025)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2025_Q1.xlsx">1Q
												2025 (release date 3/31/2025)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2024_Q4.xlsx">4Q
												2024 (release date 1/2/2025)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2024_3Q.xlsx">3Q
												2024 (release date 9/30/2024)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2024_2Q.xlsx">2Q
												2024 (release date 6/27/2024)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2024_1Q.xlsx">1Q
												2024 (release date 3/29/2024)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2023_4Q.xlsx">4Q
												2023 (release date 12/28/2023)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2023_3Q.xlsx">3Q
												2023 (release date 10/16/2023)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2023_2Q.xlsx">2Q
												2023 (release date 6/29/2023)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2023_1Q.xlsx">1Q
												2023 (release date 4/17/2023)</a></li>

										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2022_4Q.xlsx">4Q
												2022 (release date 12/29/2022)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2022_3Q.xlsx">3Q
												2022 (release date 8/22/2022)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2022_2Q.xlsx">2Q
												2022 (release date 6/8/2022)</a></li>

										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2021_4Q.xlsx">4Q
												2021 (release date 12/8/2021)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2021_3Q.xlsx">3Q
												2021 (release date 7/15/2021)</a></li>

										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2020_4Q.xlsx">4Q
												2020 (release date 11/3/2020)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2020_2Q.xlsx">2Q
												2020 (release date 4/21/2020)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2020_1Q.xlsx">1Q
												2020 (release date 1/30/2020)</a></li>

										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2019_4Q.xlsx">4Q
												2019 (release date 12/2/2019)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2019_2Q.xlsx">2Q
												2019 (release date 6/26/2019)</a></li>
										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2019_1Q.xlsx">1Q
												2019 (release date 4/1/2019)</a></li>

										<li class="ico xls"><a
												href="/naturalgas/importsexports/liquefactioncapacity/U.S.liquefactioncapacity_2018_4Q.xlsx">4Q
												2018 (release date 12/13/2018)</a></li>



									</ul>
								</div>
							</div>
						</fieldset>
					</div>
					<br>
					<br>
					<br>
					<br>
				</li>
			</ul>


		</div>
		<h3><a name="pipelines"></a>Pipelines</h3>
		<div class="accordion-content">
			<ul>
				<li class="head"><a href="/naturalgas/archive/analysis_publications/ngpipeline/index.html">About U.S.
						pipelines</a></li>
				<li>Detailed information and maps showing pipelines, capacities, flows and network design,
					transportation corridors, and other relevant information for U.S. pipelines in the lower 48 states.
				</li>
			</ul>
			<ul>
				<li class="head">U.S. state-to-state capacity</li>
				<li>Information on capacity of existing natural gas pipelines crossing between states, international
					borders, and offshore Gulf of America.</li>

				<li>
					<br>
					<div class="form-container do-not-print" style="width: 50%">
						<fieldset>
							<legend>Releases</legend>
							<div class="dropdown-container no-js">
								<div class="dropdown-button">
									<span class="text">Select one</span>
									<span class="ico d-arrow"><span>dropdown arrow</span></span>
								</div>
								<div class="dropdown-menu">
									<ul>
									    <li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_Jan2026.xlsx">January
												2026</a></li>
									    <li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_Jan2025.xlsx">January
												2025</a></li>
									   <li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_Feb2024.xlsx">February
												2024</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_Jan2023.xlsx">January
												2023</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_Jan2022.xlsx">January
												2022</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_Jan2021.xlsx">January
												2021</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_Jan2020.xlsx">January
												2020</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_Jan2019.xlsx">January
												2019</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-StatetoStateCapacity_May2018.xlsx">May
												2018</a></li>
									</ul>
								</div>
							</div>
						</fieldset>
					</div>
					<br>
					<br>
					<br>
					<br>
				</li>
			</ul>

			<ul>
				<li class="head">Pipeline projects</li>
				<li>Detailed information on the size and location of pipeline projects announced or under construction.
				</li>

				<li>
					<br>
					<div class="form-container do-not-print" style="width: 50%">
						<fieldset>
							<legend>Releases</legend>
							<div class="dropdown-container no-js">
								<div class="dropdown-button">
									<span class="text">Select one</span>
									<span class="ico d-arrow"><span>dropdown arrow</span></span>
								</div>
								<div class="dropdown-menu">
									<ul>


									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_May2026.xlsx">May 2026</a></li>

									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jan2026.xlsx">January 2026</a></li>

									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Oct2025.xlsx">October 2025</a></li>
									
									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jul2025.xlsx">July 2025</a></li>
									
									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Apr2025.xlsx">April 2025</a></li>
									
									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jan2025.xlsx">January 2025</a></li>
									
									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Oct2024.xlsx">October 2024</a></li>
									
									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jul2024.xlsx">July 2024</a></li>
									
									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Apr2024.xlsx">April 2024</a></li>											
									<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jan2024.xlsx">January
												2024</a></li>									
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Oct2023.xlsx">October
												2023</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jul2023.xlsx">July
												2023</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Apr2023.xlsx">April
												2023</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jan2023.xlsx">January
												2023</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Oct2022.xlsx">October
												2022</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jan2022.xlsx">January
												2022</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Oct2021.xlsx">October
												2021</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jul2021.xlsx">July
												2021</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jan2021.xlsx">January
												2021</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_March2020.xlsx">March
												2020</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jan2020.xlsx">January
												2020</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Oct2019.xlsx">October
												2019</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_July2019.xlsx">July
												2019</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_May2019.xlsx">May
												2019</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Jan2019.xlsx">January
												2019</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_Aug2018.xlsx">August
												2018</a></li>
										<li class="ico xls"><a
												href="/naturalgas/pipelines/EIA-NaturalGasPipelineProjects_May2018.xlsx">May
												2018</a></li>
									</ul>
								</div>
							</div>
						</fieldset>
					</div>
					<br>
					<br>
					<br>
					<br>
				</li>
			</ul>

			<ul>
		</div>
		<h3><a name="storage"></a>Storage</h3>
		<div class="accordion-content">
			<ul>
				<li class="head"><a href="/dnav/ng/ng_stor_wkly_s1_w.htm">Weekly working gas in underground storage </a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release Date:</span> <span class="date">
						<?php include('naturalgas/includes/releasedate_wngsr.inc') ?>
					</span></li>
				<li>U.S. natural gas inventories held in underground storage facilities</li>
				<li class="release-schedule">Weekly</span></li>
				<li class="list-item">
					<ul>
						<li> <a href="/dnav/ng/ng_stor_wkly_s2_w.htm">Underground storage East, West, and Producing
								regions</a></li>
						<li>(historical data 12/31/1993 - 11/06/2015)</li>
					</ul>
				</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_stor_sum_a_EPG0_sat_mmcf_m.htm">Underground storage &mdash; all
						operators</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Total storage by base gas and working gas, and storage activity by state</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_stor_type_s1_m.htm">Underground storage by type</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. storage and storage activity by all operators, salt cavern fields and nonsalt cavern</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_stor_cap_a_EPG0_SAC_Mmcf_a.htm">Underground storage capacity</a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Storage capacity, working gas capacity, and number of active fields for salt caverns, aquifers, and
					depleted fields by state</li>
				<li class="release-schedule">Monthly, annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_stor_lng_a_EPG0_SAL_MMcf_a.htm">Liquefied natural gas additions to
						and withdrawals from storage</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>By state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/naturalgas/storagecapacity/">Underground natural gas working storage
						capacity</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">May 21, 2026</span></li>
				<li>This report provides estimates of aggregate peak working gas capacity and working gas design
					capacity for the U.S. underground natural gas storage as of November of the previous year.</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a
						href="/cfapps/ngqs/ngqs.php?f_report=RP7&amp;f_sortby=&amp;f_items=&amp;f_year_start=&amp;f_year_end=&amp;f_show_compid=&amp;f_fullscreen">U.S.
						field level storage data</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/annual/includes/releasedate.inc') ?>
					</span></li>
				<li>Annual field-level storage capacity and field-type data for all underground storage fields in the
					United States.</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head">Planned storage projects</li>
				<li>Detailed information on the size and location of underground storage facilities announced or under
					construction.</li>
				<li class="hide-bullet"><span class="formats">Available formats:</span> <a
						href="/naturalgas/storage/EIA-StoragePlan.xlsx"><span class="ico xls"
							title="Planned storage projects"><span>XLS</span></span></a></li>
			</ul>
			<ul>
				<li class="head"><a href="https://ir.eia.gov/ngs/ngs.html">Weekly Natural Gas Storage Report</a></li>
				<li class="hide-bullet"><span class="release-date">Thursday 10:30 a.m. EST</span></li>
				<li>Working gas in underground storage for current week and week ago comparison.</li>
			</ul>
			<ul>
				<li class="head"><a href="/naturalgas/weekly/supplement/">Weekly Natural Gas Storage Report Supplement</a>
				<li class="hide-bullet"><span class="release-date">Release Date:</span> <span class="date">
						<?php include('naturalgas/includes/releasedate_wngsr.inc') ?>
					</span></li>
				<li>
				Companion publication to the <em>Weekly Natural Gas Storage Report</em> (WNGSR) and provides key highlights of the natural gas sector. 
				
				</li>
			</ul>
		</div>
		<h3><a name="consumption"></a>Consumption</h3>
		<div class="accordion-content">
			<ul>
				<li class="head"><a href="/dnav/ng/ng_cons_sum_dcu_nus_m.htm">Total consumption</a></li>
				<li class="hide-bullet"><span class="release-date">Monthly release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li class="hide-bullet"><span class="release-date">Annual release date:</span> <span class="date">
						<?php include('naturalgas/annual/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and State total consumption by lease and plant, pipeline, and end use consumers by sector</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_cons_sum_a_EPG0_vgt_mmcf_m.htm">Delivered to consumers</a></li>
				<li class="hide-bullet"><span class="release-date">Monthly release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li class="hide-bullet"><span class="release-date">Annual release date:</span> <span class="date">
						<?php include('naturalgas/annual/includes/releasedate.inc') ?>
					</span></li>
				<li>U.S. and State volumes delivered to end use consumers by sector</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_cons_num_a_EPG0_VN3_Count_a.htm">Number of consumers</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Number of sales and transported consumers for residential, commercial, and industrial sectors by
					state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_cons_pns_a_EPG0_VRP_pct_a.htm">State shares of U.S. deliveries</a>
				</li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>By sector and total consumption</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_cons_acct_a_EPG0_VF8_mmcf_a.htm">Delivered for the account of
						others</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Commercial, industrial and electric utility deliveries; percentage of total deliveries by state</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/dnav/ng/ng_cons_heat_a_EPG0_VGTH_btucf_a.htm">Heat content of natural gas
						consumed</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/monthly/includes/releasedate.inc') ?>
					</span></li>
				<li>Btu per cubic foot of natural gas delivered to consumers by state and other components of
					consumption for U.S.</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a
						href="/cfapps/ngqs/ngqs.php?f_report=RP1&amp;CFID=3671337&amp;CFTOKEN=adecb824a353d3ce-2B0A52F6-237D-DA68-24A4616E47171EC2">Company-level
						supply and disposition</a></li>
				<li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
						<?php include('naturalgas/annual/includes/releasedate.inc') ?>
					</span></li>
				<li>Annual company-level supply and disposition data for all natural gas local distribution companies in
					the United States.</li>
				<li class="release-schedule">Annual</li>
			</ul>
			<ul>
				<li class="head"><a href="/cfapps/ipdbproject/IEDIndex3.php?tid=3&amp;pid=26&amp;aid=2">International
						natural gas consumption</a></li>
				<li>Dry natural gas consumption, by country, region, and country groups</li>
				<li><a href="/beta/international/data/browser/">International Energy Statistics</a>
				<li class="release-schedule">Annual</li>
			</ul>
		</div>
	</div>
</div>
