<h1><a name="blog" id="blog"></a>RECS Status</h1>
 
 <!------start blog here---------->
 
 
 <div class="white_box blue_top">
  <p class="date">November 2, 2017
  <h2>More 2015 RECS estimates and reports now available!</h2>

<p> Square footage and household energy insecurity data from the 2015 RECS are <a href="/consumption/residential/data/2015/">now available</a>. Along with new tables displaying total and average square footage in homes, EIA published a <a href="/consumption/residential/reports/2015/squarefootage/">comprehensive methodology report</a> on square footage estimation for the 2015 RECS. </p> 

<p>Also included with this release was a short analysis piece that examines <a href="/consumption/residential/reports/2015/energybills/">energy insecurity</a> as measured by the RECS. The report focuses on the questions on the RECS which ask if respondents have had difficulty paying energy bills, received a disconnect notice, or faced other energy-related challenges in their home.</p>

<p>An updated microdata file, including square footage and energy insecurity variables, has been posted to the <a href="/consumption/residential/data/2015/index.php?view=microdata">2015 RECS microdata page</a>.</p> 

<p>Estimates of energy consumption and expenditures are currently in production and are expected to be available in Spring 2018.
</p>	
	</div>
  &nbsp;
 
 
 
 <div class="white_box blue_top">
  <p class="date">October 12, 2017
  <h2 class="toggle" >Recording of the 2015 RECS Webinar held Sept. 19 now available</h2>
<div class="more">
<p> <a href="https://www.youtube.com/watch?v=R6XvepTv6YY&feature=youtu.be">View the webinar recording
</a></p>  
<p> <a href="/consumption/residential/status/ppt/2015_hcwebinar.pptx" class="ico_ppt">PowerPoint: RECS Webinar Sept 19</a></p>
    <p>EIA’s Office of Energy Consumption and Efficiency Statistics held a webinar reviewing housing characteristics data from the 2015 Residential Energy Consumption Survey (RECS) on September 19, 2017. Learn more about accessing the RECS data, new methods used for the 2015 RECS survey, and how changing modes of data collection can affect future cycles of the RECS survey. The recording of the webinar includes a Q&A session with RECS Survey Manager Chip Berry and members of the RECS team.</p>	
	</div> </div>
  &nbsp;
  
  <div class="white_box blue_top">
  <p class="date">August 29, 2017</span>
  <h2 class="toggle">2015 RECS Webinar: September 19</h2>
  <div class="more">
  <p><b>UPDATE: </b>The RECS webinar was held on September 19. A recording of the event will be available soon. </p>

    <p>Join EIA’s Office of Energy Consumption and Efficiency Statistics for a webinar reviewing housing characteristics data from the 2015 Residential Energy Consumption Survey (RECS). Learn more about accessing the data, new methods used for the 2015 survey, and how changing modes can shape the RECS in future survey cycles. The webinar will conclude with a Q&A with RECS Survey Manager Chip Berry and members of the RECS team.</p>
	
	</div></div>
  &nbsp;
  
  <div class="white_box blue_top">
  <p class="date">June 2, 2017</span>
  <h2 class="toggle" >Microdata from the 2015 RECS are now available</h2>
   <div class="more">
    <p>The preliminary public use microdata file for 2015 RECS is <a href="/consumption/residential/data/2015/">now available</a>. The file contains records of survey responses from more than 5,600 households, including information on household energy characteristics and appliance usage behaviors. In addition to the data file, a codebook, and information on working with the RECS microdata can be found on the <a href="/consumption/residential/data/2015/">2015 RECS microdata page</a>. 

<p>EIA also published a new report, <a href="/consumption/residential/reports/2015/overview/">What’s new in how we use energy at home: Results from EIA’s 2015 Residential Energy Consumption Survey (RECS)</a>, which looks at highlights from the 2015 RECS data.</p>

<p>Square footage data from the 2015 RECS are expected to be available this summer. Estimates of energy consumption and expenditures are currently in production and are expected to be available in 2018.</p></div></div>
  &nbsp;
 <div class="white_box blue_top">
  <p class="date">February 27, 2017</span>
  <h2 class="toggle">Data from the 2015 RECS now available!</h2>
  <div class="more">
  <p>The <a href="/consumption/residential/data/2015/">housing  characteristics data tables</a> from the 2015 RECS are now available. The topics  covered are: Fuels used and end uses; Structural and geographic  characteristics; Space heating; Lighting; Appliances; Electronics; Air  conditioning; Water heating; and Household demographics.</p>
 <p >EIA expects to release an overview of the 2015 data,  methodology report, and preliminary public use microdata file in April 2017. Square  footage data are anticipated in summer 2017. Estimates of household energy consumption and expenditures are expected to  be ready in 2018.</p>
  
  <p>For  notifications on new products from the RECS, consider signing up for our  listserv. Visit <a href="/tools/emailupdates/">EIA's Email Updates</a> page and  select the "Energy Users" list at the bottom of the page</p>
  </div></div>
  &nbsp;
<div class="white_box blue_top">
  <p class="date">January 17, 2017</span>
  <h2 class="toggle">2015 RECS data coming soon</h2>
  <div class="more">
  <p>The initial stage of data collection  for the 2015 RECS —the Household Survey&#8212;has been completed and EIA is  working to process the data. The housing characteristics data are expected to  be released as follows:</p>
<h3>Anticipated release schedule for housing characteristics data</h3>
<table class="simpletable">
  <tr>
    <td width="526">Data tables: Fuels used and end uses; Structural and  geographic characteristics; Space heating; Lighting; Appliances; Electronics;  Air conditioning; Water heating; and Household demographics</td>
    <td width="160">February 2017</td>
  </tr>
    <tr>
    <td>Overview, methodology, and preliminary public use microdata</td>
    <td>April 2017</td>
  </tr>
    <tr>
      <td>Square footage data tables and microdata </td>
      <td>June 2017</td>
    </tr>
 
</table>
<p>The second stage of data collection—the Energy Supplier Survey (ESS)—is currently underway. After completion of the ESS, EIA will begin the End Use Modeling process to produce the estimates of household energy consumption and expenditures. These data are expected to be ready in 2018. </p>
</div></div></p>

<!-- 
  &nbsp;     
   <div class="white_box blue_top">
  <p class="date">To be published: mid-January</span>
  <h2 class="toggle" >Join us for a webinar introducing the 2015 RECS data </h2>
  <p >EIA will be hosting a webinar on February XX, 2017, at XXX p.m.  concurrent with the release of the data from the 2015 RECS. We will share  highlights from the initial data release and describe changes to the survey  methodology. </p>
  <p>To sign up, please visit: [link]</p></div>
  &nbsp;    
          <div class="white_box blue_top">
            <p class="date">To be published: when the first group of tables is published (mid Feb)</span> </p>
            <h2 class="toggle" >First data from the 2015 RECS now available</h2>
            <p >The first group of housing characteristics tables from the  2015 RECS are now available. The tables, and the accompanying overview  report, cover  these topics: Fuels used and end  uses; Structural and geographic characteristics; Space heating; and Lighting. </p>
<p>EIA will be hosting  a webinar on February XX, 2017, at XXX p.m to share highlights from the 2015  RECS and describe changes to the survey methodology. To sign up for the webinar,  please visit: [link]</p>
<p>The remaining housing characteristics tables will be published in  two groups. In April, the Appliances;  Electronics; Air conditioning; Water heating; and Household demographics data  will be released. The square footage data tables and a preliminary public use  microdata file will be released in June 2017. </p>
<div>
          <div> </div>
              <div> </div>
            </div>
          </div>-->
          <hr />
          
          <?php /*h3>Other Items</h3>
          <p><a href="/emeu/recs/census_map.html">Census 
            Map</a><br />
            <a href="/emeu/recs/climate_zone.html">US 
            Climate Zones</a></p*/ ?> 
          <?php /*h3>Special Topics - <a href="/consumption/residential/reports.cfm">Move to A&amp;P</a></h3>
          <h2><a name="st2004" id="st2004"></a>2004</h2>
          <p><a href="/emeu/recs/recs2001/insulation/insulation.html">Insulation</a> (2004)</p>
          <h2><a name="st2003" id="st2003"></a>2003</h2>
          <p><a href="/emeu/recs/ceilingfans/ceiling_fan.html">Ceiling Fans</a> (2003)</p>
          <h2><a name="st2001" id="st2001"></a>2001</h2>
          <p><a href="/emeu/recs/sqft-measure.html">Housing Unit Size</a> (2001)<br />
            <a href="/emeu/recs/fax-copiers-compare.html">Fax/Copier</a> (2001)<br />
            <a href="/emeu/recs/appliances/appliances.html">Appliances</a> (2001) <br />
            <a href="/emeu/consumptionbriefs/recs/heating_oil/heating_oil.html">Heating Oil</a> (2001)<br />
            <a href="/emeu/consumptionbriefs/recs/natgas/nat_gas_piece.html">Natural Gas</a> (2001) <br />
            <a href="/emeu/recs/cookingtrends/cooking.html">Cooking Trends</a> (2001) </p>
          <h2><a name="st2000" id="st2000"></a>2000</h2>
          <p><a href="/emeu/recs/recs97/recs022900.html">Fuel Oil Trends</a> (2000)<br />
            <a href="/emeu/consumptionbriefs/recs/thermostat_settings/thermostat.html">Thermostat Settings</a> (2000)<br />
            <a href="/emeu/consumptionbriefs/recs/actrends/recs_ac_trends.html">Air Conditioning Trends</a> (2000) </p>
          <h2><a name="st1997" id="st1997"></a>1997</h2>
          <p><a href="/emeu/recs/recs97/trends.html">Trend Analysis</a> (1997)<br />
            <a href="/emeu/recs/recs97_additions/recs_changes.html">Household Members and Buildings</a> (1997) <br />
            <a href="/emeu/recs/origin/origin_householder.html">Origin of Householder</a> (1997) <br />
            <a href="/emeu/consumptionbriefs/recs/aircond_use.html">Air Conditioning Facts</a> (1997) </p>
          <h2><a name="st1995" id="st1995"></a>1995</h2>
          <p><a href="/emeu/cbecs/lit-type.html">Lighting</a> (1995 CBECS) </p*/ ?> 
          
</div>