<span class="condaterange">
              <h2>Consumption &amp; Expenditure Tables</h2>
              <a class="no-border expandall">+ EXPAND ALL</a></span>
              <table class="contable">
                <thead id="Total">
                  <tr>
                    <th width="442"><a name="Total"></a><b>Total Energy Consumption in U.S. Households</b></th>
                    <th width="127"><a href="pdf/2001ce_tables/enduse_consump2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-1c_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-2c_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-3c_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-4c_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-7c_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-8c_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-9c_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-10c_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-11c_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-12c_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Expenditures</td>
                  <td><a href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/enduse_expend2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-1e_climate2001.pdf" class="ico_pdf">PDF</a></td>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-2e_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-3e_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-4e_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-7e_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-8e_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-9e_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-10e_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-11e_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-12e_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Consumption and Expenditures</td>
                  <td></td>
                </tr>
                <tr>
                  <td>Household Member and Demographics</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-51u_hhmem_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Household Demographics</td>
                  <td><a  href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-52u_sqft_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Member and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-61u_hhmem_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/enduse/ce1-62u_sqft_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="Space">
                  <tr>
                    <th><a name="Space"></a><b>Space Heating in U.S. Households</b></th>
                    <th><a href="pdf/2001ce_tables/spaceheat_consump2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Consumption</td>
                  <td><a href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/spaceheat_consump2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-1c_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-2c_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-3c_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-4c_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-7c_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-8c_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-9c_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-10c_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-11c_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-12c_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Expenditures</td>
                  <td><a href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/spaceheat_expend2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-1e_climate2001.pdf" class="ico_pdf">PDF</a></td>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-2e_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-3e_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-4e_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-7e_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-8e_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-9e_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-10e_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-11e_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-12e_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Consumption and Expenditures</td>
                  <td></td>
                </tr>
                <tr>
                  <td>Household Member and Demographics</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-51u_hhmem_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Household Demographics</td>
                  <td><a  href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-52u_sqft_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Member and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-61u_hhmem_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/spaceheat/ce2-62u_sqft_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="Air">
                  <tr>
                    <th><a name="Air"></a><b>Air Conditioning in U.S. Households</b></th>
                    <th><a href="pdf/2001ce_tables/ac_consump2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Consumption</td>
                  <td><a href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/ac_consump2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-1c_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-2c_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-3c_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-4c_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-7c_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-8c_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-9c_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-10c_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-11c_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-12c_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Expenditures</td>
                  <td><a  href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/ac_expend2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-1e_climate2001.pdf" class="ico_pdf">PDF</a></td>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-2e_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-3e_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-4e_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-7e_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-8e_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-9e_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-10e_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-11e_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-12e_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Consumption and Expenditures</td>
                  <td></td>
                </tr>
                <tr>
                  <td>Household Member and Demographics</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-51u_hhmem_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Household Demographics</td>
                  <td><a  href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-52u_sqft_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Member and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-61u_hhmem_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/aircondition/ce3-62u_sqft_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="Water">
                  <tr>
                    <th><a name="Water"></a><b>Water Heating in U.S. Households</b></th>
                    <th><a href="pdf/2001ce_tables/waterheat_consump2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Consumption</td>
                  <td><a href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/waterheat_consump2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-1c_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-2c_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-3c_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-4c_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-7c_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-8c_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-9c_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-10c_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-11c_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-12c_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Expenditures</td>
                  <td><a href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/waterheat_expend2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-1e_climate2001.pdf" class="ico_pdf">PDF</a></td>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-2e_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-3e_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-4e_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-7e_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-8e_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-9e_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-10e_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-11e_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-12e_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Consumption and Expenditures</td>
                  <td></td>
                </tr>
                <tr>
                  <td>Household Member and Demographics</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-51u_hhmem_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Household Demographics</td>
                  <td><a  href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-52u_sqft_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Member and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-61u_hhmem_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/waterheat/ce4-62u_sqft_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="Appliances">
                  <tr>
                    <th><a name="Appliances"></a><b>Appliances, in U.S. Households</b></th>
                    <th><a href="pdf/2001ce_tables/appl_consump2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Consumption</td>
                  <td><a href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/appl_consump2001.pdf"  class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-1c_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-2c_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-3c_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-4c_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-7c_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-8c_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-9c_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-10c_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-11c_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-12c_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Expenditures</td>
                  <td><a  href="ftp://ftp.eia.doe.gov/pub/consumption/residential/2001ce_tables/appl_expend2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-1e_climate2001.pdf" class="ico_pdf">PDF</a></td>
                <tr>
                  <td>Year of Construction A3</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-2e_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-3e_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-4e_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-7e_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-8e_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-9e_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-10e_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-11e_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-12e_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr class="summary">
                  <td>Consumption and Expenditures</td>
                  <td></td>
                </tr>
                <tr>
                  <td>Household Member and Demographics</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-51u_hhmem_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Household Demographics</td>
                  <td><a  href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-52u_sqft_demo2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Member and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-61u_hhmem_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Square Feet and Usage Indicators</td>
                  <td><a href="/consumption/residential/data/2001/pdf/ce/appliances/ce5-62u_sqft_useind2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="">
                  <tr>
                    <th><a name=""></a><b>Fuel Use, in U.S. Households</b></th>
                    <th width="25%">&nbsp;</th>
                  </tr>
                </thead>
                <tr>
                  <td>Table 1. Natural Gas Consumption and Expenditures in U.S. Households by End Uses and Census Region</td>
                  <td><a href="/emeu/recs/byfuels/2001/byfuel_ng.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Table 2. Fuel Oil Consumption and Expenditures in U.S. Households by End Uses and Census Region</td>
                  <td><a href="/emeu/recs/byfuels/2001/byfuel_fo.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <!--<tr>
                  <td>Table 2. Fuel Oil Consumption and Expenditures in U.S. Households by End Uses and Census Region</td>
                  <td><a href="/emeu/recs/byfuels/2001/byfuel_fo.pdf" class="ico_pdf">PDF</a></td>
                </tr> -->
                <tr>
                  <td>Table 3. Electricity Consumption and Expenditures in U.S. Households by End Uses and Census Region</td>
                  <td><a href="/emeu/recs/byfuels/2001/byfuel_el.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Table 4. LPG Consumption and Expenditures in U.S. Households by End Uses and Census Region</td>
                  <td><a href="/emeu/recs/byfuels/2001/byfuel_lpg.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Table 5. Kerosene Consumption and Expenditures in U.S. Households by End Uses and Census Region</td>
                  <td><a href="/emeu/recs/byfuels/2001/byfuel_kr.pdf" class="ico_pdf">PDF</a></td>
                </tr>
              </table>
              <h3>End-Use Consumption of Electricity 2001</h3>
              <p> Electricity is consumed for a wide variety of uses in the home. This web product presents a detailed account of the amount of electricity used to operate numerous appliances in 2001.</p>
              <p>Similar analyses were conducted for the 1987, 1990, 1993, and 1997 RECS. Table 1 summarizes the results.</p>
              <table class="zebra" width="100%">
                <thead id="end-use">
                  <tr>
                    <th colspan="6"><a name="end-use"></a><b><strong>Table 1. Percent of Electricity Consumption by End Use</strong></b></th>
                  </tr>
                </thead>
                <tr>
                  <td colspan="6"><div align="center"><strong>Survey Year</strong></div></td>
                </tr>
                <tr>
                  <td width="30%"><div><strong>End Use</strong></div></td>
                  <td width="22%"><div align="center"><strong>1987</strong></div></td>
                  <td width="12%"><div align="center"><strong>1990</strong></div></td>
                  <td width="12%"><div align="center"><strong>1993</strong></div></td>
                  <td width="12%"><div align="center"><strong>1997</strong></div></td>
                  <td width="12%"><div align="center"><strong>2001</strong></div></td>
                </tr>
                <tr>
                  <td><div><strong>Air-Conditioning</strong></div></td>
                  <td><div align="center">15.8</div></td>
                  <td><div align="center">15.9</div></td>
                  <td><div align="center">13.9</div></td>
                  <td><div align="center">11.8</div></td>
                  <td><div align="center">16.0</div></td>
                </tr>
                <tr>
                  <td><div><strong>Space Heating</strong></div></td>
                  <td><div align="center">10.3</div></td>
                  <td><div align="center">10.0</div></td>
                  <td><div align="center">12.4</div></td>
                  <td><div align="center">11.4</div></td>
                  <td><div align="center">10.1</div></td>
                </tr>
                <tr>
                  <td><div><strong>Water Heating</strong></div></td>
                  <td><div align="center">11.4</div></td>
                  <td><div align="center">11.2</div></td>
                  <td><div align="center">10.3</div></td>
                  <td><div align="center">11.0</div></td>
                  <td><div align="center"> 9.1</div></td>
                </tr>
                <tr>
                  <td><div><strong>Total Appliances</strong></div></td>
                  <td><div align="center">62.5</div></td>
                  <td><div align="center">63.0</div></td>
                  <td><div align="center">63.4</div></td>
                  <td><div align="center">65.9</div></td>
                  <td><div align="center">64.7</div></td>
                </tr>
              </table>
              <p>Summary Results for 2001 RECS:</p>
<ul>
                <li>The largest use of electricity in the average U.S. household was for appliances (including refrigerators and lights), which consume approximately two thirds of all the electricity used in the residential sector (<a href="http://www.eia.gov/emeu/recs/recs2001/enduse2001/figure1.html">Figure 1</a>, <a href="http://www.eia.gov/emeu/recs/recs2001/enduse2001/enduse2001.html#table2">Table 2</a>);</li>
                <li>Air-conditioning accounted for an estimated 16 percent, space heating 10 percent, and water heating 9 percent;</li>
                <li>No single appliance dominated the use of electricity. Refrigerators consumed the most electricity (14 percent of total electricity use for all purposes), followed by lighting (9 percent), clothes dryers (6 percent), freezers (3 percent), and color TV's (3 percent);</li>
                <li>The many other electrical appliances are grouped together and their total consumption is shown as &quot;All Others&quot; (Figure 1). Included are some appliances, such as VCR's that typically are found in almost all homes but use small amounts of electricity, as well as appliances that use large amounts of electricity but are found in relatively few homes, such as swimming pool pumps; </li>
                <li>&quot;Residual&quot; includes appliances for which RECS did not collect data (irons, hair dryers, electric blankets, power tools, and many more) and errors in the estimation procedure. </li>
              </ul>
              <table width="100%" class="zebra">
                <thead>
                  <tr>
                    <th colspan="7"><strong>T<strong>able 2. Residential Consumption of Electricity by End Use, 2001</strong></strong></th>
                  </tr>
                </thead>
                <tr>
                  <td></td>
                  <td colspan="6" align="left"><strong>Annual Consumption</strong></td>
                </tr>
                <tr>
                  <td><strong>End Use/Appliance </strong></td>
                  <td><strong>Households (millions)</strong></td>
                  <td><strong>Units (million)</strong></td>
                  <td><strong>kWh per unit</strong></td>
                  <td><strong>kWh per household </strong></td>
                  <td><strong>Total (billion kWh)</strong></td>
                  <td><strong>Percent</strong></td>
                </tr>
                <tr>
                  <td>Total Households</td>
                  <td>107.0</td>
                  <td></td>
                  <td></td>
                  <td>10,656</td>
                  <td>1,139.9</td>
                  <td>100.0</td>
                </tr>
                <tr>
                  <td>Refrigerators</td>
                  <td>106.8</td>
                  <td>126.0</td>
                  <td>1,239</td>
                  <td>1,462</td>
                  <td>156.1</td>
                  <td>13.7</td>
                </tr>
                <tr>
                  <td>Air-Conditioning</td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Central Air-Conditioners</td>
                  <td>57.5</td>
                  <td></td>
                  <td></td>
                  <td>2,796</td>
                  <td>160.6</td>
                  <td>14.1</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Room Air-Conditioners<sup>a</sup></td>
                  <td>23.3</td>
                  <td>38.2</td>
                  <td>580</td>
                  <td>950</td>
                  <td>22.2</td>
                  <td>1.9</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Total</td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>182.8</td>
                  <td>16.0</td>
                </tr>
                <tr>
                  <td>Space Heating
                  <td>&nbsp;</td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Main Space-Heating Systems
                  <td>30.9</td>
                  <td></td>
                  <td></td>
                  <td>3,524</td>
                  <td>109.0</td>
                  <td>9.6</td>
                </tr>
                <tr>
                  <td>Secondary Space-Heating Equipment<sup>b</sup></td>
                  <td>12.9</td>
                  <td></td>
                  <td></td>
                  <td>503</td>
                  <td>6.5</td>
                  <td>0.6</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Total
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>115.5</td>
                  <td>10.1</td>
                </tr>
                <tr>
                  <td>Water Heating</td>
                  <td>40.8</td>
                  <td></td>
                  <td></td>
                  <td>2,552</td>
                  <td>104.1</td>
                  <td>9.1</td>
                </tr>
                <tr>
                  <td>Lighting (indoor and outdoor)</td>
                  <td>107.0</td>
                  <td></td>
                  <td></td>
                  <td>940<sup>f</sup></td>
                  <td>100.5</td>
                  <td>8.8</td>
                </tr>
                <tr>
                  <td>Other Appliances (total of list below)</td>
                  <td>107.0</td>
                  <td></td>
                  <td></td>
                  <td>4,495</td>
                  <td>480.8</td>
                  <td>42.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Clothes Dryer</td>
                  <td>61.1</td>
                  <td></td>
                  <td></td>
                  <td>1,079</td>
                  <td>65.9</td>
                  <td>5.8</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Freezer</td>
                  <td>34.2</td>
                  <td>37.9</td>
                  <td div>1,&nbsp;039</td>
                  <td>1,150</td>
                  <td>39.3</td>
                  <td>3.5</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Furnace Fan</td>
                  <td>76.3</td>
                  <td></td>
                  <td>500<sup>g</sup></td>
                  <td></td>
                  <td>38.2</td>
                  <td>3.3</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Dishwasher</td>
                  <td>56.7</td>
                  <td></td>
                  <td></td>
                  <td>512<sup>l</sup></td>
                  <td>29.0</td>
                  <td>2.5</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Electric Range Top<sup>c</sup></td>
                  <td>59.7</td>
                  <td></td>
                  <td>536<sup>g</sup></td>
                  <td></td>
                  <td>32.0</td>
                  <td>2.8</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Electric Oven<sup>d</sup></td>
                  <td>47.8</td>
                  <td></td>
                  <td>440<sup>g</sup></td>
                  <td></td>
                  <td>21.0</td>
                  <td>1.8</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Microwave Oven</td>
                  <td>92.1</td>
                  <td></td>
                  <td>209<sup>g</sup></td>
                  <td></td>
                  <td>19.3</td>
                  <td>1.7</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Electric Toaster Oven</td>
                  <td>36.1</td>
                  <td></td>
                  <td div>50<sup>g</sup></td>
                  <td></td>
                  <td>1.8</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Coffee Makers<sup>e</sup></td>
                  <td>51.3</td>
                  <td></td>
                  <td div>116<sup>g</sup></td>
                  <td></td>
                  <td>6.0</td>
                  <td>0.5</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Color TV</td>
                  <td>105.8</td>
                  <td>242.6</td>
                  <td>137</td>
                  <td>313<sup>h</sup></td>
                  <td>33.1</td>
                  <td>2.9</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;VCR/DVD</td>
                  <td><div>
                    96.1</td>
                  <td><div>
                    161.9</td>
                  <td><div>
                    70<sup>h</sup></td>
                  <td>118</td>
                  <td><div>
                    11.3</td>
                  <td><div>
                    1.0</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Cable Boxes</td>
                  <td>24.4</td>
                  <td></td>
                  <td>120<sup>i</sup></td>
                  <td></td>
                  <td>2.9</td>
                  <td>0.3</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Satellite Dish</td>
                  <td>13.9</td>
                  <td></td>
                  <td>130<sup>i</sup></td>
                  <td></td>
                  <td>1.8</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Personal Computer (Desk Top)</td>
                  <td>54.2</td>
                  <td>65.8</td>
                  <td div>262<sup>j</sup></td>
                  <td>318</td>
                  <td>17.2</td>
                  <td>1.5</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Personal Computer (Lap Top)</td>
                  <td>14.2</td>
                  <td>16.6&nbsp;&nbsp;</td>
                  <td>77<sup>k</sup></td>
                  <td>90</td>
                  <td>1.3</td>
                  <td>0.1</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Printer with Fax/copier</td>
                  <td>12.6</td>
                  <td></td>
                  <td div>216<sup>g</sup></td>
                  <td></td>
                  <td>2.7</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Printer without Fax/copier</td>
                  <td>40.2</td>
                  <td></td>
                  <td div>45<sup>g</sup></td>
                  <td></td>
                  <td>1.8</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Pool Filter/pump</td>
                  <td>6.5</td>
                  <td></td>
                  <td div>1,500<sup>g</sup></td>
                  <td></td>
                  <td>9.8</td>
                  <td>0.9</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Pool/Hot Tub/Spa Heater</td>
                  <td>3.3</td>
                  <td></td>
                  <td>2,300<sup>g</sup></td>
                  <td></td>
                  <td>7.6</td>
                  <td>0.7</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Ceiling Fan</td>
                  <td>69.6</td>
                  <td>192.8</td>
                  <td>50<sup>g</sup></td>
                  <td>138</td>
                  <td>9.6</td>
                  <td>0.8</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Clothes Washer <sup>f</sup></td>
                  <td>84.1</td>
                  <td></td>
                  <td>120<sup>g,l</sup></td>
                  <td></td>
                  <td>10.1</td>
                  <td>0.9</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Waterbed Heater</td>
                  <td>5.5</td>
                  <td>6.4</td>
                  <td>900<sup>g</sup></td>
                  <td>1,035</td>
                  <td>5.7</td>
                  <td>0.5</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Well Water Pump</td>
                  <td>13.8</td>
                  <td></td>
                  <td>400<sup>g</sup></td>
                  <td></td>
                  <td>5.5</td>
                  <td>0.5</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Dehumidifier</td>
                  <td>12.1</td>
                  <td></td>
                  <td div>400<sup>g</sup></td>
                  <td></td>
                  <td>4.8</td>
                  <td>0.4</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Evaporator Cooler</td>
                  <td>2.7</td>
                  <td></td>
                  <td>1,183<sup>g</sup></td>
                  <td></td>
                  <td>3.2</td>
                  <td>0.3</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Compact Stereo System</td>
                  <td>36.5</td>
                  <td></td>
                  <td>81<sup>g</sup></td>
                  <td></td>
                  <td>3.0</td>
                  <td>0.3</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Component Stereo System</td>
                  <td>36.3</td>
                  <td></td>
                  <td>55<sup>g</sup></td>
                  <td></td>
                  <td>2.0</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Portable Stereo (Boom Box)</td>
                  <td>26.1</td>
                  <td></td>
                  <td>19<sup>g</sup></td>
                  <td></td>
                  <td>0.5</td>
                  <td>0.0</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Other Stereo System</td>
                  <td>3.1</td>
                  <td></td>
                  <td>55<sup>g</sup></td>
                  <td></td>
                  <td>0.2</td>
                  <td>0.0</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Large, Heated Aquarium</td>
                  <td>4.5</td>
                  <td></td>
                  <td>548<sup>g</sup></td>
                  <td></td>
                  <td>2.5</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Answering Machine</td>
                  <td>65.7</td>
                  <td></td>
                  <td>35<sup>g</sup></td>
                  <td></td>
                  <td>2.3</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Cordless Telephone</td>
                  <td>81.5</td>
                  <td></td>
                  <td>26<sup>g</sup></td>
                  <td></td>
                  <td>2.1</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Rechargeable Tools</td>
                  <td>47.7</td>
                  <td></td>
                  <td>43<sup>g</sup></td>
                  <td></td>
                  <td>2.1</td>
                  <td>0.2</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Humidifier</td>
                  <td>15.6</td>
                  <td></td>
                  <td>100<sup>g</sup></td>
                  <td></td>
                  <td>1.6</td>
                  <td>0.1</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Automobile Block/Engine/Battery Heater</td>
                  <td>2.3</td>
                  <td></td>
                  <td>200<sup>g</sup></td>
                  <td></td>
                  <td>0.5</td>
                  <td>0.0</td>
                </tr>
                <tr>
                  <td>&nbsp;&nbsp;Residual</td>
                  <td><p>107.0</td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>83.1</td>
                  <td>7.3</td>
                </tr>
                <tr>
                  <td colspan="7"><p>&nbsp;&nbsp;<sup>a</sup>2001 RECS reported 0.8 million households having both central air-conditioning and room/wall air-conditioners. These households were included in the count of 57.5 million households using central air-conditioning and they were excluded from the count of 23.3 million households with room/wall air-conditioners.<br />
                    &nbsp;&nbsp;<sup>b</sup>The 2001 RECS reported 2.8 million households having both electric main space-heating and electric secondary space-heating equipment. These households were included in the count of 30.9 million households using electric main space-heating and they were excluded from the count of 12.9 million households with electric secondary space-heating.<br />
                    &nbsp;&nbsp;<sup>c</sup>Households where most used range was electric and the household cooked more than one meal per week.<br />
                    &nbsp;&nbsp;<sup>d</sup>Households where most used oven was electric and the household used oven more than once per week.<br />
                    &nbsp;&nbsp;<sup>e</sup>Households that used the coffee maker more than once per week.<br />
                    &nbsp;&nbsp;<sup>f</sup>1993 Residential Energy Consumption Survey (RECS) does not cover halogen torchiere lamps.</font> <br />
                    &nbsp;&nbsp;<sup>g</sup><em>Energy Data Sourcebook for the U.S. Residential Sector</em>, Lawrence Berkeley National Laboratory, 1997.</font><br />
                    &nbsp;&nbsp;<sup>h</sup></font><em>Energy Use of Televisions and Videocassette Recorders in the U.S</em>., Lawrence Berkeley National Laboratory, 1999; <br />
                    </font>&nbsp;&nbsp;<sup>i</sup>Video Networks: <em>A Surprising Energy Drain, Home Energy Magazine Online May/June 1999</em>;</font><br />
                    &nbsp;&nbsp;<sup>j</sup><em>Electricity Consumption by Small End Uses in Residential Buildings, Arthur D. Little, 1998;</em></font><br />
                    &nbsp;&nbsp;<sup>k</sup><em>2004 Annual Energy Outlook</em>.<br />
                    </font>&nbsp;&nbsp;<sup>l</sup>Does not include energy used to heat water coming into the washer<br />
                    <br />
                    &nbsp;&nbsp;Notes: &#8226; &quot;Residual&quot; includes appliances not listed, such as irons, hair dryers, electric blankets, power tools, air cleaners, and a myriad of other small electrical appliances. &#8226; &quot;Residual&quot; also includes errors that may be present in estimates of annual consumption. &#8226; Totals may not equal sum of components due to independent rounding. &#8226; This table does not reflect the interactive effects of appliance usage, especially when mixing the estimates from RECS with those from outside sources. <br />
                    &nbsp;&nbsp;&nbsp;&nbsp;Sources: Energy Information Administration, Office of Energy Markets and End Use, Forms EIA-457A-C, E, and H of the 1997 RECS; Energy Information Administration, Office of Energy Markets and End Use, <em>1993 and 2001 Residential Energy Consumption Surveys.</em>
                    </p>
<p>A regression-based procedure <a href="/consumption/archive/residential/append_c.pdf">End-Use Estimation Methodology</a> was used to estimate the amount of electricity used for the major end uses (air conditioning, space heating, water heating, refrigerators, clothes dryers and freezers). Results of the 1993 RECS special lighting supplement <a href="/consumption/residential/data/archive/recs/lighting/contents.html">Residential Lighting Use and Potential Savings</a> were  used to estimate the average amount of electricity used for lighting. Data on the annual electricity consumption of other electrical appliances were obtained from outside sources. </p>
                  <p>The 2001 RECS estimates are air-conditioning 16 percent, space heating 10 percent, water heating 9 percent, and appliances 65 percent. Changes in the  percentages reflect actual changes in the percentages, changes in the methodology used to estimate the amount of electricity used for the various end uses, and errors in the estimation procedure. An example where a change in methodology resulted in a large change is the estimated amount of electricity used for cooking. The 1997 end-use and appliance table used a regression-based estimate and an outside estimate of the amount of electricity used in microwave ovens. The 2001 end-use and appliance table did not use a regression estimate. It used outside estimates of the amount of electricity used in electricity ranges, electric ovens, microwave ovens, electric toaster ovens, and coffee makers. </p></td>
                </tr>
                
              </table>