<span class="condaterange">
              <h2>Housing Characteristics Tables</h2>

              <a class="no-border expandall">+ EXPAND ALL</a></span>
              <table class="contable">
                <thead id="HC1">
                  <tr>
                    <th><a name="HC1"></a><b>Tables HC1: Housing Unit Characteristics, Million U.S. Households</b></th>
                    <th><a href="pdf/2001hc_tables/housingunit_household2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-1a_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-2a_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-3a_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Owner-Occupied Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-5a_ownerunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-7a_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-8a_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-9a_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-10a_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-11a_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc1-12a_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="HC2">
                  <tr>
                    <th><a name="HC2"></a><b>Tables HC2: Household Characteristics, Million U.S. Households</b></th>
                    <th><a href="pdf/2001hc_tables/char_household2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-1a_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-2a_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-3a_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/housunits/hc2-4a_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Owner-Occupied Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-5a_ownerunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Rented Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-6a_rentedunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Owner-Occupied Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-5a_ownerunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-7a_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-8a_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-9a_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-10a_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-11a_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-12a_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="HC3">
                  <tr>
                    <th><a name="HC3"></a><b>Tables HC3: Space Heating, Million U.S. Households</b></th>
                    <th><a href="pdf/2001hc_tables/spaceheat_percent2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc3-1a_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-2a_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-3a_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-4a_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Owner-Occupied Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-5a_ownerunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Rented Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-6a_rentedunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/hous-char/hc2-7a_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-8a_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-9a_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-10a_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-11a_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/spheat/hc3-12a_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="HC4">
                  <tr>
                    <th><a name="HC4"></a><b>Tables HC4: Air-Conditioning, Million U.S. Households</b></th>
                    <th><a href="pdf/2001hc_tables/ac_household2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-1a_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-2a_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-3a_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-4a_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Owner-Occupied Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-5a_ownerunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Rented Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-6a_rentedunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-7a_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-8a_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-9a_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-10a_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-11a_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/ac/hc4-12a_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="HC5">
                  <tr>
                    <th><a name="HC5"></a><b>Tables HC5: Appliances, Million U.S. Households</b></th>
                    <th><a href="pdf/2001hc_tables/appl_household2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-1a_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-2a_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-3a_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-4a_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Owner-Occupied Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-5a_ownerunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Rented Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-6a_rentedunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-7a_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-8a_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-9a_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-10a_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-11a_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/appl/hc5-12a_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="HC6">
                  <tr>
                    <th><a name="HC6"></a><b>Tables HC6: Usage Indicators, Million U.S. Households</b></th>
                    <th><a href="pdf/2001hc_tables/usage_household2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-1a_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-2a_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-3a_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-4a_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Owner-Occupied Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-5a_ownerunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Rented Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-6a_rentedunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-7a_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-8a_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-9a_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-10a_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-11a_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/usage/hc6-12a_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <thead id="HC7">
                  <tr>
                    <th><a name="HC7"></a><b>Tables HC7: Home Office Equipment, Million U.S. Households</b></th>
                    <th><a href="pdf/2001hc_tables/homeofc_household2001.pdf" class="pdf">PDF (all tables)</a></th>
                  </tr>
                </thead>
                <tr>
                  <td>Climate Zone</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-1a_climate2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Year of Construction</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-2a_construction2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Household Income</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-3a_hhincome2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-4a_housingunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Owner-Occupied Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-5a_ownerunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Type of Rented Housing Unit</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-6a_rentedunits2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Four Most Populated States</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-7a_4popstates2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Urban/Rural Location</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-8a_urbanrural2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Northeast Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-9a_ne_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>Midwest Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-10a_mw_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>South Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-11a_so_region2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
                <tr>
                  <td>West Census Region</td>
                  <td><a href="/consumption/residential/data/2001/pdf/hc/homeofc_equip/hc7-12a_westregion2001.pdf" class="ico_pdf">PDF</a></td>
                </tr>
              </table>
