      <br />
<div class="side_col right">
        <?php /* Side Column */ ?>
        <span class="grey_side blue_top">
        <p class="no_btm_border"><a class="ico_pdf" href="pdf/methodology_report.pdf">Full report</a><br /><br /><br />
       
        
        <?php /*h4>Previous Issues</h4> 
        <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_oct_30_2014.pdf">10-30-2014</a><br />
        <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_aug_28_2014.pdf">8-28-2014</a><br />
        <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_jun_26_2014.pdf">6-26-2014</a><br />
        <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_apr_24_2014.pdf">4-24-2014</a><br />
        <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_feb_27_2014.pdf">2-27-2014</a><br /> 
         <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_dec_20_2013.pdf">12-20-2013</a><br />    
         <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_oct_31_2013.pdf">10-31-2013</a><br />
         <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_aug_29_2013.pdf">8-29-2013</a><br />
         <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_jun_27_2013.pdf">6-27-2013</a><br />
        <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_apr_25_2013.pdf">4-25-2013</a><br />
        <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_feb_28_2013.pdf">2-28-2013</a><br />
        <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_dec_20_2012.pdf">12-20-2012</a><br />
          <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_oct_25_2012.pdf">10-25-2012</a><br />
          <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_aug_24_2012.pdf">8-24-2012</a><br />
          <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_jun_26_2012.pdf">6-26-2012</a><br />
          <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_apr_27_2012.pdf">4-27-2012</a><br />
          <a class="ico_pdf" href="../ndaa/archive/pdf/ndaa_feb_29_2012.pdf">2-29-2012</a><br /*/ ?>
          <?php /*<a class="ico_pdf" href="../fe/pdf/appa.pdf">Appendix A-Request Letter</a><br />
        <a class="ico_pdf" href="../fe/pdf/appb.pdf">Appendix B-Summary Tables</a> <br />*/ ?>
          <?php /* <a class="ico_pdf" href="../ces_bingaman/pdf/appc.pdf">Appendix C-Map of NEMS Electricity Market Module Regions</a><br />*/ ?>
          <?php /*<a class="ico_pdf" href="../ces_hall/pdf/errata.pdf">Updates</a>*/ ?></p>

  </span></div>
      <?php /*/ Side Content */ ?>

