<!doctype html>
<html>
<?php
$globalTitle 		= 'U.S. Energy Information Administration (EIA)';
$pageTitle          = 'Style Guide';
$pageTitle = "Coming Soon";
?>

<head>
	<title>
		<!-- title here --> -
		<?=$globalTitle?>
	</title>
	<meta property="og:title" content="<!-- title here --> - <?=$globalTitle?>">


	<link href="../style-guide/styles/style-guide.css" type="text/css" media="screen, projection" rel="stylesheet">
	<link href="../global/styles/global.css" type="text/css" media="screen, projection" rel="stylesheet">

	<script src="../vendor/jquery/jquery.min.js"></script>
	<script src="../vendor/jquery/jquery.migrate.min.js"></script>
	<script src="../vendor/jquery-ui/jquery-ui.min.js"></script>
	<script src="../vendor/jquery-ui/jquery.ui.touch-punch.min.js"></script>
	<link href="../includes/favicon.ico" rel="shortcut icon">
	<link href="../includes/favicon.ico" rel="icon" type="image/x-icon">
	<link href="../includes/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">


</head>

<body>
	<!-- includes/header.inc') ?>
	<div class="l-row l-two-col-right">
		<div class="l-col">
			<div class="article base">
				<h1 class="uk-h1 tm-heading-fragment">Size Conversions</h1>
<p class="uk-text-lead"></p>
				<div class="basic-table">
					<table class="basic-table full-width highlight-col-2 highlight-col-4 sticky">
						<thead>
							<tr>
								<th>Pixels</th>
								<th>REMs</th>
								<th>EMs</th>
								<th>Percent</th>
								<th>Points</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>6px</td>
								<td></td>
								<td>0.375em</td>
								<td>37.5%</td>
								<td>5pt</td>
							</tr>
							<tr>
								<td>7px</td>
								<td></td>
								<td>0.438em</td>
								<td>43.8%</td>
								<td>5pt</td>
							</tr>
							<tr>
								<td>8px</td>
								<td>0.5rem</td>
								<td>0.5em</td>
								<td>50.0%</td>
								<td>6pt</td>
							</tr>
							<tr>
								<td>9px</td>
								<td></td>
								<td>0.563em</td>
								<td>56.3%</td>
								<td>7pt</td>
							</tr>
							<tr>
								<td>10px</td>
								<td>0.625rem</td>
								<td>0.625em</td>
								<td>62.5%</td>
								<td>8pt</td>
							</tr>
							<tr>
								<td>11px</td>
								<td>0.6875rem</td>
								<td>0.688em</td>
								<td>68.8%</td>
								<td>8pt</td>
							</tr>
							<tr>
								<td>12px</td>
								<td>0.75rem</td>
								<td>0.75em</td>
								<td>75.0%</td>
								<td>9pt</td>
							</tr>
							<tr>
								<td>13px</td>
								<td>0.8125rem</td>
								<td>0.8125em</td>
								<td>81.3%</td>
								<td>10pt</td>
							</tr>
							<tr>
								<td>14px</td>
								<td>0.875rem</td>
								<td>0.875em</td>
								<td>87.5%</td>
								<td>11pt</td>
							</tr>
							<tr>
								<td>15px</td>
								<td>0.9375rem</td>
								<td>0.938em</td>
								<td>93.8%</td>
								<td>11pt</td>
							</tr>
							<tr>
								<td>16px</td>
								<td>1rem</td>
								<td>1em</td>
								<td>100.0%</td>
								<td>12pt</td>
							</tr>
							<tr>
								<td>17px</td>
								<td>1.0625rem</td>
								<td>1.063em</td>
								<td>106.3%</td>
								<td>13pt</td>
							</tr>
							<tr>
								<td>18px</td>
								<td>1.125rem</td>
								<td>1.125em</td>
								<td>112.5%</td>
								<td>14pt</td>
							</tr>
							<tr>
								<td>19px</td>
								<td>1.1875rem</td>
								<td>1.188em</td>
								<td>118.8%</td>
								<td>14pt</td>
							</tr>
							<tr>
								<td>20px</td>
								<td>1.25rem</td>
								<td>1.25em</td>
								<td>125.0%</td>
								<td>15pt</td>
							</tr>
							<tr>
								<td>21px</td>
								<td>1.3125rem</td>
								<td>1.313em</td>
								<td>131.3%</td>
								<td>16pt</td>
							</tr>
							<tr>
								<td>22px</td>
								<td>1.375rem</td>
								<td>1.375em</td>
								<td>137.5%</td>
								<td>17pt</td>
							</tr>
							<tr>
								<td>23px</td>
								<td>1.4375rem</td>
								<td>1.438em</td>
								<td>143.8%</td>
								<td>17pt</td>
							</tr>
							<tr>
								<td>24px</td>
								<td>1.5rem</td>
								<td>1.5em</td>
								<td>150.0%</td>
								<td>18pt</td>
							</tr>
							<tr>
								<td>25px</td>
								<td>1.5625rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>

							<tr>
								<td>26px</td>
								<td>1.625rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>27px</td>
								<td>1.6875rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>28px</td>
								<td>1.75rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>29px</td>
								<td>1.8125rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>30px</td>
								<td>1.875rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>31px</td>
								<td>1.9375rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>32px</td>
								<td>2rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>33px</td>
								<td>2.0625rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>34px</td>
								<td>2.125rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>35px</td>
								<td>2.1875rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>36px</td>
								<td>2.25rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>37px</td>
								<td>2.3125rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>38px</td>
								<td>2.375rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>39px</td>
								<td>2.4375rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>40px</td>
								<td>2.5rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>41px</td>
								<td>2.5625rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>42px</td>
								<td>2.625rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>43px</td>
								<td>2.6875rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>44px</td>
								<td>2.75rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>45px</td>
								<td>2.8125rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>46px</td>
								<td>2.875rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>47px</td>
								<td>2.9375rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>48px</td>
								<td>3rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>49px</td>
								<td>3.0625rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>50px</td>
								<td>3.125rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>51px</td>
								<td>3.1875rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>52px</td>
								<td>3.25rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>53px</td>
								<td>3.3125rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>54px</td>
								<td>3.375rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>55px</td>
								<td>3.4375rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>56px</td>
								<td>3.5rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>57px</td>
								<td>3.5625rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>58px</td>
								<td>3.625rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>59px</td>
								<td>3.6875rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>60px</td>
								<td>3.75rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>61px</td>
								<td>3.8125rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>62px</td>
								<td>3.875rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>63px</td>
								<td>3.9375rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
							<tr>
								<td>64px</td>
								<td>4rem</td>
								<td>em</td>
								<td>%</td>
								<td>pt</td>
							</tr>
						</tbody>
					</table>
				</div>
				</span>
			</div>
		</div>
		<div class="l-col base sticky">
			<?php include('./includes/sub-nav.inc') ?>
		</div>
	</div>
	<!-- includes/footer.inc') ?>
</body>


</html>