<ul class="sub-nav">
	<li class="<?php ($pageTitle == 'Base Home') ? print 'active' : print ''; ?>"><a href="index.php">Base Home</a></li>
	<li class="<?php ($pageTitle == 'Accessibility') ? print 'active' : print ''; ?>"><a href="accessibility.php">Accessibility</a></li>
	<li class="<?php ($pageTitle == 'Color Palette') ? print 'active' : print ''; ?>"><a href="color-palette.php">Color Palette</a></li>
	<li class="<?php ($pageTitle == 'Icons') ? print 'active' : print ''; ?>"><a href="icons.php">Icons</a></li>
	<li class="<?php ($pageTitle == 'Document Icons') ? print 'active' : print ''; ?>"><a href="document-icons.php">Document Icons</a></li>
	<li class="<?php ($pageTitle == 'Logos') ? print 'active' : print ''; ?>"><a href="logos.php">Logos</a></li>
	<li class="<?php ($pageTitle == 'Typography') ? print 'active' : print ''; ?>"><a href="typography.php">Typography</a></li>
	<li class="<?php ($pageTitle == 'Size Conversions') ? print 'active' : print ''; ?>"><a href="size-conversions.php">Size Conversions</a></li>
</ul>