<h3>Icon Only (no description)</h3>
<div class="accordion-content horizontal-icon-container stand-alone">



	<div class="icon-container">
		<span class="eia ico icon-only ico pdf">
			<span>PDF</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/pdf --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico xls">
			<span>XLS</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/xls --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico csv">
			<span>CSV</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/csv --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico interactive">
			<span>Interactive</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/int --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico ppt">
			<span>PPT</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/ppt --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico html">
			<span>HTML</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/html --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico doc">
			<span>DOC</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/doc --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico jspn">
			<span>JSON</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/json --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico image">
			<span>IMAGE</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/image --> -->
	</div>

	<div class="icon-container">
		<span class="eia ico icon-only ico efile">
			<span>eFile</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/efile --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico txt">
			<span>TXT</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/txt --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico pedro">
			<span>PEDRO</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/pedro --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico api">
			<span>API</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/api --> -->
	</div>
	<div class="icon-container">
		<span class="eia ico icon-only ico zip">
			<span>ZIP</span>
		</span>
		<!-- 		<?php include('./includes/icons/stand-alone/zip --> -->
	</div>
</div>
</div>