<span class="grey_side green_top">
            <h4>Survey Methods<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.eia.gov/emeu/cbecs/1999sample.htm">1999</a>&nbsp;&nbsp;<a href="http://www.eia.gov/emeu/cbecs/detailed_tables_1995.html#tech">1995</a> </h4>
            <h4><a href="http://www.eia.gov/emeu/cbecs/building_types.html">Building 
              Types Definitions</a></h4>
            <h4>
              <a href="http://www.eia.gov/emeu/cbecs/forms.html">Data Collection
              Forms</a></h4>
            <h4>
              <a href="http://www.eia.gov/emeu/cbecs/cbecs2003/background.html">Survey 
              Background and Technical Information</a></h4>
            <h4>
              <a href="http://www.eia.gov/emeu/cbecs/comparesampdesign.html">Comparison 
              Between Years</a></h4>
            <h4>
  <a href="/consumption/commercial/methodology/cbecs_glossary.cfm">Glossary</a> </h4>
            <h4>
              
              <a href="http://www.eia.gov/emeu/cbecs/census_maps.html"> Census  Map</a></h4>
            <h4>
              <a href="http://www.eia.gov/emeu/cbecs/climate_zones.html">U.S. 
              Climate Zones</a></h4>
          
              <?php /* EIB Promo */ ?>
          <?php /*span class="brt_blue_side">
            <h4 class="eib_side">What is the electric power grid and what are some challenges it faces?</h4>
            <p><a href="#">Read the Energy in Brief Article &rsaquo;</a></p>
          </span>
           EIB Promo 
           Graphic Promo 
          <span class="grey_side green_top">
            <h4>2007 State Electricity Profiles</h4>
            <h5>US Average Retail Price perKilowatthour is 9.13 Cents.</h5>
            <img src="/global/images/slush/state_map.png" />
            <h4 class="legend_title"><b>Average Retail Price </b><i>(Cents per Kilowatthour)</i></h4>
            <ul class="legend">
              <li class="leg01">5.07 &ndash; 6.83</li>
              <li class="leg04">8.54 &ndash; 12.88</li>
              <li class="leg03">6.84 &ndash; 7.44</li>
              <li class="leg05">13.01 &ndash; 21.29</li>
              <li class="leg03">7.57 &ndash; 8.53</li>
            </ul>
            <p class="no_btm_border"></p>
          </span>
           Graphic Promo 
           Update Promo Example 
          <span class="promo_side blue_top">
              <h4 class="updates_side">Updates have been made to Electricity Survey Forms <b>EIA-923</b> and <b>EIA-860</b></h4>
              <p><a href="#">Learn more about the updates &rsaquo;</a></p>
          </span*/ ?>
          <?php /* Update Promo Example */ ?>
            
</span>