<?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
                <li><a href="/consumption/efficiency/index.cfm">Efficiency Overview</a></li>
              </ul>
              <ul>
                <li><a href="/consumption/efficiency/data/">Data</a> </li>
              </ul>
              <ul>
                <li class="no_btm_border"><a  href="/consumption/efficiency/reports/">Analysis &amp; Reports</a></li>
              </ul>
              
          </span>
<?php /* Sidenav EIA Menu */ ?>
		  <span class="grey_side_nav green_top ">
         <strong>Related Information </strong><br>
                        <a href="http://www.eia.gov/emeu/efficiency/energy_savings.htm">All Sectors Energy Savings</a><br>
                        <a href="http://www.eia.gov/kids/energyfacts/saving/efficiency/moresavings.html#OnOther">Kids Energy Savings</a><br> 
                        <a href="http://www.eia.gov/emeu/efficiency/reports.html">Energy-Efficiency Related: EIA Reports and Analyses </a><br>
                        <a href="http://www.eia.gov/emeu/efficiency/energy_efficiency_links.htm">Energy Efficiency Organizations </a> <br>
                        <a href="http://www.eia.gov/emeu/efficiency/greenhouse_gas/greenhouse_links.html">Energy Related Greenhouse Gas Emissions</a><br>
                        <a href="http://www.eia.gov/emeu/efficiency/appliance_standards.html">Appliance Standards and Labeling </a><br>
                      </p>
                      </span>