          <span class="grey_side green_top">
            <h4>Lighting in Commercial Buildings</h4>
            <p>Lighting is a major consumer of electricity in commercial buildings and a target for energy savings through use of energy-efficient light sources along with other advanced lighting technologies. The Commercial Buildings Energy Consumption Survey (CBECS) collects information on types of lighting equipment, the amount of floorspace that is lit, and the percentage of floorspace lit by each type. <a href="/consumption/commercial/reports/lighting_buildings.cfm">See more &rsaquo;</a></p>
          </span>
          <div class="secondary">
<ul>
        <h4>Energy Use in Manufacturing</h4>
            <p>Energy Use in Manufacturing provides information related to energy consumption changes within the U.S. manufacturing sector between 1998 and 2002.   This report addresses both manufacturing energy consumption and characteristics of the manufacturing economy related to energy consumption. In addition, special sections on fuel switching capacity and energy-management activities between 1998 and 2002 are also featured in this report. <a href="/consumption/industrial/reports/industrial_report.cfm">See more &rsaquo;</a></p>
          </span>
          <?php /* EIB Promo */ ?>
          <?php /*span class="brt_blue_side">
            <h4 class="eib_side">What is the electric power grid and what are some challenges it faces?</h4>
            <p><a href="#">Read the Energy in Brief Article &rsaquo;</a></p>
          </span>
           EIB Promo 
           Graphic Promo 
          <span class="grey_side green_top">
            <h4>2007 State Electricity Profiles</h4>
            <h5>US Average Retail Price per<br />Kilowatthour is 9.13 Cents.</h5>
            <img src="/global/images/slush/state_map.png" />
            <h4 class="legend_title"><b>Average Retail Price </b><br /><i>(Cents per Kilowatthour)</i></h4>
            <ul class="legend">
              <li class="leg01">5.07 &ndash; 6.83</li>
              <li class="leg04">8.54 &ndash; 12.88</li>
              <li class="leg03">6.84 &ndash; 7.44</li>
              <li class="leg05">13.01 &ndash; 21.29</li>
              <li class="leg03">7.57 &ndash; 8.53</li>
            </ul>
            <p class="no_btm_border"></p>
          </span>
           Graphic Promo 
           Update Promo Example 
          <span class="promo_side blue_top">
              <h4 class="updates_side">Updates have been made to Electricity Survey Forms <b>EIA-923</b> and <b>EIA-860</b></h4>
              <p><a href="#">Learn more about the updates &rsaquo;</a></p>
          </span*/ ?>
          <?php /* Update Promo Example */ ?>