<?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
                <li><a href="../commercial/methodology/survey_background.cfm">Commercial Buildings Energy Consumption Survey</a></li>
              </ul>
              <ul>
                <li>Data
                  <ul>
                    <li><a href="/consumption/commercial/data/2003/">2003</a></li>
                    <li><a href="/consumption/commercial/data/1999/">1999</a></li>
                    <li><a href="http://www.eia.gov/emeu/cbecs/detailed_tables_1995.html">1995</a></li>
                    <li><a href="/consumption/commercial/data/archive.cfm">Archive</a></li>
                  </ul>
                </li>
              </ul>
              <ul>
                <li><a href="/consumption/commercial/reports/">Analysis &amp; Reports</a></li>
              </ul>
              <ul>
                <li class="no_btm_border"><a href="/consumption/commercial/methodology/">Methodology</a></li></ul>
              
          </span>
<?php /* Sidenav EIA Menu */ ?>