<div class="secondary">
<ul>
<h4>Most requested energy consumption &amp; efficiency data</h4>
<p class="no-border"><strong>Residential energy consumption</strong></p>
<ul>
  <li> <a href="/consumption/residential/data/2015/index.php?view=characteristics">Household characteristics</a></li>
  <li><a href="/consumption/residential/data/2015/index.php?view=consumption">Home energy use &amp; costs</a></li>
  <li><a href="/consumption/residential/data/2015/index.php?view=microdata">Detailed household microdata</a></li>
</ul>
<p class="no-border"><strong>Commercial energy consumption</strong></p>
<ul>
  <li><a href="/consumption/commercial/data/2012/index.php?view=characteristics">Building characteristics</a></li>
  <li><a href="/consumption/commercial/data/2012/index.php?view=consumption">Commercial energy use &amp; costs</a></li>
  <li><a href="/consumption/commercial/data/2012/index.php?view=microdata2003/index.cfm?view=microdata">Detailed buildings microdata</a></li>
</ul>
<p class="no-border"><strong>Manufacturing energy consumption</strong></p>
<ul>
  <li> <a href="/consumption/manufacturing/data/2014/">2014 data </a></li>
  <li> <a href="/consumption/manufacturing/data/2010/">2010 data </a></li>
  <li><a href="/consumption/manufacturing/data/2006/">2006 data </a></li>
  <li><a href="/consumption/manufacturing/data/2002/">2002 data</a></li>
  <li><a href="/consumption/manufacturing/data/1998/">1998 data</a></li>
  <li><a href="/consumption/manufacturing/data/1994/">1994 data</a></li>
    <li><a href="/consumption/manufacturing/data/1991/">1991 data</a></li>
</ul>
<!--<p class="no-border"><strong>Vehicle energy consumption&nbsp;</strong></p>
<ul>
  <li><a href="/consumption/archive/rtecs/nhts_survey/2001/tablefiles/page_a01.html">Vehicle characteristics </a></li>
  <li><a href="/consumption/archive/rtecs/nhts_survey/2001/tablefiles/page_a04.html">Vehicle stock</a></li>
  <li><a href="/consumption/archive/rtecs/nhts_survey/2001/tablefiles/page_a02.html">Fuel consumption </a></li>
</ul>
<p class="no-border"><strong>Energy intensity&nbsp;</strong></p>
<ul>
  <li> <a href="/consumption/residential/data/2009/index.cfm?view=consumption#summary">Residential</a></li>
  <li><a href="/consumption/commercial/data/2003/index.cfm?view=consumption">Commercial     buildings</a></li>
  <li><a href="/consumption/manufacturing/reports/archive/iron_steel_9802/steel_9802_data.html">Manufacturing industries</a></li>
</ul>
<p class="no-border"><strong>Consumption summaries</strong></p>
<ul>
  <li><a href="http://www.eia.gov/emeu/mer/consump.html">Monthly</a></li>
  <li><a href="http://www.eia.gov/emeu/aer/consump.html">Annual</a></li>
</ul>
<br />
<h4>International data</h4>
<p class="no-border"><strong>Overview</strong></p>
<ul>
  <li><a href="http://www.eia.gov/emeu/international/energyconsumption.html">Primary energy consumption &amp; efficiency</a></li>
</ul>
</span> <div class="secondary">
<ul>
<h4>End-use consumption<br />
  data &amp; surveys </h4>
<ul>
  <li><a href="/emeu/recs/contents.html">Residential Energy Consumption (RECS)</a></li>
  <li><a href="/emeu/cbecs/contents.html">Commercial Building Energy Consumption (CBECS)</a></li>
  <li><a href="/emeu/mecs/contents.html">Manufacturing Energy Consumption (MECS)</a></li>
  <li><a href="/consumption/archive/rtecs/">Transportation (RTECS)</a></li>
</ul>
</span> <div class="secondary">
<ul>
<h4>Sector totals:</h4>
<ul class="top">
  <li><a href="/aer/consump.html">Annual</a> &mdash; 1949-2009 </li>
  <li><a href="/mer/consump.html">Monthly</a></li>
</ul>
</span><span class="grey_side green_top">
<h4>Consumption and efficiency<br />
  analysis & projections </h4>
<p class="no-border"><strong>Annual Energy Outlook 2011, Early Release:</strong></p>
<ul>
  <li> <a href="http://www.eia.gov/forecasts/aeo/early_consumption.cfm">Energy consumption by sector </a></li>
  <li> <a href="http://www.eia.gov/forecasts/aeo/early_intensity.cfm">Energy intensity </a></li>
</ul>
<p class="no-border"><strong>Annual Energy Outlook 2010 with Projections to 2035</strong></p>
<ul>
  <li><a href="http://www.eia.doe.gov/oiaf/archive/aeo10/arra.html">American Recovery and Reinvestment Act of 2009: Summary of Provisions</a></li>
  <li><a href="http://www.eia.doe.gov/oiaf/archive/aeo10/demand.html">Energy demand</a></li>
  <li><a href="http://www.eia.doe.gov/oiaf/aeo/otheranalysis/aeo_2010analysispapers/cep.html">Comparing efficiency projections</a></li>
</ul>
<p class="no-border"><a href="http://www.eia.doe.gov/oiaf/demand.html">More analysis &rsaquo;</a></p> -->
</span>