<?php $what = 'consumption'; ?>
<?php include('about/new/whatsnew_sitewide.php'); ?>
        <div class="secondary">
<ul>
        <h4>Energy Use Information by Sector</h4>
<p class="no_btm_border"><strong>Residential</strong><br />
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="residential/"> overview</a></li>
          <li><a href="residential/data/2005/">most recent data (2005)</a></li>
          <li><a href="residential/reports/">analysis, projections &amp; reports</a></li></ul>
          <hr/>
<strong>Commercial Buildings</strong><br />
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="commercial/">overview</a></li>
          <li><a href="commercial/data/2003/">most recent data (2003)</a></li>
          <li><a href="commercial/reports/">analysis, projections &amp; reports</a></li></ul><hr/>
          <strong>Manufacturing</strong><br />
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="industrial/">overview</a></li>
          <li><a href="manufacturing/data/2006/">most recent data (2006)</a></li>
          <li><a href="manufacturing/reports/">analysis, projections &amp; reports</a></li></ul>
          <hr/>
<p class="no_btm_border" ><strong>Transportation</strong><br />
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="transportation/">overview</a></li>
          <li><a href="transportation/data/2001/">most recent data (2001)</a></li>
          <li><a href="transportation/reports/">analysis, projections &amp; reports          </a></li>
        </ul></p><hr/>
        <h4>Topics</h4>
        <p class="no_btm_border"><strong>Efficiency (Energy Intensity)</strong></p>
        
        <ul>
          <li><a href="/consumption/efficiency/index.cfm">overview</a></li>
          <li><a href="/consumption/efficiency/data/index.cfm">data</a></li>
          <li><a href="/consumption/efficiency/reports/index.cfm">aalysis, projections &amp; reports</a></li>
        </ul>
          
          </span>
<?php /* FAQ Promo */ ?>
        <span class="blue_side">
          <h4 class="q_side"><a href="consumption_faqs.cfm#rfaq1">What is the basis for EIA&#8217;s statistics on household energy consumption and expenditures?</a></h4>
          <p><a href="consumption_faqs.cfm">See all Energy End Use FAQs &rsaquo;</a></p>
        </span>
        