<?php $what = 'consumption'; ?>
<?php include('about/new/whatsnew_sitewide.php'); ?>
        <div class="secondary">
<ul>
        <h4>Energy Use Data by Sector</h4>
<p class="no_btm_border"><strong>Residential</strong><br />
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="residential/">Sector Overview</a></li><li><a href="residential/data/2005/">Most Recent Data (2005)</a></li>
          <li><a href="residential/reports/">Analysis  &amp; Reports</a></li></ul>
          </p>
<p class="no_btm_border"><strong>Commercial Buildings</strong><br />
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="commercial/">Sector Overview</a></li>
          <li><a href="commercial/data/2003/">Most Recent Data (2003)</a></li>
          <li><a href="commercial/reports/">Analysis  &amp; Reports</a></li></ul>
          </p>
<p class="no_btm_border"><strong>Manufacturing</strong><br />
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="industrial/">Sector Overview</a></li>
          <li><a href="manufacturing/data/2006/">Most Recent Data (2006)</a></li>
          <li><a href="manufacturing/reports/">Analysis  &amp; Reports</a></li></ul>
          </p>
<p class="no_btm_border" ><strong>Transportation</strong><br />
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="transportation/">Sector Overview</a></li>
          <li><a href="transportation/data/2001/">Most Recent Data (2001)</a></li>
          <li><a href="transportation/reports/">Analysis  &amp; Reports          </a></li>
        </ul></p><span style="margin-bottom:10px">&nbsp;</span>
        <h4>Topics</h4>
        <p class="no_btm_border"><strong>Efficiency (Energy Intensity)</strong></p>
        
        <ul>
          <li><a href="/consumption/efficiency/index.cfm">Overview</a></li>
          <li><a href="/consumption/efficiency/data/index.cfm">Data</a></li>
          <li><a href="/consumption/efficiency/reports/index.cfm">Analysis and Reports</a></li>
        </ul>
          
          </span>
<?php /* FAQ Promo */ ?>
        <span class="blue_side">
          <h4 class="q_side"><a href="consumption_faqs.cfm#rfaq1">What is the basis for EIA&#8217;s statistics on household energy consumption and expenditures?</a></h4>
          <p><a href="consumption_faqs.cfm">See all Energy End Use FAQs &rsaquo;</a></p>
        </span>
        