<div class="l-col"> <span class="grey_side green_top">
		<p><a href="/consumption/manufacturing/about.cfm">About the MECS</a></p>
		<p><a href="/survey/#eia-846">Survey forms</a></p>
		<p><a href="/consumption/manufacturing/maps.cfm">Maps</a></p>
		<p><a href="/consumption/manufacturing/terms.cfm">MECS Terminology</a></p>
		<p class="no-border"><a href="data/archive/">Archives</a></p>
	</span>
	<?php /* FAQ Promo */ ?>
	<?php /*span class="blue_side">
  <h4 class="q_side"> <a href="#">Were you contacted about participating in the MECS Energy Supplier Survey?</a> </h4>
  <strong>
  <p><a href="#">See all MECS FAQs &rsaquo;</a></p>
  </strong> </span*/ ?>

	<?php /* Featured Data */ ?>
	<span class="grey_side blue_top side_list_nocolumn">
		<h4>Features</h4>
		<p class="no-border"><a href="/pressroom/releases/press383.cfm">First 2010 Data Press Release</a><br />
		<p class="no-border"><a href="reports/2010/decrease_use.cfm">2010 Data Brief</a><br />
		</p>
	</span>
	<?php /* Other Consumption Surveys */ ?>
	<div class="secondary">
<ul>
		<h4>Other End Use Surveys</h4>
		<p><a href="/consumption/commercial/">Commercial Buildings - CBECS</a></p>
		<p><a href="/consumption/residential/">Residential - RECS</a> </p>
		<p class="no-border"><a href="/consumption/archive/rtecs/contents.html">Transportation</a></p>
	</span>

	<span class="grey_side blue_top side_list_nocolumn">
		<h4>DOE Uses MECS Data</h4>
		<p class="no-border"><a href="https://www.energy.gov/eere/amo/manufacturing-energy-and-carbon-footprints-2014-mecs">Manufacturing Energy and Carbon Footprints
			</a>
		<p class="no-border"><img src="/consumption/manufacturing/reports/2010/images/doe_mecs.jpg">
		<p class="no-border"><a href="http://www.energy.gov/eere/amo/downloads/us-manufacturing-energy-use-and-greenhouse-gas-emissions-analysis">Associated Analysis</a><br /><a href="http://www.energy.gov/eere/amo/sankey-diagram-energy-flow-us-manufacturing">Manufacturing Energy Sankey Diagrams</a><br /><a href="http://www.energy.gov/eere/amo/manufacturing-energy-flows-sankey-tool ">Manufacturing Energy Flows Tool </a>
	</span>



	<?php /*/ Side Content */ ?>
</div>