<?php /* Sidenav EIA Menu side_nav*/ ?>

<span class="grey_side_nav blue_top ">
	<ul class="top">
		<h4>Transportation Consumption:</h4>
		<p class="no_btm_border"> <strong>Transportation sector total</strong> </li>
		<ul>
			<li><a href="/aer/txt/ptb0201e.html">annual</a> &mdash; 1949-2009</li>
			<li><a href="/mer/consump.html">monthly</a></li>

		</ul>
		<span class="no_btm_border"><a href"http://wwwdev.eia.gov/consumption/transportation/about_trans.cfm"><strong>End-use consumption data</strong></a></span>
		</p>


		<ul>
			<!-- <li><a href="http://www.eia.gov/emeu/rtecs/nhts_survey/2001/tablefiles/t0464%282005%29.pdf" class="ico pdf">2001</a>—most recent</li>
               <li><a href="about_trans.cfm">About the survey</a></li>
               <li><a href="http://www.eia.gov/cneaf/alternate/page/atftables/afv_atf.html">Alternatives to Traditional Transportation Fuels 2008</a></li>-->
		</ul>
		<!--  <p class="no_btm_border"><strong>Residential Energy Consumption Statistics</strong><br/>
           Residential Energy Consumption Survey 2005 and previous<br />  
           Energy use in homes by fuel type, housing type, and end uses
         </p>
                <ul>
          
          <li><a href="http://wwwdev.eia.gov/consumption/residential/data/2005/index.cfm">data </a></li><li><a href="http://wwwdev.eia.gov/consumption/residential/about_recs.cfm">about the survey</a></li>
          <li><a href="http://wwwdev.eia.gov/consumption/residential/reports/">analysis &amp; reports</a></li></ul><br />-->
		<span class="no_btm_border"><strong>Efficiency related:</strong></span>
		</p>


		<ul>
			<li><a href="/aer/txt/ptb0208.html">Motor Vehicle Milage, Fuel Consumption, and Fuel Economy</a> 1949-2008<br />
				<em>Annual Energy Review 2009</em>
			</li>
			<li><a href="http://www.eia.gov/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=7-AEO2011&region=0-0&cases=ref2011-d120810c">Transportation sector key indicators and consumption</a><br /> projections to 2035<br />
				<em>Annual Energy Outlook 2011, Early Release</em>
			</li>


		</ul>
	</ul>

</span>
<?php /* Sidenav EIA Menu */ ?>