<?php /* Renewable Sub Nav */ ?>
<div class="title bg_enduse">
	<h1>Consumption & Efficiency</h1>
</div>
<?php /*/ Page/Section Title */ ?>
<div id="subnav">
	<?php /* Page/Sub Nav */ ?>
	<span class="right"><a href="#">Glossary &rsaquo;</a> <a href="#">FAQS &rsaquo;</a></span>
	<ul>
		<li class="subnav-overview"><a href="../index.cfm">Overview</a></li>
		<li class="subnav-residential"><a href="../residential/">Residential</a></li>
		<li class="subnav-commercial"><a href="../commercial/">Commercial</a></li>
		<li class="subnav-industrial"><a href="../industrial/">Industrial</a></li>
		<li class="subnav-tranportation"><a href="../transportation/">Tranportation</a></li>
	</ul>
</div><?php /*/ Page/Sub Nav */ ?>