<h3>Logos</h3>
<div class="eia accordion-content">

	<?php include('./includes/logos/logo-beta.inc') ?>
	<?php include('./includes/logos/logo.inc') ?>
	<?php include('./includes/logos/logo-shrunk.inc') ?>
	<?php include('./includes/logos/beta-logo.inc') ?>
	<?php include('./includes/logos/beta-logo-shrunk.inc') ?>
	<?php include('./includes/logos/white-background-css.inc') ?>
	<?php include('./includes/logos/white-background-png.inc') ?>
	<?php include('./includes/logos/white-background-svg.inc') ?>

</div>