<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="Button">&lt;div class="button-container"&gt;
	&lt;button type="submit" id="submitFeedback" tabIndex="0" role="button" class="submit"&gt;
		Submit Feedback
	&lt;/button&gt;
&lt;/div&gt;</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Button">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>