<h4 class="h4 base">PNG</h4>
<div class="logo-logo-white-background">
	<img src="" alt="EIA Logo White Background PNG" ?>
</div>
<!--
<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>
 Target
<pre><code class="language-html" id="Button">&lt;div class="button-container"&gt;
	&lt;button type="submit" id="submitFeedback" tabIndex="0" role="button" class="submit"&gt;
	&lt;/button&gt;
&lt;/div&gt;</code></pre>
	<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Button">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
	</div>
	</div>
	-->