<h3>Informative Icons</h3>
<div class="accordion-content horizontal-icon-container informative">

	<div class="icon-container">
		<h6>Information Icon Anchor</h6>

		<a class="eia ico info">
			Lorem ipsum
		</a>

		<?php include('./includes/icons/informative/anchor-info.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Information Icon span</h6>

		<a>
			<span class="eia ico info">
				<span>{INFORMATION}</span>
			</span>
			Lorem ipsum
		</a>

		<?php include('./includes/icons/informative/info.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Information Icon Paragraph</h6>

		<p class="eia ico info">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem massa, semper nec eros a, lacinia porttitor nunc. Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien. Suspendisse sagittis risus eu sem suscipit sodales. Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus. Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis. Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem. Vestibulum ut odio id nulla commodo dignissim. Proin a pharetra tellus.</p>

		<?php include('./includes/icons/informative/p-info.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Print</h6>
		<span class="eia ico pin">
			<span>Print</span>
		</span>
		<?php include('./includes/icons/informative/printer.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Information Icon DIV</h6>
		<?php include('./includes/icons/informative/index.inc')  ?>
		<?php include('./includes/messaging/information.inc')  ?>
	</div>

	<div class="icon-container">
		<h6>Tour Icon</h6>
		<a>
			<span class="eia ico tour">
				<span>Tour</span>
			</span>
		</a>
	</div>

	<div class="icon-container">
		<h6>Printer</h6>
		<a>
			<span class="eia ico printer">
				<span>PRINT</span>
			</span>
		</a>
	</div>
</div>

<h2>External Link</h2>
<div class="icon-container">
	<a href="https://www.google.com">https://www.google.com</a>
</div>
<!--
			
			<div class="icon-container">
				<h6>External Link to Image</h6>
				<div class="image-container">
					<a href="https://www.google.com">
						<img src="https://www.eia.gov/global/images/kids_promos/kids-standard.png" alt="Bab el-Mandeb Strait" class="responsive" />
					</a>
				</div>
			</div>
		</div
		-->
</div>
</div>