<?php
$h2 = 'Questions? We have answers.';
$q1 = 'Why Do Electric Rates Vary by States?';
$a1 = '<p>There are several factors that affect electricity rates in your state, some factors you have some control over, like load factor, and some you don&#39;t like the types of energy generation in your state.</p>
<p>The primary factors include energy consumption, state regulations, access to resources, and market conditions. For instance, states with abundant natural resources, such as North Dakota, tend to have lower electricity rates. On the other hand, states with limited resources, such as Hawaii, have higher electricity rates. The cost of generating electricity, transmission, and distribution also plays a huge role in de­termining electricity rates. Additionally, factors like weather, seasonal demand, and the availability of renewable sources can impact elec­tricity prices.</p>
<p>Your best option is to understand how you can control your electricity pricing, a few small changes in your habits can make a big impact on what your average monthly bill.</p>
<ul>
	<li><strong>What time of day you use energy:</strong> Energy suppliers use complicated models to forecast demand throughout the day. If you&#39;re using more energy at a time when demand is high than you the electricity you use cost the supplier more, in turn you will have a higher rate when you renew. </li> <br>
	<li><strong>Time of year:</strong> In Southern states, summer rates can be higher than winter rates due to higher energy demand for cooling system, vice versa for heating in cold northern states. </li> <br>
	<li><strong>Where you live:</strong> Energy rates vary from state to state and even among utility areas in the same state, regardless of whether the state has energy choice. There is a long complicated list of reasons why, but the simple answer is supply and demand. Some areas have more generation {more supply} and less demand, so rates are lower. </li>
</ul>';
$q2 = 'What drives crude oil prices: Overview';
$a2 = '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>';
$q3 = 'What states have a deregulated energy market?';
$a3 = '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>';
$q4 = 'What is the purpose of a deregulated energy market?';
$a4 = '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>';
$q5 = 'How are commercial electricity rates affected by deregulated areas?';
$a5 = '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>';
$q6 = 'What states produce the most renewable energy?';
$a6 = '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>';
?>


<section class="questions-and-answers margin-bottom">
	<div class="l-grid l-full-width-col">
		<h2><?=$h2?></h2>
		<details>
			<summary><?=$q1?></summary>
			<div><?=$a1?></div>
		</details>

		<details>
			<summary><?=$q2?></summary>
			<div><?=$a2?></div>
		</details>

		<details>
			<summary><?=$q3?></summary>
			<div><?=$a3?></div>
		</details>

		<details>
			<summary><?=$q4?></summary>
			<div><?=$a4?></div>
		</details>

		<details>
			<summary><?=$q5?></summary>
			<div><?=$a5?></div>
		</details>

		<details>
			<summary><?=$q6?></summary>
			<div><?=$a6?></div>
		</details>
	</div>
</section>