<div class="pub_title bg_pub_default"><?php /* Page/Section Title */ ?>
	<h3><?php echo $L2Title; ?></h3>
	<h1 style="padding-top:0px;">WHAT DRIVES CRUDE OIL PRICES?</h1>
	<p style="font-size:14px;margin-top:-6px;">An analysis of 7 factors that influence oil markets, with chart data
		updated monthly and quarterly</p>
</div>

<div class="subnav">
	<?php /* <span class="right"><a href="<cfoutput>#glossary_path#</cfoutput>">Glossary &rsaquo;</a>
<a href="<cfoutput>#faqs_path#</cfoutput>">FAQS &rsaquo;</a></span> */ ?>
	<ul>
		<li class="active"><a href=".">Crude Oil</a></li>
		<li><a href="../products/">Petroleum Products</a></li>
	</ul>
</div>


<div class="efmi_ui" id="efmi_ui">
	<div class="efmi_ui_container2 left">
		<?php /* Row 1 */ ?>
		<ul id="bubble2">
			<li>
				<a href="supply-nonopec.php">
					<img class="small" src="images/ui/supply_non_oecd_off.png" alt="Supply non-OECD" />
					<img class="large" src="images/ui/supply_non_oecd_on.png" alt="Supply non-OECD" />
				</a>
			</li>
			<li>&nbsp;</li>
			<li>&nbsp;</li>
			<li>&nbsp;</li>
			<li>
				<a href="demand-nonoecd.php">
					<img class="small" src="images/ui/demand_non_oecd_off.png" alt="Demand non-OECD" />
					<img class="large" src="images/ui/demand_non_oecd_on.png" alt="Demand non-OECD" />
				</a>
			</li>
		</ul>
		
		<?php /* Row 2 */ ?>
		<ul id="bubble2">
			<li>
				<a href="supply-opec.php">
					<img class="small" src="images/ui/supply_oecd_off.png" alt="Supply OECD" />
					<img class="large" src="images/ui/supply_oecd_on.png" alt="Supply OECD" />
				</a>
			</li>
			<li class="mid-adjust">
				<a href="balance.php">
					<img class="small" src="images/ui/balance_off.png" alt="Balance" />
					<img class="large" src="images/ui/balance_on.png" alt="Balance" />
				</a>
			</li>
			<li class="mid-adjust">
				<a href="spot_prices.php">
					<img class="small" src="images/ui/spot_prices_off.png" alt="Spot Prices" />
					<img class="large" src="images/ui/spot_prices_on.png" alt="Spot Prices" />
				</a>
			</li>
			<li class="mid-adjust">
				<a href="financial_markets.php">
					<img class="small" src="images/ui/financial_markets_off.png" alt="Financial Markets" />
					<img class="large" src="images/ui/financial_markets_on.png" alt="Financial Markets" />
				</a>
			</li>
			<li>
				<a href="demand-oecd.php">
					<img class="small" src="images/ui/demand_oecd_off.png" alt="Demand OECD" />
					<img class="large" src="images/ui/demand_oecd_on.png" alt="Demand OECD" />
				</a>
			</li>
		</ul>
		<!-- div class="clear"></div>
		<div>
			<a href="spot_prices.php" title="crude oil">Spot Prices</a> &nbsp;|&nbsp;
			<a href="supply-nonopec.php">Supply Non-OPEC</a> &nbsp;|&nbsp;
			<a href="supply-opec.php">Supply OPEC</a> &nbsp;|&nbsp;
			<a href="balance.php" title="crude oil">Balance</a> &nbsp;|&nbsp;
			<a href="financial_markets.php">Financial Markets</a> &nbsp;|&nbsp;
			<a href="demand-nonoecd.php">Demand Non-OECD</a> &nbsp;|&nbsp;
			<a href="demand-oecd.php">Demand OECD</a>
		</div -->
	</div>
</div>