<?php /*

<hr>
<p>Questions about CBECS may be directed to:<br>
<a href="mailto:mailto:eiainfoconsumption&efficiency@eia.gov">Consumption and efficiency data</a></p>
*/ ?>

     
<!--<p>Specific questions on the Energy Supplier Survey may be directed to:</p>
<blockquote>
<p>Marilyn Worthy<br />
<a href="mailto:marilyn.worthy@eia.gov">marilyn.worthy@eia.gov</a><br />
CBECS/Energy Supplier Survey Manager
</blockquote>
<div class="clear"></div>-->
<?php /*
<hr>
<p>Specific questions on this product may be directed to:</p>
<blockquote>
  <div class="split_2columns">
    <p>Joelle Michaels<br />
      <a href="mailto:joelle.michaels@eia.gov">joelle.michaels@eia.gov</a><br />
      Survey Manager</p>
  </div>
  <div class="split_2columns">
    <p>Katie Lewis<br />
      <a href="mailto:katie.lewis@eia.gov">katie.lewis@eia.gov</a></p>
  </div>
</blockquote>
<div class="clear"></div>
*/ ?>