<div class="secondary">
    <ul>
        <li class="head">
            <h2>Most requested energy consumption &amp; efficiency data</h2></li>
        <li class="sub-head"><strong>Residential energy consumption</strong></li>
        <li>
            <ul>
                <li><a href="/consumption/residential/data/2015/index.php?view=characteristics">Household characteristics</a></li>
                <li><a href="/consumption/residential/data/2015/index.php?view=consumption">Home energy use &amp; costs</a></li>
                <li><a href="/consumption/residential/data/2015/index.php?view=microdata">Detailed household microdata</a></li>
            </ul>
</li>
        <li class="sub-head"><strong>Commercial energy consumption</strong></li>
        <li>
            <ul>
                <li><a href="/consumption/commercial/data/2012/index.php?view=characteristics">Building characteristics</a></li>
                <li><a href="/consumption/commercial/data/2012/index.php?view=consumption">Commercial energy use &amp; costs</a></li>
                <li><a href="/consumption/commercial/data/2012/index.php?view=microdata2003/index.php?view=microdata">Detailed buildings microdata</a></li>
            </ul>
</li>
        <li class="sub-head"><strong>Manufacturing energy consumption</strong></li>
        <li>
            <ul>
                <li><a href="/consumption/manufacturing/data/2014/">2014 data</a></li>
                <li><a href="/consumption/manufacturing/data/2010/">2010 data</a></li>
                <li><a href="/consumption/manufacturing/data/2006/">2006 data</a></li>
                <li><a href="/consumption/manufacturing/data/2002/">2002 data</a></li>
                <li><a href="/consumption/manufacturing/data/1998/">1998 data</a></li>
                <li><a href="/consumption/manufacturing/data/1994/">1994 data</a></li>
                <li><a href="/consumption/manufacturing/data/1991/">1991 data</a></li>
            </ul>
</li>
    </ul>
</div>