<div class="primary">
	<p>Find statistics on energy consumption and efficiency across all fuel sources.</p>
	<span class="expand-collapse-container">
		<i class="ico expand"><span>Expand all</span></i>
		<i class="ico collapse"><span>Collapse all</span></i>
	</span>
	<div class="accordion">

		<h3><a name="rec"></a>Residential Energy Consumption Survey data</h3>
		<div class="accordion-content">
			<ul>
				<li class="head">
					<a href="/consumption/residential/data/2015/index.php?view=characteristics">Household characteristics</a>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">May 2018</span>
				</li>
				<li>Characteristics data (including structural features, appliance stock, electronics stock, and square footage)for occupied primary housing units.</li>
			</ul>
			<ul>
				<li class="head">
					<a href="/consumption/residential/data/2015/index.php?view=consumption">Home energy use &amp; costs</a>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">May 2018</span>
				</li>
				<li>Energy consumption and expenditures for occupied primary housing units by end uses and by fuel.</li>
			</ul>
			<ul>
				<li class="head">
					<a href="/consumption/residential/data/2015/index.php?view=microdata">Detailed household microdata</a>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">May 2018</span>
				</li>
				<li>Data are available in two formats: CSV (a comma delimited file) and a SAS data file.</li>
			</ul>
		</div>


		<h3><a name="cec"></a>Commercial Buildings Energy Consumption Survey data</h3>
		<div class="accordion-content">
			<ul>
				<li class="head">
					<a href="/consumption/commercial/data/2012/">Building characteristics</a>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">March 2015</span>
				</li>
				<li>Detailed tabulated data providing number of buildings and floorspace by characteristics such as geographic region, building activity, size and age, employment and occupancy, energy sources used, and energy-related equipment.</li>
			</ul>
			<ul>
				<li class="head">
					<a href="/consumption/commercial/data/2012/index.php?view=consumption">Consumption and Expenditures</a>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">May, 2016</span>
				</li>
				<li>Detailed tabulated data providing total energy, electricity, natural gas, fuel oil and district heat consumption figures and data by end use (heating, cooling, lighting, etc.).</li>
			</ul>
			<ul>
				<li class="head">
					<a href="/consumption/commercial/data/2012/index.php?view=microdata">Detailed building microdata</a>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">May, 2016</span>
				</li>
				<li>Raw data for 6,720 buildings for data users to create custom tables that are not available through the tabulated information. The data represent commercial buildings from the 50 States and the District of Columbia. Each record corresponds
					to a single responding, in-scope sampled building. Data are available in two formats: a comma delimited file (CSV) and a SAS data file.</li>
			</ul>
		</div>


		<h3><a name="mfg"></a>Manufacturing Energy Consumption Survey data</h3>
		<div class="accordion-content">
			<ul>
				<li class="head">Consumption of energy for all purposes, by industry & region</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li>
					<span class="formats">Available formats:</span>
					<a href="manufacturing/data/2014/XLS/Table1_1.xlsx" title="Consumption of energy for all purposes, by industry & region">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a><a href="manufacturing/data/2014/pdf/Table1_1.pdf" class="ico pdf" title="Consumption of energy for all purposes, by industry & region">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
			<ul>
				<li class="head">
					Energy Used as a Nonfuel (Feedstock)</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li>
					<span class="formats">Available formats:</span>
					<a href="manufacturing/data/2014/xls/Table2_1.xlsx" title="Energy Used as a Nonfuel (Feedstock)">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a><a href="manufacturing/data/2014/pdf/Table2_1.pdf" class="ico pdf" title="Energy Used as a Nonfuel (Feedstock)">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
			<ul>
				<li class="head">
					Energy consumption as a fuel, by industry &amp; region</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li>
					<span class="formats">Available formats:</span>
					<a href="manufacturing/data/2014/xls/Table3_1.xlsx" title="Energy consumption as a fuel, by industry & region">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a><a href="manufacturing/data/2014/pdf/Table3_1.pdf" class="ico pdf" title="Energy consumption as a fuel, by industry & region">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
			<ul>
				<li class="head">
					Offsite-produced fuel consumption, by industry</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li>
					<span class="formats">Available formats:</span>
					<a href="manufacturing/data/2014/xls/Table4_1.xlsx" title="Offsite-produced fuel consumption, by industry">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a><a href="manufacturing/data/2014/pdf/Table4_1.pdf" class="ico pdf" title="Offsite-produced fuel consumption, by industry">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
			<ul>
				<li class="head">
					Total consumption of electricity, by industry &amp; region</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li>
					<span class="formats">Available formats:</span>
					<a href="manufacturing/data/2014/xls/Table11_1.xlsx" title="Total consumption of electricity, by industry & region">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a><a href="manufacturing/data/2014/pdf/Table11_1.pdf" class="ico pdf" title="Total consumption of electricity, by industry & region">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>