<div class="table-wrapper">
<table class="basic-table full-width">
	<caption>
		Energy consumption estimates by sector<br />
		<span class="units"> trillion Btu</span></caption>

	<thead>
		<tr>
			<th scope="col">&nbsp;</th>
			<th scope="col">
				<div>2014 (Jan-June)</div>
			</th>
			<th scope="col">
				<div>2013</div>
			</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Residential</td>
			<td>11,440</td>
			<td>21,287</td>
		</tr>
		<tr>
			<td>Commercial</td>
			<td>9,281</td>
			<td>18,047</td>
		</tr>
		<tr>
			<td>Industrial</td>
			<td>15,580</td>
			<td>31,154</td>
		</tr>
		<tr>
			<td>Transportation</td>
			<td>13,348</td>
			<td>27,147</td>
		</tr>
		<tr class="total">
			<td>Total primary</td>
			<td>49,659</td>
			<td>97,635</td>
		</tr>
	<tfoot>
		<tr>
			<td colspan="3">Source: U.S. Energy Information Administration, <a href="/totalenergy/data/monthly/#consumption											
">Monthly Energy Review</a></td>
		</tr>
	</tfoot>
	</tbody>
</table>
<?php /*
<caption>Weekly Retail Gasoline and Diesel Prices<br />
</caption>(dollars per gallon, including taxes)
*/ ?>
<?php /* Table header */ ?>