<span class="grey_side green_top">
            <h4>Survey Methods<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="2001_recs_methodology.cfm">2001</a>&nbsp;&nbsp;<a href="http://www.eia.gov/emeu/recs/recs97/rx97appa.html">1997</a></h4>
            <h4>Data Quality<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.eia.gov/emeu/recs/recs2001/appendixb.html">2001</a> <a href="http://www.eia.gov/emeu/recs/recs97/rx97appb.html">1997</a> <a href="http://www.eia.gov/emeu/recs/recs2d.html">1993</a></h4>
            <h4>Survey Forms<br />
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="recs_survey_forms.cfm">2009 2005 2001 1997 </a></h4>
            <h4>
              <a href="http://www.eia.gov/emeu/cbecs/glossary_1.html">Glossary</a> </h4>
            <h4>
              
              <a href="http://www.eia.gov/emeu/cbecs/census_maps.html"> Census  Map</a></h4>
            <h4>
              <a href="http://www.eia.gov/emeu/cbecs/climate_zones.html">U.S. 
              Climate Zones</a></h4>
          
              <?php /* EIB Promo */ ?>
          <?php /*span class="brt_blue_side">
            <h4 class="eib_side">What is the electric power grid and what are some challenges it faces?</h4>
            <p><a href="#">Read the Energy in Brief Article &rsaquo;</a></p>
          </span>
           EIB Promo 
           Graphic Promo 
          <span class="grey_side green_top">
            <h4>2007 State Electricity Profiles</h4>
            <h5>US Average Retail Price perKilowatthour is 9.13 Cents.</h5>
            <img src="/global/images/slush/state_map.png" />
            <h4 class="legend_title"><b>Average Retail Price </b><i>(Cents per Kilowatthour)</i></h4>
            <ul class="legend">
              <li class="leg01">5.07 &ndash; 6.83</li>
              <li class="leg04">8.54 &ndash; 12.88</li>
              <li class="leg03">6.84 &ndash; 7.44</li>
              <li class="leg05">13.01 &ndash; 21.29</li>
              <li class="leg03">7.57 &ndash; 8.53</li>
            </ul>
            <p class="no_btm_border"></p>
          </span>
           Graphic Promo 
           Update Promo Example 
          <span class="promo_side blue_top">
              <h4 class="updates_side">Updates have been made to Electricity Survey Forms <b>EIA-923</b> and <b>EIA-860</b></h4>
              <p><a href="#">Learn more about the updates &rsaquo;</a></p>
          </span*/ ?>
          <?php /* Update Promo Example */ ?>
            
</span>