<span class="grey_side blue_top ">
  <h4>End-use consumption<br />
    data &amp; surveys</h4>
  <p><a href="/consumption/residential/">Residential Energy Consumption (RECS)</a></p>
  <p><a href="/consumption/commercial/">Commercial Building Energy Consumption (CBECS)</a></p>
  <p><a href="/consumption/manufacturing/">Manufacturing Energy Consumption (MECS)</a></p>
  <p class="no_btm_border"><a href="/consumption/archive/rtecs/contents.html">Transportation (RTECS)</a></p>
</span>

<span class="grey_side blue_top side_list_nocolumn">
  <h4>Sector totals:</h4>
<ul>
      <li><a href="/totalenergy/data/annual/showtext.cfm?t=ptb0201a">annual</a> &mdash; 1949-2011 </li>
      <li><a href="/totalenergy/data/monthly/index.cfm#consumption">monthly</a> </li>
    </ul>
</span>

<span class="grey_side green_top side_list_nocolumn">
  <h4>Consumption and efficiency<br />
    analysis & projections </h4>
  <p class="no-border"><strong>Annual Energy Outlook 2013<br/>
  Reference Case:</strong></p>
    <ul>
    <li> <a href="/forecasts/aeo/er/early_consumption.cfm">consumption by sector projections</a></li>
    <li> <a href="/forecasts/aeo/er/early_intensity.cfm">energy intensity projections</a></li>
<?php /*  <li> <a href="/analysis/projection-data.cfm#annualproj">Reference case   projections</a></li>
      <li> <a href="/forecasts/aeo/chapter_market_trends.cfm">Market trends discussions</a></li> */ ?>
    </ul>
<?php /* <p><a href="/analysis/reports.cfm?t=128">More analysis &rsaquo;</a></p>*/ ?>
</span>
<?php include('global/includes/kids_dates.inc'); ?>

