<?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
                <li><a href="/consumption/residential/index.cfm">Residential Overview</a></li>
              </ul>
              
               <h4>2005 Data Tables<a href="../generic.cfm"></a></h4>

<p class="no_btm_border">  Most current data for Residential Energy Consumption Surveys.
  </p>
<ul>
  <li><a href="data/index.cfm">Household Characteristics </a></li>
<li> <a href="data/index.cfm">Home Energy Use & Costs</a></li>
</ul>

  <h4><a href="data/microdata/index.cfm">Public Use Microdata</a></h4>
<p class="no_btm_border">Comma delimited data files available for public use with various software applications.          </p>
              <ul>
                <li><a href="/consumption/residential/reports/">Analysis &amp; Reports</a></li>
              </ul>
              <ul>
                <li class="no_btm_border"><a href="/consumption/residential/methodology/">Methodology</a></li></ul>
              
          </span>
<?php /* Sidenav EIA Menu */ ?>