<?php /* Sidenav EIA Menu side_nav*/ ?>
<span class="grey_side blue_top side_list_nocolumn">
  <h4>Data Tables</h4>
  <p>Building Characteristics<br />
     <a href="/emeu/cbecs/cbecs2003/detailed_tables_2003/detailed_tables_2003.html">2003</a> |
     <a href="/emeu/cbecs/detailed_tables_1999.html">1999</a> |
     <a href="/emeu/cbecs/detailed_tables_1995.html">1995</a> |
     <a href="/emeu/cbecs/detailed_tables_1992.html">1992</a></p>
  <p>Consumption and Expenditures<br />
     <a href="/emeu/cbecs/cbecs2003/detailed_tables_2003/detailed_tables_2003.html#consumexpen03">2003</a> |
     <a href="/emeu/cbecs/detailed_tables_1999.html#ce">1999</a> |
     <a href="/emeu/cbecs/detailed_tables_1995.html#ce">1995</a> |
     <a href="/emeu/cbecs/detailed_tables_1992.html">1992</a></p>
  <p>End-Use Consumption<br />
     <a href="/emeu/cbecs/cbecs2003/detailed_tables_2003/detailed_tables_2003.html#enduse03">2003</a> |
     <a href="/emeu/cbecs/cbec-eu1.html">1995</a> |
     <a href="/emeu/cbecs/detailed_tables_1992.html">1992</a></p>
  <p class="no-border">Public Use Microdata<br />
     <a href="/emeu/cbecs/cbecs2003/public_use_2003/cbecs_pudata2003.html">2003</a> |
     <a href="/emeu/cbecs/1999publicuse/99microdat.html">1999</a> |
     <a href="/emeu/cbecs/microdat.html">1995</a> |
     <a href="/emeu/cbecs/92microdat.html">1992</a><br />
     <a href="/emeu/cbecs/pubuse89/cbecs_pudata1989.html">1989</a> |
     <a href="/emeu/cbecs/pubuse86/cbecs_pudata1986.html">1986</a> |
     <a href="/consumption/commercial/data/1983/cbecs_pudata1983.html">1983</a> |
     <a href="/consumption/commercial/data/1979/cbecs_pudata1979.html">1979</a></p>
</span> 
<span class="grey_side green_top side_list_nocolumn">
<h4>Large Hospital Buildings Report</h4>
<a href="/consumption/commercial/reports/2007/large-hospital.cfm"><img src="/consumption/commercial/images/large-hospital-report-callout.png" /></a>
<p><a href="/consumption/commercial/reports/2007/large-hospital.cfm">Read the report &#8250;</a></p>
</span>
<span class="blue_side">
    <h4 class="q_side"><a href="/EMEU/cbecs/faq.html#q1">What do you mean by "commercial" building?</a></h4>
    <p><a href="/EMEU/cbecs/faq.html">See all CBECS FAQs ></a></p>
  </span> 
<style>
.ajdustment1 li {line-height:16px;padding-bottom:7px;}
</style>
<span class="grey_side blue_top side_list_nocolumn">
  <h4>Methodology</h4>
  <ul class="ajdustment1">
    <li><a href="/consumption/commercial/2012-cbecs-building-sampling.cfm">How Will Buildings Be Selected for the 2012 CBECS?</a></li>
    <li><a href="/consumption/NAS.cfm">Assessment of EIA's Building Consumption Data</a></li>
    <li>Survey Methods<br />
        <a href="/emeu/cbecs/2003sample.html">2003</a> |
        <a href="/emeu/cbecs/1999sample.htm">1999</a> |
        <a href="/emeu/cbecs/detailed_tables_1995.html#tech">1995</a></li>
    <li><a href="/emeu/cbecs/building_types.html">Building Types Definitions</a></li>
    <li><a href="/emeu/cbecs/forms.html">Data Collection Forms</a></li>
    <li><a href="/emeu/cbecs/cbecs2003/background.html">Survey Background and Technical Information</a></li>
    <li><a href="/emeu/cbecs/comparesampdesign.html">Comparison Between Years</a></li>
    <li><a href="/emeu/cbecs/glossary_1.html">Glossary</a></li>
    <li><a href="/emeu/cbecs/census_maps.html">Census Map</a></li>
    <li><a href="/emeu/cbecs/climate_zones.html">U.S. Climate Zones</a></li>
  </ul>
</span>
<span class="grey_side blue_top side_list_nocolumn">
  <h4>Special Topics</h4>
  <ul class="ajdustment1">
    <li><a href="/consumption/commercial/reports/2007/large-hospital.cfm">Large Hospital Buildings (2007)</a></li>
    <li><a href="/emeu/cbecs/cbecs2003/officereport/office1.html">Office Buildings (2003)</a></li>
    <li><a href="/emeu/cbecs/cbecs2003/lighting/lighting1.html">Lighting in Commercial Buildings (2003)</a></li>
    <li><a href="/emeu/cbecs/cbecs2003/overview1.html">Overview of Commercial Buildings, 2003</a></li>
    <li><a href="/emeu/cbecs/pba99/intro.html">A Look at Principal Building Activities</a></li>
    <li><a href="/emeu/cbecs/char99/intro.html">1999 Building Characteristics Overview</a></li>
    <li><a href="/emeu/consumptionbriefs/cbecs/cbecs_trends/main_menu.html">Trends in the Commercial Buildings Sector </a></li>
    <li><a href="/emeu/cbecs/pc_copier/pccopier99.html">Computers and Photocopiers in Commercial Buildings</a></li>
    <li><a href="/emeu/cbecs/cbecsreports.html">Additional reports</a></li>
  </ul>
</span>
<span class="grey_side blue_top side_list_nocolumn">
  <h4>Archived Publications</h4>
  <ul class="ajdustment1">
    <li><a href="/emeu/cbecs/archive/arch_hist_pubs/cbecs_pubs.html">Historical Publications</a></li>
    <li><a href="/emeu/cbecs/report_1995.html">A Look at Commercial Buildings in 1995</a></li>
    <li><a href="/emeu/cbecs/cbecs1a.html">1992 Buildings Characteristics </a></li>
    <li><a href="/emeu/cbecs/cbecs1b.html">1992 Consumption and Expenditures </a></li>
    <li><a href="/emeu/cbecs/cbecs1f.html">Buildings and Energy in the 1980's </a></li>
    <li><a href="/emeu/cbecs/cbecs1e.html">Lighting in Commercial Buildings (1986)</a></li>
  </ul>
</span>
<?php /* Other Consumption Surveys */ ?>
        <div class="secondary">
<ul>
            <h4>Other End Use Surveys</h4>
            <p><a href="/consumption/residential/">Residential Buildings - RECS</a></p>
            <p><a href="/emeu/mecs/contents.html">Manufacturing - MECS</a>
      <p class="no-border"><a href="/consumption/archive/rtecs/contents.html">Transportation</a></p>
      </span>
<?php /* Sidenav EIA Menu */ ?>