<?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
              
                <li><a href="#">Overview</a></li>
              </ul>
              <ul>
                <li><a href="#" class="active">Data</a> </li>
              </ul>
              <ul>
                <li><a href="#">Analysis, projections &amp; reports</a></li>
              </ul>
              <ul>
                <li><a href="#">Glossary</a></li>
              </ul>
              
          </span>
<?php /* Sidenav EIA Menu */ ?>