<?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
                <li><a href="/consumption/industrial/data/2006/">Manufacturing Energy Consumption Surveys</a></li>
              </ul>
              <ul>
                <li>Data
                  <ul>
                    <li><a href="/consumption/industrial/data/2006/">2006</a></li>
                    <li><a href="/consumption/industrial/data/2002/">2002</a></li>
                    <li><a href="/consumption/industrial/data/archive.cfm">Archive</a></li>
                  </ul>
                </li>
              </ul>
              <ul>
                <li><a href="/consumption/industrial/reports/">Analysis &amp; Reports</a></li>
              </ul>
              <ul>
                <li class="no_btm_border"><a href="/consumption/industrial/methodology/">Methodology</a></li></ul>
              
          </span>
<?php /* Sidenav EIA Menu */ ?>