<?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
                <li><a href="http://www.eia.gov/emeu/mecs/contents.html">Manufacturing Energy Consumption Survey</a></li>
              </ul>
              <ul>
                <li>Data
                  <ul>
                    <li><a href="http://www.eia.gov/emeu/mecs/mecs2006/2006tables.html">2006</a></li>
 <?php /*<li><a href="/consumption/industrial/data/2002/">2002</a></li>
                    <li><a href="/consumption/industrial/data/archive.cfm">Archive</a></li>*/ ?>
                  </ul>
                </li>
              </ul>
              <ul>
                <li><a href="http://www.eia.gov/reports/index.cfm?t=Consumption&amp;s=a">Analysis &amp; Reports</a></li>
              </ul>
<?php /* <ul>
                <li class="no_btm_border"><a href="/consumption/industrial/methodology/">Methodology</a></li></ul>*/ ?>
              
          </span>
<?php /* Sidenav EIA Menu */ ?>