<?php include ('consumption/includes/side_nav_commercial.inc') ; ?>

<?php /*

<span class="grey_side green_top">
<p><a href="../commercial/about.cfm">About the CBECS</a></p>
<p><a href="../commercial/about.cfm">Survey Background and Technical Information</a></p>
</span> 

<?php if ( $pageYear == "") {?>
  <?php  } else { ?>
<span class="grey_side blue_top">

		<?php if ( $pageYear != "archive") {?>
      <h4><?php echo "$pageYear"?>
    <?php  } // end if ?>
    Survey Forms
    </h4>
    <?php if ( $pageYear == "2003") {?>
      <p>Insert 2003 links</p>
    <?php  } // end if ?>
    <?php if ( $pageYear == "1999") {?>
      <p>Insert 1999 links</p>
    <?php  } // end if ?>
    <?php if ( $pageYear == "1995") {?>
      <p>Insert 1995 links</p>
    <?php  } // end if ?>
    <?php if ( $pageYear == "1992") {?>
      <p>Insert 1992 links</p>
    <?php  } // end if ?>
    <?php if ( $pageYear == "previous") {?>
      <p>Insert Previous links</p>
    <?php  } // end if ?>
    <?php if ( $pageYear == "archive") {?>
      <p>Insert archive links</p>
    <?php  } // end if ?>

</span> 
<?php  } // end if ?>
<span class="grey_side green_top">
<h4>Other End Use Survey Data</h4>
<p><a href="../../manufacturing/">Manufacturing - CBECS</a></p>
<p><a href="../../residential/">Residential - RECS</a></p>
<p class="no-border"><a href="/emeu/rtecs/contents.html">Transportation</a></p>
</span> 
*/ ?>