          <span class="grey_side green_top">
            <h4>2006 Data Tables<a href="../generic.cfm"></a></h4>

<p class="no_btm_border">  Most current data for Manufacturing Energy Consumption Surveys.
  </p>
<ul>
<li><a href="data/2006/">Consumption</a></li>
<li><a href="data/2006/">Puchased Energy</a></li>
<li><a href="data/2006/">Energy Management Activities</a></li>
<li><a href="data/2006/">Fuel Switching</a></li>
</ul>
</span>

<span class="grey_side green_top">
<p class="no_btm_border">
          <a href="http://www.eia.gov/listserv_signup.html#consumption">Get e-mail updates on Commercial Buildings Energy Use</a></p>
          </span>