<?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
                <li><a href="/consumption/transportation/index.cfm">Transportation Overview</a></li>
              </ul>
              <ul>
                <li>Data
                  <ul>
                    <li><a href="http://www.eia.gov/emeu/rtecs/nhts_survey/2001/tablefiles/t0464(2005).pdf">2001</a></li>
                    <li><a href="ftp://ftp.eia.doe.gov/pub/consumption/transportation/tables94.pdf">1994</a></li>
                    <li><a href="http://www.eia.gov/emeu/rtecs/rtecs1991/tablefiles/t0464(1991).pdf">1991</a></li>
                    <li><a href="http://www.eia.gov/emeu/rtecs/archive/arch_datatables/rtecshist_datatables.html">Archive</a></li>
                  </ul>
                </li>
              </ul>
              <ul>
                <li><a href="/consumption/transportation/reports/">Analysis &amp; Reports</a></li>
              </ul>
              <ul>
                <li class="no_btm_border"><a href="/consumption/transportation/methodology/">Methodology</a></li></ul>
              
          </span>
<?php /* Sidenav EIA Menu */ ?>