          <span class="grey_side green_top">
            <h4>Data Tables<a href="../generic.cfm"></a></h4>
            All available data for Residential Energy Consumption Surveys.
          </span>
          <div class="secondary">
<ul>
            <h4>Public Use Microdata</h4>
            <p>Comma delimited data files available for public use with various software applications.</p>
            <h4>Survey Forms</h4>
            <p>Download the survey forms used to collect data.</p>
            <h4>About the Surveys</h4>
            <p>Learn about survey details including what has changed and new variables.</p>
          </span>
          <?php /* EIB Promo */ ?>
          <?php /*span class="brt_blue_side">
            <h4 class="eib_side">What is the electric power grid and what are some challenges it faces?</h4>
            <p><a href="#">Read the Energy in Brief Article &rsaquo;</a></p>
          </span>
           EIB Promo 
           Graphic Promo 
          <span class="grey_side green_top">
            <h4>2007 State Electricity Profiles</h4>
            <h5>US Average Retail Price per<br />Kilowatthour is 9.13 Cents.</h5>
            <img src="/global/images/slush/state_map.png" />
            <h4 class="legend_title"><b>Average Retail Price </b><br /><i>(Cents per Kilowatthour)</i></h4>
            <ul class="legend">
              <li class="leg01">5.07 &ndash; 6.83</li>
              <li class="leg04">8.54 &ndash; 12.88</li>
              <li class="leg03">6.84 &ndash; 7.44</li>
              <li class="leg05">13.01 &ndash; 21.29</li>
              <li class="leg03">7.57 &ndash; 8.53</li>
            </ul>
            <p class="no_btm_border"></p>
          </span>
           Graphic Promo 
           Update Promo Example 
          <span class="promo_side blue_top">
              <h4 class="updates_side">Updates have been made to Electricity Survey Forms <b>EIA-923</b> and <b>EIA-860</b></h4>
              <p><a href="#">Learn more about the updates &rsaquo;</a></p>
          </span*/ ?>
          <?php /* Update Promo Example */ ?>