<?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
                <h4>Residential Consumption:</h4>
                 <p class="no_btm_border"> <strong>Residential Sector Total</strong> </li>         
         <ul>
          <li><a href="/aer/txt/ptb0201e.html">annual</a> 	&mdash; 1949-2009<br />
          Annual Energy Review 2009<em></em></li>
          <li><a href="/mer/consump.html">monthly</a><br />
           <em>Monthly Energy Review</em></li>
          </ul>
       <!--  <p class="no_btm_border"><strong>Residential Energy Consumption Statistics</strong><br/>
           Residential Energy Consumption Survey 2005 and previous<br />  
           Energy use in homes by fuel type, housing type, and end uses
         </p>
                <ul>
          
          <li><a href="http://wwwdev.eia.gov/consumption/residential/data/2005/index.cfm">data </a></li><li><a href="http://wwwdev.eia.gov/consumption/residential/about_recs.cfm">about the survey</a></li>
          <li><a href="http://wwwdev.eia.gov/consumption/residential/reports/">analysis &amp; reports</a></li></ul><br />-->
                <span class="no_btm_border"><strong>Efficiency related:</strong></span>
                </p>
              
                              
                <ul>
                <li><a href="/emeu/recs/recs2005/hc2005_tables/detailed_tables2005.html">Lighting usage indicator tables</a><br />
                  Residential Energy Consumption Survey 2005</li>
          <li><a href="http://www.eia.gov/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=4-AEO2011&region=0-0&cases=ref2011-d120810c">Residential sector key indicators and consumption</a><br /> projections to 2035<br />
            <em>Annual Energy Outlook 2011, Early Release</em></li>
          
          
          </ul></ul>
              
</span>
<?php /* Sidenav EIA Menu */ ?>