<?php /* Renewable Sub Nav */ ?>
<div class="title bg_transportation">

	<a href="index.cfm">&lsaquo; Consumption & Efficiency</a>
	<h1>Tranportation</h1>
</div>
<?php /*/ Page/Section Title */ ?>
<div id="subnav">
	<?php /* Page/Sub Nav */ ?>
	<span class="right"><a href="#">Glossary &rsaquo;</a> <a href="#">FAQS &rsaquo;</a></span>
	<ul>
		<li class="subnav-overview"><a href="index.cfm">Overview</a></li>
		<li class="subnav-residential"><a href="residential.cfm">Residential</a></li>
		<li class="subnav-commercial"><a href="commercial.cfm">Commercial</a></li>
		<li class="subnav-industrial"><a href="industrial.cfm">Industrial</a></li>
		<li class="subnav-tranportation"><a href="transportation.cfm">Tranportation</a></li>
	</ul>
</div><?php /*/ Page/Sub Nav */ ?>