</div>
<!--
	<h2>Links</h2>

<p class="accessibility p">https://usability.yale.edu/web-Accessibilityarticles/links</p>

<script>
	function accessibilityLinkArticle() {
		var accessibilityLink = document.getElementById("accessibilityLinkStyleSwitcher")
		accessibilityLink.setAttribute('class', 'article')
	}

	function accessibilityLinkPrimary() {
		var accessibilityLink = document.getElementById("accessibilityLinkStyleSwitcher")
		accessibilityLink.setAttribute('class', 'primary')
	}

	function accessibilityLinkPrimaryAlt() {
		var accessibilityLink = document.getElementById("accessibilityLinkStyleSwitcher")
		accessibilityLink.setAttribute('class', 'primary-alt')
	}

	function accessibilityLinkSecondary() {
		var accessibilityLink = document.getElementById("accessibilityLinkStyleSwitcher")
		accessibilityLink.setAttribute('class', 'secondary')
	}

	function accessibilityLinkSecondaryAlt() {
		var accessibilityLink = document.getElementById("accessibilityLinkStyleSwitcher")
		accessibilityLink.setAttribute('class', 'secondary-alt')
	}
</script>
<div class="style-switcher">
	<button onclick="accessibilityLinkArticle()">Article</button>
<button onclick="accessibilityLinkPrimary()">Primary</button>
<button onclick="accessibilityLinkPrimaryAlt()">Primary-alt</button>
<button onclick="accessibilityLinkSecondary()">Secondary</button>
<button onclick="accessibilityLinkSecondaryAlt()">Secondary-alt</button>
</div>
</div>
<div class="article" id="accessibilityLinkStyleSwitcher">
	<p>These end-use sectors consume <a href="/tools/glossary/index.php?id=Primary energy">primary energy</a> and also purchase and use most of the electricity (a secondary energy source) the <a href="/tools/glossary/index.php?id=Electric power sector">electric power sector</a> produces and sells. The electric power sector consumes primary energy to generate electricity for sale to the other four sectors and for export to Canada and Mexico. The end-use sectors also produce some electricity for their own use, which in the industrial and commercial sectors is called <a href="/tools/glossary/index.php?id=Direct use">direct use</a>.</p>
</div>

<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

<pre><code class="language-html" id="accessibilityLink">&lt;div class="{article,primary,secondary,primary-alt,secondary-alt"&gt;
	&lt;p&gt;Lorem ipsum dolor sit amet dolor sit amet &lt;a href="..."&gt;consectetur adipiscing elit&lt;/a&gt; Lorem ipsum dolor sit amet dolor sit amet.&lt;/p&gt;
&lt;/div&gt;</code></pre>

	<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#accessibilityLink">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
	</div>
	</div>

	ul class="accessibility ul _bullet">
	<li class="accessibility li">
		<span class="eia-accessibility-link-link">Accessable Link</span>
		</div>
	<li class="accessibility li">
		<span class="eia-accessibility-link-active">Accessable Link Active</span>
		</div>
	<li class="accessibility li">
		<span class="eia-accessibility-link-visited">Accessable Link Visited</span>
		</div>
	<li class="accessibility li">
		<span class="eia-accessibility-link-hover">Accessable Link Hover</span>
		</div>
	<li class="accessibility li">
		<span class="eia-accessibility-link-focus">Accessable Link Focus</span>
		</div>
		</ul>

		<h3 class="h3 base">Screen-reader Only Link with Description</h3>
		<p class="accessibility p">It&apos;s most important for link text to make sense without the surrounding sentences or content. The link text alone should convey the function and purpose of the link. Link text should also be unique and easy to speak out loud.</p>
		<p class="accessibility p">Consider these guidelines when writing link text:</p>
		<ul class="accessibility ul _bullet">
			<li class="accessibility li">Avoid link text like “Click Here,” “More,” and “Read More.” These kinds of links can be confusing when a screen reader reads them out of context.</div>
			<li class="accessibility li">Use unique link text where possible. Speech recognition software users may have a bad experience with duplicated link text.</div>
			<li class="accessibility li">It is OK to link a full sentence, but avoid longer.</div>
			<li class="accessibility li">Use judgment when linking full URLs. When linking a URL, consider users who must speak it out loud and who must listen to a screen reader announce it.</div>
		</ul>

		<p class="accessibility p">
			<strong>Fallbacks</strong>
		</p>
		<p class="accessibility p">Occasionally, it may not be possible to make link text alone convey the link&apos;s purpose out of context. In those cases, a few fallback strategies are available:</p>
		<ul class="accessibility ul _bullet">
			<li class="accessibility li">The link together with the surrounding sentence, paragraph, or list item should be enough to convey a link&apos;s meaning or purpose.</div>
			<li class="accessibility li">You may give more context through the link&apos;s title attribute.</div>
			<li class="accessibility li">These approaches create a worse experience for users with disabilities, so they should a last resort.</div>
		</ul>
		<p class="accessibility p">https://usability.yale.edu/web-Accessibilityarticles/links</p>


		<p class="accessibility p">
			<a href="https://usability.yale.edu/web-Accessibilityarticles/links">https://usability.yale.edu/web-Accessibilityarticles/links</a>
		</p>
		<?php include('./includes/forms/accessibility/link-label-aria.inc') ?>
		<?php include('./includes/forms/accessibility/link-description-aria.inc') ?>
		-->