<h3>Icon with Description</h3>
<div class="accordion-content horizontal-icon-container spans">



	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico pdf">
				<span>PDF</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/pdf --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico xls">
				<span>XLS</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/xls --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico csv">
				<span>CSV</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/csv --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico interactive">
				<span>Interactive</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/interactive --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico ppt">
				<span>PPT</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/ppt --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico html">
				<span>HTML</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/html --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico doc">
				<span>DOC</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/doc --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico jspn">
				<span>JSON</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/json --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico image">
				<span>IMAGE</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/image --> -->
	</div>

	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico efile">
				<span>eFile</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/efile --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico txt">
				<span>TXT</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/txt --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico pedro">
				<span>PEDRO</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/pedro --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico api">
				<span>API</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/api --> -->
	</div>
	<div class="icon-container">
		<span class="formats">Available formats:</span>
		<a>
			<span class="eia ico zip">
				<span>ZIP</span>
			</span>
		</a>
		<!-- 		<?php include('./includes/icons/spans/zip --> -->
	</div>
</div>
</div>