<div class="primary">
    
    <p>
Find statistics on renewable energy consumption by source type, electric capacity and electricity generation from renewable sources, biomass and alternative fuels.</p>
<span class="expand-collapse-container"> <i class="ico expand"><span>Expand all</span></i> <i class="ico collapse"><span>Collapse all</span></i> </span>
<div class="accordion">
<h3><a name="summary"></a>Summary</h3>
    <div class="accordion-content">
        <ul>
            <li class="head">Production and consumption</li>
            <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('totalenergy/data/monthly/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span><a href="/totalenergy/data/monthly/">Monthly Energy Review</a></li>
            <li class="hide-bullet"><span class="source">Interactive data from:</span> <a href="/totalenergy/data/browser/">Total Energy Data Browse</a></li>
            <li class="list-item">
                <ul>
                    <li>Renewable energy production and consumption by source</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec10_3.pdf" alt="Renewable energy production and consumption by source"><span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T10.01&amp;freq=m" alt="Renewable energy production and consumption by source"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/?tbl=T10.01#/?f=M&start=200001" alt="Renewable energy production and consumption by source"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
                <ul>
                    <li>Renewable energy production and total energy production by state</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/state/seds/sep_prod/SEDS_Production_Report.pdf" alt="Renewable energy production and total energy production by state"><span class="ico pdf"><span>PDF</span></span></a></li>
                </ul>
                <ul>
                    <li>Total energy consumption of renewable and nonrenewable energy sources</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec1_7.pdf" alt="Total energy consumption of renewable and nonrenewable energy sources"><span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T01.03&amp;freq=m" alt="Total energy consumption of renewable and nonrenewable energy sources"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/?tbl=T01.03#/?f=M&start=200001" alt="Total energy consumption of renewable and nonrenewable energy sources"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
                <ul>
                    <li>Renewable energy consumption and total energy consumption by state</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/state/seds/sep_use/notes/use_print.pdf" alt="Renewable energy consumption and total energy consumption by state"><span class="ico pdf"><span>PDF</span></span></a></li>
                </ul>
                <ul>
                    <li>Renewable energy consumption by sector</li>
                    <li class="list-item">
                        <ul>
                            <li>Residential and commercial</li>
                            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec10_4.pdf" alt="Renewable energy consumption by sector   Residential and commercial"><span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T10.02A&amp;freq=m" alt="Renewable energy consumption by sector   Residential and commercial"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/?tbl=T10.01#/?f=M&start=200001" alt="Renewable energy consumption by sector   Residential and commercial"><span class="ico interactive"><span>Interactive</span></span></a></li>
                        </ul>
                        <ul>
                            <li>Industrial and transportation</li>
                            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec10_5.pdf" alt="Renewable energy consumption by sector    Industrial and transportation"><span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T10.02B&amp;freq=m" alt="Renewable energy consumption by sector    Industrial and transportation"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/?tbl=T10.01#/?f=M&start=200001" alt="Renewable energy consumption by sector    Industrial and transportation"><span class="ico interactive"><span>Interactive</span></span></a></li>
                        </ul>
                        <ul>
                            <li>Electric power</li>
                            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec10_6.pdf" alt="Renewable energy consumption by sector    Electric power"><span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T10.02C&amp;freq=m" alt="Renewable energy consumption by sector    Electric power"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/?tbl=T10.01#/?f=M&start=200001" alt="Renewable energy consumption by sector    Electric power"><span class="ico interactive"><span>Interactive</span></span></a></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
        <ul>
            <li class="head">Renewable electricity</li>
            <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('electricity/annual/includes/releasedate.inc') ?></span> <span class="pipe">|</span><span class="source">Data from: </span><a href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="list-item">
                <ul>
                    <li><a href="/electricity/annual/html/epa_04_03.html">Generation capacity</a></li>
                    <li>Capacity by energy source showing renewables' share</li>
					<li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_03.xlsx" alt="Generation capacity"><span class="ico xls"><span>XLS</span></span></a></li>
                </ul>
                <ul>
                    <li><a href="/electricity/annual/html/epa_03_01_b.html">Net generation from renewable sources</a></li>
					<li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_03_01_b.xlsx" alt="net generation from renewable sources"><span class="ico xls"><span>XLS</span></span></a></li>
                </ul>
            </li>
        </ul>
        <ul>
            <li class="head">International renewable electricity</li>
            <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
            <li>
                <ul>
                    <li><a href="/international/data/world/electricity/electricity-capacity?pd=2&p=0000000000000000000007vo7&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Renewable electricity installed capacity</a></li>
                    <li><a href="/international/data/world/electricity/electricity-capacity?pd=2&p=000000000000000000000000000001vm&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Net generation from renewable sources</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <h3><a name="biomass"></a>Biofuels</h3>
    <div class="accordion-content">
        <ul>
            <li class="head">Biofuels overview</li>
            <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('totalenergy/data/monthly/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span> <a href="/totalenergy/data/monthly/">Monthly Energy Review</a><li class="hide-bullet"><span class="source">Interactive data from:</span> <a href="/totalenergy/data/browser/">Total Energy Data Browser</a></li>
            <li class="list-item">
                <ul>
                    <li>Fuel ethanol overview</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec10_7.pdf" alt="Fuel ethanol overview"><span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T10.03&amp;freq=m" alt="Fuel ethanol overview"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/?tbl=T10.03#/?f=M&start=200001" alt="Fuel ethanol overview"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
                <ul>
                    <li>Biodiesel overview</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec10_8.pdf" alt="Biodiesel overview"><span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T10.04A&freq=m" alt="Biodiesel overview"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/index.php?tbl=T10.04A#/?f=M" alt="Biodiesel  overview"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
            </li>
        </ul>
        <ul>
            <li class="head"><a href="/biofuels/biomass/#table_data">Densified biomass fuel</a></li>
            <li>Monthly densified biomass fuel (wood pellets, compressed bricks/logs) data on manufacturing facilities and capacity, production, inventories, feedstocks and cost, sales and price, exports and price, and product characteristics</li>
        </ul>
        <ul>
            <li class="head">Monthly biodiesel production</li>
            <li><!-- class="include" --><span class="release-date">Release date: </span> <span class="date"><?php include('biofuels/biodiesel/production/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span> <a href="/biofuels/biodiesel/production/">Monthly Biodiesel Production Report</a></li>
            <li class="list-item">
                <ul>
                    <li>Production capacity and production</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table1.pdf" alt="Production capacity and production"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table1.xls" alt="Production capacity and production"><span class="ico xls"><span>XLS</span></span></a></li>
                </ul>
                <ul>
                    <li>Production, sales, and stocks</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table2.pdf" alt="Production, sales, and stocks"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table2.xls" alt="Production, sales, and stocks"><span class="ico xls"><span>XLS</span></span></a></li>
                </ul>
                <ul>
                    <li>Inputs to biodiesel production</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table3.pdf" alt="Inputs to biodiesel production"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table3.xls" alt="Inputs to biodiesel production"><span class="ico xls"><span>XLS</span></span></a></li>
                </ul>
                <ul>
                    <li>Producers and production capacity, by state</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table4.pdf" alt="Producers and production capacity, by state"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table4.xls" alt="Producers and production capacity, by state"><span class="ico xls"><span>XLS</span></span></a></li>
                </ul>
                <ul>
                    <li>Production by Petroleum Administration for Defense District</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table5.pdf" alt="Production by Petroleum Administration for Defense District"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table5.xls" alt="Production by Petroleum Administration for Defense District"><span class="ico xls"><span>XLS</span></span></a></li>
                </ul>
            </li>
        </ul>
        <ul>

            <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
            <li><a href="/international/data/world/biofuels/biofuels-production">Biofuels production </a></li>
            <li><a href="/international/data/world/biofuels/biofuels-consumption">Biofuels consumption</a></li>
        </ul>
    </div>
    <h3><a name="geothermal"></a>Geothermal</h3>
    <div class="accordion-content">
        <ul>
            <li class="head">Geothermal energy consumption</li>
            <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('totalenergy/data/monthly/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span> <a href="/totalenergy/data/monthly/">Monthly Energy Review</a></li>
            <!-- li> (<a href="/totalenergy/data/monthly/#petroleum">more on petroleum</a></li -->
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec10_3.pdf" alt="Geothermal energy consumption"><span class="ico pdf"><span>PDF</span></span></a>
        </ul>
<ul>

            <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
            <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=0000000000000000000000000000004&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Geothermal net electricity generation</a></li>
            <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=00000000000000000000002&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Geothermal electricity installed capacity</a></li>
      </ul>        
    </div>
    <h3><a name="hydro"></a>Hydropower</h3>
    <div class="accordion-content">
        <ul>
            <li class="head"><a href="/electricity/annual/html/epa_03_14.html" alt="Hydropower"></span -->Generation</a></li>
            <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('electricity/annual/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span> <a href="/electricity/annual/">Electric Power Annual</a>
            <li>Net generation from hydroelectric (conventional) power by state by sector</li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_03_14.xlsx" alt="Hydropower generation"><span class="ico xls"><span>XLS</span></span></a></li>
        </ul>
<ul>

            <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
            <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=000000000000000000000000000000g&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Hydrolectricity net electricity generation</a></li>
            <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=00000000000000000000008&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Hydrolectricity electricity installed capacity</a></li>
      </ul>    
    </div>
    <h3><a name="solar"></a>Solar/Photovoltaic</h3>
    <div class="accordion-content">
         <ul>
            <li class="head">Net generation from utility-scale solar by state by sector</li>
            <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('electricity/monthly/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Interactive data from:</span> <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?></li>
            <li class="list-item">
                <ul>
                    <li>Annual (back to 2001)</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&fuel=0041&geo=vvvvvvvvvvvvo&sec=g&linechart=ELEC.GEN.SUN-US-99.A&columnchart=ELEC.GEN.SUN-US-99.A&map=ELEC.GEN.SUN-US-99.A&freq=A&ctype=linechart&ltype=pin&rtype=s&maptype=0&rse=0&pin=" alt="solar annual (back to 2001)"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
                <ul>
                    <li>Monthly (back to 2001)</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&fuel=0041&geo=vvvvvvvvvvvvo&sec=g&linechart=ELEC.GEN.SUN-US-99.M&columnchart=ELEC.GEN.SUN-US-99.M&map=ELEC.GEN.SUN-US-99.M&freq=M&ctype=linechart&ltype=pin&rtype=s&pin=&rse=0&maptype=0" alt="solar monthly (back to 2001)"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
            </li>
            <li><a href="/electricity/annual/html/epa_04_02_b.html">Electric net summer capacity by solar and other renewable sources</a>, annual (back to 2009)</li>
            <li><!-- class="include" --><span class="release-date">Release date: </span> <span class="date"><?php include('electricity/annual/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span> <a href="/electricity/annual/">Electric Power Annual</a></li>
         </ul>
        <ul>
            <li class="head">Photovoltaic industry overview and shipments</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">July 29, 2022</span><span class="pipe">|</span><span class="source">Data from: </span><a href="/renewable/annual/solar_photo/">Solar Photovoltaic Cell/Module Shipments Report</a></li>
            <li class="list-item">
                <ul>
                    <li>Number of companies involved in photovoltaic activities and number of employees</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/renewable/annual/solar_photo/pdf/pv_table1.pdf" alt="Number of companies involved in photovoltaic activities and number of employees"><span class="ico pdf"><span>PDF</span></span></a></li>
                                </ul>
                <ul>
                    <li>Annual photovoltaic module shipments, back to 2006</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/renewable/annual/solar_photo/pdf/pv_table3.pdf" alt="Annual photovoltaic module shipments, back to 2006"><span class="ico pdf"><span>PDF</span></span></a></li>
                </ul>
                <ul>
                    <li><a href="/totalenergy/data/annual/showtext.php?t=ptb1008">Photovoltaic Cell and Module Shipments by Type, Trade, and Prices</a>, 1982-2010</li>
                    <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('totalenergy/data/annual/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from:</span> <a href="/totalenergy/data/annual/">Annual Energy Review, 1949 through 2011</a> <span class="alert">(no longer updated)</span></li>
                </ul>
            </li>
            <li>Solar Photovoltaic Cell/Module Shipments Reports:</li>
            <li>
                <ul>
                    <li><a href="/renewable/annual/solar_photo/">Annual Solar Photovoltaic Cell/Module Shipments Report</a></li>
                    <li><a href="/renewable/monthly/solar_photo/">Monthly Solar Photovoltaic Module Shipments Report</a></li>
                </ul>
            </li>
        </ul>
<ul>

            <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
            <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=00000000000000000000000000000004&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Solar net electricity generation</a></li>
            <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=0000000000000000000000002&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Solar electricity installed capacity</a></li>
      </ul>        
    </div>
    <h3><a name="wind"></a>Wind</h3>
    <div class="accordion-content">
        <ul>
            <li class="head">Net generation from wind by state by sector</li>
            <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('electricity/monthly/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Interactive data from:</span> <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?></li>
            <li class="list-item">
                <ul>
                    <li>Annual (back to 2001)</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/data/browser/#/topic/0?agg=1,0,2&amp;fuel=008&amp;geo=vvvvvvvvvvvvo&amp;sec=o3g&amp;linechart=ELEC.GEN.WND-US-99.A~ELEC.GEN.WND-IA-99.A~ELEC.GEN.WND-TX-99.A&amp;columnchart=ELEC.GEN.WND-US-99.A~ELEC.GEN.WND-IA-99.A~ELEC.GEN.WND-TX-99.A&amp;map=ELEC.GEN.WND-US-99.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" alt="wind annual (back to 2001)"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
                <ul>
                    <li>Monthly (back to 2001)</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/data/browser/#/topic/0?agg=1,0,2&amp;fuel=008&amp;geo=vvvvvvvvvvvvo&amp;sec=o3g&amp;linechart=ELEC.GEN.WND-US-99.M~ELEC.GEN.WND-IA-99.M~ELEC.GEN.WND-TX-99.M&amp;columnchart=ELEC.GEN.WND-US-99.M~ELEC.GEN.WND-IA-99.M~ELEC.GEN.WND-TX-99.M&amp;map=ELEC.GEN.WND-US-99.M&amp;freq=M&amp;start=200101&amp;end=201407&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" alt="wind monthly (back to 2001)"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
            </li>
            <li><a href="/electricity/annual/html/epa_04_02_b.html">Electric net summer capacity by wind and other renewable sources</a>, annual (back to 2009)</li>
            <li><!-- class="include" --><span class="release-date">Release date: </span> <span class="date"><?php include('electricity/annual/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span> <a href="/electricity/annual/">Electric Power Annual</a></li>
         </ul>
<ul>

            <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy Statistics</a></li>
            <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=0000000000000000000000000000001&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Wind net electricity generation</a></li>
            <li><a href="/international/data/world/electricity/electricity-generation?pd=2&p=00000000000000000000000g&u=0&f=A&v=mapbubble&a=-&i=none&vo=value&&t=C&g=00000000000000000000000000000000000000000000000001&l=249-ruvvvvvfvtvnvv1vrvvvvfvvvvvvfvvvou20evvvvvvvvvvvvvvs&s=94694400000&e=1514764800000">Wind electricity installed capacity</a></li>
      </ul>        
    </div>
    <h3><a name="alternative"></a>Alternative transportation fuels</h3>
    <div class="accordion-content">
        <ul>
            <li class="head">Alternative fueled and hybrid vehicles (on-road)</li>
            <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('renewable/afv/includes/releasedate.inc') ?></span> <span class="pipe">|</span><span class="source">Data from: </span> <a href="/survey/#eia-886">Annual Survey of Alternative Fueled Vehicles</a></li>
            <li>Data on alternative fuel vehicle (AFV) supply and fuel use and number of vehicles for four types of vehicle fleets: federal government, state government, transit agencies, and fuel providers; fleet &amp; fuel data back to 2003, supplier data back to 1994</li>
            <li class="list-spacer">
                <ul>
                    <li><a href="/renewable/afv/users.php?fs=a">Fleet &amp; fuel data</a></li>
                    <li><a href="/renewable/afv/supply.php">Supplier data (includes hybrid vehicles)</a></li>
                </ul>
            </li>
        </ul>
        <ul>
            <li class="head">Ethanol</li>
            <li class="list-item">
                <ul>
                    <li>Fuel ethanol overview</li>
                    <li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('totalenergy/data/monthly/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span> <a href="/totalenergy/data/monthly/">Monthly Energy Review</a><span class="pipe">|</span><span class="source">Data from: </span> <a href="/totalenergy/data/browser/?tbl=T10.03#/?f=M&start=200001">Total Energy Data Browser</a></li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec10_7.pdf" alt="Fuel ethanol overview"><span class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/xls.php?tbl=T10.03&amp;freq=m" alt="Fuel ethanol overview"><span class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a href="/totalenergy/data/browser/?tbl=T10.03#/?f=M&start=200001" alt="Fuel ethanol overview"><span class="ico interactive"><span>Interactive</span></span></a></li>
                </ul>
                <ul>
                    <li><a href="/petroleum/ethanolcapacity/index.php">Plant production capacity</a></li>
                    <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">August 26, 2019 </span> <span class="pipe">|</span> <span class="source">Data from: </span> <a href="/survey/#eia-819">Form EIA-819M Monthly Oxygenate Report</a></li>
                    <li>Production capacity data for all operating U.S. fuel ethanol production plants</li>
                </ul>
            </li>
        </ul>
        <ul>
            <li class="head">Monthly Biodiesel Production Report</li>
            <li><!-- class="include" --><span class="release-date">Release Date:</span> <span class="date"><?php include('biofuels/biodiesel/production/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from: </span> <a href="/biofuels/biodiesel/production/">Monthly Biodiesel Production Report</a></li>
            <li class="list-item">
                <ul>
                    <li>Production capacity and production</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table1.pdf" alt="Production capacity and production"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table1.xls" alt="Production capacity and production"><span class="ico xls"><span>XLS</span></span></a>
                </ul>
                <ul>
                    <li>Production, sales, and stocks</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table2.pdf" alt="Production, sales, and stocks"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table2.xls" alt="Production, sales, and stocks"><span class="ico xls"><span>XLS</span></span></a>
                </ul>
                <ul>
                    <li>Inputs to biodiesel production</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table3.pdf" alt="Inputs to biodiesel production"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table3.xls" alt="Inputs to biodiesel production"><span class="ico xls"><span>XLS</span></span></a>
                </ul>
                <ul>
                    <li>Producers and production capacity, by state</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table4.pdf" alt="Producers and production capacity, by state"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table4.xls" alt="Producers and production capacity, by state"><span class="ico xls"><span>XLS</span></span></a>
                </ul>
                <ul>
                    <li>Production by Petroleum Administration for Defense District</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/biofuels/biodiesel/production/table5.pdf" alt="Production by Petroleum Administration for Defense District"><span class="ico pdf"><span>PDF</span></span></a><a href="/biofuels/biodiesel/production/table5.xls" alt="Production by Petroleum Administration for Defense District"><span class="ico xls"><span>XLS</span></span></a>
                </ul>
            </li>
        </ul>
    </div>
</div>
</div>