<div class="primary">
  <p>
    Find statistics on electric power plants, capacity, generation, fuel consumption, sales, prices and customers.</p>
  <span class="expand-collapse-container"><span class="ico expand"><span>Expand all</span></span>
    <span class="ico collapse"><span>Collapse all</span></span>
  </span>
  <div class="accordion">
    <h3><a name="summary"></a>Summary</h3>
    <div class="accordion-content">
      <ul>
        <li class="head">Electricity overview</li>
        <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
            <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
         </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
            href="/totalenergy/data/monthly/">Monthly Energy Review</a><span class="pipe">|</span><span
            class="source">Interactive data from:</span> <a href="/totalenergy/data/browser/">Total Energy Data
            Browser</a></li>
        <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec7_3.pdf"
            title=" Electricity overview"><span class="ico pdf"><span>PDF</span></span></a><a
            href="/totalenergy/data/browser/csv.php?tbl=T07.01" title=" Electricity overview"><span
              class="ico csv"><span>CSV</span></span></a><a
            href="/totalenergy/data/browser/xls.php?tbl=T07.01&amp;freq=m" title=" Electricity overview"><span
              class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
            href="/beta/MER/?tbl=T07.01#/?f=M&start=200001" title=" Electricity overview"><span
              class="ico interactive"><span>Interactive</span></span></a></li>
      </ul>
      <ul>
        <li class="head">Total electric power industry summary statistics</li>
        <li class="list-item">
          <ul>
            <li class="head">Monthly</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('electricity/monthly/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/monthly/">Electric Power Monthly</a></li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_es1a"
                    title=" Total electric power industry summary statistics">Latest month </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_es1a.xlsx"
                    title=" Total electric power industry summary statistics - monthly"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_es1b"
                    title=" Total electric power industry summary statistics">Year-to-date </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_es1b.xlsx"
                    title=" Total electric power industry summary statistics - Year-to-date"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
          </ul>
          <ul>
            <li class="head">Annual (back to 2009)</li>
            <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                <?php include('electricity/annual/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/annual/html/epa_01_02.html">Summary statistics </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_01_02.xlsx"
                    title=" Total electric power industry summary statistics - annual"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_01_03.html">Supply and disposition of electricity </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_01_03.xlsx"
                    title=" Total electric power industry summary statistics - annual Supply and disposition of electricity"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul>
        <li><a href="/totalenergy/data/monthly/#electricity">...more national-level summary data </a></li>
      </ul>
      <ul>
        <li><a href="/electricity/state/">State summary statistics</a> (Capacity, generation, price, emissions and more)
        </li>
        <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">October 23, 2024 </span><span
            class="pipe">|</span><span class="source">Data from:</span> State Electricity Profiles</li>
      </ul>
      <ul>
        <li class="head">International electricity data</li>
        <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy
            Statistics</a></li>
        <li>
          <ul>
            <li><a href="/international/data/world/electricity/electricity-generation">Generation </a></li>
            <li><a href="/international/data/world/electricity/electricity-consumption">Electricity net consumption </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- END Summary Content -->
    <!-- BEGIN Sales, Revenue, Prices & Customers Content -->
    <h3><a name="sales"></a>Sales (consumption), revenue, prices &amp; customers</h3>

    <div class="accordion-content">
      <ul class="highlight">
        <li class="head">Monthly Form EIA-861M (formerly <a href="/survey/#eia-826">EIA-826</a>) detailed data (1990 -
          present)</li>
        <li>Revenue, sales, customer counts, and retail price by state and sector</li>
        <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/data/eia861m/xls/sales_revenue.xlsx"
            title=" Revenue, sales, customer counts, and retail price by state and sector"><span
              class="ico xls"><span>XLS</span></span></a></li>
      </ul>
      <ul>
        <li class="head">Retail sales of electricity to ultimate customers</li>
        <li class="list-item">
          <ul>
            <li class="head">Monthly</li>
            <li class="hide-bullet"><span class="release-date">Monthly Release date:</span> <span class="date">
                <?php include('electricity/monthly/includes/releasedate.inc') ?><span class="pipe">|</span><span
                  class="source">Data from:</span> <a href="/electricity/monthly/">Electric Power Monthly</a></li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_5_01">By sector</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_5_01.xlsx"
                    title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers"
                    href="/electricity/data/browser/#/topic/5?agg=0,1&geo=g&linechart=ELEC.SALES.US-ALL.M~ELEC.SALES.US-RES.M~ELEC.SALES.US-COM.M~ELEC.SALES.US-IND.M&columnchart=ELEC.SALES.US-ALL.M~ELEC.SALES.US-RES.M~ELEC.SALES.US-COM.M~ELEC.SALES.US-IND.M&map=ELEC.SALES.US-ALL.M&freq=M&start=200101&end=201412&ctype=linechart&ltype=pin&rtype=s&maptype=0&rse=0&pin=&endsec=vg"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_5_04_a"
                    title="Monthly retail sales of electricity to ultimate customers">By sector, by state </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_5_04_b.xlsx"
                    title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers"
                    href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;linechart=ELEC.SALES.TX-ALL.M~ELEC.SALES.TX-RES.M~ELEC.SALES.TX-COM.M~ELEC.SALES.TX-IND.M&amp;columnchart=ELEC.SALES.TX-ALL.M~ELEC.SALES.TX-RES.M~ELEC.SALES.TX-COM.M~ELEC.SALES.TX-IND.M&amp;map=ELEC.SALES.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201510&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
            </li>
          </ul>
          <ul>
            <li class="head">Annual</li>
            <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                <?php include('electricity/annual/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/annual/html/epa_02_02.html"
                    title=" Annual retail sales of electricity to ultimate customers">By sector, by provider</a> (back
                  to 2009, Interactive to 2001)</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_02_02.xlsx"
                    title=" Annual retail sales of electricity to ultimate customers"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;linechart=ELEC.SALES.US-ALL.A&amp;columnchart=ELEC.SALES.US-ALL.A&amp;map=ELEC.SALES.US-ALL.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                    title=" Annual retail sales of electricity to ultimate customers"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li>By sector, by state, by provider</li>
                <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                    <?php include('electricity/sales_revenue_price/includes/releasedate.inc') ?>
                 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                    href="/electricity/data/state/">Historical state date</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/xls/861/HS861 2010-.xlsx"
                    title=" Annual retail sales of electricity to ultimate customers by sector, by state, by provider"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li class="head">By state and utility</li>
                <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                    <?php include('electricity/sales_revenue_price/includes/releasedate.inc') ?>
                 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                    href="/electricity/sales_revenue_price/">Electric Sales, Revenue, and Price</a></li>
                <li class="list-item">
                  <ul>
                    <li>Residential sector</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_6.pdf"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility residential sector"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_6.xlsx"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility residential sector"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                  <ul>
                    <li>Commercial sector</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_7.pdf"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility commercial sector"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_7.xlsx"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility commercial sector"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                  <ul>
                    <li>Industrial sector</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_8.pdf"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility industrial sector"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_8.xlsx"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility industrial sector"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                  <ul>
                    <li>Transportation sector</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_9.pdf"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility transportation sector"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_9.xlsx"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility transportation sector"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                  <ul>
                    <li>Total, all sectors</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_10.pdf"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility all sectors"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_10.xlsx"
                        title=" Annual retail sales of electricity to ultimate customers By state and utility all sectors"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">Revenue from retail sales of electricity to ultimate customers</li>
        <li class="list-item">
          <ul>
            <li class="head">Monthly</li>
            <li class="hide-bullet"><span class="release-date">Monthly Release date:</span> <span class="date">
                <?php include('electricity/monthly/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/monthly/">Electric Power Monthly</a><span class="pipe">|</span><span
                class="source">Interactive data from:</span>
              <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
            </li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_5_02"
                    title="monthly revenue from retail sales of electricity to ultimate customers">By sector</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_5_02.xlsx"
                    title="monthly revenue from retail sales of electricity to ultimate customers"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    title="View in Total Energy Browser monthly revenue from retail sales of electricity to ultimate customers by sector"
                    href="/electricity/data/browser/#/topic/6?agg=0,1&amp;geo=g&amp;linechart=ELEC.REV.US-ALL.M~ELEC.REV.US-RES.M~ELEC.REV.US-COM.M~ELEC.REV.US-IND.M&amp;columnchart=ELEC.REV.US-ALL.M~ELEC.REV.US-RES.M~ELEC.REV.US-COM.M~ELEC.REV.US-IND.M&amp;map=ELEC.REV.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_5_05_a"
                    title="monthly revenue from retail sales of electricity to ultimate customers">By sector, by
                    state</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_5_05_a.xlsx"
                    title="monthly revenue from retail sales of electricity to ultimate customers"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    title="View in Total Energy Browser monthly revenue from retail sales of electricity to ultimate customers by sector, by state"
                    href="/electricity/data/browser/#/topic/6?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
            </li>
          </ul>
          <ul>
            <li class="head">Annual</li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/annual/html/epa_02_03.html"
                    title=" annual revenue from retail sales of electricity to ultimate customers By sector">By sector,
                    by provider</a> (back to 2009)</li>
                <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                    <?php include('electricity/annual/includes/releasedate.inc') ?>
                 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                    href="/electricity/annual/">Electric Power Annual</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_02_03.xlsx"
                    title=" Revenue from Sales of Electricity to Ultimate Customers"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>By sector, by state, by provider</li>
                <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                    <?php include('electricity/sales_revenue_price/includes/releasedate.inc') ?>
                 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                    href="/electricity/data/state/">Historical state date</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/xls/861/HS861 2010-.xlsx"
                    title="Annual retail sales of electricity to ultimate customers by sector, by state, by provider"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>By sector, by state (back to 2001)</li>
                <li class="hide-bullet"><span class="source">Interactive data from:</span>
                  <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
                </li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;linechart=ELEC.SALES.US-ALL.A&amp;columnchart=ELEC.SALES.US-ALL.A&amp;map=ELEC.SALES.US-ALL.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                    title=" annual revenue from retail sales of electricity to ultimate customers By sector, by state, by provider (back to 2005)"><span
                      class="ico interactive"><span>Interactive</span></span></a></span></li>
              </ul>
              <ul>
                <li class="head">By state and utility</li>
                <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                    <?php include('electricity/sales_revenue_price/includes/releasedate.inc') ?>
                 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                    href="/electricity/sales_revenue_price/">Electric Sales, Revenue, and Price</a></li>
                <li class="list-item">
                  <ul>
                    <li>Residential sector</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_6.pdf"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility residential, sector"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_6.xlsx"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, residential sector"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                  <ul>
                    <li>Commercial sector</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_7.pdf"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, commercial sector"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_7.xlsx"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, commercial sector"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                  <ul>
                    <li>Industrial sector</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_8.pdf"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility Industrial sector"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_8.xlsx"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, Industrial sector"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                  <ul>
                    <li>Transportation sector</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_9.pdf"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, transportation sector"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_9.xlsx"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, transportation sector"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                  <ul>
                    <li>Total, all sectors</li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/sales_revenue_price/pdf/table_10.pdf"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, all sectors"><span
                          class="ico pdf"><span>PDF</span></span></a><a
                        href="/electricity/sales_revenue_price/xls/table_10.xlsx"
                        title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, all sectors"><span
                          class="ico xls"><span>XLS</span></span></a></li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">Average retail price of electricity to ultimate customers:</li>
        <li class="list-item">
          <ul>
            <li class="head">Average monthly bill <span class="release-date">(Annual data)</li>
            <li>Release date:</span> <span class="date">
                <?php include('electricity/sales_revenue_price/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/sales_revenue_price/">Electric Sales, Revenue, and Price</a></li>
            <li class="list-item">
              <ul>
                <li>Residential average monthly bill by Census Division, and State
                </li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_5A.pdf"
                    title=" Residential average monthly bill by Census Division, and State"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_5A.xlsx"
                    title="Residential average monthly bill by Census Division, and State"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Commercial average monthly bill by Census Division, and State
                </li>

                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_5B.pdf"
                    title=" Commercial average monthly bill by Census Division, and State"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_5B.xlsx"
                    title="Commercial average monthly bill by Census Division, and State"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Industrial average monthly bill by Census Division, and State
                </li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_5C.pdf"
                    title=" Industrial average monthly bill by Census Division, and State"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_5C.xlsx"
                    title="Industrial average monthly bill by Census Division, and State"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="list-item">
        <li class="head">Monthly retail price</li>
        <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
            <?php include('electricity/monthly/includes/releasedate.inc') ?>
         </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
            href="/electricity/monthly/">Electric Power Monthly</a></li>
        <li class="hide-bullet"><span class="source">Interactive data from:</span>
          <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
        </li>

        <li class="list-item">
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_5_03"
                title="Monthly average retail price of electricity to ultimate customers">By sector</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_5_03.xlsx"
                title="Monthly average retail price of electricity to ultimate customers"><span
                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                title="View in Total Energy Browser Monthly average retail price of electricity to ultimate customers by sector"
                href="/electricity/data/browser/#/topic/7?agg=0,1&amp;geo=g&amp;linechart=ELEC.PRICE.US-ALL.M~ELEC.PRICE.US-RES.M~ELEC.PRICE.US-COM.M~ELEC.PRICE.US-IND.M&amp;columnchart=ELEC.PRICE.US-ALL.M~ELEC.PRICE.US-RES.M~ELEC.PRICE.US-COM.M~ELEC.PRICE.US-IND.M&amp;map=ELEC.PRICE.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg"><span
                  class="ico interactive"><span>Interactive</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_5_06_a"
                title="Annual  average retail price of electricity to ultimate customers">By sector, by state</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_5_06_a.xlsx"
                title="Monthly average retail price of electricity to ultimate customers"><span
                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                title="View in Total Energy Browser Annual  average retail price of electricity to ultimate customers by sector"
                href="/electricity/data/browser/#/topic/7?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"><span
                  class="ico interactive"><span>Interactive</span></span></a></li>
          </ul>
        </li>
        <li>
        <li class="head">Annual retail price</li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/annual/html/epa_02_04.html"
                title="Annual  average retail price of electricity to ultimate customers">By sector, by provider</a>
              (back to 2009)</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('electricity/annual/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_02_04.xlsx"
                title="Annual  average retail price of electricity to ultimate customers  by sector, by provider(back to 2005)"><span
                  class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li>By sector, by state, by provider</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('electricity/sales_revenue_price/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/data/state/">Historical state date</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/data/state/xls/861/HS861 2010-.xlsx"
                title="Annual retail sales of electricity to ultimate customers by sector, by state, by provider"><span
                  class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li>By sector, by state (back to 2001)</li>
            <li class="hide-bullet"><span class="source">Interactive data from:</span>
              <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
            </li>
          </ul>
          <ul>
            <li class="head">By state and utility</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('electricity/sales_revenue_price/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/sales_revenue_price/">Electric Sales, Revenue, and Price</a></li>
            <li class="list-item">
              <ul>
                <li>Residential sector</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_6.pdf"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, residential sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_6.xlsx"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, residential sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Commercial sector</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_7.pdf"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, commercial sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_7.xlsx"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, commercial sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Industrial sector</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_8.pdf"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, industrial sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_8.xlsx"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, industrial sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Transportation sector</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_9.pdf"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, transportation sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_9.xlsx"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, transportation sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>All sectors</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_10.pdf"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, all sectors"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_10.xlsx"
                    title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, all sectors"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <!--
</li>
</ul>
-->
      <ul>
        <li class="head">Number of customers (annual):</li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/annual/html/epa_02_01.html"
                title=" Number of customers (annual) (back to 2009)">By sector, by provider</a> (back to 2005)</li>
            <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                <?php include('electricity/annual/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_02_01.xlsx"
                title=" Number of customers (annual) (back to 2005)"><span class="ico xls"><span>XLS</span></span></a>
            </li>
          </ul>
          <ul>
            <li class="head">By sector by state and/or utility</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('electricity/sales_revenue_price/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/data/state/">Historical state date</a></li>
            <li class="list-item">
              <ul>
                <li>By state, by provider</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/xls/861/HS861%202010-.xlsx"
                    title="Annual retail sales of electricity to ultimate customers by sector, by state, by provider"><span>XLS</span></span></a>
                </li>
              </ul>
              <ul>
                <li>By state by sector</li>
                <li><span class="source">Data from:</span> <a href="/electricity/sales_revenue_price/">Electric Sales,
                    Revenue, and Price</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_1.pdf"
                    title=" Number of customers (annual) (back to 2005) by state, by sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_1.xlsx"
                    title=" Number of customers (annual) (back to 2005) by state, by sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Residential sector</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_6.pdf"
                    title=" Number of customers (annual) (back to 2005) by state, residential sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_6.xlsx"
                    title=" Number of customers (annual) (back to 2005) by state, residential sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Commercial sector</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_7.pdf"
                    title=" Number of customers (annual) (back to 2005) by state, commercial sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_7.xlsx"
                    title=" Number of customers (annual) (back to 2005) by state, commercial sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Industrial sector</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_8.pdf"
                    title=" Number of customers (annual) (back to 2005) by state, industrial sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_8.xlsx"
                    title=" Number of customers (annual) (back to 2005) by state, industrial sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Transportation sector</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_9.pdf"
                    title=" Number of customers (annual) (back to 2005) by state, transportation sector"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_9.xlsx"
                    title=" Number of customers (annual) (back to 2005) by state, transportation sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>All sectors by state and utility</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/sales_revenue_price/pdf/table_10.pdf"
                    title=" Number of customers (annual) (back to 2005) by state, all sectors"><span
                      class="ico pdf"><span>PDF</span></span></a><a
                    href="/electricity/sales_revenue_price/xls/table_10.xlsx"
                    title=" Number of customers (annual) (back to 2005) by state, all sectors"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">International electricity data</li>
        <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy
            Statistics</a></li>
        <li>
          <ul>
            <li><a href="/international/data/world/electricity/electricity-consumption">Electricity net consumption</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>

    <h3><a name="netmetering"></a>Net metering</h3>
    <div class="accordion-content">
      <ul>
        <li class="head">Net metering</li>
        <li class="list-item">
          <ul>
            <li class="head">Monthly (back to 2011)</li>
            <li>
              <ul>
                <li><a href="/electricity/data/eia861m/#netmeter">Net metering</a> - capacity, number of meters, and
                  energy sold back, by state, sector, and utility</li>
                <li><a href="/electricity/data/eia861m/#ammeter">Advanced metering</a> - number and megawatthours
                  served, by state by sector</li>
              </ul>
            </li>
          </ul>
          <ul>
            <li class="head">Annual (back to 2009)</li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/annual/html/epa_04_10.html">Net metering customers and capacity by technology
                    type, by end use sector</a></li>
                <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                    <?php include('electricity/annual/includes/releasedate.inc') ?>
                 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                    href="/electricity/annual/">Electric Power Annual</a></li>
                <li class="hide-bullet"><span class="formats">Available formats: </span> <a href="/electricity/annual/xls/epa_04_10.xlsx"
                    title=" annual net metering back to 2005"><span class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>




    <h3><a name="generation"></a>Generation and thermal output</h3>
    <div class="accordion-content">
      <ul class="highlight">
        <li class="head">Detailed preliminary <a href="/survey/#eia-923">EIA-923</a> monthly and annual survey data
          (back to 1990)</li>
        <li>
          <ul>
            <li><a href="/electricity/data/eia923/">Plant-level generation and fuel consumption data </a></li>
            <li>State-level generation and fuel consumption data</li>
            <li class="list-item">
              <ul>
                <li>Monthly (back to 2001)</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/generation_monthly.xlsx"
                    title=" State-level generation and fuel consumption, monthly (back to 2001)"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Annual (back to 1990)</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/annual_generation_state.xls"
                    title=" State-level generation and fuel consumption, annual (back to 1990)"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">Net generation</li>
        <li class="list-item">
          <ul>
            <li class="head">Monthly</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('electricity/monthly/includes/releasedate.inc') ?><span class="pipe">|</span><span
                  class="source">Data from:</span> <a href="/electricity/monthly/">Electric Power Monthly</a></li>
            <li class="hide-bullet"><span class="source">Interactive data from:</span>
              <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
            </li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_1_01" title="Monthly Net generation">By
                    all energy sources</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_1_01.xlsx"
                    title="Monthly Net generation By all energy sources"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/0?agg=0,1&amp;fuel=vtvo&amp;geo=vvvvvvvvvvvvo&amp;linechart=ELEC.GEN.ALL-US-99.M&amp;columnchart=ELEC.GEN.ALL-US-99.M&amp;map=ELEC.GEN.ALL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                    title="Monthly Net generation By all energy sources"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_1_01_a" title="Monthly Net generation">By
                    type of renewable source</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_1_01_a.xlsx"
                    title="Monthly Net generation By type of renewable source"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/0?agg=1,0,2&amp;fuel=02&amp;geo=vvvvvvvvvvvvo&amp;sec=o3g&amp;linechart=ELEC.GEN.AOR-US-99.M~ELEC.GEN.AOR-US-1.M~ELEC.GEN.AOR-US-94.M~ELEC.GEN.AOR-US-96.M~ELEC.GEN.AOR-US-97.M&amp;columnchart=ELEC.GEN.AOR-US-99.M~ELEC.GEN.AOR-US-1.M~ELEC.GEN.AOR-US-94.M~ELEC.GEN.AOR-US-96.M~ELEC.GEN.AOR-US-97.M&amp;map=ELEC.GEN.AOR-US-99.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin="
                    title="Monthly Net generation By type of renewable source"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li>By energy source (plus by annual back to 1950)</li>
                <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                    <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
                 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                    href="/totalenergy/data/monthly/">Monthly Energy Review</a><span class="pipe">|</span><span
                    class="source">Interactive data from:</span> <a href="/totalenergy/data/browser/">Total Energy Data
                    Browser</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec7_5.pdf"
                    title="Monthly Net generation By energy source (plus by annual back to 1950)"><span
                      class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/csv.php?tbl=T07.02A"
                    title="Monthly Net generation By energy source (plus by annual back to 1950)"><span
                      class="ico csv"><span>CSV</span></span></a><a
                    href="/totalenergy/data/browser/xls.php?tbl=T07.02A&amp;freq=m"
                    title="Monthly Net generation By energy source (plus by annual back to 1950)"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/beta/MER/?tbl=T07.02A#/?f=A&amp;start=1949&amp;end=2014&amp;charted=1-2-3-5-8-14"
                    title="Monthly Net generation By energy source (plus by annual back to 1950)"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li class="head">By energy source and producing sector</li>
                <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                    <?php include('electricity/monthly/includes/releasedate.inc') ?><span class="pipe">|</span><span
                      class="source">Data from:</span> <a href="/electricity/monthly/">Electric Power Monthly</a></li>
                <li class="hide-bullet"><span class="source">Interactive data from:</span>
                  <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
                </li>
                <li class="list-item">
                  <ul>
                    <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_1_02_a"
                        title="Monthly Net generation By energy source and producing sector">Electric utilities</a></li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/monthly/xls/table_1_02.xlsx"
                        title="Monthly Net generation By energy source and producing sector Electric utilities"><span
                          class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                        href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=8&amp;linechart=ELEC.GEN.ALL-US-1.M~ELEC.GEN.COW-US-1.M~ELEC.GEN.NG-US-1.M~ELEC.GEN.NUC-US-1.M~ELEC.GEN.HYC-US-1.M&amp;columnchart=ELEC.GEN.ALL-US-1.M~ELEC.GEN.COW-US-1.M~ELEC.GEN.NG-US-1.M~ELEC.GEN.NUC-US-1.M~ELEC.GEN.HYC-US-1.M&amp;map=ELEC.GEN.ALL-US-1.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                        title="Monthly Net generation By energy source and producing sector Electric utilities"><span
                          class="ico interactive"><span>Interactive</span></span></a></li>
                  </ul>
                  <ul>
                    <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_1_02_b"
                        title="Monthly Net generation By energy source and producing sector">Independent power
                        producers</a></li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/monthly/xls/table_1_03.xlsx"
                        title="Monthly Net generation By energy source and producing sector  Independent power producers"><span
                          class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                        href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;linechart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;columnchart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;map=ELEC.GEN.ALL-US-94.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                        title="Monthly Net generation By energy source and producing sector  Independent power producers Electric utilities"><span
                          class="ico interactive"><span>Interactive</span></span></a></li>
                  </ul>
                  <ul>
                    <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_1_02_c"
                        title="Monthly Net generation By energy source and producing sector">Commercial combined heat
                        and power sector</a></li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/monthly/xls/table_1_04.xlsx"
                        title="Monthly Net generation By energy source and producing sector Commercial combined heat and power sector"><span
                          class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                        href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;linechart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;columnchart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;map=ELEC.GEN.ALL-US-94.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                        title="Monthly Net generation By energy source and producing sector Commercial combined heat and power sector"><span
                          class="ico interactive"><span>Interactive</span></span></a></li>
                  </ul>
                  <ul>
                    <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_1_02_d"
                        title="Monthly Net generation By energy source and producing sector">Industrial combined heat
                        and power sector</a></li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/monthly/xls/table_1_05.xlsx"
                        title="Monthly Net generation By energy source and producing sector Industrial combined heat and power sector"><span
                          class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                        href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=0g&amp;linechart=ELEC.GEN.ALL-US-5.M~ELEC.GEN.COW-US-5.M~ELEC.GEN.AOR-US-5.M~ELEC.GEN.NG-US-5.M&amp;columnchart=ELEC.GEN.ALL-US-5.M~ELEC.GEN.COW-US-5.M~ELEC.GEN.AOR-US-5.M~ELEC.GEN.NG-US-5.M&amp;map=ELEC.GEN.ALL-US-5.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                        title="Monthly Net generation By energy source and producing sector Industrial combined heat and power sector"><span
                          class="ico interactive"><span>Interactive</span></span></a></li>
                  </ul>
                  <ul>
                    <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_1_02_e"
                        title="Monthly Net generation By energy source and producing sector">Residential combined heat
                        and power sector</a></li>
                    <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                        href="/electricity/monthly/xls/table_1_05.xlsx"
                        title="Monthly Net generation By energy source and producing sector Residential combined heat and power sector"><span
                          class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                        href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vtvv&amp;geo=g&amp;sec=004&amp;freq=M&amp;start=200101&amp;end=201610&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin="
                        title="Monthly Net generation By energy source and producing sector Residential combined heat and power sector"><span
                          class="ico interactive"><span>Interactive</span></span></a></li>
                  </ul>
                </li>
                <li class="list-spacer"><a href="/electricity/monthly/#generation">... more monthly generation data from
                    the <a href="/electricity/monthly/#four">Electric Power Monthly</a></li>
              </ul>
            </li>
            <li class="list-item">
              <ul>
                <li class="head">Annual</li>
                <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                    <?php include('electricity/annual/includes/releasedate.inc') ?>
                 </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                    href="/electricity/annual/">Electric Power Annual</a></li>
                <li class="hide-bullet"><span class="source">Interactive data from:</span>
                  <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
                </li>
                <li class="list-item">
                  <ul>
                    <li class="head">By all energy sources and by producing sector</li>
                    <li class="list-item">
                      <ul>
                        <li><a href="/electricity/annual/html/epa_03_01_a.html"
                            title="Annual Net generation By all energy sources and by producing sector">All sectors</a>
                        </li>
                        <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                            href="/electricity/annual/xls/epa_03_01_a.xlsx"
                            title="Annual Net generation By all energy sources and by producing sector  All sectors"><span
                              class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                            href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=04&amp;linechart=ELEC.GEN.ALL-US-7.A~ELEC.GEN.COW-US-7.A~ELEC.GEN.NG-US-7.A~ELEC.GEN.AOR-US-7.A&amp;columnchart=ELEC.GEN.ALL-US-7.A~ELEC.GEN.COW-US-7.A~ELEC.GEN.NG-US-7.A~ELEC.GEN.AOR-US-7.A&amp;map=ELEC.GEN.ALL-US-7.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                            title="Annual Net generation By all energy sources and by producing sector  All sectors"><span
                              class="ico interactive"><span>Interactive</span></span></a></li>
                      </ul>
                      <ul>
                        <li><a href="/electricity/annual/html/epa_03_02_a.html"
                            title="Annual Net generation By all energy sources and by producing sector">Electric
                            utilities</a></li>
                        <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                            href="/electricity/annual/xls/epa_03_02_a.xlsx"
                            title="Annual Net generation By all energy sources and by producing sector  Electric utilities"><span
                              class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                            href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=8&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin="
                            title="Annual Net generation By all energy sources and by producing sector  Electric utilities"><span
                              class="ico interactive"><span>Interactive</span></span></a></li>
                      </ul>
                      <ul>
                        <li><a href="/electricity/annual/html/epa_03_03_a.html"
                            title="Annual Net generation By all energy sources and by producing sector">Independent
                            power producers</a></li>
                        <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                            href="/electricity/annual/xls/epa_03_03_a.xlsx"
                            title="Annual Net generation By all energy sources and by producing sector  Independent power producers"><span
                              class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                            href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                            title="Annual Net generation By all energy sources and by producing sector  Independent power producers"><span
                              class="ico interactive"><span>Interactive</span></span></a></li>
                      </ul>
                      <ul>
                        <li><a href="/electricity/annual/html/epa_03_04_a.html" title="Annual Net generation">Commercial
                            sector</a></li>
                        <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                            href="/electricity/annual/xls/epa_03_04_a.xlsx"
                            title="Annual Net generation   Commercial sector"><span
                              class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                            href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=01&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin="
                            title="Annual Net generation   Commercial sector"><span
                              class="ico interactive"><span>Interactive</span></span></a></li>
                      </ul>
                      <ul>
                        <li><a href="/electricity/annual/html/epa_03_05_a.html" title="Annual Net generation">Industrial
                            sector</a></li>
                        <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                            href="/electricity/annual/xls/epa_03_05_a.xlsx"
                            title="Annual Net generation   Industrial sector"><span
                              class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                            href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                            title="Annual Net generation   Industrial sector"><span
                              class="ico interactive"><span>Interactive</span></span></a></li>
                      </ul>
                      <ul>
                        <li class="head">By type of renewable source</li>
                        <li class="list-item">
                          <ul>
                            <li><a href="/electricity/annual/html/epa_03_01_b.html"
                                title="Annual Net generation  By type of renewable source">All sectors</a></li>
                            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                                href="/electricity/annual/xls/epa_03_01_b.xlsx"
                                title="Annual Net generation  By type of renewable source All sectors"><span
                                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                                href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                                title="Annual Net generation  By type of renewable source All sectors"><span
                                  class="ico interactive"><span>Interactive</span></span></a></li>
                          </ul>
                          <ul>
                            <li><a href="/electricity/annual/html/epa_03_02_b.html"
                                title="Annual Net generation  By type of renewable source">Electric utilities</a></li>
                            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                                href="/electricity/annual/xls/epa_03_02_b.xlsx"
                                title="Annual Net generation  By type of renewable source Electric utilities"><span
                                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                                href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=8&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin="
                                title="Annual Net generation  By type of renewable source Electric utilities"><span
                                  class="ico interactive"><span>Interactive</span></span></a></li>
                          </ul>
                          <ul>
                            <li><a href="/electricity/annual/html/epa_03_03_b.html"
                                title="Annual Net generation  By type of renewable source">Independent power
                                producers</a></li>
                            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                                href="/electricity/annual/xls/epa_03_03_b.xlsx"
                                title="Annual Net generation  By type of renewable source Independent power producers"><span
                                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                                href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=00g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                                title="Annual Net generation  By type of renewable source Independent power producers"><span
                                  class="ico interactive"><span>Interactive</span></span></a></li>
                          </ul>
                          <ul>
                            <li><a href="/electricity/annual/html/epa_03_04_b.html"
                                title="Annual Net generation  By type of renewable source">Commercial sector</a></li>
                            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                                href="/electricity/annual/xls/epa_03_04_b.xlsx"
                                title="Annual Net generation  By type of renewable source Commercial sector"><span
                                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                                href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=01&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin="
                                title="Annual Net generation  By type of renewable source Commercial sector"><span
                                  class="ico interactive"><span>Interactive</span></span></a></li>
                          </ul>
                          <ul>
                            <li><a href="/electricity/annual/html/epa_03_05_b.html"
                                title="Annual Net generation  By type of renewable source">Industrial sector</a></li>
                            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                                href="/electricity/annual/xls/epa_03_05_b.xlsx"
                                title="Annual Net generation  By type of renewable source Industrial sector"><span
                                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                                href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                                title="Annual Net generation  By type of renewable source Industrial sector"><span
                                  class="ico interactive"><span>Interactive</span></span></a></li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">Useful thermal output</li>
        <li class="list-item">
          <ul>
            <li class="head">By energy source and type of combined heat and power producers</li>
            <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                <?php include('electricity/annual/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/annual/html/epa_03_23.html" title="Useful thermal output">All sectors</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_03_23.xlsx"
                    title="Useful thermal output All sectors"><span class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_03_24.html" title="Useful thermal output">Electric power
                    sector</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_03_24.xlsx"
                    title="Useful thermal output Electric power sector"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_03_25.html" title="Useful thermal output">Commercial
                    sector</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_03_25.xlsx"
                    title="Useful thermal output Commercial sector"><span class="ico xls"><span>XLS</span></span></a>
                </li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_03_26.html" title="Useful thermal output">Industrial
                    sector</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_03_26.xlsx"
                    title="Useful thermal output Industrial sector"><span class="ico xls"><span>XLS</span></span></a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">International electricity data</li>
        <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy
            Statistics</a></li>
        <li>
          <ul>
            <li><a href="/international/data/world/electricity/electricity-generation">Generation </a></li>
          </ul>
        </li>
      </ul>

    </div>
    <!-- END Generation and Thermal Output Content -->
    <!-- BEGIN Electric Power Plants Generating Capacity Content -->
    <h3><a name="gencapacity"></a>Capacity of electric power plants</h3>

    <div class="accordion-content">
      <ul class="highlight">
        <li class="head">Detailed <a href="/survey/#eia-860">EIA-860</a> survey data</li>
        <li>
          <ul>
            <li><a href="/electricity/data/eia860M/">Preliminary monthly electric generator inventory </a></li>
            <li><a href="/electricity/data/eia860/">Annual generator-level capacity information</a> (back to 1990)</li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="list-item">
          <ul>
            <li class="head">Monthly</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('electricity/monthly/includes/releasedate.inc') ?><span class="pipe">|</span><span
                  class="source">Data from:</span> <a href="/electricity/monthly/">Electric Power Monthly</a></li>
            <li class="list-item">
              <ul>
                <li>New electric generating units</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_6_03.xlsx"
                    title="Monthly New electric generating units"><span class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Planned electric generating unit additions</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_6_05.xlsx"
                    title="Monthly Planned electric generating unit additions"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Planned electric generating unit retirements</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_6_06.xlsx"
                    title="Monthly Planned electric generating unit retirements"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Retired electric generating units</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_6_04.xlsx"
                    title="Monthly Retired electric generating units"><span class="ico xls"><span>XLS</span></span></a>
                </li>
              </ul>
            </li>
          </ul>
          <ul>
            <li class="head">Annual</li>
            <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                <?php include('electricity/annual/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/annual/html/epa_04_03.html" title="Annual Net generation">By energy source</a>
                </li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_03.xlsx"
                    title="Annual Net generation By energy source"><span class="ico xls"><span>XLS</span></span></a>
                </li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_04_04.html" title="Annual Net generation">By producer type</a>
                </li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_04.xlsx"
                    title="Annual Net generation By producer type"><span class="ico xls"><span>XLS</span></span></a>
                </li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_04_02_a.html" title="Annual Net generation">By energy source,
                    by producer </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_02_a.xlsx"
                    title="Annual Net generation By energy source, by producer"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_04_02_b.html" title="Annual Net generation">By other
                    renewables, by producer </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_02_b.xlsx"
                    title="Annual Net generation By other renewables, by producer"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Existing capacity by energy source, by producer, by state back to 2000 (annual data from the
                  EIA-860)</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/existcapacity_annual.xlsx"
                    title="Existing capacity by energy source, by producer, by state back to 2000 (annual data from: the EIA-860)"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_04_06.html">Additions, retirements and changes in 2019 </a>
                </li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_06.xlsx"
                    title="Annual Additions, retirements and changes in 2019"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_04_05.html">Planned generating capacity changes, by energy
                    source, 2020-2024</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_05.xlsx"
                    title="Annual Planned generating capacity changes, by energy source, 2020-2024"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_04_01.html">Count of power plants by predominant source </a>
                </li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_01.xlsx"
                    title="Annual Count of power plants by predominant source"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_08_01.html">Heat rates for selected energy sources </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_08_02.xlsx"
                    title="Annual Heat rates for selected energy sources"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_08_02.html">Heat rates by prime mover </a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_04.xlsx"
                    title="Annual Heat rates by prime mover"><span class="ico xls"><span>XLS</span></span></a></li>

                <!--
<li>Proposed additions by year, energy source, and state (annual <span class="source">Data from:</span> the</li>
<li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_04_04.xlsx" title="Annual Heat rates by prime mover"><span class="ico xls"><span>XLS</span></span></a></li>
-->
              </ul>
              <ul>
                <li>Proposed additions by year, energy source, and state (annual data from the <a
                    href="/electricity/data/eia860/">Form EIA-860</a>)</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/plancapacity_annual.xls"
                    title="Annual Proposed additions by year, energy source, and state"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="list-item">
          <ul>
            <li class="head">Daily nuclear capacity status/outages (with annual capacity)</li>
            <li class="list-item">
              <ul>
                <li>Status of nuclear power plants</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/beta/outages/"
                    title="Status of nuclear power plants"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">International electricity data</li>
        <li><span class="source">Data from:</span> <a href="/international/data/world/">International Energy
            Statistics</a></li>
        <li>
          <ul>
            <li><a href="/international/data/world/electricity/electricity-capacity">Capacity </a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- END Electric Power Plants Generating Capacity Content -->
    <!-- BEGIN Consumption of Fuels Used to Generate Electricity Content -->
    <h3><a name="consumption"></a>Consumption of fuels used to generate electricity</h3>

    <div class="accordion-content">
      <ul class="highlight">
        <li class="head">Detailed <a href="/survey/#eia-923">EIA-923</a> (and previous) annual and preliminary monthly
          survey data</li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/data/eia923/">By plant and utility/operator</a></li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">Monthly and annual</li>
        <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
            <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
         </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
            href="/totalenergy/data/monthly/">Monthly Energy Review</a><span class="pipe">|</span><span
            class="source">Interactive data from:</span><a href="/totalenergy/data/browser/">Total Energy Data
            Browser</a></li>
        <li class="list-item">
          <ul>
            <li>All combustible fuels (monthly back to 1973, annual to 1949)</li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec7_9.pdf"
                title="All combustible fuels (monthly back to 1973, annual to 1949)"><span
                  class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/csv.php?tbl=T07.03A"
                title="All combustible fuels (monthly back to 1973, annual to 1949)"><span
                  class="ico csv"><span>CSV</span></span></a><a
                href="/totalenergy/data/browser/xls.php?tbl=T07.03A&amp;freq=m"
                title="All combustible fuels (monthly back to 1973, annual to 1949)"><span
                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                href="/beta/MER/?tbl=T07.03A#/?f=M&amp;start=200001"
                title="All combustible fuels (monthly back to 1973, annual to 1949)"><span
                  class="ico interactive"><span>Interactive</span></span></a></li>
          </ul>
          <ul>
            <li class="head">By energy source</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('electricity/monthly/includes/releasedate.inc') ?><span class="pipe">|</span><span
                  class="source">Data from:</span> <a href="/electricity/monthly/">Electric Power Monthly</a></li>
            <li class="hide-bullet"><span class="source">Interactive data from:</span>
              <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
            </li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_2_01_a"
                    title="Consumption of fuels used to generate electricity by">Coal</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_2_01_a.xlsx"
                    title="Consumption of fuels used to generate electricity by coal"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=8&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.COW-US-99.M~ELEC.CONS_EG.COW-US-1.M~ELEC.CONS_EG.COW-US-94.M~ELEC.CONS_EG.COW-US-96.M~ELEC.CONS_EG.COW-US-97.M&amp;columnchart=ELEC.CONS_EG.COW-US-99.M~ELEC.CONS_EG.COW-US-1.M~ELEC.CONS_EG.COW-US-94.M~ELEC.CONS_EG.COW-US-96.M~ELEC.CONS_EG.COW-US-97.M&amp;map=ELEC.CONS_EG.COW-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                    title="Consumption of fuels used to generate electricity by coal"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_2_02_a"
                    title="Consumption of fuels used to generate electricity by">Petroleum liquids</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_2_02_a.xlsx"
                    title="Consumption of fuels used to generate electricity by Petroleum liquids"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=4&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.PEL-US-99.M~ELEC.CONS_EG.PEL-US-1.M~ELEC.CONS_EG.PEL-US-94.M~ELEC.CONS_EG.PEL-US-96.M~ELEC.CONS_EG.PEL-US-97.M&amp;columnchart=ELEC.CONS_EG.PEL-US-99.M~ELEC.CONS_EG.PEL-US-1.M~ELEC.CONS_EG.PEL-US-94.M~ELEC.CONS_EG.PEL-US-96.M~ELEC.CONS_EG.PEL-US-97.M&amp;map=ELEC.CONS_EG.PEL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                    title="Consumption of fuels used to generate electricity by Petroleum liquids"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_2_03_a"
                    title="Consumption of fuels used to generate electricity by">Petroleum coke</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_2_03_a.xlsx"
                    title="Consumption of fuels used to generate electricity by Petroleum coke"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=2&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.PC-US-99.M~ELEC.CONS_EG.PC-US-1.M~ELEC.CONS_EG.PC-US-94.M~ELEC.CONS_EG.PC-US-96.M~ELEC.CONS_EG.PC-US-97.M&amp;columnchart=ELEC.CONS_EG.PC-US-99.M~ELEC.CONS_EG.PC-US-1.M~ELEC.CONS_EG.PC-US-94.M~ELEC.CONS_EG.PC-US-96.M~ELEC.CONS_EG.PC-US-97.M&amp;map=ELEC.CONS_EG.PC-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                    title="Consumption of fuels used to generate electricity by Petroleum coke"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_2_04_a"
                    title="Consumption of fuels used to generate electricity by">Natural gas</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_2_04_a.xlsx"
                    title="Consumption of fuels used to generate electricity by Natural gas"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                    title="Consumption of fuels used to generate electricity by Natural gas"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
            </li>
          </ul>
          <ul>
            <li class="head">By industry type and state</li>
            <li class="list-item">
              <ul>
                <li>Monthly</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/consumption_monthly.xls"
                    title="Consumption of fuels used to generate electricity by industry type and state, monthly"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li>Annual (back to 1990)</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/data/state/annual_consumption_state.xls"
                    title="Consumption of fuels used to generate electricity by industry type and state, annual"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
            <li>... more fuel consumption data from: <a href="/electricity/monthly/#two">Electric Power Monthly</a> and
              <a href="/electricity/annual/#five">Electric Power Annual</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- END Consumption of Fuels Used to Generate Electricity Content -->
    <!-- BEGIN Receipts of Fossil-Fuels for Electricity Generation Content -->
    <h3><a name="fossilfuels"></a>Receipts of fossil-fuels for electricity generation</h3>
    <div class="accordion-content">
      <ul>
        <li class="head">Monthly summary</li>
        <li class="hide-bullet"><span class="release-date">Monthly Release date:</span> <span class="date">
            <?php include('electricity/monthly/includes/releasedate.inc') ?><span class="pipe">|</span><span
              class="source">Data from:</span> <a href="/electricity/monthly/">Electric Power Monthly</a></li>
        <li class="list-item">
          <ul>
            <li>Physical units</li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_es2a.xlsx"
                title="Monthly summary Receipts of fossil-fuels for electricity generation Physical units"><span
                  class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li>Btu</li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_es2b.xlsx"><span
                  class="ico xls"><span>XLS</span></span></a></li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">By fuel</li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_4_06_a"
                title="Monthly summary Receipts of fossil-fuels for electricity generation">Coal</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_4_06_a.xlsx"
                title="Monthly summary Receipts of fossil-fuels for electricity generation coal"><span
                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=8&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.COW-US-99.M&amp;columnchart=ELEC.RECEIPTS.COW-US-99.M&amp;map=ELEC.RECEIPTS.COW-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                title="Monthly summary Receipts of fossil-fuels for electricity generation coal"><span
                  class="ico interactive"><span>Interactive</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_4_07_a"
                title="Monthly summary Receipts of fossil-fuels for electricity generation">Petroleum liquids</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_4_07_a.xlsx"
                title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum liquids"><span
                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=4&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.PEL-US-99.M&amp;columnchart=ELEC.RECEIPTS.PEL-US-99.M&amp;map=ELEC.RECEIPTS.PEL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum liquids"><span
                  class="ico interactive"><span>Interactive</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_4_08_a"
                title="Monthly summary Receipts of fossil-fuels for electricity generation">Petroleum coke</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_4_08_a.xlsx"
                title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum coke"><span
                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=2&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.PC-US-99.M&amp;columnchart=ELEC.RECEIPTS.PC-US-99.M&amp;map=ELEC.RECEIPTS.PC-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum coke"><span
                  class="ico interactive"><span>Interactive</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_4_09_a"
                title="Monthly summary Receipts of fossil-fuels for electricity generation">Natural gas</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_4_09_a.xlsx"
                title="Monthly summary Receipts of fossil-fuels for electricity generation natural gas"><span
                  class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=1&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.NG-US-99.M&amp;columnchart=ELEC.RECEIPTS.NG-US-99.M&amp;map=ELEC.RECEIPTS.NG-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                title="Monthly summary Receipts of fossil-fuels for electricity generation natural gas"><span
                  class="ico interactive"><span>Interactive</span></span></a></li>
          </ul>
        </li>
        <li>... more fuel receipts data from: <a href="/electricity/monthly/#four"
            title="more fuel receipts data from:">Electric Power Monthly</a> and <a href="/electricity/annual/#seven"
            title="more fuel receipts">Electric Power Annual</a></li>
      </ul>
    </div>
    <!-- END Monthly Receipts of Fossil-Fuels for Electricity Generation Content -->
    <!-- BEGIN Average Cost of Fossil-Fuels for Electricity Generation Content -->
    <h3><a name="avgcost"></a>Average cost of fossil-fuels for electricity generation</h3>

    <div class="accordion-content">
      <ul class="highlight">
        <li class="head">Detailed <a href="/survey/#eia-923">EIA-923</a> (and previous) annual and preliminary monthly
          survey data</li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/data/eia923/">By plant and utility/operator</a></li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="list-item">
          <ul>
            <li class="head">Monthly</li>
            <li class="head">Average cost of fossil fuels delivered by state</li>
            <li class="hide-bullet"><span class="release-date">Monthly Release date:</span> <span class="date">
                <?php include('electricity/monthly/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/monthly/">Electric Power Monthly</a><span class="pipe">|</span><span
                class="source">Interactive data from:</span>
              <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
            </li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_4_10_a"
                    title="Monthly Average cost of fossil fuels delivered by state">Coal</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_4_10_a.xlsx"
                    title="Monthly Average cost of fossil fuels delivered by state  Coal"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=8&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.COW-US-98.M&amp;columnchart=ELEC.COST_BTU.COW-US-98.M&amp;map=ELEC.COST_BTU.COW-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                    title="Monthly Average cost of fossil fuels delivered by state  Coal"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_4_11_a"
                    title="Monthly Average cost of fossil fuels delivered by state">Petroleum liquids</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_4_11_a.xlsx"
                    title="Monthly Average cost of fossil fuels delivered by state Petroleum liquids"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=4&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.PEL-US-98.M&amp;columnchart=ELEC.COST_BTU.PEL-US-98.M&amp;map=ELEC.COST_BTU.PEL-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                    title="Monthly Average cost of fossil fuels delivered by state Petroleum liquids"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_4_12_a"
                    title="Monthly Average cost of fossil fuels delivered by state">Petroleum coke</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_4_12_a.xlsx"
                    title="Monthly Average cost of fossil fuels delivered by state Petroleum coke"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=2&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.PC-US-98.M&amp;columnchart=ELEC.COST_BTU.PC-US-98.M&amp;map=ELEC.COST_BTU.PC-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                    title="Monthly Average cost of fossil fuels delivered by state Petroleum coke"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_4_13_a"
                    title="Monthly Average cost of fossil fuels delivered by state">Natural gas</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_4_13_a.xlsx"
                    title="Monthly Average cost of fossil fuels delivered by state Natural gas"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=1&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.NG-US-98.M&amp;columnchart=ELEC.COST_BTU.NG-US-98.M&amp;map=ELEC.COST_BTU.NG-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                    title="Monthly Average cost of fossil fuels delivered by state Natural gas"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
            </li>
            <li>... more fuel cost data from: <a href="/electricity/monthly/#four">Electric Power Monthly</a></li>
          </ul>
        </li>
        <li class="list-item">
          <ul>
            <li class="head">Annual</li>
            <li class="head">Receipts, average cost, and quality of fossil fuels for electricity generation</li>
            <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                <?php include('electricity/annual/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/annual/html/epa_07_01.html">Receipts, cost, and quality of coal, petroleum,
                    and natural gas</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_07_01.xlsx"
                    title="Receipts, cost, and quality of coal, petroleum, and natural gas"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_07_02.html">Receipts and quality of coal</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_07_02.xlsx"
                    title="Receipts and quality of coal"><span class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_07_03.html">Average quality of coal, petroleum, and natural
                    gas</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_07_03.xlsx"
                    title="Average quality of coal, petroleum, and natural gas"><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_07_04.html">Weighted average cost of coal, petroleum, and
                    natural gas</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                    href="/electricity/annual/xls/epa_07_04.xlsx"><span class="ico xls"><span>XLS</span></span></a></li>
              </ul>
            </li>
            <li>... more fuel cost data from: <a href="/electricity/annual/#seven">Electric Power Annual</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- END Average Cost of Fossil-Fuels for Electricity Generation Content -->
    <!-- BEGIN Fossil-Fuel Stocks for Electricity Generation Content -->
    <h3><a name="ffstocks"></a>Fossil-fuel stocks for electricity generation</h3>

    <div class="accordion-content">
      <ul>
        <li class="head">Stocks of fossil fuels by</li>
        <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
            <?php include('electricity/monthly/includes/releasedate.inc') ?>
         </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
            href="/electricity/monthly/">Electric Power Monthly</a><span class="pipe">|</span><span
            class="source">Interactive data from:</span>
          <?php include('electricity/monthly/includes/electricity-data-browser.inc') ?>
        </li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_3_01"
                title="Stocks of fossil fuels by">Electric power sector</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_3_01.xlsx"
                title="Stocks of fossil fuels by Electric power sector"><span
                  class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_3_02"
                title="Stocks of fossil fuels by">State</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_3_02.xlsx"
                title="Stocks of fossil fuels by state"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_3_03"
                title="Stocks of fossil fuels by">Census division</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_3_03.xlsx"
                title="Stocks of fossil fuels by Census division"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/monthly/epm_table_grapher.php?t=epmt_3_04" title="Stocks of fossil fuels by">Coal
                and rank</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_3_04.xlsx"
                title="Stocks of fossil fuels by Coal and rank"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li>State and Census division</li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/data/browser/#/topic/11?agg=2,0,1&amp;fuel=e&amp;geo=vvvvvvvvvvvvo&amp;sec=008&amp;freq=M&amp;start=200801&amp;end=201411&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                title="Stocks of fossil fuels by State and Census division"><span
                  class="ico interactive"><span>Interactive</span></span></a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- END Fossil-Fuel Stocks for Electricity Generation Content -->
    <!-- BEGIN Electricity Costs Content -->
    <!-- END Electricity Costs Content -->
    <!-- BEGIN Revenue and Exepense Statistics for... Content -->
    <h3><a name="revenue"></a>Cost, revenue and expenses</h3>
    <div class="accordion-content">
      <ul>
        <li class="head">For major investor-owned utilities</li>
        <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
            <?php include('electricity/annual/includes/releasedate.inc') ?>
         </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
            href="/electricity/annual/">Electric Power Annual</a></li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/annual/html/epa_08_03.html">Revenue and expense statistics </a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_08_03.xlsx"
                title="Revenue and expense statistics"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/annual/html/epa_08_04.html">Average power plant operating expenses </a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_08_03.xlsx"
                title="Average power plant operating expenses"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
        </li>
        <li class="head">Forecast assumptions</li>
        <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">February 3, 2021</span><span
            class="pipe">|</span><span class="source">Data from:</span> <a href="/outlooks/aeo/">Annual Energy Outlook
            2021</a></li>
        <li>
          <ul>
            <li><a href="/outlooks/aeo/electricity_generation/">Levelized cost of new generating technologies</a></li>
            <li><a href="/outlooks/aeo/assumptions/pdf/elec_cost_perf.pdf">Cost and performance characteristics of new
                generating technologies</a></li>
          </ul>
        </li>

        <li class="head">Generator construction cost data</li>

        <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">July 14, 2021</span><span
            class="pipe">|</span><span class="source">Data from:</span> <a href="/electricity/data/eia860/">Form
            EIA-860</a></li>

        <li>
          <ul>
            <li><a href="/electricity/generatorcosts/">For electric generators installed in 2019</a></li>

            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/generatorcosts/xls/generator_costs_2019.xlsx"
                title="Generator Construction cost data for electric generators installed in 2019 "><span
                  class="ico xls"><span>XLS</span></span></a></li>
            <li><a href="/electricity/generatorcosts/">For electric generators installed in 2018</a></li>

            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/generatorcosts/xls/generator_costs_2018.xlsx"
                title="Generator Construction cost data for electric generators installed in 2018 "><span
                  class="ico xls"><span>XLS</span></span></a></li>

            <li><a href="/electricity/generatorcosts/archive/2017/">For electric generators installed in 2017</a></li>

            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/generatorcosts/archive/2017/xls/generator_costs_2017.xlsx"
                title="Generator Construction cost data for electric generators installed in 2017 "><span
                  class="ico xls"><span>XLS</span></span></a></li>


            <li><a href="/electricity/generatorcosts/archive/2016/">For electric generators installed in 2016</a></li>

            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/generatorcosts/archive/2016/xls/generator_costs_2016.xlsx"
                title="Generator Construction cost data for electric generators installed in 2016 "><span
                  class="ico xls"><span>XLS</span></span></a></li>

            <li><a href="/electricity/generatorcosts/archive/2015/">For electric generators installed in 2015</a></li>

            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/generatorcosts/archive/2015/xls/generator_costs_2015.xlsx"
                title="Generator Construction cost data for electric generators installed in 2015 "><span
                  class="ico xls"><span>XLS</span></span></a></li>

            <li><a href="/electricity/generatorcosts/archive/2014/">For electric generators installed in 2014</a></li>

            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/generatorcosts/archive/2014/xls/generator_costs_2014.xlsx"
                title="Generator Construction cost data for electric generators installed in 2014 "><span
                  class="ico xls"><span>XLS</span></span></a></li>

            <li><a href="/electricity/generatorcosts/archive/2013/">For electric generators installed in 2013</a></li>

            <li class="hide-bullet"><span class="formats">Available formats:</span> <a
                href="/electricity/generatorcosts/archive/2013/xls/generator_costs_2013.xlsx"
                title="Generator Construction cost data for electric generators installed in 2013 "><span
                  class="ico xls"><span>XLS</span></span></a></li>

          </ul>
        </li>

    </div>
    <!-- END Revenue and Exepenses Content -->





    <!-- BEGIN Electricity Costs: Trade &amp; Reliability Content -->
    <h3><a name="traderel"></a>Electricity transactions</h3>
    <div class="accordion-content">
      <ul class="highlight">
        <li class="head">Detailed EIA-411 survey data (Data for 1990-2015, projections for 2016-2026)</li>
        <li>
          <ul>
            <li><a href="/electricity/data/eia411/">Electric reliability information and bulk power supply and demand
                information </a></li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="head">Electricity transactions</li>
        <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
            <?php include('electricity/annual/includes/releasedate.inc') ?>
         </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
            href="/electricity/annual/">Electric Power Annual</a></li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/annual/html/epa_02_12.html">Electricity purchases</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_02_12.xlsx"
                title="Electricity purchases "><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/annual/html/epa_02_13.html">Electricity sales for resale</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_02_13.xlsx"
                title="Electricity sales for resale"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/annual/html/epa_02_14.html">Electricity imports and exports</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_02_14.xlsx"
                title="Electricity imports and exports"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/wholesale/">Wholesale market data</a></li>
          </ul>
        </li>
       <!--<li class="head">Electric disturbance events</li>
        <li class="hide-bullet"><span class="release-date">Monthly Release date:</span> <span class="date">
            <?php include('electricity/monthly/includes/releasedate.inc') ?><span class="pipe">|</span><span
              class="source">Data from:</span> <a href="/electricity/monthly/">Electric Power Monthly</a></li>
        <li class="list-item">
          <ul>
            <li>Monthly, year-to-date current year</li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_b_1.xlsx"
                title="Electric disturbance events,  Monthly, year-to-date current year"><span
                  class="ico xls"><span>XLS</span></span></a></li> 
          </ul>
          <ul>
            <li>Monthly, last year</li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/monthly/xls/table_b_2.xlsx"
                title="Electric disturbance events, Monthly, last year  "><span
                  class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/data/disturbance/disturb_events_archive.html"
                title="Electric disturbance events,">Monthly, prior years</a></li>
          </ul>
        </li> -->
      </ul>
    </div>
    <!-- END Electricity Costs: Trade &amp; Reliability Content -->
    <!-- BEGIN Demand, Capability Resources, and Capability Margins Content -->
    <h3><a name="dsm"></a>Demand-side management program</h3>
    <div class="accordion-content">
      <ul>
        <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
            <?php include('electricity/annual/includes/releasedate.inc') ?>
         </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
            href="/electricity/annual/">Electric Power Annual</a></li>
        <li class="list-item">
          <ul>
            <li><a href="/electricity/annual/html/epa_10_01.html">Energy efficiency</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_10_01.xlsx"
                title="Energy efficiency"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/annual/html/epa_10_02.html">Energy efficiency - life cycle</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_10_02.xlsx"
                title="Energy efficiency - life cycle  "><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/annual/html/epa_10_03.html">Demand response - yearly energy and demand savings</a>
            </li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_10_03.xlsx"
                title="Demand response - yearly energy and demand savings"><span
                  class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/annual/html/epa_10_04.html">Demand response- program costs</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_10_04.xlsx"
                title="Demand response- program costs"><span class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/annual/html/epa_10_05.html">Advanced metering count by technology type</a></li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_10_05.xlsx"
                title="Advanced metering count by technology type"><span class="ico xls"><span>XLS</span></span></a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- END Demand, Capability Resources, and Capability Margins Content -->
    <!-- BEGIN Electricity and the Environment Content -->
    <h3><a name="elecenv"></a>Electricity and the environment</h3>
    <div class="accordion-content">
      <ul class="highlight">
        <li class="head">Detailed EIA-923 emissions survey data</li>
        <li class="list-item">
          <ul>
            <li>Electric power industry estimated emissions by state (back to 1990 )</li>
            <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/data/state/emission_annual.xlsx"
                title="Electric power industry estimated emissions by state (back to 1990 )"><span
                  class="ico xls"><span>XLS</span></span></a></li>
          </ul>
          <ul>
            <li><a href="/electricity/data/emissions/">Annual emissions by plant and region</a></li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date"> November 1, 2021 </span></li>
          </ul>
          <ul>
            <li><a href="/electricity/data/water/">Annual thermoelectric cooling water data</a></li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">November 1, 2021 </span></li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="list-item">
          <ul>
            <li class="head">Annual</li>
            <li class="hide-bullet"><span class="release-date">Release date: </span> <span class="date">
                <?php include('electricity/annual/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/electricity/annual/">Electric Power Annual</a></li>
            <li class="list-item">
              <ul>
                <li><a href="/electricity/annual/html/epa_09_01.html">Emissions from energy consumption at power
                    plants</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_09_01.xlsx"
                    title="Emissions from energy consumption at power plants "><span
                      class="ico xls"><span>XLS</span></span></a></li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_09_02.html">Generators with environmental equipment</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_09_02.xlsx"
                    title="Generators with environmental equipment"><span class="ico xls"><span>XLS</span></span></a>
                </li>
              </ul>
              <ul>
                <li><a href="/electricity/annual/html/epa_09_04.html">Average flue gas desulfurization costs</a></li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/electricity/annual/xls/epa_09_04.xlsx"
                    title="Average flue gas desulfurization costs"><span class="ico xls"><span>XLS</span></span></a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="list-item">
          <ul>
            <li class="head">Monthly/Annual (monthly back to 2015, annual to 1950)</li>
            <li class="hide-bullet"><span class="release-date">Release date:</span> <span class="date">
                <?php include('totalenergy/data/monthly/includes/releasedate.inc') ?>
             </span> <span class="pipe">|</span> <span class="source">Data from:</span> <a
                href="/totalenergy/data/monthly/">Monthly Energy Review</a><span class="pipe">|</span><span
                class="source">Interactive data from:</span> <a href="/totalenergy/data/browser/">Total Energy Data
                Browser</a></li>
            <li class="list-item">
              <ul>
                <li>Carbon dioxide emissions from electricity generation</li>
                <li class="hide-bullet"><span class="formats">Available formats:</span> <a href="/totalenergy/data/monthly/pdf/sec12_9.pdf"
                    title="Carbon dioxide emissions from electricity generation"><span
                      class="ico pdf"><span>PDF</span></span></a><a href="/totalenergy/data/browser/csv.php?tbl=T12.06"
                    title="Carbon dioxide emissions from electricity generation"><span
                      class="ico csv"><span>CSV</span></span></a><a
                    href="/totalenergy/data/browser/xls.php?tbl=T12.06&amp;freq=m"
                    title="Carbon dioxide emissions from electricity generation"><span
                      class="ico xls"><span>XLS</span></span></a><span class="pipe-alt">|</span><a
                    href="/beta/MER/?tbl=T12.06#/?f=M&amp;start=200001"
                    title="Carbon dioxide emissions from electricity generation"><span
                      class="ico interactive"><span>Interactive</span></span></a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>