<div class="primary">
  <div class="alert-banner-background-color" id="ColorExamples"></div>
  <div class="alert-banner-link-color" id="ColorExamples"></div>
</div>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <div class="alert">
    <p>The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.</p>
  </div>
  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="Alert">&lt;div class="alert"&gt;
  &lt;p&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;&lt;/p&gt;
&lt;/div&gt;</code></pre>
    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Alert"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
