<div class="primary">
  <div class="alert-banner-background-color" id="ColorExamples"></div>
  <div class="alert-banner-link-color" id="ColorExamples"></div>
</div>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor <span class="alert">five boxing wizards jump quickly</span> et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="Alert">&lt;span class="alert"&gt; &lt;!-- five boxing wizards jump quickly --&gt;&lt;/span&gt;</code></pre>
    <!--
		div class="btn-container">
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Alert">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
	</div
	-->
  </div>
</div>
