<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Notice Banner</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd><a href="http://wwwdev.eia.gov/international/data/world">http://wwwdev.eia.gov/international/data/world</a></li>
			</ul>
			<div class="banner-notice-background-color" id="ColorExamples"></div>
			<div class="banner-notice-border-color" id="ColorExamples"></div>
			<div class="banner-notice-link-color" id="ColorExamples"></div>
			</div>
			<!-- Example -->
			<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
			<div class="eia-card">
				<div class="l-row l-full-width-col banner-notice">
					<p>The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.</p>
				</div>
				<br />
				<br />
				<!-- HTML -->
				<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
				<div class="uk-margin-medium">


					<pre><code class="language-html" id="BannerNotice">&lt;div class="l-row l-full-width-col banner-notice"&gt;
  &lt;p&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;.&lt;/p&gt;
&lt;/div&gt;</code></pre>

				</div>
				<!-- Copy Button -->
				<p>
					<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#BannerNotice">
						<span uk-icon="copy"></span>Copy to clipboard
					</button>
			</div>
			</div>