<h4>Live examples:</h4>

<div class="primary">
  <ul class="live-examples">
    <li><a href="https://www.eia.gov/uranium/marketing/">https://www.eia.gov/uranium/marketing/</a></li>
  </ul>
  <div class="call-out-banner-background-color" id="ColorExamples"></div>
  <div class="call-out-banner-link-color" id="ColorExamples"></div>
</div>

<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <div class="call-out">
    <p>The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.</p>
  </div>

  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="CallOut">&lt;div class="call-out"&gt;
&lt;p&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;./p&gt;
&lt;/div&gt;</code></pre>

    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#CallOut"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
