<div class="error-wide">
	<div class="error-content">
		<p>
			The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.
		</p>
	</div>
</div>

<div class="l-row l-full-width-col">
	<div class="l-col">
		<span class="modules">
			<div class="primary">
				<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>



				<pre><code class="language-html" id="Error">&lt;div class="error-wide"&gt;
  &lt;div class="error-content"&gt;
    &lt;p&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;./p&gt;
  &lt;/div&gt;
&lt;/div&gt;</code></pre>

			</div>
			<!-- Copy Button -->
			<p>
				<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Error">
					<span uk-icon="copy"></span>Copy to clipboard
				</button>
	</div>
</div>
</div>
</span>
</div>
</div>