<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd><a href="https://www.eia.gov/opendata/">Opendata Forgot Key modal</a></li>
			<li><a href="https://www.eia.gov/opendata/">Opendata Register modal</a></li>
			</ul>
			<div class="error-banner-background-color" id="ColorExamples"></div>
			<div class="error-banner-link-color" id="ColorExamples"></div>
			</div>
			<div class="error">
				<p>
					The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.
				</p>
			</div>

			<!-- HTML -->
			<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
			<div class="uk-margin-medium">


				<pre><code class="language-html" id="Error">&lt;div class="error"&gt;
  &lt;p&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;./p&gt;
&lt;/div&gt;</code></pre>

			</div>
			<!-- Copy Button -->
			<p>
				<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Error">
					<span uk-icon="copy"></span>Copy to clipboard
				</button>
				</div>
				</div>