<!-- h4 class="h4">Live examples:</h4 -->
<div class="primary">
  <!--
				ul class="live-examples">
				<li><a>n/a</a></li>
			</ul
			-->
  <div class="information-banner-background-color" id="ColorExamples"></div>
  <div class="information-banner-border-color" id="ColorExamples"></div>
</div>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <div class="info">
    <p>The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.</p>
  </div>
  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="Info">&lt;div class="info"&gt;
  &lt;p&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;.&lt;/p&gt;
&lt;/div&gt;</code></pre>

    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Info"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
