<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Note Inline</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd>https://www.eia.gov/petroleum/marketing/prime</li>
			</ul>
			</div>
			<!-- Example -->
			<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
			<div class="eia-card">
				<p class="note right">The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.</p>
				<!-- HTML -->
				<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
				<div class="uk-margin-medium">


					<pre><code class="language-html" id="NoteInlineRight">&lt;p class="note right"&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;.&lt;/p&gt;</code></pre>

				</div>
				<!-- Copy Button -->
				<p>
					<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#NoteInlineRight">
						<span uk-icon="copy"></span>Copy to clipboard
					</button>
			</div>
			</div>