<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Note Inline</h2>
<div class="primary">
  <ul class="live-examples">
    <li><a>n/a</a></li>
  </ul>
  <span class="beta-banner-background-color"></span>
  <span class="beta-banner-border-color"></span>
</div>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <p class="note">The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.</p>

  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="NoteInline">&lt;p class="note"&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;.&lt;/p&gt;</code></pre>

    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#NoteInline"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
