<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd><a href="https://www.eia.gov/petroleum/supply/weekly/">https://www.eia.gov/petroleum/supply/weekly/</a></li>
			<li><a href="https://www.eia.gov/opendata/excel/">https://www.eia.gov/opendata/excel/</a></li>
			</ul>
			<div class="notice-banner-background-color" id="ColorExamples"></div>
			<div class="notice-banner-link-color" id="ColorExamples"></div>
			</div>
			<!-- Example -->
			<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
			<div class="eia-card">
				<div class="notice">
					<p>
						The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.
					</p>
				</div>
				<!-- HTML -->
				<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
				<div class="uk-margin-medium">


					<pre><code class="language-html" id="Notice">&lt;div class="notice"&gt;
  &lt;p class="notice"&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;.&lt;/p&gt;
&lt;/div&gt;</code></pre>

				</div>
				<!-- Copy Button -->
				<p>
					<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Notice">
						<span uk-icon="copy"></span>Copy to clipboard
					</button>
			</div>
			</div>