<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd>https://www.eia.gov/opendata/ Forgot Key modal</li>
			<li>https://www.eia.gov/opendata/ Register modal</li>
			</ul>
			<div class="success-banner-background-color" id="ColorExamples"></div>
			<div class="success-banner-link-color" id="ColorExamples"></div>
			</div>
			<!-- Example -->
			<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
			<div class="eia-card">
				<div class="success">
					<p>
						The <strong>five boxing</strong> wizards jump quickly <a>jump quickly</a>.
					</p>
				</div>
				<!-- HTML -->
				<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
				<div class="uk-margin-medium">


					<pre><code class="language-html" id="Success">&lt;div class="success"&gt;
  &lt;p&gt;The &lt;strong&gt;five boxing&lt;/strong&gt; wizards jump quickly &lt;a&gt;jump quickly&lt;/a&gt;./p&gt;
&lt;/div&gt;</code></pre>

				</div>
				<!-- Copy Button -->
				<p>
					<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Success">
						<span uk-icon="copy"></span>Copy to clipboard
					</button>
			</div>
			</div>