<div class="clipboard-container">
	<h4>HTML Code Example</h4>

	<h4><span>&lt;/&gt;</span> Source</h4>
	<div class="clipboard-container">


		<pre><code class="language-html" id="Dilly">Code sample not ready yet.</code></pre>
	</div>
	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
	</p>
	</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">

	<pre><code class="html"><!-- PDF -->
<span class="eia ico inline pdf">
	<span>PDF</span>
</span></code></pre>

	<pre><code class="html"><!-- XLS -->
<span class="eia ico xls">
<span>XLS</span>
</span></code></pre>

	<pre><code class="html"><!-- CSV -->
<span class="eia ico csv">
<span>CSV</span>
</span></code></pre>

	<pre><code class="html"><!-- interactive -->
<span class="eia ico interactive">
<span>INTERACTIVE</span>
</span></code></pre>

	<pre><code class="html"><!-- PPT -->
<span class="eia ico ppt">
<span>PPT</span>
</span></code></pre>

	<pre><code class="html"><!-- html -->
<span class="eia ico html">
<span>HTML</span>
</span></code></pre>

	<pre><code class="html"><!-- doc -->
<span class="eia ico doc">
<span>DOC</span>
</span></code></pre>

	<pre><code class="html"><!-- image -->
<span class="eia ico image">
<span>IMAGE</span>
</span></code></pre>

	<pre><code class="html"><!-- json -->
<span class="eia ico json">
<span>JSON</span>
</span></code></pre>

	<pre><code class="html"><!-- eFile -->
<span class="eia ico efile">
<span>eFile</span>
</span></code></pre>

	<pre><code class="html"><!-- txt -->
<span class="eia ico txt">
<span>TXT</span>
</span></code></pre>

	<pre><code class="html"><!-- PDF -->
<a class="eia ico pdf">
<span>PDF</span>
</a></code></pre>

	<span class="eia ico html">
		<!-- XLS -->
		<a class="eia ico xls">
			<span>XLS</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- CSV -->
		<a class="eia ico csv">
			<span>CSV</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- interactive -->
		<a class="eia ico interactive">
			<span>INTERACTIVE</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- PPT -->
		<a class="eia ico ppt">
			<span>PPT</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- html -->
		<a class="eia ico html">
			<span>HTML</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- doc -->
		<a class="eia ico doc">
			<span>DOC</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- image -->
		<a class="eia ico image">
			<span>IMAGE</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- pedro -->
		<a class="eia ico pedro">
			<span>PEDRO</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- eFile -->
		<a class="eia ico efile">
			<span>eFile</span>
		</a></code></pre>
	</span>
	<span class="eia ico html">
		<!-- txt -->
		<a class="eia ico txt">
			<span>TXT</span>
		</a></code></pre>
	</span>
	<pre><code class="html"><!-- PDF -->
<span class="eia ico icon-only pdf">
<span>PDF</span>
</span></code></pre>
	<pre><code class="html"><!-- XLS -->
<span class="eia ico icon-only xls">
<span>XLS</span>
</span></code></pre>
	<pre><code class="html"><!-- CSV -->
<span class="eia ico icon-only csv">
<span>CSV</span>
</span></code></pre>
	<pre><code class="html"><!-- interactive -->
<span class="eia ico icon-only interactive">
<span>Interactive</span>
</span></code></pre>
	<pre><code class="html"><!-- PPT -->
<span class="eia ico icon-only ppt">
<span>PPT</span>
</span></code></pre>
	<pre><code class="html"><!-- html -->
<span class="eia ico icon-only html">
<span>HTML</span>
</span></code></pre>
	<pre><code class="html"><!-- doc -->
<span class="eia ico icon-only doc">
<span>DOC</span>
</span></code></pre>
	<pre><code class="html"><!-- image -->
<span class="eia ico icon-only image">
<span>IMAGE</span>
</span></code></pre>
	<pre><code class="html"><!-- pedro -->
<span  class="eia ico icon-only pedro">
<span>PEDRO</span>
</span></code></pre>
	<pre><code class="html"><!-- eFile -->
<span  class="eia ico icon-only efile">
<span>eFile</span>
</span></code></pre>
	<pre><code class="html"><!-- txt -->
<span  class="eia ico icon-only txt">
<span>TXT</span>
</span></code></pre>
	<pre><code class="html"><!-- PDF -->
<li class="eia ico pdf">
<a>Lorem ipsum...</a>
</li></code></pre>
	<pre><code class="html"><!-- XLS -->
<li class="eia ico xls">
<a>Lorem ipsum...</a>
</li></code></pre>
	<pre><code class="html"><!-- CSV -->
<li class="eia ico csv">
<a>Lorem ipsum...</a>
</li></code></pre>

	<pre><code class="html"><!-- interactive -->
<li class="eia ico interactive">
<a>Lorem ipsum...</a>
</li></code></pre>

	<pre><code class="html"><!-- PPT -->
<li class="eia ico ppt">
<a>Lorem ipsum...</a>
</li></code></pre>

	<pre><code class="html"><!-- html -->
<li class="eia ico html">
<a>Lorem ipsum...</a>
</li></code></pre>

	<pre><code class="html"><!-- doc -->
<li class="eia ico doc">
<a>Lorem ipsum...</a>
</li></code></pre>

	<pre><code class="html"><!-- image -->
<li class="eia ico image">
<a>Lorem ipsum...</a>
</li></code></pre>

	<pre><code class="html"><!-- pedro -->
<li  class="eia ico pedro">
<a>Lorem ipsum...</a>
</li></code></pre>

	<pre><code class="html"><!-- eFile -->
<li  class="eia ico efile">
<a>Lorem ipsum...</a>
</li></code></pre>

	<pre><code class="html"><!-- txt -->
<li  class="eia ico txt">
<a>Lorem ipsum...</a>
</li></code></pre>
	<pre><code class="html"><!-- PDF -->
<td class="eia ico pdf">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- XLS -->
<td class="eia ico xls">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- CSV -->
<td class="eia ico csv">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- interactive -->
<td class="eia ico interactive">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- PPT -->
<td class="eia ico ppt">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- html -->
<td class="eia ico html">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- doc -->
<td class="eia ico doc">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- image -->
<td class="eia ico image">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- pedro -->
<td  class="eia ico pedro">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- eFile -->
<td  class="eia ico efile">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- txt -->
<td  class="eia ico txt">
<a>Lorem ipsum...</a>
</td></code></pre>
	<pre><code class="html"><!-- close-menu -->
<span class="eia ico close-menu">
<span>CLOSE MENU</span>
</span></code></pre>
	<pre><code class="html"><!-- search-submit -->
<span class="eia ico search-submit">
<span>SUBMIT</span>
</span></code></pre>
	<pre><code class="html"><!-- analysis -->
<span class="eia ico analysis">
<span>analysis</span>
</span></code></pre>
	<pre><code class="html"><!-- cancel -->
<span class="eia ico cancel">
<span>cancel</span>
</span></code></pre>
	<pre><code class="html"><!-- column-chart -->
<span class="eia ico column-chart">
<span>column-chart</span>
</span></code></pre>
	<pre><code class="html"><!-- compare -->
<span class="eia ico compare">
<span>compare</span>
</span></code></pre>
	<pre><code class="html"><!-- d-arrow -->
<span class="eia ico d-arrow">
<span>DOWN ARROW</span>
</span></code></pre>
	<pre><code class="html"><!-- download -->
<span class="eia ico download">
<span>download</span>
</span></code></pre>
	<pre><code class="html"><!-- edit -->
<span class="eia ico edit">
<span>edit</span>
</span></code></pre>
	<pre><code class="html"><!-- filter -->
<span class="eia ico filter">
<span>filter</span>
</span></code></pre>
	<pre><code class="html"><!-- grab-dot -->
<span class="eia ico grab-dot">
<span>grab-dot</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-column -->
<span class="eia ico grid-column">
<span>grid column</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-line -->
<span class="eia ico grid-line">
<span>grid line</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-map -->
<span class="eia ico grid-map">
<span>grid map</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-parent-column -->
<span class="eia ico grid-parent-column">
<span>grid parent column</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-parent-line -->
<span class="eia ico grid-parent-line">
<span>grid parent line</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-parent-map -->
<span class="eia ico grid-parent-map">
<span>grid-parent-map</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-parent-pin -->
<span class="eia ico grid-parent-pin">
<span>grid-parent-pin</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-pin -->
<span class="eia ico grid-pin">
<span>grid-pin</span>
</span></code></pre>
	<pre><code class="html"><!-- grid-key -->
<span class="eia ico grid-key">
<span>grid-key</span>
</span></code></pre>
	<pre><code class="html"><!-- help -->
<span class="eia ico help">
<span>help</span>
</span></code></pre>
	<pre><code class="html"><!-- key -->
<span class="eia ico key">
<span>key</span>
</span></code></pre>
	<pre><code class="html"><!-- l-arrow -->
<span class="eia ico l-arrow">
<span>l-arrow</span>
</span></code></pre>
	<pre><code class="html"><!-- l-range -->
<span class="eia ico l-range">
<span>l-range</span>
</span></code></pre>
	<pre><code class="html"><!-- line-chart -->
<span class="eia ico line-chart">
<span>line-chart</span>
</span></code></pre>
	<pre><code class="html"><!-- map -->
<span class="eia ico map">
<span>map</span>
</span></code></pre>
	<pre><code class="html"><!-- pause -->
<span class="eia ico pause">
<span>pause</span>
</span></code></pre>
	<pre><code class="html"><!-- pin -->
<span class="eia ico pin">
<span>PIN</span>
</span></code></pre>
	<pre><code class="html"><!-- play -->
<span class="eia ico play">
<span>play</span>
</span></code></pre>
	<pre><code class="html"><!-- r-arrow -->
<span class="eia ico r-arrow">
<span>r-arrow</span>
</span></code></pre>
	<pre><code class="html"><!-- r-range -->
<span class="eia ico r-range">
<span>r-range</span>
</span></code></pre>
	<pre><code class="html"><!-- remove -->
<span class="eia ico remove">
<span>remove</span>
</span></code></pre>
	<pre><code class="html"><!-- reset -->
<span class="eia ico reset">
<span>reset</span>
</span></code></pre>
	<pre><code class="html"><!-- reset-animation -->
<span class="eia ico reset-animation">
<span>reset-animation</span>
</span></code></pre>
	<pre><code class="html"><!-- scroll-h -->
<span class="eia ico scroll-h">
<span>scroll-h</span>
</span></code></pre>
	<pre><code class="html"><!-- scroll-v -->
<span class="eia ico scroll-v">
<span>scroll-v</span>
</span></code></pre>
	<pre><code class="html"><!-- search-icon -->
<span class="eia ico search-icon">
<span>SEARCH</span>
</span></code></pre>
	<pre><code class="html"><!-- slide -->
<span class="eia ico slide">
<span>slide</span>
</span></code></pre>
	<pre><code class="html"><!-- sort -->
<span class="eia ico sort">
<span>sort</span>
</span></code></pre>
	<pre><code class="html"><!-- sort-down -->
<span class="eia ico sort-down">
<span>sort-down</span>
</span></code></pre>
	<pre><code class="html"><!-- sort-up -->
<span class="eia ico sort-up">
<span>sort-up</span>
</span></code></pre>
	<pre><code class="html"><!-- submit -->
<span class="eia ico submit">
<span>submit</span>
</span></code></pre>
	<pre><code class="html"><!-- checkmark -->
<span class="eia ico checkmark">
<span>checkmark</span>
</span></code></pre>
	<pre><code class="html"><!-- dash -->
<span class="eia ico dash">
<span>dash</span>
</span></code></pre>
	<pre><code class="html"><!-- dot -->
<span class="eia ico dot">
<span>dot</span>
</span></code></pre>
	<pre><code class="html"><!-- add-chart -->
<span class="eia ico add-chart">
<span>add-chart</span>
</span></code></pre>
	<pre><code class="html"><!-- add-download -->
<span class="eia ico add-download">
<span>add-download</span>
</span></code></pre>
	<pre><code class="html"><!-- full-screen -->
<span class="eia ico full-screen">
<span>full-screen</span>
</span></code></pre>
	<pre><code class="html"><!-- options -->
<span class="eia ico options">
<span>options</span>
</span></code></pre>
	<pre><code class="html"><!-- table -->
<span class="eia ico table">
<span>table</span>
</span></code></pre>
	<pre><code class="html"><!-- lock -->
<span class="eia ico lock">
<span>lock</span>
</span></code></pre>
	<pre><code class="html"><!-- unlock -->
<span class="eia ico unlock">
<span>unlock</span>
</span></code></pre>
	<pre><code class="html"><!-- submit -->
<span class="eia ico submit">
<span>submit</span>
</span></code></pre>
	<pre><code class="html"><!-- clone -->
<span class="eia ico clone">
<span>clone</span>
</span></code></pre>
	<pre><code class="html"><!-- d -->
<span class="eia ico d">
<span>ico d</span>
</span></code></pre>
	<pre><code class="html"><!-- a -->
<span class="eia ico a">
<span>ico a</span>
</span></code></pre>
	<pre><code class="html"><!-- p -->
<span class="eia ico p">
<span>ico p</span>
</span></code></pre>
	<pre><code class="html"><!-- da -->
<span class="eia ico da">
<span>ico da</span>
</span></code></pre>
	<pre><code class="html"><!-- ap -->
<span class="eia ico ap">
<span>ico ap</span>
</span></code></pre>
	<pre><code class="html"><!-- dp -->
<span class="eia ico dp">
<span>ico dp</span>
</span></code></pre>
	<pre><code class="html"><!-- dap -->
<span class="eia ico dap">
<span>ico dap</span>
</span></code></pre>
	<pre><code class="html"><!-- print -->
<span class="eia ico print">
<span>PRINT</span>
</span></code></pre>
	<pre><code class="html"><!-- info -->
<span class="eia ico info">
<span>Info</span>
</span></code></pre>
	<pre><code class="html"><!-- tour -->
<span class="eia ico tour">
<span>Tour</span>
</span></code></pre>
	<pre><code class="html"><!-- external-link -->
<span class="external-link">
<span>External Link</span>
</span></code></pre>
	<pre><code class="html"><!--  analysis-projections -->
<span class="ico-menu analysis-projections-icon">
<span>analysis-projections</span>
</span></code></pre>
	<pre><code class="html"><!-- az-index -->
<span class="ico-menu a-z-index-icon">
<span>az-index</span>
</span></code></pre>
	<pre><code class="html"><!-- beta -->
<span class="ico-menu beta-icon">
<span>beta</span>
</span></code></pre>
	<pre><code class="html"><!-- coal -->
<span class="ico-menu coal-icon">
<span>coal</span>
</span></code></pre>
	<pre><code class="html"><!-- upcoming -->
<span class="ico-menu upcoming-icon">
<span>upcoming</span>
</span></code></pre>
	<pre><code class="html"><!-- consumption -->
<span class="ico-menu consumption-icon">
<span>consumption</span>
</span></code></pre>
	<pre><code class="html"><!-- data-tools-model -->
<span class="ico-menu data-tools-model-icon">
<span>data-tools-model</span>
</span></code></pre>
	<pre><code class="html"><!-- electricity -->
<span class="ico-menu electricity-icon">
<span>electricity</span>
</span></code></pre>
	<pre><code class="html"><!-- email-complex -->
<span class="ico-menu email-complex-icon">
<span>email-complex</span>
</span></code></pre>
	<pre><code class="html"><!-- email-simple -->
<span class="ico-menu email-simple">
<span>email-simple</span>
</span></code></pre>
	<pre><code class="html"><!-- energy-explained -->
<span class="ico-menu energy-explained-icon">
<span>energy-explained</span>
</span></code></pre>
	<pre><code class="html"><!-- energy-in-brief -->
<span class="ico-menu energy-in-brief-icon">
<span>energy-in-brief</span>
</span></code></pre>
	<pre><code class="html"><!-- environment -->
<span class="ico-menu environment-icon">
<span>environment</span>
</span></code></pre>
	<pre><code class="html"><!-- disruptions -->
<span class="ico-menu disruptions-icon">
<span>disruptions</span>
</span></code></pre>
	<pre><code class="html"><!-- faq -->
<span class="ico-menu faq-icon">
<span>faq</span>
</span></code></pre>
	<pre><code class="html"><!-- featured-reports -->
<span class="ico-menu featured-reports-icon">
<span>featured-reports</span>
</span></code></pre>
	<pre><code class="html"><!-- markets-finance -->
<span class="ico-menu markets-finance-icon">
<span>markets-finance</span>
</span></code></pre>
	<pre><code class="html"><!-- follow-us -->
<span class="ico-menu follow-us-icon">
<span>follow-us</span>
</span></code></pre>
	<pre><code class="html"><!-- glossary -->
<span class="ico-menu eia-glossary-icon">
<span>glossary</span>
</span></code></pre>
	<pre><code class="html"><!-- international -->
<span class="ico-menu international-icon">
<span>international</span>
</span></code></pre>
	<pre><code class="html"><!-- maps -->
<span class="ico-menu maps-icon">
<span>maps</span>
</span></code></pre>
	<pre><code class="html"><!-- natural-gas -->
<span class="ico-menu natural-gas-icon">
<span>natural-gas</span>
</span></code></pre>
	<pre><code class="html"><!-- nuclear -->
<span class="ico-menu nuclear-icon">
<span>nuclear</span>
</span></code></pre>
	<pre><code class="html"><!-- open-data -->
<span class="ico-menu open-data-icon">
<span>open-data</span>
</span></code></pre>
	<pre><code class="html"><!-- petroleum -->
<span class="ico-menu petroleum-icon">
<span>petroleum</span>
</span></code></pre>
	<pre><code class="html"><!-- press-room -->
<span class="ico-menu press-room-icon">
<span>press-room</span>
</span></code></pre>
	<pre><code class="html"><!--  regional-icon -->
<span class="ico-menu regional-icon">
<span>regional-icons</span>
</span></code></pre>
	<pre><code class="html"><!-- renewable -->
<span class="ico-menu renewable-icon">
<span>renewable</span>
</span></code></pre>
	<pre><code class="html"><!-- reports -->
<span class="ico-menu reports-icon">
<span>reports</span>
</span></code></pre>
	<pre><code class="html"><!-- rss-complex -->
<span class="ico-menu rss-complex-icon">
<span>rss-complex</span>
</span></code></pre>
	<pre><code class="html"><!-- survey-forms -->
<span class="ico-menu survey-forms-icon">
<span>survey-forms</span>
</span></code></pre>
	<pre><code class="html"><!-- teachers -->
<span class="ico-menu teachers-icon">
<span>teachers</span>
</span></code></pre>
	<pre><code class="html"><!-- today-in-energy -->
<span class="ico-menu today-in-energy-icon">
<span>today-in-energy</span>
</span></code></pre>
	<pre><code class="html"><!-- total-energy -->
<span class="ico-menu total-energy-icon">
<span>total-energy</span>
</span></code></pre>
	<pre><code class="html"><!-- states -->
<span class="ico-menu states-icon">
<span>states</span>
</span></code></pre>
	<pre><code class="html"><!-- whats-new -->
<span class="ico-menu whats-new-icon">
<span>whats-new</span>
</span></code></pre>
	<pre><code class="html">
<ul class="eia ico icon-list">
<li class="eia ico reports-icon">
<a href>Link</a>
</li>
</ul></code></pre>
	<pre><code class="html">
<ul class="eia ico icon-list">
<li class="eia ico email-simple">
<a href>Link</a>
</li>
</ul></code></pre>
	<pre><code class="html">
<ul class="eia ico icon-list">
<li class="eia ico rss-complex-icon">
<a href>Link</a>
</li>
</ul></code></pre>
	<pre><code class="html"><!-- residential -->
<span class="residential-icon">
<span>residential</span>
</span></code></pre>
	<pre><code class="html"><!-- commercial -->
<span class="commercial-icon">
<span>commercial</span>
</span></code></pre>
	<pre><code class="html"><!-- industrial -->
<span class="industrial-icon">
<span>industrial</span>
</span></code></pre>
	<pre><code class="html"><!-- facebook -->
<span class="facebook">
<span>facebook</span>
</span></code></pre>
	<pre><code class="html"><!-- twitter -->
<span class="twitter">
<span>twitter</span>
</span></code></pre>
	<pre><code class="html"><!-- youtube -->
<span class="youtube">
<span>youtube</span>
</span></code></pre>
	<pre><code class="html"><!-- flickr -->
<span class="flickr">
<span>flickr</span>
</span></code></pre>
	<pre><code class="html"><!-- linkedin -->
<span class="linkedin">
<span>linkedin</span>
</span></code></pre>
	<pre><code class="html"><!-- email -->
<span class="email">
<span>email</span>
</span></code></pre>
	<pre><code class="html"><!-- rss -->
<span class="rss">
<span>rss</span>
</span></code></pre>