<h3>Analysis Projections Icons</h3>
<div class="accordion-content horizontal-icon-container analysis-projections">

	<div class="icon-container">
		<span class="eia ico d">
			<span>D</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico a">
			<span>A</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico p">
			<span>P</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico da">
			<span>DA</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico ap">
			<span>AP</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico dp">
			<span>DP</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico dap">
			<span>DAP</span>
		</span>
	</div>
</div>
</div>