<h3>Control Icons</h3>


<div class="accordion-content horizontal-icon-container general-icons">

	<?php
include('./includes/help.inc');
include('./includes/key.inc');
include('./includes/left-arrow.inc');
include('./includes/map.inc');
include('./includes/line-chart.inc');
include('./includes/pin.inc');
include('./includes/left-range.inc');
include('./includes/play.inc');
include('./includes/pause.inc');
include('./includes/right-arrow.inc');
include('./includes/right-range.inc');
include('./includes/remove.inc');
include('./includes/reset.inc');
include('./includes/reset-animation.inc');
include('./includes/scroll-horizontal.inc');
include('./includes/scroll-vertical.inc');
include('./includes/search.inc');
include('./includes/slide.inc');
include('./includes/sort.inc');
include('./includes/sort-up.inc');
include('./includes/sort-down.inc');
include('./includes/submit.inc');
include('./includes/checkmark.inc');
include('./includes/dash.inc');
include('./includes/dot.inc');
include('./includes/add-chart.inc');
include('./includes/add-download.inc');
include('./includes/full-screen.inc');
include('./includes/options.inc');
include('./includes/table.inc');
include('./includes/lock.inc');
include('./includes/unlock.inc');
include('./includes/clone.inc');
	?>
</div>
</div>