<h3>General Icons</h3>
<div class="accordion-content horizontal-icon-container general">


	<?php include('./icons/grid-column.inc');?>
	<?php include('./icons/grid-line.inc');?>
	<?php include('./icons/grid-map.inc');?>
	<?php include('./icons/grid-parent-map.inc');?>
	<?php include('./icons/grid-parent-line.inc');?>
	<?php include('./icons/grid-parent-pin.inc');?>
	<?php include('./icons/grid-parent-column.inc');?>

</div>