<!--

<ul class="icon-list">
<li class="eia ico radio">
<a>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a>
</li>
</ul>


-->
<div class="clipboard-container">
	<h6>HTML Code Example Icon</h6>

	<h4><span>&lt;/&gt;</span> Source</h4>
	<div class="clipboard-container">


		<pre><code class="language-html" id="Dilly">Code sample not ready yet.</code></pre>
	</div>
	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
	</p>
	</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">