<h3>Navigational Icons</h3>
<div class="accordion-content horizontal-icon-container navigational">

	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu analysis-projections-icon">
			<span>Analysis &amp; Projections</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu a-z-index-icon">
			<span>A-Z Index</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu beta-icon">
			<span>EIA Beta</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu coal-icon">
			<span>Coal</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu upcoming-icon">
			<span>Coming Up</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu consumption-icon">
			<span>Consumption &amp; Efficiency</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu data-tools-model-icon">
			<span>Data Tools &amp; Models</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu electricity-icon">
			<span>Electricity</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu email-complex-icon">
			<span>Email Updates</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu email-simple">
			<span>RSS Feeds</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu energy-explained-icon">
			<span>Energy Explained</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu energy-in-brief-icon">
			<span>Energy in Brief</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu environment-icon">
			<span>Environment</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu disruptions-icon">
			<span>Disruptions</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu faq-icon">
			<span>FAQs</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu featured-reports-icon">
			<span>Featured Reports</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu markets-finance-icon">
			<span>Markets &amp; Finance</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu follow-us-icon">
			<span>Follow us. . .</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu eia-glossary-icon">
			<span>Glossary</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu international-icon">
			<span>International</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu maps-icon">
			<span>Maps</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu natural-gas-icon">
			<span>Natural Gas</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu nuclear-icon">
			<span>Nuclear &amp; Uranium</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu open-data-icon">
			<span>Open Data</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu petroleum-icon">
			<span>Petroleum &amp; Other Liquids</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu press-room-icon">
			<span>Press Room</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu regional-icon">
			<span>regional-icon</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu renewable-icon">
			<span>Renewable &amp; Alternative Fuels</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu reports-icon">
			<span>All Reports &amp; Publications</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu rss-complex-icon">
			<span>RSS Feeds</span>
		</span>

	</div>

	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu survey-forms-icon">
			<span>EIA Survey Forms</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu teachers-icon">
			<span>For Teachers</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu today-in-energy-icon">
			<span>Today in Energy</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu total-energy-icon">
			<span>Total Energy</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu states-icon">
			<span>U.S. States</span>
		</span>

	</div>
	<div class="icon-container">
		<!-- h4></h4 -->

		<span class="ico-menu whats-new-icon">
			<span>What's New?</span>
		</span>

	</div>
</div>
</div>