<h3>Open Data</h3>
<div class="accordion-content horizontal-icon-container open-data">

	<h4>Special Icons</h4>

	<div class="secondary-alt">
		<ul class="basic">
			<li class="head">
				<h2>Lorem ipsum dolor sit amet</h2>
			</li>
			<li class="api-icon"><span class="eia ico widgets"><span>API Widgets</span></span></li>
			<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis at felis nibh. Fusce vulputate enim quis tincidunt bibendum. Pellentesque vitae fermentum metus, ac cursus velit. Praesent et odio libero. Ut sed diam vitae augue pretium commodo.</li>
		</ul>
	</div>
</div>


<div class="secondary-alt">
	<ul class="basic">
		<li class="head">
			<h2>Lorem ipsum dolor sit amet</h2>
		</li>
		<li class="api-icon"><span class="eia ico api"><span>API Icon</span></span></li>
		<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis at felis nibh. Fusce vulputate enim quis tincidunt bibendum. Pellentesque vitae fermentum metus, ac cursus velit. Praesent et odio libero. Ut sed diam vitae augue pretium commodo.</li>
	</ul>
</div>
</div>


<div class="secondary-alt">
	<ul class="basic">
		<li class="head">
			<h2>Lorem ipsum dolor sit amet</h2>
		</li>
		<li class="api-icon"><span class="eia ico addon"><span>API Spreadsheet Adds Icon</span></span></li>
		<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis at felis nibh. Fusce vulputate enim quis tincidunt bibendum. Pellentesque vitae fermentum metus, ac cursus velit. Praesent et odio libero. Ut sed diam vitae augue pretium commodo.</li>
	</ul>
</div>
</div>
</div>