<!--
IconRightRange -->
<!-- code

<span class="eia ico r-range">
<span>Icon Right Range</span>
</span>


-->
<div class="icon-container">
	<h6>Right Range Icon</h6>

	<span class="eia ico r-range">
		<span>r-range</span>
	</span>

	<h4><span>&lt;/&gt;</span> Source</h4>
	<div class="clipboard-container">


		<pre><code class="language-html" id="Dilly">Code sample not ready yet.</code></pre>
	</div>
	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
	</p>
	</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">