<h3>Consumption Surveys</h3>
<div class="accordion-content horizontal-icon-container consumption-surveys">

	<div class="icon-container">
		<span class="eia ico residential">
			<span>Residential</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico commercial">
			<span>Commercial</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico industrial">
			<span>Industrial</span>
		</span>
	</div>

	<div class="clipboard-container">
		<h4><span>&lt;/&gt;</span> Source</h4>

		<pre><code class="language-html" id="consumptionSurveys"">&lt;span class="eia ico residential/commercial/industrial"&gt;
  &lt;span&gt;Residential/Commercial/Industrial&lt;/span&gt;
&lt;/span&gt;</code></pre>
	</div>
	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#consumptionSurveys">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
	</p>
	</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">