<div class="clipboard-container">
	<h3>Iconic Table Cells</h3>
	<div class="basic-table">
		<table class="basic-table full-width">
			<tbody>
				<tr>
					<td class="eia ico pdf">
						<a>Link to PDF</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico xls">
						<a>Link to XLS</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico json">
						<a>Link to JSON</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico csv">
						<a>Link to CSV</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico ppt">
						<a>Link to PPT</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico html">
						<a>Link to HTML</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico doc">
						<a>Link to DOC</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico image">
						<a>Link to image</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico interactive">
						<a>Link to interactive</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico efile">
						<a>Link to eFile</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td class="eia ico pedro">
						<a>Link to PEDRO</a>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>