<h3>This Week in...</h3>
<div class="horizontal-icon-container this-week">



	<h6>Inactive Icon</h6>
	<div class="icon-container">
		<a class="eia ico this-week-analysis">
			<span>Analysis</span>
		</a>
	</div>

	<div class="icon-container">
		<a class="eia ico crude-oil">
			<span>Crude Oil</span>
		</a>
	</div>

	<div class="icon-container">
		<a class="eia ico gasoline">
			<span>Gasoline</span>
		</a>
	</div>

	<div class="icon-container">
		<a class="eia ico distillate">
			<span>Distillate</span>
		</a>
	</div>

	<div class="icon-container">
		<a class="eia ico propane">
			<span>Propane</span>
		</a>
	</div>

	<h6>Tabs Icon</h6>
	<div class="icon-container">
		<a class="eia ico this-week-analysis active">
			<span>Analysis</span>
		</a>
	</div>

	<div class="icon-container">
		<a class="eia ico crude-oil active">
			<span>Crude Oil</span>
		</a>
	</div>

	<div class="icon-container">
		<a class="eia ico gasoline active">
			<span>Gasoline</span>
		</a>
	</div>

	<div class="icon-container">
		<a class="eia ico distillate active">
			<span>Distillate</span>
		</a>
	</div>

	<div class="icon-container">
		<a class="eia ico propane active">
			<span>Propane</span>
		</a>
	</div>
</div>
</div>
<!--

		<div class="_icon-vertical">
		<div class="icon-container">
			<h6>Tabs Icon</h6>
			<div class="g_container">
				<div class="tabs petroleum-weekly">
					<ul>
						<li class="ui-state-active">
							<a>
								<span class="eia ico grid-line">
									<span>Graph</span>
								</span>
								Contract 1
							</a>
						</li>
						<li>
							<a>
								<span class="eia ico grid-line">
									<span>Graph</span>
								</span>
								Contract 2
							</a>
						</li>
						<li>
							<a>
								<span class="eia ico grid-line">
									<span>Graph</span>
								</span>
								Contract 3
							</a>
						</li>
						<li>
							<a>
								<span class="eia ico grid-line">
									<span>Graph</span>
								</span>
								Contract 4
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="icon-container">
			<div class="l-row l-report-header-petroleum-weekly">
				<h6>Tabs Icon</h6>
				<div class="release-dates">
					<span class="responsive-container">
						<a class="eia ico download iframe">
							Download data
						</a>
					</span>

					<span class="responsive-container">
						<a class="eia ico printer">
							Print
						</a>
					</span>
				</div>
			</div>
		</div>
	</div>


-->