<a name="Accessibility"></a>
<h2>Accessible Tables</h2>
<p>Data tables are used to organize data with a logical relationship in grids. Accessible tables need HTML markup that indicates header cells and data cells and defines their relationship. Assistive technologies use this information to provide context to users.</p>

<?php include('./includes/tables/basic -->

<?php include('./includes/tables/row-section-head -->

<?php include('./includes/tables/double-head -->

<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>

	<pre><code class="language-html" id="AccessibleTables"></code></pre>

<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#AccessibleTables">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>