<a name="ColumnDivider"></a>

<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Table Column Divider</h2>

<p>
	Adding a <code>class="vertical-divider-after-col-1/2/3/4/5/6/7/8/9/10"</code> to the to the table class (Note, this may not have the desired effect if there are spanned columns).
</p>


<div class="basic-table">
	<table class="basic-table full-width vertical-divider-after-col-1">
		<thead>
			<tr>
				<th scope="col"><code>left aligned</code></th>
				<th scope="col"><code>right aligned</code></th>
				<th scope="col"><code>right aligned</code></th>
				<th scope="col"><code>right aligned</code></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr class="divider">
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td scope="colgroup" colSpan="99" class="footnotes">
					Footnotes: Aligned-left
				</td>
			</tr>
		</tfoot>
	</table>
</div>
<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="ColumnDivider">&lt;div class="basic-table"&gt;
  &lt;table class="basic-table full-width vertical-divider-after-col-1"&gt;
    &lt;thead&gt;
      &lt;tr&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
      &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr class="divider"&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
    &lt;tfoot&gt;
      &lt;tr&gt;
        &lt;td scope="colgroup" colspan="99" class="footnotes"&gt;
          Footnotes: Aligned-left
        &lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tfoot&gt;
  &lt;/table&gt;
&lt;/div&gt;</code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#ColumnDivider">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">