<a name="Default"></a>

<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Table with default base styles</h2>

<div>
	<table>
		<thead>
			<tr>
				<th><code>left aligned</code></th>
				<th><code>left aligned</code></th>
				<th><code>left aligned</code></th>
				<th><code>left aligned</code></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
			</tr>
			<tr>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
			</tr>
			<tr>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
			</tr>
			<tr>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
				<td><code>left aligned</code></td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td colSpan="4"><code>left aligned</code></td>
			</tr>
		</tfoot>
	</table>
</div>
<!--

  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div><pre><code class="language-html" id="Default"></code></pre>
  <!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Default">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
-->