<a name="Footnotes"></a>

<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Table Footnotes Ordered List</h2>
<!--
    <h4>Live examples:</h4>
  <div class="primary">
    <ul class="live-examples">
      <li><a>n/1</a></li>
    </ul>
  </div>  
  -->
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
	<div class="basic-table">
		<table class="basic-table full-width">
			<thead>
				<tr>
					<th scope="col">...</th>
					<th scope="col">...</th>
					<th scope="col">...</th>
					<th scope="col">...</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">...</th>
					<td>...</td>
					<td>...</td>
					<td>...</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colSpan="99" scope="colgroup" class="footnotes">
						<ul class="footnotes">
							<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
							<li>Donec lorem massa, semper nec eros a, lacinia porttitor nunc.</li>
							<li>Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien.</li>
							<li>Suspendisse sagittis risus eu sem suscipit sodales.</li>
							<li>Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus.</li>
							<li>Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis.</li>
							<li>Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem.</li>
							<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
						</ul>
					</td>
				</tr>
			</tfoot>
		</table>
	</div>

	<!-- HTML -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
	<div class="uk-margin-medium">
		<pre><code class="language-html" id="TableFootnotesOrderedList">&lt;div class="basic-table"&gt;
  &lt;table class="basic-table full-width"&gt;
    &lt;tfoot&gt;
      &lt;tr&gt;
        &lt;td colspan="99" scope="colgroup" class="footnotes"&gt;
          &lt;ul class="footnotes"&gt;
            &lt;li&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit.&lt;/li&gt;
            &lt;li&gt;Donec lorem massa, semper nec eros a, lacinia porttitor nunc.&lt;/li&gt;
            &lt;li&gt;Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien.&lt;/li&gt;
            &lt;li&gt;Suspendisse sagittis risus eu sem suscipit sodales.&lt;/li&gt;
            &lt;li&gt;Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus.&lt;/li&gt;
            &lt;li&gt;Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis.&lt;/li&gt;
            &lt;li&gt;Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem.&lt;/li&gt;
            &lt;li&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.&lt;/li&gt;
          &lt;/ul&gt;
        &lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tfoot&gt;
  &lt;/table&gt;
&lt;/div&gt;</code></pre>
		<!-- Copy Button -->
		<p>
			<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#TableFootnotesOrderedList">
				<span uk-icon="copy"></span>Copy to clipboard
			</button>
		</p>
		</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">