<a name="Foot"></a>

<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Table Foot</h2>

<div class="basic-table">
	<table class="basic-table full-width">
		<thead>
			<tr>
				<th scope="col">...</th>
				<th scope="col">...</th>
				<th scope="col">...</th>
				<th scope="col">...</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row">...</th>
				<td>...</td>
				<td>...</td>
				<td>...</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td scope="col"><code>left aligned</code></td>
				<td scope="col"><code>right aligned</code></td>
				<td scope="col"><code>right aligned</code></td>
				<td scope="col"><code>right aligned</code></td>
			</tr>
		</tfoot>
	</table>
</div>
<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="Foot">&lt;div class="basic-table"&gt;
  &lt;table class="basic-table full-width"&gt;
    &lt;thead&gt;
      &lt;tr&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
      &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
    &lt;tfoot&gt;
      &lt;tr&gt;
        &lt;td scope="col"&gt;...&lt;/td&gt;
        &lt;td scope="col"&gt;...&lt;/td&gt;
        &lt;td scope="col"&gt;...&lt;/td&gt;
        &lt;td scope="col"&gt;...&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tfoot&gt;
  &lt;/table&gt;
&lt;/div&gt;</code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Foot">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">