<a name="FullWidth"></a>

<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Full Width Table</h2>
<p>
	Adding a <code>&lt;full-width&gt;</code> to the table class (&lt;table class="basic-table full-width&gt;).
</p>

<div class="basic-table">
	<table class="basic-table full-width">
		<thead>
			<tr>
				<th scope="col"><code>left aligned</code></th>
				<th scope="col"><code>right aligned</code></th>
				<th scope="col"><code>right aligned</code></th>
				<th scope="col"><code>right aligned</code></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td scope="row"><code>left aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<td scope="row"><code>left aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<td scope="row"><code>left aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<td scope="row"><code>left aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td colSpan="4" scope="colgroup"><code>left aligned</code>
				</td>
			</tr>
		</tfoot>
	</table>
</div>

<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>


<!-- textarea id="FullWidth" -->
<pre><code class="language-html" id="FullWidth">&lt;div class="basic-table"&gt;
  &lt;table class="basic-table full-width"&gt;
    &lt;thead&gt;
      &lt;tr&gt;
        &lt;th scope="col"&gt;&lt;/th&gt;
        &lt;th scope="col"&gt;&lt;/th&gt;
        &lt;th scope="col"&gt;&lt;/th&gt;
        &lt;th scope="col"&gt;&lt;/th&gt;
      &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
      &lt;tr&gt;
        &lt;td scope="row"&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td scope="row"&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td scope="row"&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td scope="row"&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
    &lt;tfoot&gt;
      &lt;tr&gt;
        &lt;td colSpan="4" scope="colgroup"&gt;
        &lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tfoot&gt;
  &lt;/table&gt;
&lt;/div&gt;
</code></pre>


<!-- Trigger -->
<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#FullWidth">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">