<a name="RowHead"></a>

<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">
	Table Row Head (<span class="accessibility-requirement">Accessibility requirement</span>)
</h2>

<p>
	Adding a <code>&lt;th scope="row"&gt;&lt;/th&gt;</code> to the first cell (&lt;th&gt; or &lt;td&gt;) in a table row.
	<br />
	<strong>Note:</strong> This does not change the appearance and is ony added for accessibility.
</p>


<div class="basic-table">
	<table class="basic-table full-width">
		<thead>
			<tr>
				<th scope="col">...</th>
				<th scope="col">...</th>
				<th scope="col">...</th>
				<th scope="col">...</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
			<tr>
				<th scope="row"><code>left aligned</code></th>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
				<td><code>right aligned</code></td>
			</tr>
		</tbody>
	</table>
</div>
<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="RowHead">&lt;div class="basic-table"&gt;
  &lt;table class="basic-table full-width"&gt;
    &lt;thead&gt;
      &lt;tr&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
      &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th scope="row"&gt;...&lt;/th&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
  &lt;/table&gt;
&lt;/div&gt;</code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#RowHead">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">