<a name="RowSelected"></a>

<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Row Selected</h2>
<p>
	Overiding the column alignment (head, body and foot) can be accomplished by adding a <code>selector</code> to the table class.
</p>

<div class="basic-table">
	<table class="basic-table full-width highlight-col-2 selector">
		<thead>
			<tr>
				<th>&nbsp;</th>
				<th>03/27/19</th>
				<th>week ago</th>
				<th>year ago</th>
			</tr>
		</thead>
		<tbody>
			<tr class="selected" id="rp_us">
				<td>
					<span class="eia ico grid-line" title="Click to chart this series">
						<span>CHART ICON</span>
					</span>
					Connecticut
				</td>
				<td>2.969</td>
				<td>
					-0.019
					<span class="eia ico down-arrow">
						<span>DOWN</span>
					</span>
				</td>
				<td>
					0.457
					<span class="eia ico up-arrow">
						<span>UP</span>
					</span>
				</td>
			</tr>
			<tr id="rp_padd1">
				<td>
					<span class="eia ico grid-line" title="Click to chart this series">
						<span>CHART ICON</span>
					</span>
					Maine
				</td>
				<td>2.596</td>
				<td>
					-0.011
					<span class="eia ico down-arrow">
						<span>DOWN</span>
					</span>
				</td>
				<td>
					0.335
					<span class="eia ico up-arrow">
						<span>UP</span>
					</span>
				</td>
			</tr>
			<tr id="rp_padd2">
				<td>
					<span class="eia ico grid-line" title="Click to chart this series">
						<span>CHART ICON</span>
					</span>
					Massachusetts
				</td>
				<td>3.120</td>
				<td>
					-0.011
					<span class="eia ico down-arrow">
						<span>DOWN</span>
					</span>
				</td>
				<td>
					0.208
					<span class="eia ico up-arrow">
						<span>UP</span>
					</span>
				</td>
			</tr>
			<tr id="rp_padd3">
				<td>
					<span class="eia ico grid-line" title="Click to chart this series">
						<span>CHART ICON</span>
					</span>
					New Hampshire
				</td>
				<td>3.579</td>
				<td>
					-0.003
					<span class="eia ico down-arrow">
						<span>DOWN</span>
					</span>
				</td>
				<td>
					0.598
					<span class="eia ico up-arrow">
						<span>UP</span>
					</span>
				</td>
			</tr>
		</tbody>
	</table>
	<table class="basic-table full-width selector">
		<tbody>
			<tr>
				<td>
					<span class="eia ico grid-column">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-line">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-map">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-parent-column">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-parent-line">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-parent-map">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-parent-pin">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-pin">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-key">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td class="sectionhead" colSpan="3">
					Selected
				</td>
			</tr>
			<tr>
				<td>
					<span class="eia ico grid-column">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-line">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-map">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-parent-column">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-parent-line">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-parent-map">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-parent-pin">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-pin">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>

			<tr>
				<td>
					<span class="eia ico grid-key">
						<span></span>
					</span>
					Lorem ipsum
				</td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
	</table>
</div>
<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="RowSelected">&lt;div class="basic-table"&gt;
  &lt;table class="basic-table full-width highlight-col-2 selector"&gt;
    &lt;thead&gt;
      &lt;tr&gt;
        &lt;th&gt;&amp;nbsp;&lt;/th&gt;
        &lt;th&gt;03/27/19&lt;/th&gt;
        &lt;th&gt;week ago&lt;/th&gt;
        &lt;th&gt;year ago&lt;/th&gt;
      &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
      &lt;tr class="selected" id="rp_us"&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-line" title="Click to chart this series"&gt;
            &lt;span&gt;CHART ICON&lt;/span&gt;
          &lt;/span&gt;
          Connecticut
        &lt;/td&gt;
        &lt;td&gt;2.969&lt;/td&gt;
        &lt;td&gt;
          -0.019
          &lt;span class="eia ico down-arrow"&gt;
            &lt;span&gt;DOWN&lt;/span&gt;
          &lt;/span&gt;
        &lt;/td&gt;
        &lt;td&gt;
          0.457
          &lt;span class="eia ico up-arrow"&gt;
            &lt;span&gt;UP&lt;/span&gt;
          &lt;/span&gt;
        &lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr id="rp_padd1"&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-line" title="Click to chart this series"&gt;
            &lt;span&gt;CHART ICON&lt;/span&gt;
          &lt;/span&gt;
          Maine
        &lt;/td&gt;
        &lt;td&gt;2.596&lt;/td&gt;
        &lt;td&gt;
          -0.011
          &lt;span class="eia ico down-arrow"&gt;
            &lt;span&gt;DOWN&lt;/span&gt;
          &lt;/span&gt;
        &lt;/td&gt;
        &lt;td&gt;
          0.335
          &lt;span class="eia ico up-arrow"&gt;
            &lt;span&gt;UP&lt;/span&gt;
          &lt;/span&gt;
        &lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr id="rp_padd2"&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-line" title="Click to chart this series"&gt;
            &lt;span&gt;CHART ICON&lt;/span&gt;
          &lt;/span&gt;
          Massachusetts
        &lt;/td&gt;
        &lt;td&gt;3.120&lt;/td&gt;
        &lt;td&gt;
          -0.011
          &lt;span class="eia ico down-arrow"&gt;
            &lt;span&gt;DOWN&lt;/span&gt;
          &lt;/span&gt;
        &lt;/td&gt;
        &lt;td&gt;
          0.208
          &lt;span class="eia ico up-arrow"&gt;
            &lt;span&gt;UP&lt;/span&gt;
          &lt;/span&gt;
        &lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr id="rp_padd3"&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-line" title="Click to chart this series"&gt;
            &lt;span&gt;CHART ICON&lt;/span&gt;
          &lt;/span&gt;
          New Hampshire
        &lt;/td&gt;
        &lt;td&gt;3.579&lt;/td&gt;
        &lt;td&gt;
          -0.003
          &lt;span class="eia ico down-arrow"&gt;
            &lt;span&gt;DOWN&lt;/span&gt;
          &lt;/span&gt;
        &lt;/td&gt;
        &lt;td&gt;
          0.598
          &lt;span class="eia ico up-arrow"&gt;
            &lt;span&gt;UP&lt;/span&gt;
          &lt;/span&gt;
        &lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
  &lt;/table&gt;
  &lt;table class="basic-table full-width selector"&gt;
    &lt;tbody&gt;
      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-column"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-line"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-map"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-parent-column"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-parent-line"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-parent-map"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-parent-pin"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-pin"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-key"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td class="sectionhead" colspan="3"&gt;
          Selected
        &lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-column"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-line"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-map"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-parent-column"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-parent-line"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-parent-map"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-parent-pin"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-pin"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;

      &lt;tr&gt;
        &lt;td&gt;
          &lt;span class="eia ico grid-key"&gt;
            &lt;span&gt;&lt;/span&gt;
          &lt;/span&gt;
          Lorem ipsum
        &lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
        &lt;td&gt;&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
  &lt;/table&gt;
&lt;/div&gt;</code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#RowSelected">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">