<a name="Stacked"></a>

<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Multiple Tables (stacked)</h2>

<div class="basic-table">
	<table class="basic-table full-width">
		<caption>Table One</caption>
		<thead>
			<tr>
				<th scope="col">...</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>...</td>
			</tr>
			<tr>
				<td>...</td>
			</tr>
		</tbody>
	</table>

	<table class="basic-table full-width">
		<caption>Table Two</caption>
		<thead>
			<tr>
				<th scope="col">...</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>...</td>
			</tr>
			<tr>
				<td>...</td>
			</tr>
		</tbody>
	</table>

	<table class="basic-table full-width">
		<caption>Table Three</caption>
		<thead>
			<tr>
				<th scope="col">...</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>...</td>
			</tr>
			<tr>
				<td>...</td>
			</tr>
		</tbody>
	</table>
</div>
<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="Stacked">&lt;div class="basic-table"&gt;
  &lt;table class="basic-table full-width"&gt;
    &lt;caption&gt;Table One&lt;/caption&gt;
    &lt;thead&gt;
      &lt;tr&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
      &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
      &lt;tr&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
  &lt;/table&gt;

  &lt;table class="basic-table full-width"&gt;
    &lt;caption&gt;Table Two&lt;/caption&gt;
    &lt;thead&gt;
      &lt;tr&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
      &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
      &lt;tr&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
  &lt;/table&gt;

  &lt;table class="basic-table full-width"&gt;
    &lt;caption&gt;Table Three&lt;/caption&gt;
    &lt;thead&gt;
      &lt;tr&gt;
        &lt;th scope="col"&gt;...&lt;/th&gt;
      &lt;/tr&gt;
    &lt;/thead&gt;
    &lt;tbody&gt;
      &lt;tr&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;td&gt;...&lt;/td&gt;
      &lt;/tr&gt;
    &lt;/tbody&gt;
  &lt;/table&gt;
&lt;/div&gt;</code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Stacked">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">