<ul class="tertiary-table-nav">
	<li>
		<a href="#Basic">Basic</a>
	</li>
	<li>
		<a href="#FullWidth">Full-Width</a>
	</li>
	<li>
		<a href="#Caption">Caption</a>
	</li>
	<li>
		<a href="#HeadDouble">Double-head</a>
	</li>
	<li>
		<a href="#RowHead">Head-row</a>
	</li>
	<li>
		<a href="#RowTotal">Row Total</a>
	</li>
	<li>
		<a href="#RowBold">Row Bold</a>
	</li>
	<li>
		<a href="#RowIndent">Row Indent</a>
	</li>
	<li>
		<a href="#RowSectionHead">Row Section Head</a>
	</li>
	<li>
		<a href="#RowSectionDivider">Row Section Divider</a>
	</li>
	<li>
		<a href="#ColumnHighlight">Column Highlight</a>
	</li>
	<li>
		<a href="#ColumnDivider">Column Divider</a>
	</li>
	<li>
		<a href="#ColumnAlign">Column Align</a>
	</li>
	<li>
		<a href="#ColumnHide">Column Hide</a>
	</li>
	<li>
		<a href="#Foot">Foot</a>
	</li>
	<li>
		<a href="#Footnotes">Footnotes</a>
	</li>
	<li>
		<a href="#Stacked">Stacked</a>
	</li>
	<li>
		<a href="#RowSelected">Selected</a>
	</li>
	<li>
		<a href="#HolidaySchedule">Holiday Schedule</a>
	</li>
</ul>