<div class="carousel-container">

	<div aria-label="carousel" class="slider" data-carousel>
		<button class="prev" data-carousel-button="prev">&#10094;</button>
		<button class="next" data-carousel-button="next">&#10095;</button>
<ul data-slides>
			<li class="slide" data-active>
				<div class="carousel-content">
			   <!-- slide 1 -->
<h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=21" target="new">The chemicals subsector accounted for the largest share of purchased electricity, natural gas, and steam</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=21" target="new"><img src="data/2022/images/slide21.svg" width="620" style="background-color: white; padding: 0px 0px; margin-bottom: 0px;" alt="The chemicals subsector accounted for the largest share of purchased electricity, natural gas, and stea" /></a>
<div class="footnotes">
						<p>Data source: U.S. Energy Information Administration, <em>2022 Manufacturing Energy Consumption Survey</em></p>
</div>
</div>
</li>
<li class="slide">
<div class="carousel-content">
			   <!-- slider 2 -->
<h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=39" target="new">On average, primary metals, paper, and transportation equipment establishments were the largest</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=39" target="new" width="325"><img src="data/2022/images/slide39.svg" width="400" style="background-color: white; padding: 0px 0px; margin-bottom: 0px;" alt="Average enclosed floorspace by manufacturing subsector, 2022" /></a>
<div class="footnotes">
						<p>Data source: U.S. Energy Information Administration, <em>2022 Manufacturing Energy Consumption Survey</em></p>
</div>
</div>
</li>
<li class="slide">
<div class="carousel-content">
			  <!-- slide 3 -->
			  <li>
              <h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=27" target="new">More than 40% of manufacturing establishments participated in general energy management activities</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=27" target="new"><img src="data/2022/images/slide23.svg" width="550" style="background-color: white; padding: 0px 0px; margin-bottom: 0px; " alt="Energy management activities, 2022" /></a>
<div class="footnotes">
						<p>Data source: U.S. Energy Information Administration, <em>Manufacturing Energy Consumption Survey</em></p>
</div>
</div>
</li>
<li class="slide">
<div class="carousel-content">
			  <!-- slide 4 -->
<h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=35" target="new">Improving energy efficiency is important for the top energy-consuming subsectors</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=35" target="new" width="525"><img src="data/2022/images/slide31.svg" width="400" style="background-color: white; padding: 0px 0px; margin-bottom: 0px; max-width: 450px;" alt="Energy consumption improvement efforts in manufacturing, 2022" /></a>
<div class="footnotes">
					<p>Data source: U.S. Energy Information Administration, <em>Manufacturing Energy Consumption Survey</em></p>
</div>
</div>
</li>
<li class="slide">
<div class="carousel-content">
			  <!-- slide 5 -->
<h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=7" target="new">Natural gas and HGLs continue to increase their shares of total consumption</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=7" target="new" width="525"><img src="data/2022/images/slide7.svg" width="400" style="background-color: white; padding: 0px 0px; margin-bottom: 0px; max-width: 450px;" alt="Natural gas and HGLs continue to increase their shares of total consumption" /></a>
<div class="footnotes">
					<p>Data source: U.S. Energy Information Administration, <em>Manufacturing Energy Consumption Survey</em></p>
</div>
</div>
</li>
<li class="slide">
<div class="carousel-content">
			  <!-- slide 6 -->
<h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=8" target="new">Growth in gross output continues to outpace manufacturing energy consumption growth</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=8" target="new" width="525"><img src="data/2022/images/slide8.svg" width="400" style="background-color: white; margin-bottom: 0px; max-width: 600px;" alt="Growth in gross output continues to outpace manufacturing energy consumption growth" /></a>
<div class="footnotes">
					<p>Data sources: U.S. Energy Information Administration, <em>Manufacturing Energy Consumption Survey</em>; Bureau of Economic Analysis, <em>Gross Output by Industry</em></p>
</div>
</div>
</li>
<li class="slide">
<div class="carousel-content">
			  	    <!-- slide 7 -->
<h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=9" target="new">Nonfuel consumption is dominant in the chemicals sector</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=9" target="new" width="705"><img src="data/2022/images/slide9.svg" width="800" style="background-color: white; margin-bottom: 0px; max-width: 620px;" alt="Nonfuel consumption is dominant in the chemicals sector" /></a>
<div class="footnotes">
						<p>Data source: U.S. Energy Information Administration, <em>Manufacturing Energy Consumption Survey</em></p>
					</div>
				</div>
			</li>
			  	    <!-- slide 8 -->
<h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=33" target="new">Four sectors account for most manufacturing energy consumption</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=33" target="new" width="705"><img src="data/2022/images/slide10_v3-01.svg" width="600" style="background-color: white; margin-bottom: 0px; max-width: 550px;" alt="Four sectors account for most manufacturing energy consumption" /></a>
<div class="footnotes">
					<p>Data source: U.S. Energy Information Administration, <em>Manufacturing Energy Consumption Survey</em></p>
</div>
</div>
</li>
<li class="slide">
<div class="carousel-content">
			    <!-- slide 9 -->
<h1><a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=12" target="new">Natural gas was the most-used fuel for all end uses</a></h1>
<a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf#page=12" target="new" width="705"><img src="data/2022/images/slide13.svg" width="520" style="background-color: white; margin-bottom: 0px; max-width: 550px;" alt="Natural gas was the most-used fuel for all end uses" /></a>
<div class="footnotes">
					<p>Data source: U.S. Energy Information Administration, <em>Manufacturing Energy Consumption Survey</em></p>
</div>
</div>
</li>
</ul>
		<ul class="dots" data-dots>
			<li class="dot" data-active>
			<li class="dot">
			<li class="dot">
			<li class="dot">
			<li class="dot">
					<li class="dot">
			<li class="dot">
			<li class="dot">
			<li class="dot">
		</ul>
	</div>
</div>