<hr>
<p>Specific questions on this product may be directed to:</p>
	  <p><a href="mailto:thomas.lorenz@eia.gov">Tom Lorenz</a><br />
      Phone: 202-586-3442
		  <!--<br />Fax: 202-586-0018--></p>


<!--
<blockquote>
  <div class="split_2columns">
    <p><a href="mailto:thomas.lorenz@eia.gov">Tom Lorenz</a><br />
      Phone: 202-586-3442<br />
      Fax: 202-586-0018</p>
  </div>
<div class="split_2columns">
<p><a href="mailto:robert.adler@eia.gov">Robert Adler</a><br />
  Phone: 202-586-1134<br />
  Fax: 202-586-0018</p>
  </div>
</blockquote>-->
<div class="clear"></div>
<?php echo PHP_EOL; ?>