<h2>Final results from the <em>2022 Manufacturing Energy Consumption Survey</em> (MECS) are now available</h2> 
	  	<p><i>Release date: March 18, 2026</i></p>
		 <p>The final set of results from  the 2022 <em>Manufacturing Energy Consumption Survey </em>(MECS), which includes 12 new <a href="/consumption/manufacturing/data/2022/">data tables</a> and accompanying  <a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf" class="ico_pdf">highlights</a>, provides information on ratios of manufacturing fuel consumption to economic characteristics, average prices and quantities of purchased energy sources, and floorspace and building counts.	     </p>
		 <p>The new data show:</p>
        <ul>
           <li>Consumption  ratios of fuel by region were highest in the South.</li>
           <li>On  average, electricity and distillate fuel oil were the most expensive energy  sources.</li>
           <li>The  average price of energy varied by region.</li>
           <li>The  chemicals subsector accounted for the largest share of purchased electricity,  natural gas, and steam.</li>
           <li>Petroleum  and coal products had the highest energy consumption per employee.</li>
           <li>Fabricated  metal products establishments were the most numerous of all industries.</li>
           <li>On  average, primary metals, paper, and transportation equipment establishments  were the largest.</li>
         </ul>
         <p>Further, we republished nine data tables to provide hydrogen estimates by subsector and industry at the national level. This release is the first time we have published hydrogen estimates for the <em>Manufacturing Energy Consumption Survey </em>(MECS). You can find these data in our data tables for:</p>
         <ul>
           <li>Consumption Energy for All Purposes (First Use)</li>
           <li>Energy Used as a Nonfuel (Feedstock)</li>
           <li>Energy Consumption as a Fuel</li>
           <li>Offsite-Produced Fuel Consumption</li>
         </ul>
         <p><strong><a href="/consumption/manufacturing/data/2022/">Data Tables</a></strong> <br />
         <strong>2022 Manufacturing Energy Consumption Survey: Highlights from Final Data Release&nbsp;</strong> <a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf" class="ico_pdf"><strong>PDF</strong></a></p>
		<div>
		  <div> </div>
		</div>
		<hr style="height: 1.5px" />
    <?php /*  <span class="side_left">
			
			<!-- Start Industry Analysis Briefs --> 
        <h4 >Industry Analysis Briefs </h4>
        <h5><a href="briefs/steel/">Steel Industry Analysis</a></h5>
        <p>The steel industry is critical to the U.S. economy. Steel is the material of choice for many elements of construction, transportation, manufacturing, and a variety of consumer products. It is the backbone of bridges, skyscrapers, railroads, automobiles, and appliances. Most grades of steel used today - particularly high-strength steels that are lighter and more versatile - were not available a decade ago.</p>
        <h5><a href="briefs/chemical/">Chemical Industry Analysis</a></h5>
        <p>The chemical industries are a cornerstone of the U.S. economy, converting raw materials such as oil, natural gas, air, water, metals, and minerals into thousands of various products. Chemicals are key materials for producing an extensive assortment of consumer goods.</p>*/ ?>
        <?php /*p><a href="briefs/">See all MECS analyis briefs &raquo;</a></p <?php /* 
     <hr />
        </span>
        <?php /* Features */ ?>
        
        <!-- Start Features -->
		    <span class="full">
				
			<h4>Features</h4>
				 <h3>Final results for energy management activities and establishment counts from the <em>2022 Manufacturing Energy Consumption Survey</em> (MECS) are now available</h3> 
	  	<p><i>Release date: December 17, 2025</i></p>
		 <p>The third set of results from  the 2022 <em>Manufacturing  Energy Consumption Survey</em> (MECS), which include 29 new <a href="/consumption/manufacturing/data/2022/">data tables</a> and accompanying <a href="/consumption/manufacturing/data/2022/pdf/MECS 2022 Release 1-3 Results.pdf" class="ico_pdf">highlights</a>, provide information on U.S. manufacturing energy management activities and  establishment counts.</p>
		  
	     <p>The new data show:</p>
        <ul>
           <li>Price changes would not affect the switch to alternative fuels.</li>
           <li>More than 40% of manufacturing establishments participated in general energy management activities. </li>
           <li>Less than 1% of manufacturing establishments had cogeneration technologies.</li>
           <li>The largest shares of onsite cogeneration and onsite generation from <em>other</em> sources were in the South.</li>
           <li>Improving energy efficiency is important for the top energy-consuming subsectors.</li>
         </ul>
         <p>We will continue releasing the final 2022 MECS data through Spring 2026. A detailed schedule of the 2022 MECS release dates is available on the <a href="/consumption/manufacturing/data/2022/">MECS data website</a>.</p>
         <p><strong><a href="/consumption/manufacturing/data/2022/">Data Tables</a></strong> <br />
         <strong>2022 Manufacturing Energy Consumption Survey: Highlights from Data Release 1&ndash;3&nbsp;</strong> <a href="/consumption/manufacturing/data/2022/pdf/MECS 2022 Release 1-3 Results.pdf" class="ico_pdf"><strong>PDF</strong></a></p>
				
				<hr>
					    <h3><a href="/consumption/manufacturing/data/2022/">Final results for consumption by economic characteristics of the manufacturers and expenditures for purchased energy sources from the <em>2022 Manufacturing Energy Consumption Survey</em> (MECS) are now available</a></h3> 
	  	<p><i>Release date: September 24, 2025</i></p>
		 <p>The second set of results from the 2022 <a href="/consumption/manufacturing/"><em>Manufacturing Energy  Consumption Survey</em> (MECS)</a>, which include 9  new <a href="/consumption/manufacturing/data/2022/">data tables</a> and accompanying <a href="/consumption/manufacturing/data/2022/pdf/MECS 2022 Release 1-2 Results.pdf" class="ico_pdf">highlights</a>, provide information on U.S. manufacturing energy consumption by economic characteristics of the manufacturers and expenditures for purchased energy sources.</p>
		  
	     <p>The new data show:</p>
        <ul>
           <li>The top five energy-consuming sectors  account for about three-fourths of energy expenditures.</li>
           <li>Establishments with the largest value  of shipments and receipts accounted for over half of energy consumption.</li>
           <li>At the national level, total  consumption was similar across employment size categories.</li>
           <li>Most natural gas and steam were  purchased from nonutilities.</li>
         </ul>
         <p>We will continue releasing the final 2022 MECS data through Spring 2026. A detailed schedule of the 2022 MECS release dates is available on the  <a href="/consumption/manufacturing/data/2022/">MECS data website</a>.</p>
         <p><strong><a href="/consumption/manufacturing/data/2022/">Data Tables</a></strong> <br />
         <strong>2022 Manufacturing Energy Consumption Survey: Highlights from Data Release 1 and 2&nbsp;</strong> <a href="/consumption/manufacturing/data/2022/pdf/MECS 2022 Release 1-2 Results.pdf" class="ico_pdf"><strong>PDF</strong></a></p>
				  <hr />
				
			<h3><a href="/consumption/manufacturing/data/2022/">Final consumption, end use, and fuel-switching results from the 2022 Manufacturing Energy Consumption Survey (MECS) are now available</a></h3>
        <p><i>Release date: August 6, 2025</i></p>
        <p>First set of results from the 2022 Manufacturing Energy Consumption Survey (MECS), which include 35 new <a href="/consumption/manufacturing/data/2022/">data tables</a> and accompanying <a href="/consumption/manufacturing/data/2022/pdf/MECS2022-flipbook_v2.pdf" class="ico_pdf">highlights</a>, provide information on U.S. manufacturing energy consumption (fuel and nonfuel), end uses of fuel consumption, and fuel-switching capability.</p>
</span>
		    <p>The new data show:</p>
            <ul>
              <li>Manufacturing energy consumption continues to grow, in part, due to increased natural gas consumption </li>
              <li>Nonfuel (feedstock) consumption is greatest in chemical manufacturing </li>
              <li>Four subsectors—chemical, petroleum  and coal products, paper, and primary metals—account for most of the manufacturing energy consumption </li>
              <li>Most subsectors cannot easily switch from natural gas to alternative fuels such as coal, electricity, and renewables</li>
            </ul>
            <p>We will continue releasing the final 2022 MECS data through Spring 2026. A detailed schedule of the 2022 MECS release dates is available on the <a href="/consumption/manufacturing/data/2022/">MECS data website</a>.</p>
            <span class="full">
        <hr />
				
			<h3><a href="/consumption/manufacturing/reports/2022/prelim_estimates/"><!--<img src="data/2022/images/slide7.svg" alt="bar chart" width="147" height="115"/>-->Preliminary estimates show increased total U.S. manufacturing energy consumption in 2022</a></h3>
        <p><i>Release date: March 20, 2025</i></p>
        <p>Preliminary results from our 2022 Manufacturing Energy Consumption Survey (MECS) show that total U.S. manufacturing energy consumption increased 6% between 2018 and 2022. MECS is the only source for national estimates of energy-related characteristics, consumption, and expenditures for manufacturers in the United States.</p>
        <!--<hr />
        <h3><a href="reports/2014/fuel_switching/"><img src="reports/2014/fuel_switching/images/fig1.png"  alt="bar chart" width="147" height="115"/>The Capability of U.S. Manufacturing to Switch Fuels </a></h3>
        <p><i>Release Date: September 6, 2018</i></p>
        <p>Preliminary estimates show that the total U.S. manufacturing  energy consumption increased about 3.7% between 2010 and 2014. This is the first measured 4-year increase in manufacturing energy consumption since 2002 (Figure 1). Energy source shares have changed modestly since 2002, with natural gas rising from 29% to 33% of all manufacturing energy consumption. Conversely, during this same period, the share of delivered energy to manufacturing from coal, coke and breeze declined from 10% to 8%, while the  share of fuel oils and naphtha together decreased from 7% to 5%.</p>-->
       
				<?php /*<hr />
			
			<h3><a href="reports/2014/enduse_intensity/"><img src="reports/2014/enduse_intensity/images/fig1.png"  alt="bar chart" width="147" height="115"/>Energy Use and Energy Intensity of U.S. Manufacturing—Data from the 2014 Manufacturing Energy Consumption Survey (MECS) </a></h3>
        <p><i>Release Date: October 18, 2017</i></p>
       
        Energy intensity in manufacturing  in the United States decreased from 2010 to 2014.U.S. manufacturing overall fuel intensity decreased by 4.4% from 3.016   thousand British thermal units (Btu) per dollar of output in 2010 to 2.882 thousand Btu in 2014. U.S. manufacturing fuel consumption rose 4.7% from 2010 to 2014, although real gross output increased  more rapidly at 9.6%. 
        <p>&nbsp;</p>
        <hr />
        
			<h3><a href="reports/2014/pre_estimates/"><img src="reports/2014/pre_estimates/images/figure_1.png"  alt="bar chart" width="147" height="115"/>Preliminary estimates show that U.S. manufacturing energy consumption increased between 2010 and 2014 </a></h3>
        <p><i>Release Date: October 13, 2016</i></p>
        <p>Preliminary estimates show that the total U.S. manufacturing  energy consumption increased about 3.7% between 2010 and 2014. This is the first measured 4-year increase in manufacturing energy consumption since 2002 (Figure 1). Energy source shares have changed modestly since 2002, with natural gas rising from 29% to 33% of all manufacturing energy consumption. Conversely, during this same period, the share of delivered energy to manufacturing from coal, coke and breeze declined from 10% to 8%, while the share of fuel oils and naphtha together decreased from 7% to 5%.</p>
       
          <p>&nbsp;</p>
		   <hr />
       <h3><a href="reports/2010/ng_cost/"><img src="reports/2010/ng_cost/fig1.png"  alt="bar chart" width="147" height="115"/>Cost of Natural Gas Used in Manufacturing Sector Has Fallen</a></h3>
        <p><i>Release Date: September 6, 2013</i></p>
        <p>Natural gas has been an important exception to the trend of rising prices for energy sources used by manufacturers. Production of natural gas in the United States increased rapidly beginning in 2007 as a result of resources found in shale formations. That increase in supply has in turn lowered the price of natural gas to manufacturers as well as other consumers.</p>
        <hr />
         <h3><a href="reports/2010/decrease_use.cfm"><img src="reports/2010/images/fig1-lg.png"  alt="bar chart" width="147" height="115"/>Manufacturing energy consumption data show large reductions in both manufacturing energy use and the energy intensity of manufacturing activity between 2002 and 2010</a></h3>
        <p><i>Release Date: March 19, 2013</i></p>
        <p>Total energy consumption in the manufacturing sector decreased by 17 percent from 2002 to 2010 (Figure 1), according to new 2010 MECS data.</p>
        <hr />
        <h3><a href="reports/2010/early_estimates.cfm"><img src="reports/2010/images/acbfig1-lg.jpg"  alt="bar chart" width="147" height="115"/>Early-release estimates from the 2010 MECS show that energy consumption in the manufacturing sector decreased between 2006 and 2010</a></h3>
        <p><i>Release Date: March 28, 2012</i></p>
        <p>Energy consumption in the U.S. manufacturing sector fell from 21,098 trillion Btu (tBtu) in 2006 to 19,062 tBtu in 2010, a decline of almost 10 percent, based on preliminary estimates released from the 2010 Manufacturing Energy Consumption Survey (MECS). This decline continues the downward trend in manufacturing energy use since the 1998 MECS report.</p>*/ ?>
	