<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="gridPin">&lt;span class="eia ico grid-pin&gt;
	&lt;span&gt;Grid pin&lt;/span&gt;
&lt;/span&gt;</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#gridPin">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>