<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="gridParentPin">&lt;span class="eia ico grid-parent-pin&gt;
	&lt;span&gt;Grid parent pin&lt;/span&gt;
&lt;/span&gt;</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#gridParentPin">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>