<h3>Grid Icons</h3>
<div class="accordion-content horizontal-icon-container grid">

	<div class="icon-container">
		<h6>Grid-Column Icon</h6>
		<span class="eia ico grid-column">
			<span>grid column</span>
		</span>
		<?php include('./includes/icons/grid/grid-column.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Grid-Key Icon</h6>
		<span class="eia ico grid-key">
			<span>grid-key</span>
		</span>
		<?php include('./includes/icons/grid/grid-key.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Grid-Line Icon</h6>
		<span class="eia ico grid-line">
			<span>grid line</span>
		</span>
		<?php include('./includes/icons/grid/grid-line.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Grid-Map Icon</h6>
		<span class="eia ico grid-map">
			<span>grid map</span>
		</span>
		<?php include('./includes/icons/grid/grid-map.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Grid-Parent-Map Icon</h6>
		<span class="eia ico grid-parent-map">
			<span>grid-parent-map</span>
		</span>
		<?php include('./includes/icons/grid/grid-parent-map.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Grid-Parent-Line Icon</h6>
		<span class="eia ico grid-parent-line">
			<span>grid parent line</span>
		</span>
		<?php include('./includes/icons/grid/grid-parent-line.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Grid-Parent-PIN Icon</h6>
		<span class="eia ico grid-parent-pin">
			<span>grid-parent-pin</span>
		</span>
		<?php include('./includes/icons/grid/grid-parent-pin.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Grid-Parent-Column Icon</h6>
		<span class="eia ico grid-parent-column">
			<span>grid parent column</span>
		</span>
		<?php include('./includes/icons/grid/grid-parent-column.inc') ?>
	</div>
	<div class="icon-container">
		<h6>Grid-PIN Icon</h6>
		<span class="eia ico grid-pin">
			<span>grid-pin</span>
		</span>
		<?php include('./includes/icons/grid/grid-pin.inc') ?>
	</div>
</div>
</div>