<?php /* Faux-blog box */ ?>
<style type="text/css">
  .white_box.blue_top .date {
    color: #C0C0C0;
  }
</style>

<h1 style="font-size: 20px"><a name="blog" id="blog"></a>CBECS Status</h1>
<?php /*<div class="notice">
Data collection for the 2012 CBECS Energy Supplier Survey (ESS) is in progress. Westat, EIA's contractor for the ESS, is currently contacting energy providers with instructions and support for accessing the secure ESS web portal for data submission.  EIA conducts the ESS under its mandatory authority. To learn more about the ESS, visit <a href="/consumption/commercial/about.cfm">About the CBECS</a>.
</div> */ ?>

<!--start blog here -->
<div class="white_box blue_top">
  <p class="date">July 25, 2024</p>
  <h2>CBECS releases exploratory survey results about changes to office buildings following the COVID-19 pandemic</h2>
  <p>We conducted an exploratory, web-only survey to learn about changes to commercial buildings brought about by the COVID-19 pandemic. The results will inform questionnaire development for the next CBECS. Although the survey results do not represent all commercial buildings or all offices, we found patterns in the data related to offices. A new report,  <a
      href="/consumption/commercial/reports/2024/covid/"><em>Energy-Related Changes in Office Buildings Following the COVID-19 Pandemic</em></a>, describes those changes.</p>
      <p>The number of people decreased in many of the responding office buildings, especially in large office buildings and office buildings with multiple businesses or organizations. We also observed changes in commercial building equipment that may affect energy consumption patterns.</p>
</div>

<div class="white_box blue_top">
  <p class="date">December 18, 2023</p>
  <h2 class="toggle">2018 CBECS all-electric building estimates are now available</h2>
   <div class="more">
  <p>We have released a new set of data tables for commercial buildings using only electricity for certain end uses.
    These
    estimates may serve as a baseline for electrification policies and to understand the market for all-electric
    building
    technologies and equipment. More information on the new tables is available in a recent <a
      href="/todayinenergy/detail.php?id=60983"><em>Today in Energy</em></a> article. You can access the new tables from
    the <a href="/consumption/commercial/faq.php#q14"><em>FAQs for CBECS</em></a>.</p>
    </div>
</div>

<div class="white_box blue_top">
  <p class="date">July 27, 2023</p>
  <h2 class="toggle">2018 CBECS building type reports released</h2>
  <div class="more">
    <p>CBECS covers a wide variety of <a
        href="https://www.eia.gov/consumption/commercial/building-type-definitions.php">building types</a>—office
      buildings, schools, shopping malls, hospitals, churches, and fire stations, to name just a few—and each building
      type has unique characteristics and patterns of energy use. This new <a
        href="https://www.eia.gov/consumption/commercial/pba/">series of 2018 CBECS reports</a> provides graphs and data
      highlights for each of the 14 building types. In each report, we show how much the building type contributes to
      the
      building stock, floorspace, energy consumption, and expenditures, and we also unpack the building type
      subcategories. We provide energy consumption data by energy source, building type subcategories, and end uses.
      Each
      report concludes with a section on heating equipment, cooling equipment, and any other types of equipment that are
      specific to the building type.</p>
  </div>
</div>

<div class="white_box blue_top">
  <p class="date">April 27, 2023</p>
  <h2 class="toggle">2018 CBECS webinar recording now available</h2>
  <div class="more">
    <p>On April 19, 2023, we hosted a webinar to share 2018 CBECS results and survey methodology. The <a
        href="/consumption/commercial/pdf/2018 CBECS webinar.pdf" class="ico_pdf">presentation slides</a> describe the
      U.S. commercial buildings stock and energy consumption in 2018, show how we collected the data, and offer tips for
      using information from CBECS. A <a href="https://www.youtube.com/watch?v=U8Xrmvl0W9g">recording</a> of the webinar
      is also available on our YouTube channel.</p>
  </div>
</div>

<div class="white_box blue_top">
  <p class="date">April 12, 2023</p>
  <h2 class="toggle">Full set of 2018 CBECS methodology reports is now available</h2>
  <div class="more">
    <p>We just released a <a href="/consumption/commercial/data/2018/index.php?view=methodology">set of new reports</a>
      about how we gathered information for the 2018 CBECS from start to finish. The reports provide details about the
      CBECS process, including constructing a frame, selecting a sample, conducting the <em>Buildings Survey</em> and
      the
      <em>Energy Supplier Survey</em>, processing the data, and modeling energy end-use consumption.
    </p>
    <p>Information from these reports will be part of a CBECS webinar being held on Wednesday, April 19 from 2:00 p.m.
      to
      3:00 p.m. eastern time, which will also include highlights from our 2018 CBECS data reports, tips and tricks on
      using the CBECS data, and a live Q&amp;A session. The webinar is open to the public, but <a
        href="https://doe.webex.com/weblink/register/r312729e36257f783f99899b9a02db033">registration</a> is required.
      After registering, you will receive a confirmation email with instructions on how to join the webinar.</p>
  </div>
</div>


<div class="white_box blue_top">
  <p class="date">December 21, 2022</p>
  <h2 class="toggle">2018 CBECS final consumption and expenditures results and microdata released</h2>
  <div class="more">
    <p>The final 2018 CBECS data are now available. Today’s data release includes more <a
        href="/consumption/commercial/data/2018/index.php?view=consumption">tables</a> on total major fuel, electricity,
      and natural gas consumption and expenditures, and it adds data tables for fuel oil, district heat, and end-use
      data
      estimates. We also expanded the consumption and expenditures <a
        href="/consumption/commercial/data/2018/pdf/CBECS 2018 CE Release 2 Flipbook.pdf">flipbook</a> with new
      highlights
      from the data.</p>
    <p>The <a href="/consumption/commercial/data/2018/index.php?view=microdata">public use microdata file</a> now
      contains
      final data across the building characteristics, consumption, expenditures, and end-use variables, so data users
      can
      create custom tables.</p>
  </div>
</div>

<div class="white_box blue_top">
  <p class="date">September 28, 2022</p>
  <h2 class="toggle">2018 CBECS preliminary consumption and expenditures results released</h2>
  <div class="more">
    <p>The 2018 CBECS preliminary consumption and expenditures data are now available. This preliminary data release
      includes <a href="/consumption/commercial/data/2018/index.php?view=consumption">tables</a> on total major fuel,
      electricity, and natural gas consumption and expenditures, providing totals and energy intensities for the United
      States and for census regions in detailed categories. We have also prepared a <a
        href="/consumption/commercial/data/2018/pdf/CBECS 2018 C&E Flipbook.pdf">flipbook</a> that shows highlights from
      the preliminary data. </p>
    <p>We will release final 2018 CBECS data in December 2022. This data release will add end-use data estimates (for
      example, Tables E1–E11 from the <a href="/consumption/commercial/data/2012/index.php?view=consumption">2012
        CBECS</a>) and data tables for fuel oil and district heat. We will also release the remaining consumption data
      tables for total energy, electricity, and natural gas. We will add the energy consumption and expenditures
      variables
      to the <a href="/consumption/commercial/data/2018/index.php?view=microdata">public use microdata file</a>; the
      microdata file is provided so data users can create their own custom tables.</p>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">MARCH 10, 2022</p>
  <h2 class="toggle">Update: We will release preliminary consumption and expenditures data in August</h2>
  <div class="more">
    <p>We are currently processing energy consumption data and modeling end uses, and we expect to release preliminary
      data in August 2022. We strive to provide accurate release dates and to continually refine our project roadmap
      because we understand how release dates help you plan when and how you use CBECS data. </p>
    <p>The August 2022 data release will include detailed tables of total major fuel, electricity, and natural gas
      consumption. The tables will present consumption and expenditures totals and intensities for the United States and
      for census regions in detailed row categories (for example, Tables C1-C5, C13-C15, and C23-25 from the <a
        href="/consumption/commercial/data/2012/index.php?view=consumption">2012 CBECS</a>). We are also preparing a
      graphical report highlighting the data in these tables.</p>
    <p>We will release final 2018 CBECS data in November 2022. This data release will add end-use data estimates (for
      example, Tables E1-E11 from the <a href="/consumption/commercial/data/2012/index.php?view=consumption">2012
        CBECS</a>). We will also release the remaining detailed consumption data tables and append the <a
        href="/consumption/commercial/data/2018/index.php?view=microdata">public use microdata file</a> with variables
      for energy consumption and expenditures. We publish this file so that data users can create custom tables.</p>

    <h3>Projected schedule of 2018 CBECS data releases</h3>
    <table class="simpletable">
      <?php /* <tr>
          <td width="526">Public use microdata on building characteristics</td>
          <td width="160">November 2021</td>
        </tr> */ ?>
      <tr>
        <td>Consumption and expenditures (C&E) preliminary estimates</td>
        <td>August 2022</td>
      </tr>
      <tr>
        <td>C&E detailed tables and microdata</td>
        <td>November 2022</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">NOVEMBER 30, 2021</span>
  <h2 class="toggle">2018 CBECS building characteristics public use files now available</h2>
  <div class="more">
    <p>The <a href="/consumption/commercial/data/2018/index.php?view=microdata">2018 CBECS building
        characteristics microdata file</a> is now available for public use. We publish this file so that data users can
      create custom tables. We provide CSV (comma delimited) files and SAS data files along with data file
      documentation. The data represent commercial buildings from the 50 states and the District of Columbia. Each
      record corresponds to a single response from an in-scope building in the sample. The sample represents an
      estimated 5.9 million buildings in the United States.</p>
    <p>Next, we will publish preliminary consumption and expenditures data. Through the Energy Supplier Survey (ESS), we
      collected data from energy providers of buildings that responded to the CBECS buildings survey. We combine and
      process the ESS energy usage data with energy usage data from the building respondents. We then provide estimates
      of energy consumption and expenditures for electricity, natural gas, fuel oil, and district heat. We will publish
      preliminary consumption and expenditures data in spring 2022. You can find further descriptions of the two phases
      of CBECS data collection on the <a href="/consumption/commercial/about.php">About the CBECS</a> webpage.</p>
    <p>In the last stage of the consumption and expenditures data release, we will publish detailed tables and
      microdata. Detailed tables include consumption and expenditures data by energy source in total, per building, and
      per square foot by categories such as building floorspace, principal building activity, year constructed, and
      census division. We also provide consumption by end use, such as heating, air conditioning, ventilation, and
      lighting. We will publish consumption and expenditures detailed tables and microdata in summer 2022.</p>

    <h3>Projected schedule of 2018 CBECS data releases</h3>
    <table class="simpletable">
      <?php /* <tr>
          <td width="526">Public use microdata on building characteristics</td>
          <td width="160">November 2021</td>
        </tr> */ ?>
      <tr>
        <td>Consumption and expenditures (C&E) preliminary estimates</td>
        <td>Spring 2022</td>
      </tr>
      <tr>
        <td>C&E detailed tables and microdata</td>
        <td>Summer 2022</td>
    </table>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">September 21, 2021</span>
  <h2 class="toggle">2018 CBECS building characteristics results released</h2>
  <div class="more">
    <p>The 2018 CBECS building characteristics estimates are now available. This data release includes number of
      buildings and floorspace by characteristics such as geographic region, building activity, size and age, employment
      and occupancy, energy sources used, and energy-related equipment. Data are available in detailed <a
        href="/consumption/commercial/data/2018/">tables</a> and a <a
        href="/consumption/commercial/data/2018/pdf/CBECS_2018_Building_Characteristics_Flipbook.pdf">flipbook</a>.</p>

    <p>In November, we will publish the raw data files for building characteristics. We will provide CSV (comma
      delimited) files and SAS data files to the public along with data file documentation.</p>

    <p>Next, we will publish preliminary consumption and expenditures data. Through the <em>Energy Supplier Survey</em>
      (ESS), we collected data from energy providers of buildings that responded to the CBECS buildings survey. We
      combine and process the ESS energy usage data with energy usage data from the building respondents. We then
      provide estimates of energy consumption and expenditures for electricity, natural gas, fuel oil, and district
      heat. We plan to publish preliminary consumption and expenditures data in spring 2022. You can find further
      descriptions of the two phases of CBECS data collection on the <a href="/consumption/commercial/about.php">About
        the CBECS</a> webpage.</p>

    <p>In the last stage of the consumption and expenditures data release, we will publish detailed tables and
      microdata. Detailed tables include consumption and expenditures data by energy source in total, per building, and
      per square foot by categories such as building floorspace, principal building activity, year constructed, and
      census division. We also provide consumption by end use, such as heating, air conditioning, ventilation, and
      lighting. We will publish consumption and expenditures detailed tables and microdata in summer 2022.</p>

    <h3>Projected schedule of 2018 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Public use microdata on building characteristics</td>
        <td width="160">November 2021</td>
      </tr>
      <tr>
        <td>Consumption and expenditures (C&E) preliminary estimates</td>
        <td>Spring 2022</td>
      </tr>
      <tr>
        <td>CC&E detailed tables and microdata</td>
        <td>Summer 2022</td>
        </td>
      </tr>
    </table>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">July 14, 2021</span>
  <h2 class="toggle">Update to data release schedule: detailed information on building characteristics will be released
    before the microdata</h2>
  <div class="more">
    <p>To ensure you receive the highest possible quality in public use microdata and support in its use, we have
      rescheduled the release of this file along with supporting documentation to November 2021.</p>

    <p>The release of the detailed tables is still on track for publication in late summer 2021. These tables contain
      information on topics such as number of workers, ownership and occupancy, structural characteristics, energy
      sources and uses, heating and cooling equipment, refrigeration and lighting types, and much more.</p>

    <p>In addition, we still plan to release the preliminary consumption and expenditures data in spring 2022.</p>

    <p>For more information about the two phases of CBECS data collection, visit <a
        href="/consumption/commercial/about.php">About the CBECS</a>.</p>

    <h3>Projected schedule of 2018 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Detailed tables on building characteristics</td>
        <td width="160">August/September 2021</td>
      </tr>
      <tr>
        <td>Public use microdata on building characteristics</td>
        <td>November 2021</td>
      </tr>
      <tr>
        <td>Consumption and expenditures (C&amp;E) preliminary estimates</td>
        <td>Spring 2022</td>
      </tr>
      <tr>
        <td>C&amp;E detailed tables and microdata</td>
        <td>Summer 2022</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">May 11, 2021</span>
  <h2 class="toggle">CBECS releases data center research findings; detailed building characteristics coming soon</h2>
  <div class="more">
    <p>As part of the 2018 CBECS data collection, we conducted a pilot study of 50 data center buildings to assess the
      feasibility of publishing data centers as a separate building type. A new report, <em><a
          href="/consumption/commercial/reports/2018/pilot/">2018 CBECS Data Center
          Pilot Results</a></em>, discusses this study’s approach and key findings. We concluded that we would need both
      a high-quality frame and industry cooperation to collect statistically valid building characteristics and energy
      consumption estimates for data centers.</p>

    <p>We continue to process the data we collected during the 2018 CBECS survey cycle, and we will release detailed
      2018 CBECS building characteristics data later this summer. We plan to release the preliminary consumption and
      expenditures data in Spring 2022. For further descriptions of the two phases of CBECS data collection, visit <a
        href="https://www.eia.gov/consumption/commercial/about.php">About the CBECS</a>.</p>

    <h3>Projected schedule of 2018 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Detailed tables and public use microdata on building characteristics </td>
        <td width="160">August 2021</td>
      </tr>
      <tr>
        <td>Consumption and expenditures (C&amp;E) preliminary estimates</td>
        <td>Spring 2022</td>
      </tr>
      <tr>
        <td>C&amp;E detailed tables and microdata</td>
        <td>Summer 2022</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">November 18, 2020</span>
  <h2 class="toggle">2018 CBECS preliminary results released</h2>
  <div class="more">
    <p>The 2018 CBECS preliminary building characteristics are now available. This preliminary data release includes
      building counts, square footage, and age of buildings by building size, building activity, year of construction,
      and census region and division. Data are available in a <a
        href="/consumption/commercial/xls/2018_preliminary_estimates.xlsx" class="ico_xls">table</a> and a <a
        href="/consumption/commercial/pdf/CBECS 2018 Preliminary Results Flipbook.pdf" class="ico_pdf">flipbook</a>.</p>
    <p>The next release (in spring or summer of 2021) will include more detailed building characteristics, which will
      have similar content as the <a href="/consumption/commercial/data/2012/index.php?view=characteristics">2012 CBECS
        Detailed Tables</a>. In the last stage of the building characteristics data release, EIA will publish the raw
      data files.</p>

    <p>The 2018 CBECS recently completed its final phase of data collection: the <em>Energy Supplier Survey</em> (ESS).
      EIA collected data from energy providers of buildings that responded to the CBECS buildings survey. Next, EIA will
      combine and process the ESS energy usage data with energy usage data from the building respondents. Energy
      consumption and expenditures data should be available beginning in spring 2022. See <a
        href="/consumption/commercial/about.php">About the CBECS</a> for further descriptions of the two phases of CBECS
      data collection.</p>
    <h3>Projected schedule of 2018 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Detailed tables and public use microdata on building characteristics </td>
        <td width="160">Spring or summer 2021</td>
      </tr>
      <tr>
        <td>Consumption and expenditures (C&amp;E) preliminary estimates</td>
        <td>Spring 2022</td>
      </tr>
      <tr>
        <td>C&amp;E detailed tables and microdata</td>
        <td>Spring or summer 2022</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">September 10, 2020</span>
  <h2 class="toggle">2018 CBECS data releases start soon</h2>
  <div class="more">
    <p>The first stage of 2018 CBECS data processing is complete, and EIA plans to release preliminary building
      characteristics estimates in November. This preliminary data release will include building counts and total square
      footage by categories such as building activity, census region, building size, and year of construction. The next
      data release will include more detailed building characteristics in the form of tables and public use microdata
      files.</p>
    <p>CBECS data collection is currently in its second phase, the Energy Supplier Survey (ESS), which wraps up this
      fall. Since April, EIA has been collecting data from energy providers of buildings that responded to the CBECS
      buildings survey. After the ESS is finished, the ESS energy usage data will be combined and processed along with
      energy usage data from the building respondents. Energy consumption and expenditures data should be available
      beginning in spring 2022. See <a href="/consumption/commercial/about.php">About the CBECS</a> for further
      descriptions of the two phases of CBECS data collection.</p>
    <h3>Projected schedule of 2018 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Building characteristics (BC) preliminary estimates</td>
        <td width="160">November 2020</td>
      </tr>
      <tr>
        <td>BC detailed tables and public use microdata</td>
        <td>Spring/Summer 2021</td>
      </tr>
      <tr>
        <td>Consumption and expenditures (C&amp;E) preliminary estimates</td>
        <td>Spring 2022</td>
      </tr>
      <tr>
        <td>C&amp;E detailed tables and microdata</td>
        <td>Spring/Summer 2022</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">January 22, 2020</span>
  <h2 class="toggle">2018 CBECS buildings survey data collection completed</h2>
  <div class="more">
    <p>The field data collection phase of the 2018 CBECS has just ended. The field period began in mid-April 2019,
      employing about 180 interviewers across the United States. As interviewers left over the course of the project, an
      additional 65 interviewers were hired and trained.</p>
    <p>The starting sample size for the 2018 CBECS was about 16,000 buildings. We estimated that about 8,000 of those
      buildings would be eligible and respond to the survey. To be eligible for the CBECS, a building must be 1,000
      square feet or larger and at least half the floorspace must be for commercial use (i.e., not residential,
      manufacturing/industrial, or agricultural).</p>
    <p>Participation rates in federal surveys have been declining in recent years, CBECS included. After observing that
      the 2018 CBECS presented the most challenging field issues in CBECS history, we estimate that the resulting sample
      size will be similar to the 2012 CBECS, which was 6,720 buildings.</p>
    <p>We aim to publish the first characteristics results this summer, after data review and processing at EIA. We’ll
      be following up with the energy suppliers for the responding buildings starting this March. The supplier data will
      provide energy usage and cost data for these buildings.</p>

  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">June 20, 2019</span>
  <h2 class="toggle">Learn how buildings were selected for the 2018 CBECS</h2>
  <div class="more">
    <p>The 2018 CBECS is currently being fielded by interviewers across the United States. We sampled about 16,000
      buildings for our starting sample. Want to learn how those buildings were selected from the stock of more than 5.6
      million commercial buildings? See <a href="/consumption/commercial/reports/2018/methodology/sampling.php">
        How Were Buildings Selected for the 2018 CBECS?</a></p>
    <p>New for the 2018 CBECS was the introduction of virtual listing, which is the use of satellite imagery and GIS
      tools to build the sampling frame. To read more about this innovation, see <a
        href="/consumption/commercial/reports/2018/methodology/vls.php">
        Virtual Listing in the 2018 CBECS</a>.
    </p>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">April 22, 2019</span>
  <h2 class="toggle">Data collection begins for the 2018 CBECS</h2>
  <div class="more">
    <p>Training for the field interviewers for the 2018 CBECS was held April 2-6 in Atlanta, GA.</p>
    <p><img src="./includes/training.png" style="width: 250px;" alt="training sign photo"></p>
    <p>Data collection began April 8, 2019 and will continue for about 8 months. Preliminary results will be available
      to the public in spring 2020.</p>

    <p>About 180 interviewers participated in a five-day training on CBECS. They were thoroughly instructed on all the
      steps necessary to find the sampled building, identify the best respondent, and complete the CBECS interview. </p>

    <p>For the 2018 CBECS, respondents now have the option to self-complete the survey via the web!</p>

    <p>For quality control purposes, an interviewer will still make an initial visit to each building. During the visit,
      interviewers will first validate that the building interviewed is the same one that was sampled. If not, the
      results will not be representative of the U.S. building stock. Second, interviewers will orient respondents to the
      purpose of CBECS and offer information about getting started via the web. </p>

    <p>In every case, interviewers will still be available on demand to answer any questions or to complete the
      interview in person, if desired.</p>

    <p><b>Was your building contacted to complete the CBECS?</b></br>
      Go to <a href="http://www.CBECS2018.org">www.CBECS2018.org</a> for more information and to complete the survey.
      You will need a PIN.</p>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">October 31, 2018</span>
  <h2 class="toggle">The 2018 CBECS questionnaire has been finalized</h2>
  <div class="more">
    <p>Over the past year, EIA has held CBECS outreach events via webinar, engaged in discussions with stakeholders,
      published a Federal Register Notice, and solicited input from building energy experts. After gathering all of this
      input, the 2018 CBECS questionnaire has been finalized and will soon be under review by the Office of Management
      and Budget (OMB). Here is a <a href="pdf/questionnaire_cbecs.pdf">five-page summary of the questions</a>—the
      document provides a comparison with the 2012 CBECS, showing which questions have been kept, removed, and added. In
      a future status update here, we will provide a document with the complete set of questions.</p>

    <p>Data collection will begin in April 2019. For the first time ever, respondents will have the option to complete
      the CBECS on their own via a website. EIA will still offer to conduct the CBECS in person with a trained
      interviewer for those who need or prefer that option. We expect to begin publishing data in mid-2020.</p>
  </div>
</div>
&nbsp;

<div class="white_box blue_top">
  <p class="date">May 30, 2018</span>
  <h2 class="toggle">A draft 2018 CBECS questionnaire is available for review</h2>
  <div class="more">
    <p>EIA would like to thank those who participated in the stakeholder outreach webinars held in early March. We have
      used your feedback to modify the content of the 2018 CBECS.</p>
    <p>A short amount of time remains for comments on potential improvements to the CBECS questionnaire. With each new
      survey cycle, we make changes to keep the survey relevant, and we welcome your input. </p>
    <p>You can submit feedback to EIA in these ways:</p>

    <ul>
      <li>Contacting the CBECS Survey Manager, <a href="mailto:joelle.michaels@eia.gov">Joelle Michaels</a>
      </li>
      <li>Responding to the <a href="https://www.eia.gov/survey/#eia-871">Federal Register Notice (FRN)</a>
      </li>
    </ul>

    <p>As you review the questionnaire (available with the FRN at the link above), use this <a
        href="/consumption/commercial/pdf/2018CBECSQuestionnaireOutline.pdf">overview of the 2018 CBECS and outline of
        the questionnaire</a>, which highlights the changes made to date.</p>
  </div>
</div>
&nbsp;


<div class="white_box blue_top">
  <p class="date">November 2, 2017</span>
  <h2 class="toggle">The next CBECS will collect data for calendar year 2018</h2>
  <div class="more">
    <p>EIA is planning the next Commercial Buildings Energy Consumption Survey (CBECS). The data collection period will
      begin in April 2019, gathering information for reference year 2018. </p>

    <p>Two notable innovations to the study are in the works. One is the introduction of satellite imagery and GIS tools
      to build the sampling frame. This <em>virtual listing</em> should save time and resources compared to <a
        href="/consumption/commercial/reports/2012/methodology/sampling.php">traditional on-the-ground field listing
        methods</a>. The other innovation is that the 2018 CBECS will offer a web option to building respondents, in
      response to feedback during the 2012 CBECS. The web option will allow respondents the flexibility to complete and
      submit their CBECS data when it is convenient for them and will provide automated methods to attach supporting
      documents.</p>

    <p>In the coming months, EIA will be soliciting input from stakeholders on planned survey content. If you wish to
      participate, please contact <a href="mailto:joelle.michaels@eia.gov">Joelle Michaels</a>, CBECS Survey Manager,
      and indicate your area of interest. </p>

    <p>Regular project status updates will be provided throughout the CBECS 2018 survey cycle here.
    </p>
  </div>
</div>
&nbsp;
<div class="white_box blue_top">
  <p class="date">May 17, 2017</span>
  <h2 class="toggle">CBECS lighting report just published</h2>
  <div class="more">
    <p>A new CBECS report, <a href="/consumption/commercial/reports/2012/lighting/">Trends in Lighting in Commercial
        Buildings</a>, provides detailed information on lighting from the 2012 CBECS and reviews trends in commercial
      lighting going back to the 1995 CBECS. It compares the amount of commercial buildings floorspace lit by standard
      fluorescent, compact fluorescent, incandescent, high-intensity discharge, and halogen lighting across different
      building activities from 2003 to 2012. The report also provides information on lighting use by building size and
      on the use of lighting controls and control strategies.</a> </p>
  </div>
</div>
&nbsp;
<div class="white_box blue_top">

  <p class="date">February 9, 2017</span>
  <h2 class="toggle">Water consumption data for large buildings from the 2012 CBECS now available</h2>
  <div class="more">
    <p>Estimates of water consumption in large (greater than 200,000 square feet) commercial buildings from the 2012
      CBECS are now available in this report: <a href="/consumption/commercial/reports/2012/water/">Water Consumption in
        Large Buildings Summary.</a> Included in the report are annual water consumption estimates <a
        href="/consumption/commercial/reports/2012/water/xls/water consumption_w1.xlsx">(Table W1)</a> and daily
      estimates <a href="/consumption/commercial/reports/2012/water/xls/water consumption per day_wd1.xlsx">(Table
        WD1).</a> Additionally, a public use microdata file is available for users to perform custom analysis. For
      information on how the data were collected, see <a
        href="/consumption/commercial/reports/2012/water/methodology.php">How was water usage information collected for
        commercial buildings?</a> </p>
  </div>
</div>
&nbsp;
<div class="white_box blue_top">
  <p class="date">December 20, 2016</span>
  <h2 class="toggle">Building activity subcategory tables from the 2012 CBECS now available</h2>
  <div class="more">
    <p>National-level estimates for 53 building activity subcategories are now available in five new tables. The CBECS
      Detailed Tables provide 16 categories for principal building activity, but the CBECS questionnaire actually
      collects around 100 different building activities. Not all of the subcategories have large enough sample counts to
      provide statistically significant estimates, but there are 53 subcategories that were already provided in the
      public use microdata files and are now pretabulated. For characteristics such as building counts, building size,
      operating hours, and age, see Tables <a href="/consumption/commercial/data/2012/bc/cfm/pba1.cfm">PBA1</a> and <a
        href="/consumption/commercial/data/2012/bc/cfm/pba2.cfm">PBA2</a>, which are found in the <em>building activity
      </em>section of the <a href="/consumption/commercial/data/2012/index.php?view=characteristics">building
        characteristics tables</a>. For energy consumption estimates, see tables <a
        href="/consumption/commercial/data/2012/c&e/cfm/pba3.cfm">PBA3</a>, <a
        href="/consumption/commercial/data/2012/c&e/cfm/pba4.cfm">PBA4</a>, and<a
        href="/consumption/commercial/data/2012/c&e/cfm/pba5.cfm"> PBA5</a>, found in the major fuels, electricity, and
      natural gas sections, respectively, of the <a
        href="/consumption/commercial/data/2012/index.php?view=consumption">consumption and expenditures tables</a>. For
      further information on the types of buildings included in each activity subcategory, see <a
        href="/consumption/commercial/data/2012/bc/pdf/pbaplus examples and definitions.pdf">2012 CBECS Building
        Activity Subcategory Examples and Definitions <a
          href="/consumption/commercial/data/2012/bc/pdf/pbaplus examples and definitions.pdf" class="ico_pdf"></a>.</p>

    <p>Additionally, minor revisions have been made to <a href="/consumption/commercial/data/2012/">Detailed Tables</a>
      B1, B2, and C4. In B1, the calculation of the <em>mean square feet per worker</em> column was modified to exclude
      buildings with zero workers; in Table B2, the calculation of the median operating hours per week column was
      modified to include buildings that were never open; and in Table C4, the calculation of the building-level
      intensity percentiles were modified to include buildings that do not use any energy.</p>
  </div>
</div>
&nbsp;
<div class="white_box blue_top">
  <p class="date">May 17, 2016</span>
  <h2 class="toggle">2012 CBECS consumption and expenditures detailed tables and public use microdata released </h2>
  <div class="more">
    <p>The release of the CBECS consumption and expenditures data is complete. The <a
        href="/consumption/commercial/data/2012/index.cfm?view=consumption">2012 CBECS consumption and expenditures
        detailed tables</a> are comprised of tables C1-C38, which cover overall electricity, natural gas, fuel oil and
      district heat consumption, and tables E1-E11, which disaggregate the same energy sources by end use (heating,
      cooling, lighting, etc.). All of the detailed tables contain extensive row categories of building characteristics.
    <p>The <a href="/consumption/commercial/data/2012/index.cfm?view=microdata" title="2012 CBECS microdata files">2012
        CBECS microdata files</a>&nbsp;now contain additional variables for energy consumption and expenditures, in
      total, by energy source, and by end use. These files contain untabulated records for 6,720 buildings so that data
      users can create custom tables that are not available through the pretabulated detailed tables. They represent
      commercial buildings from the 50 States and the District of Columbia. Each record corresponds to a single
      responding, in-scope sampled building. The sample represents an estimated 5.6 million total buildings in the
      United States. </p>
    <p>Want to learn more about where the CBECS consumption estimates come from? See&nbsp;<a
        href="/consumption/commercial/reports/2012/methodology/usage.cfm">How Was Energy Usage Information Collected in
        the 2012 CBECS?</a></p>
  </div>
</div>
&nbsp;
<div class="white_box blue_top">
  <p class="date">March 18, 2016</span>
  <h2 class="toggle">First 2012 CBECS energy usage estimates now available</h2>
  <div class="more">
    <p><a href="/consumption/commercial/reports/2012/energyusage/index.cfm">The 2012 CBECS summary energy consumption
        estimates</a> have been released. The tables present electricity, natural gas, fuel oil and district heat
      consumption in total, per building, per square foot and by end use. Each table has row categories for building
      floorspace, principal building activity, year constructed, and Census region and division. Within the next two
      months, EIA will be releasing additional tables with many more row categories and adding consumption and
      expenditures variables to the <a href="/consumption/commercial/data/2012/index.cfm?view=microdata">public use
        microdata files</a>. Want to learn more about where the CBECS consumption estimates come from? See <a
        href="/consumption/commercial/reports/2012/methodology/usage.cfm">How Was Energy Usage Information Collected in
        the 2012 CBECS?
        </table>
      </a>
  </div>
</div>
&nbsp;
<div class="white_box blue_top">
  <p class="date">December 10, 2015</span>
  <h2 class="toggle">2012 CBECS energy usage data coming soon</h2>
  <div class="more">
    <p>EIA continues to work on end use modeling to complete the processing of the consumption and expenditures data.
      The projected release dates have been adjusted to account for the work remaining. </p>
    <h3>Projected schedule of 2012 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Building characteristics (BC) preliminary estimates</td>
        <td width="160">Released June 2014</td>
      </tr>
      <tr>
        <td>BC detailed tables </td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B1-B14 (summary; geographic region; size and age; building activity)
        </td>
        <td>Released March 2015</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B15-B21 (employment and occupancy)</td>
        <td>Released April 2015</td>

      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tables B22-B46 (energy sources and uses; end-use equipment)</td>
        <td>Released April 2015</td>
      </tr>
      <tr>
        <td>BC public use microdata</td>
        <td>Released June 2015</td>
      </tr>
      <tr>
        <td>Consumption & expenditures (C&E) preliminary estimates</td>
        <td>February 2016</td>
      </tr>
      <tr>
        <td>C&E detailed tables</td>
        <td>March 2016</td>
      </tr>
      <tr>
        <td>C&E public use microdata</td>
        <td>April 2016</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;<div class="white_box blue_top">
  <p class="date">June 25, 2015</span>
  <h2 class="toggle">2012 CBECS building characteristics public use files now available</h2>
  <div class="more">
    <p>The <a href="/consumption/commercial/data/2012/index.cfm?view=microdata" title="2012 CBECS microdata files">2012
        CBECS microdata files</a> are now available for public use. These files contain untabulated records for
      individual buildings so that data users can create custom tables that are not available through the pretabulated
      Detailed Tables. They represent commercial buildings from the 50 States and the District of Columbia. Each record
      corresponds to a single responding, in-scope sampled building. The sample represents an estimated 5.6 million
      total buildings in the United States.</p>
    <p>There have been some improvements since the 2003 CBECS public use data release. The data file is no longer split
      up into groups, so one download will provide users with all the CBECS variables. Also, in addition to a CSV (comma
      delimited) file, the data are also available as a SAS data file. The files contain replicate weights so that data
      users can calculate standard errors. Detailed examples of how to perform these calculations can be found in an
      extensive User's Guide. And finally, the CBECS questionnaire has been annotated to be used with the public use
      files. </p>
    <p>EIA continues to work on processing the consumption and expenditures data. The projected release dates have been
      adjusted slightly to account for the work remaining. The Energy Supplier Survey (ESS) was conducted between March
      and October 2014, collecting data from energy providers of buildings in the CBECS for which energy usage data was
      not obtained from the building respondent. Now the ESS energy usage data is being combined and processed with the
      energy usage from the building respondents and end use estimates (the amount of energy used for heating, cooling,
      lighting, etc.) are being modeled. See <a href="http://www.eia.gov/consumption/commercial/about.cfm"
        title="About the CBECS">About the CBECS</a> for further description of the two phases of CBECS data collection.
    </p>
    <h3>Projected schedule of 2012 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Building characteristics (BC) preliminary estimates</td>
        <td width="160">Released June 2014</td>
      </tr>
      <tr>
        <td>BC detailed tables </td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B1-B14 (summary; geographic region; size and age; building activity)
        </td>
        <td>Released March 2015</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B15-B21 (employment and occupancy)</td>
        <td>Released April 2015</td>

      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tables B22-B46 (energy sources and uses; end-use equipment)</td>
        <td>Released April 2015</td>
      </tr>
      <tr>
        <td>BC public use microdata</td>
        <td>Released June 2015</td>
      </tr>
      <tr>
        <td>Consumption & expenditures (C&E) preliminary estimates</td>
        <td>November 2015</td>
      </tr>
      <tr>
        <td>C&E detailed tables</td>
        <td>December 2015</td>
      </tr>
      <tr>
        <td>C&E public use microdata</td>
        <td>February 2016</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">April 30, 2015</span>

  <h2 class="toggle">Complete set of 2012 CBECS building characteristics tables released</h2>
  <div class="more">
    <p>
      The remaining <a href="/consumption/commercial/data/2012/">building characteristics tables</a> (Tables B15 through
      B46) have just been released. These tables provide detailed information related to employment; building ownership
      and occupancy; energy sources used; and heating, cooling, water heating, lighting, and refrigeration equipment.
    </p>
    <p>There was a minor error detected in previously released totals for floorspace in the West North Central division
      within the <em>Leased to tenants</em> line in the <em>Ownership and occupancy</em> row category; that estimate
      changed from 1,357 million square feet to 1,364 million square feet, and the total U.S. floorspace for buildings
      leased to tenants changed from 26,093 million square feet to 26,100 million square feet. It should be noted that
      all the tables still contain preliminary data and many of the estimates are expected to change slightly when the
      consumption data are released near the end of this year.</p>
    <p>EIA continues to work on processing the consumption and expenditures data. The Energy Supplier Survey (ESS) was
      conducted between March and October 2014, collecting data from energy providers of buildings in the CBECS for
      which energy usage data was not obtained from the building respondent. Now the ESS energy usage data is being
      combined and processed with the energy usage from the building respondents. See <a
        href="/consumption/commercial/about.cfm">About the CBECS</a> for further description of the two phases of CBECS
      data collection. </p>
    <h3>Projected schedule of 2012 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Building characteristics (BC) preliminary estimates</td>
        <td width="160">Released June 2014</td>
      </tr>
      <tr>
        <td>BC detailed tables </td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B1-B14(summary; geographic region; size and age; building activity)
        </td>
        <td>Released March 2015</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B15-B21 (employment and occupancy)</td>
        <td>April 2015</td>

      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tables B22-B46 (energy sources and uses; end-use equipment)</td>
        <td>May 2015</td>
      </tr>
      <tr>
        <td>BC public use microdata</td>
        <td>May 2015</td>
      </tr>
      <tr>
        <td>Consumption & expenditures (C&E) preliminary estimates</td>
        <td>September 2015</td>
      </tr>
      <tr>
        <td>C&E detailed tables</td>
        <td>November 2015</td>
      </tr>
      <tr>
        <td>C&E public use microdata</td>
        <td>December 2015</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">March 4, 2015</span>
  <h2 class="toggle">First 2012 CBECS Detailed Tables released</h2>
  <div class="more">
    <p>
      The first fourteen building <a href="/consumption/commercial/data/2012/">characteristics Detailed Tables</a>, an
      <a href="/consumption/commercial/reports/2012/buildstock/">accompanying report</a>, and survey methodology
      information - <a href="/consumption/commercial/data/2012/conducted.cfm">How was the 2012 CBECS buildings survey
        conducted?</a> - have just been released. The remaining building characteristics data releases will include two
      more groups of Detailed Tables and the public use microdata files. The public use microdata files are
      building-level records provided for data users to perform individualized analyses. The data are inoculated so that
      it is not possible to identify any individual building on the file.
    </p>
    <p>EIA continues to work on processing the consumption and expenditures data. The Energy Supplier Survey (ESS) was
      conducted between March and October 2014, collecting data from energy providers of buildings in the CBECS for
      which energy usage data was not obtained from the building respondent. Now the ESS energy usage data is being
      combined and processed with the energy usage from the building respondents. See <a
        href="/consumption/commercial/about.cfm">About the CBECS</a> for further description of the two phases of CBECS
      data collection. </p>
    <h3>Projected schedule of 2012 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Building characteristics (BC) preliminary estimates</td>
        <td width="160">Released June 2014</td>
      </tr>
      <tr>
        <td>BC detailed tables </td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B1-B14(summary; geographic region; size and age; building activity)
        </td>
        <td>Released March 2015</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B15-B21 (employment and occupancy)</td>
        <td>April 2015</td>

      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tables B22-B46 (energy sources and uses; end-use equipment)</td>
        <td>May 2015</td>
      </tr>
      <tr>
        <td>BC public use microdata</td>
        <td>May 2015</td>
      </tr>
      <tr>
        <td>Consumption & expenditures (C&E) preliminary estimates</td>
        <td>September 2015</td>
      </tr>
      <tr>
        <td>C&E detailed tables</td>
        <td>November 2015</td>
      </tr>
      <tr>
        <td>C&E public use microdata</td>
        <td>December 2015</td>
      </tr>
    </table>
  </div>
</div>


&nbsp;<div class="white_box blue_top"><span class="date">October 23, 2014</span>
  <h2 class="toggle">2012 CBECS ESS data collection completed</h2>

  <div class="more">

    <p>
      EIA is concluding the second and final phase of CBECS data collection, the Energy Supplier Survey (ESS). Since
      March, EIA has been collecting data from energy providers of buildings in the CBECS for which energy usage data
      was not obtained from the building respondent. Now the ESS energy usage data will be combined and processed with
      the energy usage from the building respondents. See <a href="/consumption/commercial/about.cfm">About the
        CBECS</a> for further description of the two phases of CBECS data collection. </p>
    <p>The <a href="/consumption/commercial/reports/2012/preliminary/index.cfm">2012 CBECS preliminary building
        characteristics</a> were released in June. This preliminary data release includes building counts and total
      square footage by building activity, Census region and division, and building size category, and year of
      construction. </p>
    <p>The next release will be the Building Characteristics Detailed Tables; the tables will be similar to those
      published for the 2003 CBECS. We have evaluated the work remaining to ensure high data quality and adjusted the
      projected schedule of data releases as shown below. The Detailed Tables will be released in four groups; the table
      numbers shown below correspond to the <a href="/consumption/commercial/data/2003/index.cfm">2003 CBECS tables</a>.
      Please note that the table descriptions in the schedule below refer to the data presented as columns in the
      tables. Every table will have extensive CBECS data presented as rows, including building size, activity,
      occupancy, etc.&nbsp;</p>
    <h3>Projected schedule of 2012 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Building characteristics (BC) preliminary estimates</td>
        <td width="160">Released June 2014</td>
      </tr>
      <tr>
        <td>BC detailed tables </td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B1-B10 (summary; geographic region; size and age)</td>
        <td>January 2015</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B11-B14 (building activity)</td>
        <td>February 2015</td>

      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B15-B21 (employment and occupancy)</td>
        <td>March 2015</td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables B22-B46 (energy sources and uses; end-use equipment)</td>
        <td>April 2015</td>
      </tr>
      <tr>
        <td>BC public use microdata</td>
        <td>April 2015</td>
      </tr>
      <tr>
        <td>Consumption &amp; expenditures (C&amp;E) preliminary estimates</td>
        <td>Summer 2015</td>
      </tr>
      <tr>
        <td>C&amp;E detailed tables</td>
        <td>Fall 2015</td>
      </tr>
      <tr>
        <td>C&amp;E public use microdata</td>
        <td>Winter 2015</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">June 19, 2014</span>
  <h2 class="toggle">2012 CBECS preliminary data released</h2>
  <div class="more">
    <p>
      The <a href="/consumption/commercial/reports/2012/preliminary/index.cfm">2012 CBECS preliminary building
        characteristics</a> have been completed! This preliminary data release includes building counts and total square
      footage by building activity, Census region and division, and building size category, and year of construction.
    </p>
    <p>The next release will be the Building Characteristics Detailed Tables, which will be similar to those published
      for the 2003 CBECS. In the last stage of building characteristics data release, the raw data files will be made
      available for public use.</p>
    <p>CBECS data collection is currently in its second phase, the Energy Supplier Survey (ESS). EIA is collecting data
      from energy providers of buildings in the CBECS for which energy usage data was not obtained from the building
      respondent. The ESS will be completed this summer, at which point the ESS energy usage data will be combined and
      processed with the energy usage from the building respondents. Energy consumption and expenditures data will be
      available beginning in spring 2015. See <a href="/consumption/commercial/about.cfm">About the CBECS</a> for
      further description of the two phases of CBECS data collection. </p>

    <h3>Projected schedule of 2012 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="526">Building characteristics (BC) preliminary estimates</td>
        <td width="160">Released June 2014</td>
      </tr>
      <tr>
        <td>BC detailed tables </td>
        <td>Fall 2014</td>
      </tr>
      <tr>
        <td>BC public use microdata</td>
        <td>Winter 2014</td>
      </tr>
      <tr>
        <td>Consumption & expenditures (C&E) preliminary estimates</td>
        <td>Spring 2015</td>

      <tr>
        <td>C&E detailed tables</td>
        <td>Fall 2015</td>
      </tr>
      <tr>
        <td>C&amp;E public use microdata</td>
        <td>Winter 2015</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">March 26, 2014</span>
  <h2 class="toggle">2012 CBECS data will be published in stages</h2>
  <div class="more">
    <p>
      The first stage of CBECS data processing is almost complete and EIA expects to release preliminary building
      characteristics estimates by early June. This preliminary data release will include building counts and total
      square footage by categories such as building activity, Census region, and building size category. Next will be
      the release of Building Characteristics Detailed Tables, which will be similar <a
        href="/consumption/commercial/data/2003/">to those published for the 2003 CBECS.</a> In the last stage of
      building characteristics data release, the raw data files will be made available for public use.</p>
    <p>CBECS data collection is currently in its second phase, the Energy Supplier Survey (ESS). EIA is collecting data
      from energy providers of buildings in the CBECS for which energy usage data was not obtained from the building
      respondent. The ESS will be completed this summer, at which point the ESS energy usage data will be combined and
      processed with the energy usage from the building respondents. Energy consumption and expenditures data will be
      available beginning in spring 2015. See <a href="/consumption/commercial/about.cfm">About the CBECS </a>for
      further description of the two phases of CBECS data collection. </p>

    <h3>Projected schedule of 2012 CBECS data releases</h3>
    <table class="simpletable">
      <tr>
        <td width="518">Building characteristics (BC) preliminary estimates</td>
        <td width="108">June 2014</td>
      </tr>
      <tr>
        <td>BC detailed tables </td>
        <td>September 2014</td>
      </tr>
      <tr>
        <td>BC public use microdata</td>
        <td>November 2014</td>
      </tr>
      <tr>
        <td>Consumption & expenditures (C&E) preliminary estimates</td>
        <td>Spring 2015</td>
      </tr>
      <tr>
        <td>C&E detailed tables</td>
        <td>Fall 2015</td>
      </tr>
      <tr>
        <td>C&amp;E public use microdata</td>
        <td>Winter 2015</td>
      </tr>
    </table>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">November 20, 2013</span>
  <h2 class="toggle">CBECS field data collection completed</h2>
  <div class="more">
    <p>The active field data collection phase of the 2012 CBECS ended last week. In the next month, home office staff at
      Westat (the CBECS survey contractor) will continue to work on open cases via telephone interviews. With over 200
      interviewers deployed across the U.S. starting in mid-April 2013, the 2012 CBECS was the largest field collection
      in the 30-year history of CBECS.</p>
    <p>Westat has been transmitting cases to EIA every few weeks since May, and the data editing phase here at EIA is
      making good progress. We are on track to publish the first characteristics results in late April or early May. The
      consumption and expenditures data releases will follow in about a year. The Energy Suppliers Survey (ESS) data
      collection begins in early spring: those data will provide energy usage and cost data for about half the CBECS
      cases. </p>
  </div>
</div>

&nbsp;
<div class="white_box blue_top"><span class="date">August 7, 2013</span>
  <h2 class="toggle">CBECS data collection making steady progress</h2>
  <div class="more">
    <p>The CBECS interviewers have been in the field for 3 months now, and they have already collected data for about
      4,500 buildings all across the country.</p>
    <p>Back here at EIA, CBECS staff are reviewing the data files as we receive them. The information collected in these
      interviews has already passed through and cleared two levels of automated data checks. Now, we're checking all the
      open-ended responses and interviewer comments and running case-level edits that check for item consistency within
      questionnaires and help to verify that the energy usage data are accurate. </p>
    <p>We're also gearing up for the CBECS Energy Suppliers Survey (ESS). In this follow-up survey, we will request
      energy use and cost data directly from the energy suppliers of electricity, natural gas, fuel oil, or district
      energy. ESS data collection is on schedule to begin in early spring 2014. </p>
  </div>
</div>

&nbsp;
<div class="white_box blue_top"><span class="date">April 29, 2013</span>
  <h2 class="toggle">The 2012 CBECS is in the field!</h2>
  <div class="more">
    <p>Data collection for the 2012 CBECS began the week of April 15, 2013. About 250 interviewers are visiting
      buildings across the U.S. to collect data on their structure, operational characteristics, and energy use. In two
      recent four-day training sessions, the interviewers were thoroughly trained on all the steps necessary to complete
      an interview: determining if the building is in scope for the survey, making an appointment, gaining cooperation,
      using the computer to conduct the interview, and scanning utility bills. </p>
    <p>Who are these CBECS interviewers? They are professionals, but usually not energy experts. Many have worked on
      other large-scale surveys of various topics, while some are new to interviewing. Interviewers are an interesting,
      diverse group of people from all walks of life. Some of their previous or current other occupations include:
      accountants, firefighters, social workers, interior designers, caterers, military personnel, teachers, tax
      preparers, government workers, geological technicians, sales people, certified energy managers, dairy farmers,
      electrical contractors, DJs, architects, parents, and grandparents. The skills that they all have in common that
      make them effective interviewers are the ability to talk to respondents, an eye for detail, and a talent for
      organization.
    </p>
    <p>At least one interviewer is returning to the CBECS for the third time. After working on the 2003 and the 2007
      CBECS, this particular experienced interviewer was happy to be back: "This is my favorite project! I find that the
      majority of the respondents are cooperative. Many have gotten the Advance Package of materials and are happy to
      talk about their building."</p>

    <p>Data collection will continue for approximately the next 6 months.
    </p>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">March 6, 2013</span>
  <h2 class="toggle">Countdown to CBECS data collection</h2>
  <div class="more">
    <p><span><img src="/consumption/commercial/images/folders.jpg" width="200"
          alt="Folders for each building caseFolders for each building case"
          title="Folders for each building case" /><span class="caption">Folders with materials for each building case
          <br />assignment being put together.</span></span>The start of the 2012 CBECS field period is just over a
      month away, and there is a lot of activity occurring right now in preparation!</p>
    <p>Over 12,000 buildings across the U.S. have been selected to be interviewed (see <a
        href="/consumption/commercial/2012-cbecs-building-sampling.cfm">How Will Buildings Be Selected for the 2012
        CBECS?</a> for more information on sample selection). The CBECS contractor, Westat, is hiring about 300 field
      interviewers who will visit each of these buildings to determine eligibility for the CBECS. Then they will conduct
      interviews&mdash;either in-person or by telephone&mdash;using a survey instrument on a laptop computer. See the <a
        href="/survey/form/eia_871/2012/cbecs-buildings-871a.pdf">final version of the 2012 CBECS questionnaire</a>.</p>
    <p>The CBECS interviewers will be trained in-depth to ensure that high quality data are collected. They will begin
      their training with distance learning modules to acclimate them with the CBECS and energy concepts before they
      travel to the in-person training. At the beginning of April, they will attend a four-day in-person training
      session in Los Angeles where they will learn the ins-and-outs of the CBECS interviewing process and the
      questionnaire. They will get lots of practice with the survey instrument before they hit the streets as soon as
      they return home from training.</p>
    <p>Meanwhile, back at Westat's home office in Rockville, MD, staff are working hard to make sure the
      behind-the-scenes logistics are in place. Materials for each case assignment are carefully being put together,
      including maps and other forms that will allow the interviewer to find the sampled buildings. Each respondent will
      be provided a package of materials about the CBECS when they are first contacted. Among other items, this package
      contains worksheets to help the building respondents prepare for the interview and <a
        href="/survey/form/eia_871/2012/endorsement-insert.pdf">a list of organizations that have encouraged
        participation in the CBECS </a>.
    </p>
  </div>
</div>
&nbsp;

<div class="white_box blue_top"><span class="date">December 31, 2012</span>
  <h2 class="toggle">2012 CBECS area frame construction complete</h2>
  <div class="more">
    <p>The "area frame" for the 2012 CBECS is complete! Over a 3 month period, 90 field listers created lists of
      buildings in 307 area segments by walking or driving through every street in these segments and recording every
      commercial building eligible for CBECS. Of these segments, 257 are new to the 2012 CBECS and 50 were in the 2003
      CBECS and are now updated for changes since 2003. There are an additional 461 segments that were listed in 2003
      that will also be part of the area frame. See <a
        href="/consumption/commercial/2012-cbecs-building-sampling.cfm">How Will Buildings Be Selected for the 2012
        CBECS?</a> for more information on how the sample frame is constructed. EIA and Westat are preparing these lists
      for the statistical sampling of buildings that will be selected for the 2012 CBECS. The sampling phase is expected
      to be completed in January 2013, and data collection remains on schedule, with a start date expected in April
      2013. </p>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">October 1, 2012</span>
  <h2 class="toggle">2012 CBECS questionnaire completed</h2>
  <div class="more">
    <p>After reviewing 400+ suggestions from stakeholders, the proposed 2012 CBECS questionnaire is currently under
      review by the Office of Management and Budget (OMB). The survey is administered using a computerized survey
      instrument, but we've provided a <a
        href="../../survey/form/eia_871/2012/2012 CBECS Form 871A Building Questionnaire.pdf" class="ico_pdf">paper
        representation of the questionnaire</a> (240 pages) and a <a
        href="/consumption/commercial/data/2012/pdf/ChangesForThe2012CBECS.pdf" class="ico_pdf">summary of the major
        changes</a> (7 pages) here. Because the computer automates all the question skip patterns, the survey is not as
      long or complicated as it appears! </p>
  </div>
</div>
&nbsp;

<div class="white_box blue_top"><span class="date">September 17, 2012</span>
  <h2 class="toggle">2012 CBECS field lister training completed</h2>
  <div class="more">
    <p>A major milestone in the 2012 CBECS sample frame construction is complete! EIA and Westat, the CBECS survey
      contractor, trained the listers, which are the field staff that will create the area frame portion of the sample
      frame. See <a href="/consumption/commercial/2012-cbecs-building-sampling.cfm">How Will Buildings Be Selected for
        the 2012 CBECS?</a> for more information on how the sample frame is constructed. Two training sessions of three
      and a half days each were held in Bethesda, Maryland from September 6 through September 12, 2012. About 90 listers
      from across the U.S. were trained using a mix of classroom education and practice listings around the streets of
      Bethesda. They learned all about EIA, the CBECS, and how to canvass their assigned geographic areas to list all
      CBECS-eligible buildings and record the information that is needed to select the sample of buildings that will be
      interviewed.</p>
    <p>The field listers' hard work and attention to detail will ensure that the sample frame is accurate and complete.
      They are enthusiastic about working on CBECS and ready to begin their assignments. One field supervisor with many
      years of experience on various surveys said: "I can't think of a more important study to be working on right now."
    </p>
    <p>The listing is now underway and will be complete in November 2012. The sample, significantly larger than previous
      cycles, will be selected in January 2013 and the interviewing of the sampled buildings will begin in April 2013.
    </p>
  </div>
</div>
&nbsp;

<div class="white_box blue_top"><span class="date">August 26, 2012</span>
  <h2 class="toggle">EIA collects data on water usage in commercial buildings for the first time</h2>
  <div class="more">
    <p>The 2007 round of CBECS was the first time in the 30 year history of CBECS that commercial buildings were
      surveyed about water consumption and characteristics. These questions were experimental, and EIA found the
      collection of this data to be successful. See <a
        href="/consumption/commercial/reports/2007/hospital-water-data-collection.cfm">Water Data Collection in the 2007
        CBECS</a> for details. EIA plans to collect water consumption data again in the 2012 CBECS.</p>
  </div>
</div>
&nbsp;


<div class="white_box blue_top"><span class="date">August 17, 2012</span>
  <h2 class="toggle">EIA releases data on large hospitals from the 2007 CBECS</h2>
  <div class="more">
    <p>Though most of the data collected as part of the CBECS 2007 cycle could not be released, EIA has been able to
      produce data on energy characteristics found in large hospitals in 2007. The data include estimates of building
      characteristics, energy sources, end uses, energy management features, energy consumption, and water consumption
      for hospital buildings greater than 200,000 square feet. See <a
        href="/consumption/commercial/reports/2007/large-hospital.cfm">Energy Characteristics and Energy Consumed in
        Large Hospital Buildings</a> in the United States in 2007 for a discussion of the estimates, <a
        href="/consumption/commercial/reports/2007/large-hospital-list-of-tables.cfm">table list</a> for detailed
      tables, and <a href="/consumption/commercial/reports/2007/large-hospital-methodology.cfm">2007 CBECS Large
        Hospital Building Methodology Report</a> for a methodological report.</p>
  </div>
</div>
&nbsp;


<div class="white_box blue_top"><span class="date">July 12, 2012</span>
  <h2 class="toggle">Under construction: the CBECS sampling frame</h2>
  <div class="more">
    <p>EIA and the CBECS survey contractor (Westat) are working hard right now to create the CBECS sampling "frame,"
      which is the list from which buildings will be randomly selected to be interviewed. For the details of how the
      CBECS sampling frame is constructed, see: <a href="/consumption/commercial/2012-cbecs-building-sampling.cfm">How
        Will Buildings Be Selected for the 2012 CBECS?</a></p>
  </div>
</div>
&nbsp;

<div class="white_box blue_top"><span class="date">May 24, 2012</span>
  <h2 class="toggle">CBECS enters the final phase of questionnaire design</h2>
  <div class="more">
    <p>EIA thanks the U.S. Green Building Council for hosting an informative 2012 CBECS Stakeholder Meeting on May 15,
      2012. We had about 20 participants attending in-person and another 40 or 50 participants via webinar, representing
      a variety of industries &#8211; government, trade associations, real estate, energy consultants, advocacy groups,
      architects, engineers, laboratories, and equipment manufacturers. EIA presented our planned changes to the 2012
      CBECS questionnaire and took comments from the audience on each questionnaire section.</p>
    <p><a href="/consumption/commercial/ppt/2012stakeholde-mtg051512.pptx" class="ico_ppt"
        title="Download the PowerPoint file: 2012-05-15 - 2012 CBECS Stakeholder Meeting.pptx">PowerPoint slides from
        the meeting.</a></p>
    <p>The last steps before the questionnaire is finalized are to (1) write all the new questions according to best
      practices for survey design and then (2) program them into the CBECS survey instrument. The CBECS is administered
      by a trained interviewer using a laptop and a structured survey instrument. The questionnaire is programmed
      in-house by EIA using a survey processing language called <a href="http://www.blaise.com/"
        target="_blank">Blaise</a>.</p>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">April 20, 2012</span>
  <h2 class="toggle">Last call for 2012 CBECS stakeholder input</h2>
  <div class="more">
    <p>We are hard at work reviewing all the great feedback on the 2012 questionnaire that we've received to date. So
      far, we've heard from: the U.S. Green Building Council, ASHRAE, members of the Real Estate Roundtable (RER) such
      as Tishman Speyer, Simon Property Group, and Transwestern, the American Institute of Architects (AIA), EPA Energy
      Star, EPA Office of Water, National Renewable Energy Laboratory (NREL), Consortium for Energy Efficiency, Energy
      Performance Measurement Institute, San Diego State University, BuildingWise, Lutron Electronics, SRG Partnership,
      Performance Buildings Systems, Grundfos, National Trust for Historic Preservation, and Center for Environmental
      Innovation in Roofing. Thank you all for taking the time to review the questionnaire.</p>
    <p>Please join us on May 15 for an update on the revisions that we've made to the questionnaire so far and a
      discussion of any last potential updates:</p>
    <div align="center">
      <div class="weeklies" align="center"> <span>
          <h3><strong>Energy Information Administration (EIA) 2012 CBECS Stakeholder Meeting</strong> </h3>
          <p>Tuesday, May 15th, 1pm-4:30pm<br />
            U.S. Green Building Council<br />
            2101 L Street, NW Suite 500 Washington, D.C. 20037<br />
            Board Room</p>
          <p><strong>Please RSVP* to <a
                href="mailto:Joelle.Michaels@eia.gov?subject=CBECS Stakeholder Meeting RSVP">Joelle Michaels</a> by
              Thursday May 10th</strong><br />
            Agenda and slides will be distributed to all RSVPs by Friday, May 11th </p>
          <p>*For those who are not able to participate in person we will provide webcast and call-in information</p>
        </span> </div>
    </div>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">March 30, 2012</span>
  <h2 class="toggle">CBECS is back, and we want your input! </h2>
  <div class="more">
    <p>We have created this CBECS section to provide updates on the survey progress.</p>
    <p>After a budget delay in 2011, CBECS will now be conducted for reference year 2012. Data collection will begin in
      April 2013, with the first data releases expected in Spring 2014.Our main focus now is collaborating with our
      stakeholders to develop the CBECS questionnaire (referred to as the &quot;Final survey instrument&quot; in the
      graphic below). Each survey cycle we make changes to keep the survey relevant, and we welcome your input. You can
      submit feedback to EIA in these ways:</p>
    &nbsp;
    <ul>
      <li>Responding to our <a href="http://www.gpo.gov/fdsys/pkg/FR-2012-03-28/pdf/2012-7424.pdf" class="ico_pdf_right"
          target="_new" s="s">Federal Register Notice</a></li>
      <li>Contacting the CBECS Survey Manager, <a href="mailto:joelle.michaels@eia.gov">Joelle Michaels</a>.</li>
    </ul>
    <p>We will post updates on the progress of the 2012 CBECS according to the timeline below.</p>
    &nbsp; <img src="images/cbecs-timeline0312.png" />
    <?php /*div class="comments">
     <h3>Comments</h3>
     <p>3/22/12 Change this and change that. - Christian S.</p>
</div*/ ?>
  </div>
</div>
&nbsp;
<div class="white_box blue_top"><span class="date">January 11, 2012</span>
  <h2 class="toggle">CBECS funded for 2012 collection </h2>
  <div class="more">
    <p>Following the suspension of the 2011 Commercial Buildings Energy Consumption Survey (CBECS) given insurmountable
      funding constraints in FY 2011, EIA has resumed preparations to conduct the next Commercial Buildings Energy
      Consumption Survey (CBECS). EIA plans to field the survey in April 2013, collecting data for reference year 2012.
      EIA expects to publish the first results of the survey in the first half of FY 2014. EIA is now working with
      stakeholders to develop the survey instrument. EIA will provide regular project status reports to the public
      throughout the course of the project.</p>
    <p>EIA previously reported that the CBECS 2007 data do not meet EIA standards for quality, credible energy
      information. As a result, EIA will not publish complete data tables from CBECS 2007 or release a public use file.
      EIA's status reports for CBECS 2012 will report on risk mitigation strategies undertaken to assure the delivery of
      CBECS 2012 data.</p>
    <p>For further information, please contact <a href="mailto:joelle.michaels@eia.gov">Joelle Michaels</a>, CBECS
      Survey Manager, or by phone at 202-586-8952; or <a href="mailto:thomas.leckey@eia.gov">Tom Leckey</a>.</p>
  </div>
</div>
<?php /* /Faux-blog box */ ?>