<!--

<a class="eia ico api">API</a>


-->

<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="inlineAPI">&lt;a class="eia ico pdf"&gt;
	&lt;span&gt;PDF&lt;/span&gt;
&lt;/a&gt;</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#inlineAPI">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>