<h3>Inline</h3>
<div class="accordion-content horizontal-icon-container inline">

	<h4><span>&lt;/&gt;</span> Source</h4>
	<pre><code class="language-html" id="anchorPDF">&lt;a class="eia ico pdf"&gt;
	&lt;span&gt;PDF&lt;/span&gt;
&lt;/a&gt;</code></pre>

	<h4>Paragraph example:</h4>
	<p>Lorem ipsum dolor sit amet, consectetur <a>Lorem ipsum dolor sit amet <span class="eia ico pdf">PDF</span></a> elit. Donec lorem massa, semper nec eros a, lacinia porttitor nunc. Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien. Suspendisse sagittis risus eu sem suscipit sodales. Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus. Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis. Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem. Vestibulum ut odio id nulla commodo dignissim. Proin a pharetra tellus.</p>

	<h4>List example:</h4>
	<ul>
		<li>Lorem ipsum dolor sit amet, consectetur <a>orem ipsum dolor sit amet <span class="eia ico pdf">PDF</span></a> elit</li>
		<li><a>Lorem ipsum dolor sit amet, consectetur <span class="eia ico pdf">PDF</span></a></li>
	</ul>
	<!--
		<li>
			<a class="eia ico xls">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico csv">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico interactive">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico ppt">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico html">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico doc">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico image">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico json">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico efile">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico txt">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico pedro">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
		<li>
			<a class="eia ico api">PDF Lorem ipsum dolor sit amet consectetur adipiscing elit</a>
		</li>
	</ul>
-->

	<div class="icon-container">
		<a class="eia ico pdf">
			<span>PDF</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/pdf --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico xls">
			<span>XLS</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/xls --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico csv">
			<span>CSV</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/csv --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico interactive">
			<span>Interactive</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/interactive --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico ppt">
			<span>PPT</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/ppt --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico html">
			<span>HTML</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/html --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico doc">
			<span>DOC</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/doc --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico jspn">
			<span>JSON</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/json --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico image">
			<span>IMAGE</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/image --> -->
	</div>

	<div class="icon-container">
		<a class="eia ico efile">
			<span>eFile</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/efile --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico txt">
			<span>TXT</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/txt --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico pedro">
			<span>PEDRO</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/pedro --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico api">
			<span>API</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/api --> -->
	</div>
	<div class="icon-container">
		<a class="eia ico zip">
			<span>ZIP</span>
		</a>
		<!-- 		<?php include('./includes/icons/anchors/zip --> -->
	</div>
</div>
</div>