<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="inlinePPT">&lt;a class="eia ico ppt"&gt;
	&lt;span&gt;PPT&lt;/span&gt;
&lt;/a&gt;</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#inlinePPT">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>