<h2>Methodology</h2>
<br>
<p>Technical documentation will be released in May 2026.</p>

<!--<p>
<ul>
	<?php /* <li><a href="/consumption/residential/data/2020/index.php?view=characteristics">2020 RECS Housing Characteristics tables are now available.</a></li> */ ?>
	<li><a href="pdf/Comparing_2020_with_previous_RECS.pdf" class="ico_pdf">Comparing the 2020 RECS with Previous RECS
			and Other Studies</a></li>
	<li><a href="pdf/2020 RECS CE Methodology - Monthly Appendix - Final.pdf" class="ico_pdf">2020 Residential Energy Consumption Survey:
			Consumption and Expenditures Technical Documentation Summary</a></li>
	<li><a href=" pdf/2020 RECS_Square Footage Methodology.pdf" class="ico_pdf">2020 Residential Energy Consumption
			Survey (RECS) Square
			Footage Data Collection and Estimation Methodology</a></li>
	<li><a href=" pdf/2020 RECS_Methodology Report.pdf" class="ico_pdf">2020 Residential Energy Consumption Survey
			(RECS) Household Characteristics Technical Documentation Summary</a></li>

	</p>-->