<h2>Microdata</h2>
<br>
<p>Housing characteristics microdata will be released in May 2026.</p>


<!--<p>The 2020 RECS study represents the 15th iteration of the program. First conducted in 1978, the Residential Energy
  Consumption Survey is a national sample survey that collects energy-related data for housing units occupied as a
  primary residence and the households that live in them. We collected data from nearly 18,500 households in housing
  units statistically selected to represent the 123.5 million housing units that are occupied as primary residences.</p>
<ul>
  <li>July 2022 - The first version of the 2020 RECS microdata file reflected preliminary household characteristics
    data. </li>
  <li>June 2023 - The final version of the file includes consumption and expenditures data as well as end-use estimates.
  </li>
  <li>July 2023 - An update to the final version of the file includes two additional variables measuring dry bulb design
    temperature (DBT1 and DBT99). </li>
  <li>September 2023 – An update to the final version of the file includes the additional variable of ground water
    temperature.</li>
  <li>November 2023 – An update to the final version of the file includes the additional variable of wood type for space
    heating.</li>
  <li>January 2024 – An update to the final version of the file includes nine additional variables for electric
    vehicles.</li>
</ul>
<p>Appendix A of the Housing Characteristics documentation contains details on differences between the preliminary and
  final estimates.</p>
<p>We strongly encourage data users to read <a href="/consumption/residential/data/2020/pdf/microdata-guide.pdf"
    class="ico_pdf" title="microdata">Using the 2020 microdata file to compute estimates and standard errors (RSEs)</a>.
</p>-->


<!--<table class="basic_table" width="100%">
  <thead id="complete_data">
    <tr>
      <th width="15%">Data files</th>
      <th width="35%">Variable and response codebook</th>
      <th width="15%">Survey forms</th>
      <th width="15%" style="text-align:left">Release date</th>
    </tr>
  </thead>
  <tr>
    <td><a href="sas/recs2020_public_v7.zip" class="ico_sas" id="sas">SAS</a>&nbsp;&nbsp;&nbsp;&nbsp;<a
        href=" csv/recs2020_public_v7.csv" class="ico_csv">CSV</a></td>
    <!--  <td><div align="center"><a href="csv/public_layout.csv" class="ico_csv">CSV</a></div></td>-->
    <!--<td style="width: 45px; text-align: left; padding-left: 75px" align="left;"><a
        href="xls/RECS 2020 Codebook for Public File - v7.xlsx" title="Download RECS 2020 Codebook for Public File"
        class="ico_xls">XLSX</a></td>
    <td><a href="/survey/#eia-457">EIA-457 A-G&nbsp;&nbsp;</a></td>
    <td style="text-align: left">January 2024</td>
  </tr>
</table>-->
<!--<p>Researchers interested in accessing confidential data files for statistical purposes can find instructions on our <a href="/about/cipsea_reporting.php">CIPSEA data page</a> on applying for access via the Standard Application Process. We only grant access to confidential data under special circumstances.</p>-->