<h2>State Data</h2>

<span class="condaterange"><a class="no-border expandall">+ EXPAND ALL</a></span>
<table width="100%" class="contable">

  <thead id="hc">
    <tr>
      <th colspan="2"><a name="hc"></a>Housing characteristics</th>
    </tr>
  </thead>


  <tr class="hc">
    <td>Preliminary release date: March 2026</td>
    <td></td>

  <tr>
    <td style="color: #adadad">Highlights for space heating in U.S. homes by state, 2024 (<em>data will be released in early 2027</em>)</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
   <!--<td><span class="right"><a href="state/pdf/State Space Heating.pdf" class="ico_pdf"
          title="Highlights for space heating in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/State Space Heating.xlsx" class="ico_xls"
          title="Highlights for space heating in U.S. homes by state, 2024">XLSX</a>
    </td>-->
  </tr>
  <tr class="white_first">
    <td style="color: #adadad">Highlights for air conditioning in U.S. homes by state, 2024 (<em>data will be released in early 2027</em>)</td>
  	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/State Air Conditioning.pdf" class="ico_pdf"
          title="Highlights for air conditioning in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/State Air Conditioning.xlsx" class="ico_xls"
          title="Highlights for air conditioning in U.S. homes by state, 2024">XLSX</a></td>-->
  </tr>
  <tr>
    <td>Highlights for appliances in U.S. homes by state, 2024</td>
    <td><span class="right"><a href="state/pdf/STappliances_2024.pdf" class="ico_pdf"
          title="Download Highlights for appliances in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/STappliances_2024.xlsx" class="ico_xls"
          title="Download Highlights for appliances in U.S. homes by state, 2024">XLSX</a></td>
  </tr>
  <tr>
    <td>Highlights for electronics and lighting in U.S. homes by state, 2024</td>
    <td><span class="right"><a href="state/pdf/STelectronicsAndLighting_2024.pdf" class="ico_pdf"
          title="Highlights for electronics and lighting in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/STelectronicsAndLighting_2024.xlsx" class="ico_xls"
          title="Highlights for electronics and lighting in U.S. homes by state, 2024">XLSX</a></td>
  </tr>
  <tr>
    <td style="color: #adadad">Highlights for fuels used in U.S. homes by state, 2024 (<em>data will be released in early 2027</em>)</td>
	    <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/State Fuels Used.pdf" class="ico_pdf"
          title="Highlights for fuels used in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/State Fuels Used.xlsx" class="ico_xls"
          title="Highlights for fuels used in U.S. homes by state, 2024">XLSX</a>
    </td>-->
  </tr>
  <!--<tr>
    <td>Highlights for household characteristics of U.S. homes by state, 2024</td>
    <td><span class="right"><a href="state/pdf/State Household Characteristics.pdf" class="ico_pdf"
          title="Highlights for household characteristics of U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/State Household Characteristics.xlsx" class="ico_xls"
          title="Highlights for household characteristics of U.S. homes by state, 2024">XLSX</a>
    </td>
  </tr>-->
  <tr>
    <td style="color: #adadad">Highlights for space heating fuel in U.S. homes by state, 2024 (<em>data will be released in early 2027</em>)</td>
	  	<td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/State Space Heating Fuels.pdf" class="ico_pdf"
          title="Highlights for space heating fuel in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/State Space Heating Fuels.xlsx" class="ico_xls"
          title="Highlights for space heating fuel in U.S. homes by state, 2024">XLSX</a>
    </td>-->
  </tr>
  <tr>
    <td>Highlights for structural characteristics of U.S. homes by state, 2024</td>
    <td><span class="right"><a href="state/pdf/STstructural_2024.pdf" class="ico_pdf"
          title="Highlights for structural characteristics of U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/STstructural_2024.xlsx" class="ico_xls"
          title="Highlights for structural characteristics of U.S. homes by state, 2024">XLSX</a>
    </td>
  </tr>
  <tr>
    <td style="color: #adadad">Highlights for water heating in U.S. homes by state, 2024 (<em>data will be released in early 2027</em>)</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/State Water Heating.pdf" class="ico_pdf"
          title="Highlights for water heating in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/State Water Heating.xlsx" class="ico_xls"
          title="Highlights for water heating in U.S. homes by state, 2024">XLSX</a>
    </td>-->
  </tr>
  <tr>
    <td>Highlights for square footage in U.S. homes by state, 2024</td>
    <td><span class="right"><a href="state/pdf/STsquareFootage_2024.pdf" class="ico_pdf"
          title="Highlights for square footage in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/STsquareFootage_2024.xlsx" class="ico_xls"
          title="Highlights for square footage in U.S. homes by state, 2024">XLSX</a>
    </td>
  </tr>

  <thead id="ce">

    <tr>
      <th colspan="2"><a name="ce"></a>Consumption & expenditures</th>
  </thead>

  <tr class="by fuel">
	  <td colspan="2">Data will be released in early 2027.</td>
    <!--<td>Release date: March 29, 2023<br>
      Final Release Date: June 13, 2023</td>
    <td>&nbsp;</td>-->
  </tr>
  <tr class="white_first">
    <td><strong>Summary statistics</strong></td>
    <td></td>
  </tr>
  <tr>
    <td style="color: #adadad">CE1.1.ST – Summary household site consumption and expenditures in U.S. homes by state, 2024</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce1.1.st.pdf" class="ico_pdf"
          title="Summary household site consumption and expenditures in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce1.1.st.xlsx" class="ico_xls"
          title="Summary household site consumption and expenditures in U.S. homes by state, 2024">XLSX</a></td>-->
  </tr>
  <tr class="white_first">
    <td><strong>by Fuel (includes Btu and physical unit tabs)</strong></td>
    <td></td>
  </tr>
  <tr>
    <td style="color: #adadad">CE2.1.ST – Household site fuel consumption in U.S. homes by state, 2024</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce2.1.st.pdf" class="ico_pdf"
          title="Household site fuel consumption in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce2.1.st.xlsx" class="ico_xls"
          title="Household site fuel consumption in U.S. homes by state, 2024">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE2.6.ST – Household fuel expenditures in U.S. homes by state, 2024</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce2.6.st.pdf" class="ico_pdf"
          title="Household fuel expenditures in U.S. homes by state, 2024">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce2.6.st.xlsx" class="ico_xls"
          title="Household fuel expenditures in U.S. homes by state, 2024">XLSX</a></td>-->
  </tr>
  <tr class="white_first">
    <td><strong>by End uses </strong></td>
    <td></td>
  </tr>
  <tr>
    <td style="color: #adadad">CE3.1.ST – Consumption by end use by state - totals and averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce3.1.st.pdf" class="ico_pdf"
          title="Consumption by end use by state - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce3.1.st.xlsx" class="ico_xls"
          title="Consumption by end use by state - totals and averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE3.6.ST – Expenditures by end use by state - totals and averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce3.6.st.pdf" class="ico_pdf"
          title="Expenditures by end use by state - totals and averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce3.6.st.xlsx" class="ico_xls"
          title="Expenditures by end use by state - totals and averages">XLSX</a></td>-->
  </tr>
  <tr class="white_first">
    <td><strong>by End uses by fuel (includes Btu and physical unit tabs)</strong></td>
    <td></td>
  </tr>
  <tr>
    <td style="color: #adadad">CE4.1EL.ST – Electricity by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.1.el.st.pdf" class="ico_pdf"
          title="Electricity by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.1.el.st.xlsx" class="ico_xls"
          title="Electricity by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.1NG.ST – Natural gas consumption by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.1.ng.st.pdf" class="ico_pdf"
          title="Natural gas consumption by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.1.ng.st.xlsx" class="ico_xls"
          title="Natural gas consumption by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.1LP.ST – Propane consumption by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.1.lp.st.pdf" class="ico_pdf"
          title="Propane consumption by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.1.lp.st.xlsx" class="ico_xls"
          title="Propane consumption by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.1FO.ST – Fuel oil consumption by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.1.fo.st.pdf" class="ico_pdf"
          title="Fuel oil consumption by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.1.fo.st.xlsx" class="ico_xls"
          title="Fuel oil consumption by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.6EL.ST – Electricity consumption by end use by state - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.6.el.st.pdf" class="ico_pdf"
          title="Electricity consumption by end use by state - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.6.el.st.xlsx" class="ico_xls"
          title="Electricity consumption by end use by state - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.6NG.ST – Natural gas consumption by end use by state - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
   <!--<td><span class="right"><a href="state/pdf/ce4.6.ng.st.pdf" class="ico_pdf"
          title="Natural gas consumption by end use by state - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.6.ng.st.xlsx" class="ico_xls"
          title="Natural gas consumption by end use by state - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.6LP.ST – Propane consumption by end use by state - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.6.lp.st.pdf" class="ico_pdf"
          title="Propane consumption by end use by state - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.6.lp.st.xlsx" class="ico_xls"
          title="Propane consumption by end use by state - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.6FO.ST – Fuel oil consumption by end use by state - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.6.fo.st.pdf" class="ico_pdf"
          title="Fuel oil consumption by end use by state - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.6.fo.st.xlsx" class="ico_xls"
          title="Fuel oil consumption by end use by state - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.11EL.ST – Electricity expenditures by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.11.el.st.pdf" class="ico_pdf"
          title="Electricity expenditures by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.11.el.st.xlsx" class="ico_xls"
          title="Electricity expenditures by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.11NG.ST – Natural gas expenditures by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.11.ng.st.pdf" class="ico_pdf"
          title="Natural gas expenditures by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.11.ng.st.xlsx" class="ico_xls"
          title="Natural gas expenditures by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.11LP.ST – Propane expenditures by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.11.lp.st.pdf" class="ico_pdf"
          title="Propane expenditures by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.11.lp.st.xlsx" class="ico_xls"
          title="Propane expenditures by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.11FO.ST – Fuel oil expenditures by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.11.fo.st.pdf" class="ico_pdf"
          title="Fuel oil expenditures by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.11.fo.st.xlsx" class="ico_xls"
          title="Fuel oil expenditures by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.16EL.ST – Electricity expenditures by end use by state - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.16.el.st.pdf" class="ico_pdf"
          title="Electricity expenditures by end use by state - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.16.el.st.xlsx" class="ico_xls"
          title="Electricity expenditures by end use by state - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.16NG.ST – Natural gas expenditures by end use by state - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.16.ng.st.pdf" class="ico_pdf"
          title="Natural gas expenditures by end use by state - averages">PDF</a>&nbsp;&nbsp;<a
         href="state/xls/ce4.16.ng.st.xlsx" class="ico_xls"
          title="Natural gas expenditures by end use by state - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.16LP.ST – Propane expenditures by end use by state - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.16.lp.st.pdf" class="ico_pdf"
          title="Propane expenditures by end use by state - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.16.lp.st.xlsx" class="ico_xls"
          title="Propane expenditures by end use by state - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE4.16FO.ST – Fuel oil expenditures by end use by state - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce4.16.fo.st.pdf" class="ico_pdf"
          title="Fuel oil expenditures by end use by state - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce4.16.fo.st.xlsx" class="ico_xls"
          title="Fuel oil expenditures by end use by state - averages">XLSX</a></td>-->
  </tr>
  <tr class="white_first">
    <td><strong>Detailed end-use consumption and expenditure estimates</strong></td>
    <td></td>
  </tr>
  <tr>
    <td style="color: #adadad">CE5.1.ST – Detailed electricity end uses by state - consumption - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce5.1.st.pdf" class="ico_pdf"
          title="Detailed electricity end uses by state - consumption - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce5.1.st.xlsx" class="ico_xls"
          title="Detailed electricity end uses by state - consumption - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.2.ST – Detailed natural gas, propane, and fuel oil by state - consumption - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce5.2.st.pdf" class="ico_pdf"
          title="Detailed natural gas, propane, and fuel oil by state - consumption - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce5.2.st.xlsx" class="ico_xls"
          title="Detailed natural gas, propane, and fuel oil by state - consumption - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.3.ST – Detailed electricity end uses by state - consumption - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce5.3.st.pdf" class="ico_pdf"
          title="Detailed electricity end uses by state - consumption - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce5.3.st.xlsx" class="ico_xls"
          title="Detailed electricity end uses by state - consumption - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.4.ST – Detailed natural gas, propane, and fuel oil by state - consumption - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce5.4.st.pdf" class="ico_pdf"
          title="Detailed natural gas, propane, and fuel oil by state - consumption - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce5.4.st.xlsx" class="ico_xls"
          title="Detailed natural gas, propane, and fuel oil by state - consumption - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.5.ST – Detailed electricity end uses by state - expenditures - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce5.5.st.pdf" class="ico_pdf"
          title="Detailed electricity end uses by state - expenditures - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce5.5.st.xlsx" class="ico_xls"
          title="Detailed electricity end uses by state - expenditures - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.6.ST – Detailed natural gas, propane, and fuel oil by state - expenditures - totals</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce5.6.st.pdf" class="ico_pdf"
          title="Detailed natural gas, propane, and fuel oil by state - expenditures - totals">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce5.6.st.xlsx" class="ico_xls"
          title="Detailed natural gas, propane, and fuel oil by state - expenditures - totals">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.7.ST – Detailed electricity end uses by state - expenditures - averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce5.7.st.pdf" class="ico_pdf"
          title="Detailed electricity end uses by state - expenditures - averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce5.7.st.xlsx" class="ico_xls"
          title="Detailed electricity end uses by state - expenditures - averages">XLSX</a></td>-->
  </tr>
  <tr>
    <td style="color: #adadad">CE5.8.ST – Detailed natural gas, propane, and fuel oil by state - expenditures – averages</td>
	  <td style="color: #adadad"><span class="right" style="padding-left: 50px">&nbsp;PDF&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;XLSX</span></td>
    <!--<td><span class="right"><a href="state/pdf/ce5.8.st.pdf" class="ico_pdf"
          title="Detailed natural gas, propane, and fuel oil by state - expenditures – averages">PDF</a>&nbsp;&nbsp;<a
          href="state/xls/ce5.8.st.xlsx" class="ico_xls"
          title="Detailed natural gas, propane, and fuel oil by state - expenditures – averages">XLSX</a></td>-->
  </tr>
</table>