<div id="header-tag-search" class="reports-publication-search form-wrapper">
	<form id="header-bookshelf-search-form">
		<input type="text" class="fancy-search-box" value="" tabindex="-1" placeholder="Enter tags. Tags should be separated with the + character" onfocus="this.placeholder=''" onblur="this.placeholder='Enter tags. Tags should be separated with the + character'" />
		<button class="search-submit" id="goBtn"></button>
		<div id="header-tags-search" class="tags-search">
			<ul class="bookshelftags"></ul>
		</div>
	</form>
</div>





