<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">All Open</h2>
<p>
	Add <code>all-open</code> to the accordion <code>div</code>
</p>
<pre>
          <code class="html">&lt;div class=&#34;accordion all-open&#34;</code>
        </pre>
<h4>Live examples:</h4>

<div class="primary">
	<ul class="live-examples">
		<li><a></a></li>
	</ul>
</div>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
	<div class="primary">
		<div class="all-open">
			<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Introduction</h2>
			<div class="accordion-content" style="display: block">
				<h2>H2 Lorem Ipsum Dolor</h2>
				<!-- includes/placeholders/lorem-ipsum-p -->
			</div>
			<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Current</h2>
			<div class="accordion-content" style="display: block">
				<h2>H2 Lorem Ipsum Dolor</h2>
				<!-- includes/placeholders/lorem-ipsum-p -->
			</div>
			<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Discontinued</h2>
			<div class="accordion-content" style="display: block">
				<h2>H2 Lorem Ipsum Dolor</h2>
				<!-- includes/placeholders/lorem-ipsum-p -->
			</div>
		</div>
	</div>

	<br />
	<br />
	<!-- HTML -->
	<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
	<div class="uk-margin-medium">


		<pre><code class="language-html" id="AccordionAllOpen">&lt;div class="primary"&gt;
  &lt;div class="all-open"&gt;
    &lt;h3&gt;Lorem ipsum dolor sit amet&lt;/h3&gt;
    &lt;div class="accordion-content"&gt;
      &lt;ul&gt;
        &lt;li class="head"&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
        &lt;li&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/div&gt;
    &lt;h3&gt;Lorem ipsum dolor sit amet&lt;/h3&gt;
    &lt;div class="accordion-content"&gt;
      &lt;ul&gt;
        &lt;li class="head"&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
        &lt;li&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/div&gt;
    &lt;h3&gt;Lorem ipsum dolor sit amet&lt;/h3&gt;
    &lt;div class="accordion-content"&gt;
      &lt;ul&gt;
        &lt;li class="head"&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
        &lt;li&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;</code></pre>
		<!-- Copy Button -->
		<p>
			<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#AccordionAllOpen">
				<span uk-icon="copy"></span>Copy to clipboard
			</button>
		</p>
		</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">