<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">First Open</h2>
<p>
	Add <code>first-open</code> to the <code>&lt;div class=&#34;accordion first-open&#34;&gt;</code>.</p>


<h4>Live examples:</h4>

<div class="primary">
	<ul class="live-examples">
		<li><a></a></li>
	</ul>
</div>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
	<div class="primary">
		<span class="expand-collapse-container">
			<span class="eia ico expand">
				<span>Expand all</span>
			</span>
		</span>
		<div class="accordion first-open">
			<h3 class="ui-accordion-header" tabIndex="-1">
				<span class="ui-accordion-header-icon ui-icon ico collapse" style="display: block"></span>
				Introduction
				</h2>
				<div class="accordion-content" style="display: block">
					<!-- includes/placeholders/h1 -->
					<h2>H2 Lorem Ipsum Dolor</h2>
					<!-- includes/placeholders/lorem-ipsum-p -->
					<h2>H2 Lorem Ipsum Dolor</h2>
					<!-- includes/placeholders/lorem-ipsum-p -->
					<h2>H2 Lorem Ipsum Dolor</h2>
					<!-- includes/placeholders/lorem-ipsum-p -->
				</div>
				<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">
					<span class="ui-accordion-header-icon ui-icon ico expand" style="display: block"></span>
					Current
				</h2>
				<div class="accordion-content" style="display: none"></div>
				<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">
					<span class="ui-accordion-header-icon ui-icon ico expand" style="display: block"></span>
					Discontinued
				</h2>
				<div class="accordion-content" style="display: none"></div>
		</div>
	</div>
</div>
<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="AccordionFirstOpen">&lt;div class="primary"&gt;
  &lt;span class="expand-collapse-container"&gt;
    &lt;span class="eia ico expand"&gt;
      &lt;span&gt;Expand all&lt;/span&gt;
    &lt;/span&gt;
    &lt;span class="eia ico collapse"&gt;
      &lt;span&gt;Collapse all&lt;/span&gt;
    &lt;/span&gt;
  &lt;/span&gt;
  &lt;div class="accordion first-open"&gt;
    &lt;h3&gt;Lorem ipsum dolor sit amet&lt;/h3&gt;
    &lt;div class="accordion-content"&gt;
      &lt;ul&gt;
        &lt;li class="head"&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
        &lt;li&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/div&gt;
    &lt;h3&gt;Lorem ipsum dolor sit amet&lt;/h3&gt;
    &lt;div class="accordion-content"&gt;
      &lt;ul&gt;
        &lt;li class="head"&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
        &lt;li&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/div&gt;
    &lt;h3&gt;Lorem ipsum dolor sit amet&lt;/h3&gt;
    &lt;div class="accordion-content"&gt;
      &lt;ul&gt;
        &lt;li class="head"&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
        &lt;li&gt;Lorem ipsum dolor sit amet&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;</code></pre>

<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#AccordionFirstOpen">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">