<h3>Social (Stay Connected...)</h3>
<div class="accordion-content horizontal-icon-container social">


	<div class="icon-container">
		<span class="eia ico facebook">
			<span>Facebook</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico twitter">
			<span>Twitter</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico youtube">
			<span>Youtube</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico flickr">
			<span>Flickr</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico linkedin">
			<span>LinkedIn</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico email">
			<span>Email Updates</span>
		</span>
	</div>
	<div class="icon-container">
		<span class="eia ico rss">
			<span>RSS Feeds</span>
		</span>
	</div>
</div>
</div>