<!--



class EnergyEducationExample -->
<!-- code

<div class="l-row l-three-col-even energy-education">
<h1>Energy Education</h1>
<p class="uk-text-lead"></p>
<div class="l-col">
<span class="eia ico energy-education petroleum"></span>
<ul>
<li class="head">
<h2>
<a href="https://www.eia.gov">Oil: Crude &amp; Petroleum Products Explained</a>
</h2>
</li>
<li class="sub-head">
<a href="https://www.eia.gov">Gasoline Prices and Outlook</a>
</li>
<li class="foot">
<a href="https://www.eia.gov">See more petroleum topics</a>
</li>
</ul>
</div>
<div class="l-col">
<span class="eia ico energy-education faq"></span>
<ul>
<li class="head">
<h2>
<a href="https://www.eia.gov">FAQs</a>
</h2>
</li>
<li class="sub-head">
<a href="https://www.eia.gov">What are Mcf, Btu, and therms? How do I convert prices in Mcf to Btu's and therms?</a>
</li>
<li class="foot">
<a href="https://www.eia.gov">See all petroleum FAQs</a>
</li>
</ul>
</div>
<div class="l-col">
<span class="eia ico energy-education energy-kids"></span>
<ul>
<li class="head">
<h2>
<a href="https://www.eia.gov">Energy Kids</a>
</h2>
</li>
<li class="sub-head">
<a href="https://www.eia.gov">How was oil formed?</a>
</li>
<li class="foot">
<a href="https://www.eia.gov">See nonrenewable sources on Energy Kids</a>
</li>
</ul>
</div>
</div>


-->