<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Energy Education</h2>
<h4>Live examples:</h4>
<ul class="live-examples">
  <li class="li">
    <strong>Live example(s)</strong>
  </li>
  <li class="li">
    <a href="https://www.eia.gov/petroleum/">https://www.eia.gov/petroleum/</a>
  </li>
</ul>
<!-- Example -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
<div class="eia-card">
  <div>
    <div class="l-row l-three-col-even energy-education">
      <h1>Energy Education</h1>
      <p class="uk-text-lead"></p>
      <div class="l-col">
        <span class="eia ico energy-education petroleum"></span>
        <ul>
          <li class="head">
            <h2>
              <a href="https://www.eia.gov">Oil: Crude &amp; Petroleum Products Explained</a>
            </h2>
          </li>
          <li class="sub-head">
            <a href="https://www.eia.gov">Gasoline Prices and Outlook</a>
          </li>
          <li class="foot">
            <a href="https://www.eia.gov">See more petroleum topics</a>
          </li>
        </ul>
      </div>
      <div class="l-col">
        <span class="eia ico energy-education faq"></span>
        <ul>
          <li class="head">
            <h2>
              <a href="https://www.eia.gov">FAQs</a>
            </h2>
          </li>
          <li class="sub-head">
            <a href="https://www.eia.gov">What are Mcf, Btu, and therms? How do I convert prices in Mcf to Btu's and therms?</a>
          </li>
          <li class="foot">
            <a href="https://www.eia.gov">See all petroleum FAQs</a>
          </li>
        </ul>
      </div>
      <div class="l-col">
        <span class="eia ico energy-education energy-kids"></span>
        <ul>
          <li class="head">
            <h2>
              <a href="https://www.eia.gov">Energy Kids</a>
            </h2>
          </li>
          <li class="sub-head">
            <a href="https://www.eia.gov">How was oil formed?</a>
          </li>
          <li class="foot">
            <a href="https://www.eia.gov">See nonrenewable sources on Energy Kids</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- HTML -->
  <div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
  <div class="uk-margin-medium">
    <pre><code class="language-html" id="Dilly">&lt;div class="l-row l-three-col-even energy-education"&gt;
  &lt;h1&gt;Energy Education&lt;/h1&gt;
  &lt;div class="l-col"&gt;
    &lt;span class="eia ico energy-education petroleum"&gt;&lt;/span&gt;
    &lt;ul&gt;
      &lt;li class="head"&gt;
        &lt;h2&gt;
          &lt;a href="https://www.eia.gov"&gt;Oil: Crude &amp;amp; Petroleum Products Explained&lt;/a&gt;
        &lt;/h2&gt;
      &lt;/li&gt;
      &lt;li class="sub-head"&gt;
          &lt;a href="https://www.eia.gov"&gt;Gasoline Prices and Outlook&lt;/a&gt;
      &lt;/li&gt;
      &lt;li class="foot"&gt;
          &lt;a href="https://www.eia.gov"&gt;See more petroleum topics&lt;/a&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
  &lt;div class="l-col"&gt;
    &lt;span class="eia ico energy-education faq"&gt;&lt;/span&gt;
    &lt;ul&gt;
      &lt;li class="head"&gt;
        &lt;h2&gt;
          &lt;a href="https://www.eia.gov"&gt;FAQs&lt;/a&gt;
        &lt;/h2&gt;
      &lt;/li&gt;
      &lt;li class="sub-head"&gt;
          &lt;a href="https://www.eia.gov"&gt;What are Mcf, Btu, and therms? How do I convert prices in Mcf to Btu's and therms?&lt;/a&gt;
      &lt;/li&gt;
      &lt;li class="foot"&gt;
          &lt;a href="https://www.eia.gov"&gt;See all petroleum FAQs&lt;/a&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
  &lt;div class="l-col"&gt;
    &lt;span class="eia ico energy-education energy-kids"&gt;&lt;/span&gt;
    &lt;ul&gt;
      &lt;li class="head"&gt;
        &lt;h2&gt;
          &lt;a href="https://www.eia.gov"&gt;Energy Kids&lt;/a&gt;
        &lt;/h2&gt;
      &lt;/li&gt;
      &lt;li class="sub-head"&gt;
          &lt;a href="https://www.eia.gov"&gt;How was oil formed?&lt;/a&gt;
      &lt;/li&gt;
      &lt;li class="foot"&gt;
          &lt;a href="https://www.eia.gov"&gt;See nonrenewable sources on Energy Kids&lt;/a&gt;
      &lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
  &lt;/div&gt;</code></pre>
    <!-- Copy Button -->
    <p>
      <button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly"><span uk-icon="copy"></span>Copy to clipboard</button>
    </p>
  </div>
</div>
