<!--



class PetroleumWeekly -->
<!-- code

<div class="l-row l-report-header-petroleum-weekly l-two-col-even">
<div class="l-col">\n
    <!-- see the default report header -->\n
</div>
<div class="l-col twip-navigation">
	<a href="index.php" class="eia ico this-week-analysis active">
		<span>Analysis</span> <!-- for accessibility -->
	</a>
	<a href="crude.php" div="" class="eia ico crude-oil">
		<span>Crude Oil</span> <!-- for accessibility -->
	</a>
	<a href="gasoline.php" class="eia ico gasoline">
		<span>Gasoline</span> <!-- for accessibility -->
	</a>
	<a href="distillate.php" class="eia ico distillate">
		<span>Distillate</span> <!-- for accessibility -->
	</a>
	<a href="propane.php" class="eia ico propane">
		<span>Propane</span> <!-- for accessibility -->
	</a>
</div>
</div>


-->


<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Petroleum Weekly</h2>
<p>
	Example: <a href="http://www.eia.gov/petroleum/weekly">http://www.eia.gov/petroleum/weekly</a>
</p>

<div>
	<div class="l-row l-report-header-petroleum-weekly l-two-col-even">
		<div class="l-col">
			<div class="see-all">
				<a>See all Petroleum &amp; Other Liquids Reports</a>
			</div>
			<h1>This Week in Petroleum</h1>
			<p class="uk-text-lead"></p>
			<div class="release-dates">
				<span class="responsive-container">
					<span class="label">Release Date:</span> <span class="date">September 10, 2020</span>
				</span>
				<span class="responsive-container">
					<span class="label">Next Release Date:</span> <span class="date">September 16, 2020</span>
				</span>
			</div>
			<div class="release-dates do-not-print">
				<span class="responsive-container">
					<a class="eia ico download iframe">
						Download data
					</a>
				</span>
				<span class="responsive-container">
					<a class="iframe">
						Past Weeks
						<!--  in Petroleum  -->
					</a>
				</span>
				<span class="responsive-container">
					<a class="iframe">
						Release schedule
					</a>
				</span>
				<span class="responsive-container">
					<a class="iframe ico printer">
						Print
					</a>
				</span>
			</div>
		</div>
		<div class="l-col twip-navigation">
			<a href="index.php" class="eia ico this-week-analysis active">
				<span>Analysis</span>
			</a>
			<a href="crude.php" div="" class="eia ico crude-oil">
				<span>Crude Oil</span>
			</a>
			<a href="gasoline.php" class="eia ico gasoline">
				<span>Gasoline</span>
			</a>
			<a href="distillate.php" class="eia ico distillate">
				<span>Distillate</span>
			</a>
			<a href="propane.php" class="eia ico propane">
				<span>Propane</span>
			</a>
		</div>
	</div>
</div>


</div>