<h2>Final results from the <em>2022 Manufacturing Energy Consumption Survey</em> (MECS) are now available</h2>
<p><em>Release date: March 18, 2026</em></p>
<p>The final set of results from the 2022 <em>Manufacturing Energy Consumption Survey </em>(MECS), which includes 12 new <a href="/consumption/manufacturing/data/2022/">data tables</a> and accompanying <a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf" class="ico_pdf">highlights</a>, provides information on ratios of manufacturing fuel consumption to economic characteristics, average prices and quantities of purchased energy sources, and floorspace and building counts. </p>
<p>The new data show:</p>
<ul>
    <li>Consumption ratios of fuel by region were highest in the South.</li>
    <li>On average, electricity and distillate fuel oil were the most expensive energy sources.</li>
    <li>The average price of energy varied by region.</li>
    <li>The chemicals subsector accounted for the largest share of purchased electricity, natural gas, and steam.</li>
    <li>Petroleum and coal products had the highest energy consumption per employee.</li>
    <li>Fabricated metal products establishments were the most numerous of all industries.</li>
    <li>On average, primary metals, paper, and transportation equipment establishments were the largest.</li>
</ul>
<p>Further, we republished nine data tables to provide hydrogen estimates by subsector and industry at the national level. This release is the first time we have published hydrogen estimates for the <em>Manufacturing Energy Consumption Survey </em>(MECS). You can find these data in our data tables for:</p>
<ul>
    <li>Consumption Energy for All Purposes (First Use)</li>
    <li>Energy Used as a Nonfuel (Feedstock)</li>
    <li>Energy Consumption as a Fuel</li>
    <li>Offsite-Produced Fuel Consumption</li>
</ul>
<p><strong><a href="/consumption/manufacturing/data/2022/">Data Tables</a></strong> <br> <strong>2022 Manufacturing Energy Consumption Survey: Highlights from Final Data Release&nbsp;</strong> <a href="/consumption/manufacturing/data/2022/pdf/2022 MECS Results.pdf" class="ico_pdf"><strong>PDF</strong></a> </p>
<h4>Features</h4>
<h3 class="f1">Final results for energy management activities and establishment counts from the <em>2022 Manufacturing Energy Consumption Survey</em> (MECS) are now available</h3>
<p><em>Release date: December 17, 2025</i></p>
<p>The third set of results from the 2022 <em>Manufacturing Energy Consumption Survey</em> (MECS), which include 29 new <a href="/consumption/manufacturing/data/2022/">data tables</a> and accompanying <a href="/consumption/manufacturing/data/2022/pdf/MECS 2022 Release 1-3 Results.pdf" class="ico_pdf">highlights</a>, provide information on U.S. manufacturing energy management activities and establishment counts.</p>
<p>The new data show:</p>
<ul>
    <li>Price changes would not affect the switch to alternative fuels.</li>
    <li>More than 40% of manufacturing establishments participated in general energy management activities. </li>
    <li>Less than 1% of manufacturing establishments had cogeneration technologies.</li>
    <li>The largest shares of onsite cogeneration and onsite generation from <em>other</em> sources were in the South.</li>
    <li>Improving energy efficiency is important for the top energy-consuming subsectors.</li>
</ul>
<p>We will continue releasing the final 2022 MECS data through Spring 2026. A detailed schedule of the 2022 MECS release dates is available on the <a href="/consumption/manufacturing/data/2022/">MECS data website</a>.</p>
<p><strong><a href="/consumption/manufacturing/data/2022/">Data Tables</a></strong> <br> <strong>2022 Manufacturing Energy Consumption Survey: Highlights from Data Release 1–3&nbsp;</strong> <a href="/consumption/manufacturing/data/2022/pdf/MECS 2022 Release 1-3 Results.pdf" class="ico_pdf"><strong>PDF</strong></a> </p>
<hr>
<h3 class="f2"><a href="/consumption/manufacturing/data/2022/?src=‹ Consumption Manufacturing Energy Consumption Survey (MECS)-f2">Final results for consumption by economic characteristics of the manufacturers and expenditures for purchased energy sources from the <em>2022 Manufacturing Energy Consumption Survey</em> (MECS) are now available</a></h3>
<p><em>Release date: September 24, 2025</i></p>
<p>The second set of results from the 2022 <a href="/consumption/manufacturing/"><em>Manufacturing Energy Consumption Survey</em> (MECS)</a>, which include 9 new <a href="/consumption/manufacturing/data/2022/">data tables</a> and accompanying <a href="/consumption/manufacturing/data/2022/pdf/MECS 2022 Release 1-2 Results.pdf" class="ico_pdf">highlights</a>, provide information on U.S. manufacturing energy consumption by economic characteristics of the manufacturers and expenditures for purchased energy sources.</p>
<p>The new data show:</p>
<ul>
    <li>The top five energy-consuming sectors account for about three-fourths of energy expenditures.</li>
    <li>Establishments with the largest value of shipments and receipts accounted for over half of energy consumption.</li>
    <li>At the national level, total consumption was similar across employment size categories.</li>
    <li>Most natural gas and steam were purchased from nonutilities.</li>
</ul>
<p>We will continue releasing the final 2022 MECS data through Spring 2026. A detailed schedule of the 2022 MECS release dates is available on the <a href="/consumption/manufacturing/data/2022/">MECS data website</a>.</p>
<p><strong><a href="/consumption/manufacturing/data/2022/">Data Tables</a></strong> <br> <strong>2022 Manufacturing Energy Consumption Survey: Highlights from Data Release 1 and 2&nbsp;</strong> <a href="/consumption/manufacturing/data/2022/pdf/MECS 2022 Release 1-2 Results.pdf" class="ico_pdf"><strong>PDF</strong></a> </p>
<hr>
<h3 class="f3"><a href="/consumption/manufacturing/data/2022/?src=‹ Consumption Manufacturing Energy Consumption Survey (MECS)-f3">Final consumption, end use, and fuel-switching results from the 2022 Manufacturing Energy Consumption Survey (MECS) are now available</a></h3>
<p><em>Release date: August 6, 2025</i></p>
<p>First set of results from the 2022 Manufacturing Energy Consumption Survey (MECS), which include 35 new <a href="/consumption/manufacturing/data/2022/">data tables</a> and accompanying <a href="/consumption/manufacturing/data/2022/pdf/MECS2022-flipbook_v2.pdf" class="ico_pdf">highlights</a>, provide information on U.S. manufacturing energy consumption (fuel and nonfuel), end uses of fuel consumption, and fuel-switching capability.</p> </span>
<p>The new data show:</p>
<ul>
    <li>Manufacturing energy consumption continues to grow, in part, due to increased natural gas consumption </li>
    <li>Nonfuel (feedstock) consumption is greatest in chemical manufacturing </li>
    <li>Four subsectors—chemical, petroleum and coal products, paper, and primary metals—account for most of the manufacturing energy consumption </li>
    <li>Most subsectors cannot easily switch from natural gas to alternative fuels such as coal, electricity, and renewables</li>
</ul>
<p>We will continue releasing the final 2022 MECS data through Spring 2026. A detailed schedule of the 2022 MECS release dates is available on the <a href="/consumption/manufacturing/data/2022/">MECS data website</a>.</p>
<!-- span class="full" -->
<hr>
<h3 class="f4"><a href="/consumption/manufacturing/reports/2022/prelim_estimates/?src=‹ Consumption Manufacturing Energy Consumption Survey (MECS)-f4"><!--<img src="data/2022/images/slide7.svg" alt="bar chart" width="147" height="115"/>-->Preliminary estimates show increased total U.S. manufacturing energy consumption in 2022</a></h3>
<p><em>Release date: March 20, 2025</i></p>
<p>Preliminary results from our 2022 Manufacturing Energy Consumption Survey (MECS) show that total U.S. manufacturing energy consumption increased 6% between 2018 and 2022. MECS is the only source for national estimates of energy-related characteristics, consumption, and expenditures for manufacturers in the United States.</p>