<span class="grey_side blue_top">
<p><a href="../../about.php">About the MECS</a></p>
<p><a href="/consumption/manufacturing/xls/MECS Attributes.xlsx" class="ico_xls">&nbsp;Attributes</a></p>
<p><a href="/survey/#eia-846">Survey forms</a></p>
<p><a href="/consumption/manufacturing/maps.php">Maps</a></p>
<p><a href="../../terms.php">MECS terminology</a></p>
<p><a href="/consumption/manufacturing/data/archive/">Archives</a></p>
<p class="no-border"><a href="mailto:eiainfoconsumption&amp;efficiency@eia.gov?subject=MECS%20inquiry"email MECS staff">Contact MECS staff </a></p>
</span>
  
<?php if ( isset($briefTopic)) {?>
  <?php if ( $briefTopic == "Steel") {?>
    <h1>Steel</h1>
    <cfelseif briefTopic is "Chemical">
    <h1>Chemical</h1>
    <?php  } else { ?>
  <?php  } // end if ?>
<?php  } // end if ?>
<?php if ( $page['year'] == "") {?>
  <?php  } else { ?>
  <?php /*span class="grey_side blue_top">
  <h4>
    <?php if ( $page['year'] != "archive") {?>
      <?php echo "$page['year']"?>
    <?php  } // end if ?>
    Survey Forms</h4>
  <?php if ( $page['year'] == "2010") {?>
    <p><a href="http://wwwdev.eia.gov/survey/#eia-846"> 2010 </a></p>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "2006") {?>
    <p><a href="http://www.eia.gov/emeu/mecs/mecs2006/forms2006.html">2006</a></p>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "2002") {?>
    <p><a href="http://www.eia.gov/emeu/mecs/mecs2002/forms2002/mecs_forms.html">2002</a></p>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "1998") {?>
    <p><a href="http://www.eia.gov/emeu/mecs/mecs_forms.html">1998 </a></p>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "1994") {?>
    <p>Insert 1994 links</p>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "1991") {?>
    <p>Insert 1991 links</p>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "1988") {?>
    <p>Insert 1988 links</p>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "1985") {?>
    <p>Insert 1985 links</p>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "archive") {?>
    <p>Insert archive links</p>
  <?php  } // end if ?>
  </span */ ?>
<?php  } // end if ?>
<span class="grey_side green_top">
<h4>Other End Use Survey Data</h4>
<p><a href="/consumption/commercial/">Commercial Buildings - CBECS</a></p>
<p><a href="/consumption/residential/">Residential - RECS</a></p>
<p class="no-border"><a href="/consumption/archive/rtecs/contents.html">Transportation</a></p>
</span> 
