<!--

<ul class="numbered build-anchor">
<li>
<span class="number">ES1.A</span>
<span class="report-name">Total Electric Power Industry</span>
</li>
<li>
<span class="formats">Available formats:</span>
<a href="./xls/table_es1a.xlsx" class="eia ico xls" title="ES1.A Total Electric Power Industry">
<span>XLS</span>
</a>
</li>
</ul>


-->
<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="Dilly">Code sample not ready yet.</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>