<div class="l-row l-two-col-right">
	<div class="l-col">
		<h4>Inactive Icon</h4>
	</div>
</div>
<div class="l-row l-report-header-opendata l-two-col-right-wide">

	<div class="l-col opendata-navigation">
		<a href="/opendata/" class="eia ico intro">
			<span>Introduction</span>
		</a>

		<a href="/opendata/register.php" class="eia ico api">
			<span>API</span>
		</a>

		<a href="/opendata/excel/" class="eia ico addon">
			<span>Add-Ons</span>
		</a>

		<a href="/opendata/widgets.php" class="eia ico graphsmaps">
			<span>Graphs & Maps</span>
		</a>
	</div>
</div>

<!-- 
					<div class="icon-container">
						<a class="eia ico intro">
							<span>Intro</span>
						</a>
					</div>

					<div class="icon-container">
						<a class="eia ico api">
							<span>API</span>
						</a>
					</div>

					<div class="icon-container">
						<a class="eia ico addon">
							<span>Add-Ons</span>
						</a>
					</div>

					<div class="icon-container">
						<a class="eia ico graphsmaps">
							<span>Graphs &amp; Maps</span>
						</a>
					</div>
 -->
<div class="l-row l-two-col-right">
	<div class="l-col">
		<h4>Active Icon</h4>
	</div>
</div>

<div class="l-row l-report-header-opendata l-two-col-right-wide">
	<div class="l-col opendata-navigation">
		<a href="/opendata/" class="eia ico intro active">
			<span>Introduction</span>
		</a>

		<a href="/opendata/register.php" class="eia ico api active">
			<span>API</span>
		</a>

		<a href="/opendata/excel/" class="eia ico addon active">
			<span>Add-Ons</span>
		</a>

		<a href="/opendata/widgets.php" class="eia ico graphsmaps active">
			<span>Graphs & Maps</span>
		</a>

	</div>
</div>