<div class="l-row l-full-width-col">
	<div class="l-col">

		<h3>Page Title with No Sub-Navigation</h3>
		<h4>Live examples:</h4>
		<div class="primary">
			<ul class="live-examples">
				<li>With sub-navigation: <a href="https://wwwdev.eia.gov/petroleum/data.php">/petroleum/data.php</a></li>
				<li>Without sub-navigation: <a href="https://wwwdev.eia.gov/tools/rssfeeds/">/tools/rssfeeds/</a></li>
			</ul>
		</div>

	</div>
</div>


<div class="l-row header l-full-width-col no-sub-navigation">
	<div class="title-banner bg-glossary">
		<h1>
			<?php echo "$pageTitle"?>
		</h1>
		<p class="uk-text-lead"></p>
	</div>
</div>
<div id="page-sub-nav" class="eia-accessibility">This page has no sub-navigation. <a href="#page-content">Skip to page content</a>.</div>
<div class="l-row l-two-col-left-wide">
	<div class="l-col hide-overflow">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem massa, semper nec eros a, lacinia porttitor nunc. Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien. Suspendisse sagittis risus eu sem suscipit sodales. Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus. Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis. Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem. Vestibulum ut odio id nulla commodo dignissim. Proin a pharetra tellus.<div class="fade"></div>
	</div>
	<div class="l-col hide-overflow">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem massa, semper nec eros a, lacinia porttitor nunc. Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien. Suspendisse sagittis risus eu sem suscipit sodales. Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus. Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis. Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem. Vestibulum ut odio id nulla commodo dignissim. Proin a pharetra tellus.<div class="fade"></div>
	</div>
</div>

<!-- HTML -->
<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
<pre><code class="language-html" id="ReportHeaderOne">&lt;div class="l-row header l-full-width-col no-sub-navigation&gt;
    &lt;div class="l-col"&gt;
    &lt;!-- see page titles in modules --&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;div id="page-sub-nav" class="eia-accessibility"&gt;This page has no sub-navigation. &lt;a href="#page-content"&gt;Skip to page content&lt;/a&gt;.&lt;/div&gt;</code></pre>
<!-- Copy Button -->
<p>
	<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#ReportHeaderOne">
		<span uk-icon="copy"></span>Copy to clipboard
	</button>
</p>
</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">

<div class="l-row l-full-width-col">
	<div class="l-col">

		<h3>Report Header With No Sub-Navigation</h3>
		<h4>Live examples:</h4>
		<div class="primary">
			<ul class="live-examples">
				<li>With sub-navigation: <a href="https://wwwdev.eia.gov/petroleum/supply/weekly/">/petroleum/supply/weekly/</a></li>
				<li>Without sub-navigation: <a href="https://wwwdev.eia.gov/adaptive/petroleum/production/">/petroleum/production/</a></li>
			</ul>
		</div>

	</div>
</div>


<div class="l-row l-report-header no-sub-navigation">
	<div class="l-col">
		<div class="see-all">
			<a>SEE ALL REPORTS</a>
		</div>
		<h1>Weekly Status Report</h1>
		<p class="uk-text-lead"></p>
		<div class="release-dates">
			<span class="responsive-container">Data for week ending Oct. 4, XXXX</span>
			<span class="responsive-container">
				<span class="label">Release Date:</span>
				<span class="date">Oct. 9, XXXX</span>
			</span>
			<span class="responsive-container">
				<span class="label">Next Release Date:</span>
				<span class="date">Oct. 17, XXXX</span>
			</span>
			<span class="responsive-container">
				<a>
					full report
					<span class="eia ico pdf">
						<span>PDF</span>
					</span>
				</a>
			</span>
		</div>
	</div>
	<div class="l-col">
		<div class="form-container do-not-print">
			<fieldset>
				<legend>Previous reports</legend>
				<div class="dropdown-container no-js">
					<div class="dropdown-button">
						<span class="text">Select Month</span>
						<span class="eia ico d-arrow">
							<span>dropdown arrow</span>
						</span>
					</div>
					<div class="dropdown-menu">
						<ul>
							<li>
								<a>October, XXXX</a>
							</li>
							<li>
								<a>September, XXXX</a>
							</li>
							<li>
								<a>August, XXXX</a>
							</li>
							<li>
								<a>prior issues</a>
							</li>
						</ul>
					</div>
				</div>
			</fieldset>
		</div>
	</div>
</div>
<div id="page-sub-nav" class="eia-accessibility">This page has no sub-navigation. <a href="#page-content">Skip to page content</a>.</div>
<div class="l-row l-two-col-left-wide">
	<div class="l-col hide-overflow">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem massa, semper nec eros a, lacinia porttitor nunc. Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien. Suspendisse sagittis risus eu sem suscipit sodales. Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus. Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis. Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem. Vestibulum ut odio id nulla commodo dignissim. Proin a pharetra tellus.<div class="fade"></div>
	</div>
	<div class="l-col hide-overflow">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem massa, semper nec eros a, lacinia porttitor nunc. Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien. Suspendisse sagittis risus eu sem suscipit sodales. Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus. Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis. Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem. Vestibulum ut odio id nulla commodo dignissim. Proin a pharetra tellus.<div class="fade"></div>
	</div>
</div>
</div>

<div class="l-row l-full-width-col">
	<div class="l-col">

		<h4><span>&lt;/&gt;</span> Source</h4>
		<div class="clipboard-container">
			<pre><code class="language-html" id="ReportHeaderOne">&lt;div class="l-row l-report-header no-sub-navigation"&gt;
  &lt;div class="l-col"&gt;
    &lt;!-- see report header in modules --&gt;
  &lt;/div&gt;
&lt;/div&gt;
&lt;div id="page-sub-nav" class="eia-accessibility"&gt;This page has no sub-navigation. &lt;a href="#page-content"&gt;Skip to page content&lt;/a&gt;.&lt;/div&gt;</code></pre>

		</div>
		<!-- Copy Button -->
		<p>
			<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#ReportHeaderOne">
				<span uk-icon="copy"></span>Copy to clipboard
			</button>
		</p>
		</div>
</section>
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<!-- $$$$$$$$$$      dilly      $$$$$$$$$$ -->
<!-- $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
<section id="dilly">
<div class="eia-container">