<!--



class PrimaryExample -->
<!-- code

<div class="primary hide-mt">
<ul>
<li class="head">
      <h2>Lorem ipsum dolor sit amet consectetur</h2>
    </li>
<li><a href="https://www.eia.gov">1) Lorem ipsum dolor sit amet</a></li>
<li><a>2) This should be hidden</a></li>
<li><a href="https://www.eia.gov">3) Lorem ipsum dolor sit amet</a></li>
<li><a>4) This should be hidden</a></li>
<li><a href="https://www.eia.gov">5) Lorem ipsum dolor sit amet</a></li>
</ul>
</div>


-->

<h3>Primary</h3>
<code>.hide-mt</code>
<div>
	<div class="primary hide-mt">
		<ul>
			<li class="head">
				<h2>Lorem ipsum dolor sit amet consectetur</h2>
			</li>
			<li>
				<a href="https://www.eia.gov">1) Lorem ipsum dolor sit amet</a>
			</li>
			<li>
				<a href="https://www.eia.gov">2) Lorem ipsum dolor sit amet</a>
			</li>
			<li>
				<a href="https://www.eia.gov">3) Lorem ipsum dolor sit amet</a>
			</li>
			<li>
				<a href="https://www.eia.gov">4) Lorem ipsum dolor sit amet</a>
			</li>
			<li>
				<a href="https://www.eia.gov">5) Lorem ipsum dolor sit amet</a>
			</li>
		</ul>
	</div>
</div>
<div>
	<div class="primary hide-mt">
		<ul>
			<li class="head">
				<h2>Lorem ipsum dolor sit amet consectetur</h2>
			</li>
			<li>
				<a href="https://www.eia.gov">1) Lorem ipsum dolor sit amet</a>
			</li>
			<li>
				<a>2) This should be hidden</a>
			</li>
			<li>
				<a href="https://www.eia.gov">3) Lorem ipsum dolor sit amet</a>
			</li>
			<li>
				<a>4) This should be hidden</a>
			</li>
			<li>
				<a href="https://www.eia.gov">5) Lorem ipsum dolor sit amet</a>
			</li>
		</ul>
	</div>
</div>
<div class="clipboard-container">
	<h4><span>&lt;/&gt;</span> Source</h4>

	<pre><code class="language-html" id="Dilly">Code sample not ready yet.</code></pre>

	<!-- Copy Button -->
	<p>
		<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Dilly">
			<span uk-icon="copy"></span>Copy to clipboard
		</button>
</div>
</div>