<ul class="sub-nav">
	<li class="<?php ($pageTitle == 'Themes Home') ? print 'active' : print ''; ?>"><a href="index.php">Themes Home</a></li>
	<li class="<?php ($pageTitle == 'Article Template') ? print 'active' : print ''; ?>"><a href="article.php">Article Template</a></li>
	<li class="<?php ($pageTitle == 'Faqs Template') ? print 'active' : print ''; ?>"><a href="faqs.php">Faqs Template</a></li>
	<li class="<?php ($pageTitle == 'No Sub-Navigation') ? print 'active' : print ''; ?>"><a href="no-sub-navigation.php">No Sub-Navigation</a></li>
	<li class="<?php ($pageTitle == 'Open Data') ? print 'active' : print ''; ?>"><a href="open-data.php">Open Data</a></li>
	<li class="<?php ($pageTitle == 'This Week') ? print 'active' : print ''; ?>"><a href="this-week.php">This Week</a></li>
	<!--

  <li class="<?php ($pageTitle == 'Modules Home') ? print 'active' : print ''; ?>"><a href="themes-tables.php">themes-tables</a></li>
  <li class="<?php ($pageTitle == 'Modules Home') ? print 'active' : print ''; ?>"><a href="themes-tabs.php">themes-tabs</a></li>
-->
</ul>