<div class="horizontal-icon-container this-week">

	<div class="_icon-vertical">
		<div class="icon-container">
			<h6>Tabs Icon</h6>
			<div class="g_container">
				<div class="tabs petroleum-weekly">
					<ul>
						<li class="ui-state-active">
							<a>
								<span class="eia ico grid-line">
									<span>Graph</span>
								</span>
								Contract 1
							</a>
						</li>
						<li>
							<a>
								<span class="eia ico grid-line">
									<span>Graph</span>
								</span>
								Contract 2
							</a>
						</li>
						<li>
							<a>
								<span class="eia ico grid-line">
									<span>Graph</span>
								</span>
								Contract 3
							</a>
						</li>
						<li>
							<a>
								<span class="eia ico grid-line">
									<span>Graph</span>
								</span>
								Contract 4
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="icon-container">
			<div class="l-row l-report-header-petroleum-weekly">
				<h6>Tabs Icon</h6>
				<div class="release-dates">
					<span class="responsive-container">
						<a class="eia ico download iframe">
							Download data
						</a>
					</span>

					<span class="responsive-container">
						<a class="eia ico printer">
							Print
						</a>
					</span>
				</div>
			</div>
		</div>
	</div>
</div>
</div>