<h2 id="" class="uk-h3 tm-heading-fragment uk-margin-xlarge-top">Code Block</h2>
<h3 class="uk-h3 uk-heading-small">Live Examples</h2>
	<dl class="uk-description-list uk-description-list-divider">
		<dd><a href="https://www.eia.gov/opendata/">https://www.eia.gov/opendata/</a></li>
			</ul>
			</div>
			<!-- Example -->
			<div class="uk-text-default uk-text-normal uk-text-uppercase">Example</div>
			<div class="eia-card">

				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem massa, semper nec eros a, lacinia porttitor nunc: <code>https://api.eia.gov/v2/electricity/retail-sales?api_key=your_api_key</code>. Phasellus ex dolor, ultricies eu ornare ut, placerat non sapien. Suspendisse sagittis risus eu sem suscipit sodales. Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus. Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis. Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem. Vestibulum ut odio id nulla commodo dignissim. Proin a pharetra tellus.</p>

				<div class="uk-text-default uk-text-normal uk-text-uppercase">HTML</div>
				<pre><code class="language-html" id="Code">&lt;p&gt;Lorem ipsum dolor nunc: &lt;code&gt;https://api.eia.gov/v2/electricity/retail-sales?api_key=your_api_key&lt;/code&gt;. Vivamus ligula turpis, aliquam et maximus vel, tempor sed lectus. Mauris quis posuere massa. Ut quis diam sed mi placerat efficitur eu sed felis. Aliquam ipsum metus, bibendum vel ipsum sed, lobortis fringilla sem. Vestibulum ut odio id nulla commodo dignissim. Proin a pharetra tellus.&lt;/p&gt;</code></pre>
			</div>
			<!-- Copy Button -->
			<p>
				<button class="copy-element uk-button uk-button-primary" data-clipboard-action="copy" data-clipboard-target="#Code">
					<span uk-icon="copy"></span>Copy to clipboard
				</button>
				</div>
				</div>
				</div>