<section class="questions-and-answers margin-bottom">
	<div class="l-grid l-full-width-col">
		<p class="para">Electricity prices vary in each state. We have compiled years of data to find pricing trends around the country. You can see data for all 50 states below, but deregulated states are labeled in each chart/graph.</p>
		<ul>
			<li>
				The Average Electricity Rate in the U.S. is 17.47 cents per kilowatt-hour.
			</li>
			<br>
			<li>
				Hawaii has the hig hest average electricity rate of 39.36 cents per kilowatt-hour.
			</li>
			<br>
			<li>
				Idaho has the lowest average electricity rate of 12.28 cents per kilowatt-hour.
			</li>
		</ul>
	</div>
</section>